-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Promoted_From_KHR_global_priority (
  DeviceQueueGlobalPriorityCreateInfo (..),
  PhysicalDeviceGlobalPriorityQueryFeatures (..),
  QueueFamilyGlobalPriorityProperties (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core14.Enums.QueueGlobalPriority

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceQueueGlobalPriorityCreateInfo.html VkDeviceQueueGlobalPriorityCreateInfo>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkDeviceQueueGlobalPriorityCreateInfoKHR
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data DeviceQueueGlobalPriorityCreateInfo = DeviceQueueGlobalPriorityCreateInfo
  { globalPriority :: Open QueueGlobalPriority
  }

instance CStruct DeviceQueueGlobalPriorityCreateInfo where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000174000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (openToWire x.globalPriority))
    pure ()

instance FromCStruct DeviceQueueGlobalPriorityCreateInfo where
  peekCStruct p = do
    v_globalPriority <- (openFromWire <$> peekByteOff p 16)
    pure DeviceQueueGlobalPriorityCreateInfo{globalPriority = v_globalPriority}

instance Nil DeviceQueueGlobalPriorityCreateInfo where
  nil =
    DeviceQueueGlobalPriorityCreateInfo
      { globalPriority = Known QueueGlobalPriorityLow
      }

instance Chainable DeviceQueueGlobalPriorityCreateInfo where
  sTypeWire = 1000174000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceGlobalPriorityQueryFeatures.html VkPhysicalDeviceGlobalPriorityQueryFeatures>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPhysicalDeviceGlobalPriorityQueryFeaturesKHR
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceGlobalPriorityQueryFeatures = PhysicalDeviceGlobalPriorityQueryFeatures
  { globalPriorityQuery :: Bool
  }

instance CStruct PhysicalDeviceGlobalPriorityQueryFeatures where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000388000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.globalPriorityQuery then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDeviceGlobalPriorityQueryFeatures where
  peekCStruct p = do
    v_globalPriorityQuery <- (toBool <$> peekByteOff p 16)
    pure PhysicalDeviceGlobalPriorityQueryFeatures{globalPriorityQuery = v_globalPriorityQuery}

instance Nil PhysicalDeviceGlobalPriorityQueryFeatures where
  nil =
    PhysicalDeviceGlobalPriorityQueryFeatures
      { globalPriorityQuery = False
      }

instance Chainable PhysicalDeviceGlobalPriorityQueryFeatures where
  sTypeWire = 1000388000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkQueueFamilyGlobalPriorityProperties.html VkQueueFamilyGlobalPriorityProperties>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkQueueFamilyGlobalPriorityPropertiesKHR
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data QueueFamilyGlobalPriorityProperties = QueueFamilyGlobalPriorityProperties
  { priorities :: V.Vector (Open QueueGlobalPriority)
  }

instance CStruct QueueFamilyGlobalPriorityProperties where
  cSize = 88
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000388001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    unless (V.length x.priorities == 16) (error "lithon: priorities must have exactly 16 elements")
    liftIO (V.imapM_ (\i v -> pokeByteOff p (20 + i * 4) (openToWire v)) x.priorities)
    pure ()

instance FromCStruct QueueFamilyGlobalPriorityProperties where
  peekCStruct p = do
    v_priorities <- V.generateM 16 (\i -> openFromWire <$> peekByteOff p (20 + i * 4))
    pure QueueFamilyGlobalPriorityProperties{priorities = v_priorities}

instance Nil QueueFamilyGlobalPriorityProperties where
  nil =
    QueueFamilyGlobalPriorityProperties
      { priorities = V.replicate 16 (Known QueueGlobalPriorityLow)
      }

instance Chainable QueueFamilyGlobalPriorityProperties where
  sTypeWire = 1000388001
  chainOffset = 8
