-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Promoted_From_EXT_pipeline_protected_access (
  PhysicalDevicePipelineProtectedAccessFeatures (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDevicePipelineProtectedAccessFeatures.html VkPhysicalDevicePipelineProtectedAccessFeatures>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPhysicalDevicePipelineProtectedAccessFeaturesEXT
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDevicePipelineProtectedAccessFeatures = PhysicalDevicePipelineProtectedAccessFeatures
  { pipelineProtectedAccess :: Bool
  }

instance CStruct PhysicalDevicePipelineProtectedAccessFeatures where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000466000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.pipelineProtectedAccess then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDevicePipelineProtectedAccessFeatures where
  peekCStruct p = do
    v_pipelineProtectedAccess <- (toBool <$> peekByteOff p 16)
    pure
      PhysicalDevicePipelineProtectedAccessFeatures{pipelineProtectedAccess = v_pipelineProtectedAccess}

instance Nil PhysicalDevicePipelineProtectedAccessFeatures where
  nil =
    PhysicalDevicePipelineProtectedAccessFeatures
      { pipelineProtectedAccess = False
      }

instance Chainable PhysicalDevicePipelineProtectedAccessFeatures where
  sTypeWire = 1000466000
  chainOffset = 8
