-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Promoted_From_EXT_pipeline_robustness (
  PhysicalDevicePipelineRobustnessFeatures (..),
  PhysicalDevicePipelineRobustnessProperties (..),
  PipelineRobustnessCreateInfo (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core14.Enums.PipelineRobustnessBufferBehavior
import Lithon.Vk.Core14.Enums.PipelineRobustnessImageBehavior

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDevicePipelineRobustnessFeatures.html VkPhysicalDevicePipelineRobustnessFeatures>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPhysicalDevicePipelineRobustnessFeaturesEXT
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDevicePipelineRobustnessFeatures = PhysicalDevicePipelineRobustnessFeatures
  { pipelineRobustness :: Bool
  }

instance CStruct PhysicalDevicePipelineRobustnessFeatures where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000068001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.pipelineRobustness then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDevicePipelineRobustnessFeatures where
  peekCStruct p = do
    v_pipelineRobustness <- (toBool <$> peekByteOff p 16)
    pure PhysicalDevicePipelineRobustnessFeatures{pipelineRobustness = v_pipelineRobustness}

instance Nil PhysicalDevicePipelineRobustnessFeatures where
  nil =
    PhysicalDevicePipelineRobustnessFeatures
      { pipelineRobustness = False
      }

instance Chainable PhysicalDevicePipelineRobustnessFeatures where
  sTypeWire = 1000068001
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDevicePipelineRobustnessProperties.html VkPhysicalDevicePipelineRobustnessProperties>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPhysicalDevicePipelineRobustnessPropertiesEXT
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDevicePipelineRobustnessProperties = PhysicalDevicePipelineRobustnessProperties
  { defaultRobustnessStorageBuffers :: Open PipelineRobustnessBufferBehavior
  , defaultRobustnessUniformBuffers :: Open PipelineRobustnessBufferBehavior
  , defaultRobustnessVertexInputs :: Open PipelineRobustnessBufferBehavior
  , defaultRobustnessImages :: Open PipelineRobustnessImageBehavior
  }

instance CStruct PhysicalDevicePipelineRobustnessProperties where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000068002 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (openToWire x.defaultRobustnessStorageBuffers))
    liftIO (pokeByteOff p 20 (openToWire x.defaultRobustnessUniformBuffers))
    liftIO (pokeByteOff p 24 (openToWire x.defaultRobustnessVertexInputs))
    liftIO (pokeByteOff p 28 (openToWire x.defaultRobustnessImages))
    pure ()

instance FromCStruct PhysicalDevicePipelineRobustnessProperties where
  peekCStruct p = do
    v_defaultRobustnessStorageBuffers <- (openFromWire <$> peekByteOff p 16)
    v_defaultRobustnessUniformBuffers <- (openFromWire <$> peekByteOff p 20)
    v_defaultRobustnessVertexInputs <- (openFromWire <$> peekByteOff p 24)
    v_defaultRobustnessImages <- (openFromWire <$> peekByteOff p 28)
    pure
      PhysicalDevicePipelineRobustnessProperties
        { defaultRobustnessStorageBuffers = v_defaultRobustnessStorageBuffers
        , defaultRobustnessUniformBuffers = v_defaultRobustnessUniformBuffers
        , defaultRobustnessVertexInputs = v_defaultRobustnessVertexInputs
        , defaultRobustnessImages = v_defaultRobustnessImages
        }

instance Nil PhysicalDevicePipelineRobustnessProperties where
  nil =
    PhysicalDevicePipelineRobustnessProperties
      { defaultRobustnessStorageBuffers = Known PipelineRobustnessBufferBehaviorDeviceDefault
      , defaultRobustnessUniformBuffers = Known PipelineRobustnessBufferBehaviorDeviceDefault
      , defaultRobustnessVertexInputs = Known PipelineRobustnessBufferBehaviorDeviceDefault
      , defaultRobustnessImages = Known PipelineRobustnessImageBehaviorDeviceDefault
      }

instance Chainable PhysicalDevicePipelineRobustnessProperties where
  sTypeWire = 1000068002
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineRobustnessCreateInfo.html VkPipelineRobustnessCreateInfo>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPipelineRobustnessCreateInfoEXT
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PipelineRobustnessCreateInfo = PipelineRobustnessCreateInfo
  { storageBuffers :: Open PipelineRobustnessBufferBehavior
  , uniformBuffers :: Open PipelineRobustnessBufferBehavior
  , vertexInputs :: Open PipelineRobustnessBufferBehavior
  , images :: Open PipelineRobustnessImageBehavior
  }

instance CStruct PipelineRobustnessCreateInfo where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000068000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (openToWire x.storageBuffers))
    liftIO (pokeByteOff p 20 (openToWire x.uniformBuffers))
    liftIO (pokeByteOff p 24 (openToWire x.vertexInputs))
    liftIO (pokeByteOff p 28 (openToWire x.images))
    pure ()

instance FromCStruct PipelineRobustnessCreateInfo where
  peekCStruct p = do
    v_storageBuffers <- (openFromWire <$> peekByteOff p 16)
    v_uniformBuffers <- (openFromWire <$> peekByteOff p 20)
    v_vertexInputs <- (openFromWire <$> peekByteOff p 24)
    v_images <- (openFromWire <$> peekByteOff p 28)
    pure
      PipelineRobustnessCreateInfo
        { storageBuffers = v_storageBuffers
        , uniformBuffers = v_uniformBuffers
        , vertexInputs = v_vertexInputs
        , images = v_images
        }

instance Nil PipelineRobustnessCreateInfo where
  nil =
    PipelineRobustnessCreateInfo
      { storageBuffers = Known PipelineRobustnessBufferBehaviorDeviceDefault
      , uniformBuffers = Known PipelineRobustnessBufferBehaviorDeviceDefault
      , vertexInputs = Known PipelineRobustnessBufferBehaviorDeviceDefault
      , images = Known PipelineRobustnessImageBehaviorDeviceDefault
      }

instance Chainable PipelineRobustnessCreateInfo where
  sTypeWire = 1000068000
  chainOffset = 8
