-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Promoted_From_KHR_shader_subgroup_rotate (
  PhysicalDeviceShaderSubgroupRotateFeatures (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceShaderSubgroupRotateFeatures.html VkPhysicalDeviceShaderSubgroupRotateFeatures>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPhysicalDeviceShaderSubgroupRotateFeaturesKHR
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceShaderSubgroupRotateFeatures = PhysicalDeviceShaderSubgroupRotateFeatures
  { shaderSubgroupRotate :: Bool
  , shaderSubgroupRotateClustered :: Bool
  }

instance CStruct PhysicalDeviceShaderSubgroupRotateFeatures where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000416000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.shaderSubgroupRotate then TRUE else FALSE))
    liftIO (pokeByteOff p 20 (if x.shaderSubgroupRotateClustered then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDeviceShaderSubgroupRotateFeatures where
  peekCStruct p = do
    v_shaderSubgroupRotate <- (toBool <$> peekByteOff p 16)
    v_shaderSubgroupRotateClustered <- (toBool <$> peekByteOff p 20)
    pure
      PhysicalDeviceShaderSubgroupRotateFeatures
        { shaderSubgroupRotate = v_shaderSubgroupRotate
        , shaderSubgroupRotateClustered = v_shaderSubgroupRotateClustered
        }

instance Nil PhysicalDeviceShaderSubgroupRotateFeatures where
  nil =
    PhysicalDeviceShaderSubgroupRotateFeatures
      { shaderSubgroupRotate = False
      , shaderSubgroupRotateClustered = False
      }

instance Chainable PhysicalDeviceShaderSubgroupRotateFeatures where
  sTypeWire = 1000416000
  chainOffset = 8
