{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ExplicitForAll #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UnboxedTuples #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

-- | Defines constants which identify keyboard keys and modifiers.
--
--     Please refer to the Best Keyboard Practices document for details on what this information means and how best to use it.
--
--     [https:\/\/wiki.libsdl.org\/SDL3\/BestKeyboardPractices](https://wiki.libsdl.org/SDL3/BestKeyboardPractices) The SDL virtual key representation.
--
--     Values of this type are used to represent keyboard keys using the current layout of the keyboard. These values include Unicode values representing the unmodified character that would be generated by pressing the key, or an @SDLK_*@ constant for those keys that do not generate characters.
--
--     A special exception is the number keys at the top of the keyboard which map by default to SDLK_0...SDLK_9 on AZERTY layouts.
--
--     Keys with the @'sDLK_EXTENDED_MASK'@ bit set do not map to a scancode or Unicode code point.
--
--     Many common keycodes are listed below, but this list is not exhaustive.
--
--     @since 3.2.0
--
--     [See also]: SDL_HINT_KEYCODE_OPTIONS
module SDL3.Sys.Bindgen.Keycode (
  SDL3.Sys.Bindgen.Keycode.SDL_Keycode (..),
  SDL3.Sys.Bindgen.Keycode.sDLK_EXTENDED_MASK,
  SDL3.Sys.Bindgen.Keycode.sDLK_SCANCODE_MASK,
  SDL3.Sys.Bindgen.Keycode.sDL_SCANCODE_TO_KEYCODE,
  SDL3.Sys.Bindgen.Keycode.sDLK_UNKNOWN,
  SDL3.Sys.Bindgen.Keycode.sDLK_RETURN,
  SDL3.Sys.Bindgen.Keycode.sDLK_ESCAPE,
  SDL3.Sys.Bindgen.Keycode.sDLK_BACKSPACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_TAB,
  SDL3.Sys.Bindgen.Keycode.sDLK_SPACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_EXCLAIM,
  SDL3.Sys.Bindgen.Keycode.sDLK_DBLAPOSTROPHE,
  SDL3.Sys.Bindgen.Keycode.sDLK_HASH,
  SDL3.Sys.Bindgen.Keycode.sDLK_DOLLAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_PERCENT,
  SDL3.Sys.Bindgen.Keycode.sDLK_AMPERSAND,
  SDL3.Sys.Bindgen.Keycode.sDLK_APOSTROPHE,
  SDL3.Sys.Bindgen.Keycode.sDLK_LEFTPAREN,
  SDL3.Sys.Bindgen.Keycode.sDLK_RIGHTPAREN,
  SDL3.Sys.Bindgen.Keycode.sDLK_ASTERISK,
  SDL3.Sys.Bindgen.Keycode.sDLK_PLUS,
  SDL3.Sys.Bindgen.Keycode.sDLK_COMMA,
  SDL3.Sys.Bindgen.Keycode.sDLK_MINUS,
  SDL3.Sys.Bindgen.Keycode.sDLK_PERIOD,
  SDL3.Sys.Bindgen.Keycode.sDLK_SLASH,
  SDL3.Sys.Bindgen.Keycode.sDLK_0,
  SDL3.Sys.Bindgen.Keycode.sDLK_1,
  SDL3.Sys.Bindgen.Keycode.sDLK_2,
  SDL3.Sys.Bindgen.Keycode.sDLK_3,
  SDL3.Sys.Bindgen.Keycode.sDLK_4,
  SDL3.Sys.Bindgen.Keycode.sDLK_5,
  SDL3.Sys.Bindgen.Keycode.sDLK_6,
  SDL3.Sys.Bindgen.Keycode.sDLK_7,
  SDL3.Sys.Bindgen.Keycode.sDLK_8,
  SDL3.Sys.Bindgen.Keycode.sDLK_9,
  SDL3.Sys.Bindgen.Keycode.sDLK_COLON,
  SDL3.Sys.Bindgen.Keycode.sDLK_SEMICOLON,
  SDL3.Sys.Bindgen.Keycode.sDLK_LESS,
  SDL3.Sys.Bindgen.Keycode.sDLK_EQUALS,
  SDL3.Sys.Bindgen.Keycode.sDLK_GREATER,
  SDL3.Sys.Bindgen.Keycode.sDLK_QUESTION,
  SDL3.Sys.Bindgen.Keycode.sDLK_AT,
  SDL3.Sys.Bindgen.Keycode.sDLK_LEFTBRACKET,
  SDL3.Sys.Bindgen.Keycode.sDLK_BACKSLASH,
  SDL3.Sys.Bindgen.Keycode.sDLK_RIGHTBRACKET,
  SDL3.Sys.Bindgen.Keycode.sDLK_CARET,
  SDL3.Sys.Bindgen.Keycode.sDLK_UNDERSCORE,
  SDL3.Sys.Bindgen.Keycode.sDLK_GRAVE,
  SDL3.Sys.Bindgen.Keycode.sDLK_A,
  SDL3.Sys.Bindgen.Keycode.sDLK_B,
  SDL3.Sys.Bindgen.Keycode.sDLK_C,
  SDL3.Sys.Bindgen.Keycode.sDLK_D,
  SDL3.Sys.Bindgen.Keycode.sDLK_E,
  SDL3.Sys.Bindgen.Keycode.sDLK_F,
  SDL3.Sys.Bindgen.Keycode.sDLK_G,
  SDL3.Sys.Bindgen.Keycode.sDLK_H,
  SDL3.Sys.Bindgen.Keycode.sDLK_I,
  SDL3.Sys.Bindgen.Keycode.sDLK_J,
  SDL3.Sys.Bindgen.Keycode.sDLK_K,
  SDL3.Sys.Bindgen.Keycode.sDLK_L,
  SDL3.Sys.Bindgen.Keycode.sDLK_M,
  SDL3.Sys.Bindgen.Keycode.sDLK_N,
  SDL3.Sys.Bindgen.Keycode.sDLK_O,
  SDL3.Sys.Bindgen.Keycode.sDLK_P,
  SDL3.Sys.Bindgen.Keycode.sDLK_Q,
  SDL3.Sys.Bindgen.Keycode.sDLK_R,
  SDL3.Sys.Bindgen.Keycode.sDLK_S,
  SDL3.Sys.Bindgen.Keycode.sDLK_T,
  SDL3.Sys.Bindgen.Keycode.sDLK_U,
  SDL3.Sys.Bindgen.Keycode.sDLK_V,
  SDL3.Sys.Bindgen.Keycode.sDLK_W,
  SDL3.Sys.Bindgen.Keycode.sDLK_X,
  SDL3.Sys.Bindgen.Keycode.sDLK_Y,
  SDL3.Sys.Bindgen.Keycode.sDLK_Z,
  SDL3.Sys.Bindgen.Keycode.sDLK_LEFTBRACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_PIPE,
  SDL3.Sys.Bindgen.Keycode.sDLK_RIGHTBRACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_TILDE,
  SDL3.Sys.Bindgen.Keycode.sDLK_DELETE,
  SDL3.Sys.Bindgen.Keycode.sDLK_PLUSMINUS,
  SDL3.Sys.Bindgen.Keycode.sDLK_CAPSLOCK,
  SDL3.Sys.Bindgen.Keycode.sDLK_F1,
  SDL3.Sys.Bindgen.Keycode.sDLK_F2,
  SDL3.Sys.Bindgen.Keycode.sDLK_F3,
  SDL3.Sys.Bindgen.Keycode.sDLK_F4,
  SDL3.Sys.Bindgen.Keycode.sDLK_F5,
  SDL3.Sys.Bindgen.Keycode.sDLK_F6,
  SDL3.Sys.Bindgen.Keycode.sDLK_F7,
  SDL3.Sys.Bindgen.Keycode.sDLK_F8,
  SDL3.Sys.Bindgen.Keycode.sDLK_F9,
  SDL3.Sys.Bindgen.Keycode.sDLK_F10,
  SDL3.Sys.Bindgen.Keycode.sDLK_F11,
  SDL3.Sys.Bindgen.Keycode.sDLK_F12,
  SDL3.Sys.Bindgen.Keycode.sDLK_PRINTSCREEN,
  SDL3.Sys.Bindgen.Keycode.sDLK_SCROLLLOCK,
  SDL3.Sys.Bindgen.Keycode.sDLK_PAUSE,
  SDL3.Sys.Bindgen.Keycode.sDLK_INSERT,
  SDL3.Sys.Bindgen.Keycode.sDLK_HOME,
  SDL3.Sys.Bindgen.Keycode.sDLK_PAGEUP,
  SDL3.Sys.Bindgen.Keycode.sDLK_END,
  SDL3.Sys.Bindgen.Keycode.sDLK_PAGEDOWN,
  SDL3.Sys.Bindgen.Keycode.sDLK_RIGHT,
  SDL3.Sys.Bindgen.Keycode.sDLK_LEFT,
  SDL3.Sys.Bindgen.Keycode.sDLK_DOWN,
  SDL3.Sys.Bindgen.Keycode.sDLK_UP,
  SDL3.Sys.Bindgen.Keycode.sDLK_NUMLOCKCLEAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_DIVIDE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MULTIPLY,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MINUS,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_PLUS,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_ENTER,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_1,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_2,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_3,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_4,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_5,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_6,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_7,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_8,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_9,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_0,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_PERIOD,
  SDL3.Sys.Bindgen.Keycode.sDLK_APPLICATION,
  SDL3.Sys.Bindgen.Keycode.sDLK_POWER,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_EQUALS,
  SDL3.Sys.Bindgen.Keycode.sDLK_F13,
  SDL3.Sys.Bindgen.Keycode.sDLK_F14,
  SDL3.Sys.Bindgen.Keycode.sDLK_F15,
  SDL3.Sys.Bindgen.Keycode.sDLK_F16,
  SDL3.Sys.Bindgen.Keycode.sDLK_F17,
  SDL3.Sys.Bindgen.Keycode.sDLK_F18,
  SDL3.Sys.Bindgen.Keycode.sDLK_F19,
  SDL3.Sys.Bindgen.Keycode.sDLK_F20,
  SDL3.Sys.Bindgen.Keycode.sDLK_F21,
  SDL3.Sys.Bindgen.Keycode.sDLK_F22,
  SDL3.Sys.Bindgen.Keycode.sDLK_F23,
  SDL3.Sys.Bindgen.Keycode.sDLK_F24,
  SDL3.Sys.Bindgen.Keycode.sDLK_EXECUTE,
  SDL3.Sys.Bindgen.Keycode.sDLK_HELP,
  SDL3.Sys.Bindgen.Keycode.sDLK_MENU,
  SDL3.Sys.Bindgen.Keycode.sDLK_SELECT,
  SDL3.Sys.Bindgen.Keycode.sDLK_STOP,
  SDL3.Sys.Bindgen.Keycode.sDLK_AGAIN,
  SDL3.Sys.Bindgen.Keycode.sDLK_UNDO,
  SDL3.Sys.Bindgen.Keycode.sDLK_CUT,
  SDL3.Sys.Bindgen.Keycode.sDLK_COPY,
  SDL3.Sys.Bindgen.Keycode.sDLK_PASTE,
  SDL3.Sys.Bindgen.Keycode.sDLK_FIND,
  SDL3.Sys.Bindgen.Keycode.sDLK_MUTE,
  SDL3.Sys.Bindgen.Keycode.sDLK_VOLUMEUP,
  SDL3.Sys.Bindgen.Keycode.sDLK_VOLUMEDOWN,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_COMMA,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_EQUALSAS400,
  SDL3.Sys.Bindgen.Keycode.sDLK_ALTERASE,
  SDL3.Sys.Bindgen.Keycode.sDLK_SYSREQ,
  SDL3.Sys.Bindgen.Keycode.sDLK_CANCEL,
  SDL3.Sys.Bindgen.Keycode.sDLK_CLEAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_PRIOR,
  SDL3.Sys.Bindgen.Keycode.sDLK_RETURN2,
  SDL3.Sys.Bindgen.Keycode.sDLK_SEPARATOR,
  SDL3.Sys.Bindgen.Keycode.sDLK_OUT,
  SDL3.Sys.Bindgen.Keycode.sDLK_OPER,
  SDL3.Sys.Bindgen.Keycode.sDLK_CLEARAGAIN,
  SDL3.Sys.Bindgen.Keycode.sDLK_CRSEL,
  SDL3.Sys.Bindgen.Keycode.sDLK_EXSEL,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_00,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_000,
  SDL3.Sys.Bindgen.Keycode.sDLK_THOUSANDSSEPARATOR,
  SDL3.Sys.Bindgen.Keycode.sDLK_DECIMALSEPARATOR,
  SDL3.Sys.Bindgen.Keycode.sDLK_CURRENCYUNIT,
  SDL3.Sys.Bindgen.Keycode.sDLK_CURRENCYSUBUNIT,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_LEFTPAREN,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_RIGHTPAREN,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_LEFTBRACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_RIGHTBRACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_TAB,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_BACKSPACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_A,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_B,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_C,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_D,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_E,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_F,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_XOR,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_POWER,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_PERCENT,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_LESS,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_GREATER,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_AMPERSAND,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_DBLAMPERSAND,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_VERTICALBAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_DBLVERTICALBAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_COLON,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_HASH,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_SPACE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_AT,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_EXCLAM,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMSTORE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMRECALL,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMCLEAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMADD,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMSUBTRACT,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMMULTIPLY,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_MEMDIVIDE,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_PLUSMINUS,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_CLEAR,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_CLEARENTRY,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_BINARY,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_OCTAL,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_DECIMAL,
  SDL3.Sys.Bindgen.Keycode.sDLK_KP_HEXADECIMAL,
  SDL3.Sys.Bindgen.Keycode.sDLK_LCTRL,
  SDL3.Sys.Bindgen.Keycode.sDLK_LSHIFT,
  SDL3.Sys.Bindgen.Keycode.sDLK_LALT,
  SDL3.Sys.Bindgen.Keycode.sDLK_LGUI,
  SDL3.Sys.Bindgen.Keycode.sDLK_RCTRL,
  SDL3.Sys.Bindgen.Keycode.sDLK_RSHIFT,
  SDL3.Sys.Bindgen.Keycode.sDLK_RALT,
  SDL3.Sys.Bindgen.Keycode.sDLK_RGUI,
  SDL3.Sys.Bindgen.Keycode.sDLK_MODE,
  SDL3.Sys.Bindgen.Keycode.sDLK_SLEEP,
  SDL3.Sys.Bindgen.Keycode.sDLK_WAKE,
  SDL3.Sys.Bindgen.Keycode.sDLK_CHANNEL_INCREMENT,
  SDL3.Sys.Bindgen.Keycode.sDLK_CHANNEL_DECREMENT,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_PLAY,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_PAUSE,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_RECORD,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_FAST_FORWARD,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_REWIND,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_NEXT_TRACK,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_PREVIOUS_TRACK,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_STOP,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_EJECT,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_PLAY_PAUSE,
  SDL3.Sys.Bindgen.Keycode.sDLK_MEDIA_SELECT,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_NEW,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_OPEN,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_CLOSE,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_EXIT,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_SAVE,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_PRINT,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_PROPERTIES,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_SEARCH,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_HOME,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_BACK,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_FORWARD,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_STOP,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_REFRESH,
  SDL3.Sys.Bindgen.Keycode.sDLK_AC_BOOKMARKS,
  SDL3.Sys.Bindgen.Keycode.sDLK_SOFTLEFT,
  SDL3.Sys.Bindgen.Keycode.sDLK_SOFTRIGHT,
  SDL3.Sys.Bindgen.Keycode.sDLK_CALL,
  SDL3.Sys.Bindgen.Keycode.sDLK_ENDCALL,
  SDL3.Sys.Bindgen.Keycode.sDLK_LEFT_TAB,
  SDL3.Sys.Bindgen.Keycode.sDLK_LEVEL5_SHIFT,
  SDL3.Sys.Bindgen.Keycode.sDLK_MULTI_KEY_COMPOSE,
  SDL3.Sys.Bindgen.Keycode.sDLK_LMETA,
  SDL3.Sys.Bindgen.Keycode.sDLK_RMETA,
  SDL3.Sys.Bindgen.Keycode.sDLK_LHYPER,
  SDL3.Sys.Bindgen.Keycode.sDLK_RHYPER,
  SDL3.Sys.Bindgen.Keycode.SDL_Keymod (..),
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_NONE,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_LSHIFT,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_RSHIFT,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_LEVEL5,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_LCTRL,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_RCTRL,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_LALT,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_RALT,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_LGUI,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_RGUI,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_NUM,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_CAPS,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_MODE,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_SCROLL,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_CTRL,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_SHIFT,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_ALT,
  SDL3.Sys.Bindgen.Keycode.sDL_KMOD_GUI,
)
where

import C.Expr.HostPlatform qualified
import HsBindgen.Runtime.HasCField qualified as HasCField
import HsBindgen.Runtime.Marshal qualified as Marshal
import HsBindgen.Runtime.Support qualified as BG
import HsBindgen.Runtime.Support.CompatHasField qualified as BG.CompatHasField
import SDL3.Sys.Bindgen.Stdinc qualified

-- | [C declaration]: @SDL_Keycode@, defined at @SDL3\/SDL_keycode.h 59:16@
newtype SDL_Keycode = SDL_Keycode
  { unwrap :: SDL3.Sys.Bindgen.Stdinc.Uint32
  }
  deriving stock (BG.Generic, Eq, Ord, Read, Show)
  deriving newtype
    ( BG.Bitfield
    , BG.Bits
    , BG.FiniteBits
    , BG.HasFFIType
    , BG.Ix
    , BG.Prim
    , BG.Storable
    , Bounded
    , Enum
    , Integral
    , Marshal.ReadRaw
    , Marshal.StaticSize
    , Marshal.WriteRaw
    , Num
    , Real
    )

instance
  (ty ~ SDL3.Sys.Bindgen.Stdinc.Uint32)
  => BG.CompatHasField.HasField "unwrap" SDL_Keycode ty
  where
  hasField =
    \x0 ->
      ( \y1 ->
          SDL_Keycode{unwrap = y1}
      , BG.getField @"unwrap" x0
      )

instance
  (ty ~ SDL3.Sys.Bindgen.Stdinc.Uint32)
  => BG.HasField "unwrap" (BG.Ptr SDL_Keycode) (BG.Ptr ty)
  where
  getField = HasCField.fromPtr (BG.Proxy @"unwrap")

instance HasCField.HasCField SDL_Keycode "unwrap" where
  type
    CFieldType SDL_Keycode "unwrap" =
      SDL3.Sys.Bindgen.Stdinc.Uint32

  offset# = \_ -> \_ -> 0

-- | [C declaration]: @macro SDLK_EXTENDED_MASK@, defined at @SDL3\/SDL_keycode.h 61:9@
sDLK_EXTENDED_MASK :: BG.CUInt
sDLK_EXTENDED_MASK =
  (C.Expr.HostPlatform.<<) (1 :: BG.CUInt) (29 :: BG.CInt)

-- | [C declaration]: @macro SDLK_SCANCODE_MASK@, defined at @SDL3\/SDL_keycode.h 62:9@
sDLK_SCANCODE_MASK :: BG.CUInt
sDLK_SCANCODE_MASK =
  (C.Expr.HostPlatform.<<) (1 :: BG.CUInt) (30 :: BG.CInt)

-- | [C declaration]: @macro SDL_SCANCODE_TO_KEYCODE@, defined at @SDL3\/SDL_keycode.h 63:9@
sDL_SCANCODE_TO_KEYCODE
  :: forall a0. (C.Expr.HostPlatform.Bitwise a0 BG.CUInt) => a0 -> C.Expr.HostPlatform.BitsRes a0 BG.CUInt
sDL_SCANCODE_TO_KEYCODE =
  \x0 ->
    (C.Expr.HostPlatform..|.) x0 sDLK_SCANCODE_MASK

-- | 0
--
--     [C declaration]: @macro SDLK_UNKNOWN@, defined at @SDL3\/SDL_keycode.h 64:9@
sDLK_UNKNOWN :: BG.CUInt
sDLK_UNKNOWN = (0 :: BG.CUInt)

-- | \'\\r\'
--
--     [C declaration]: @macro SDLK_RETURN@, defined at @SDL3\/SDL_keycode.h 65:9@
sDLK_RETURN :: BG.CUInt
sDLK_RETURN = (13 :: BG.CUInt)

-- | \'\\x1B\'
--
--     [C declaration]: @macro SDLK_ESCAPE@, defined at @SDL3\/SDL_keycode.h 66:9@
sDLK_ESCAPE :: BG.CUInt
sDLK_ESCAPE = (27 :: BG.CUInt)

-- | \' ____ \'
--
--     [C declaration]: @macro SDLK_BACKSPACE@, defined at @SDL3\/SDL_keycode.h 67:9@
sDLK_BACKSPACE :: BG.CUInt
sDLK_BACKSPACE = (8 :: BG.CUInt)

-- | \'\\t\'
--
--     [C declaration]: @macro SDLK_TAB@, defined at @SDL3\/SDL_keycode.h 68:9@
sDLK_TAB :: BG.CUInt
sDLK_TAB = (9 :: BG.CUInt)

-- | \' \'
--
--     [C declaration]: @macro SDLK_SPACE@, defined at @SDL3\/SDL_keycode.h 69:9@
sDLK_SPACE :: BG.CUInt
sDLK_SPACE = (32 :: BG.CUInt)

-- | \'!\'
--
--     [C declaration]: @macro SDLK_EXCLAIM@, defined at @SDL3\/SDL_keycode.h 70:9@
sDLK_EXCLAIM :: BG.CUInt
sDLK_EXCLAIM = (33 :: BG.CUInt)

-- | \'\"\'
--
--     [C declaration]: @macro SDLK_DBLAPOSTROPHE@, defined at @SDL3\/SDL_keycode.h 71:9@
sDLK_DBLAPOSTROPHE :: BG.CUInt
sDLK_DBLAPOSTROPHE = (34 :: BG.CUInt)

-- | \'\#\'
--
--     [C declaration]: @macro SDLK_HASH@, defined at @SDL3\/SDL_keycode.h 72:9@
sDLK_HASH :: BG.CUInt
sDLK_HASH = (35 :: BG.CUInt)

-- | \'\$\'
--
--     [C declaration]: @macro SDLK_DOLLAR@, defined at @SDL3\/SDL_keycode.h 73:9@
sDLK_DOLLAR :: BG.CUInt
sDLK_DOLLAR = (36 :: BG.CUInt)

-- | \'\'
--
--     [C declaration]: @macro SDLK_PERCENT@, defined at @SDL3\/SDL_keycode.h 74:9@
sDLK_PERCENT :: BG.CUInt
sDLK_PERCENT = (37 :: BG.CUInt)

-- | \'&\'
--
--     [C declaration]: @macro SDLK_AMPERSAND@, defined at @SDL3\/SDL_keycode.h 75:9@
sDLK_AMPERSAND :: BG.CUInt
sDLK_AMPERSAND = (38 :: BG.CUInt)

-- | \'\\\'\'
--
--     [C declaration]: @macro SDLK_APOSTROPHE@, defined at @SDL3\/SDL_keycode.h 76:9@
sDLK_APOSTROPHE :: BG.CUInt
sDLK_APOSTROPHE = (39 :: BG.CUInt)

-- | \'(\'
--
--     [C declaration]: @macro SDLK_LEFTPAREN@, defined at @SDL3\/SDL_keycode.h 77:9@
sDLK_LEFTPAREN :: BG.CUInt
sDLK_LEFTPAREN = (40 :: BG.CUInt)

-- | \')\'
--
--     [C declaration]: @macro SDLK_RIGHTPAREN@, defined at @SDL3\/SDL_keycode.h 78:9@
sDLK_RIGHTPAREN :: BG.CUInt
sDLK_RIGHTPAREN = (41 :: BG.CUInt)

-- | \'*\'
--
--     [C declaration]: @macro SDLK_ASTERISK@, defined at @SDL3\/SDL_keycode.h 79:9@
sDLK_ASTERISK :: BG.CUInt
sDLK_ASTERISK = (42 :: BG.CUInt)

-- | \'+\'
--
--     [C declaration]: @macro SDLK_PLUS@, defined at @SDL3\/SDL_keycode.h 80:9@
sDLK_PLUS :: BG.CUInt
sDLK_PLUS = (43 :: BG.CUInt)

-- | \',\'
--
--     [C declaration]: @macro SDLK_COMMA@, defined at @SDL3\/SDL_keycode.h 81:9@
sDLK_COMMA :: BG.CUInt
sDLK_COMMA = (44 :: BG.CUInt)

-- | \'-\'
--
--     [C declaration]: @macro SDLK_MINUS@, defined at @SDL3\/SDL_keycode.h 82:9@
sDLK_MINUS :: BG.CUInt
sDLK_MINUS = (45 :: BG.CUInt)

-- | \'.\'
--
--     [C declaration]: @macro SDLK_PERIOD@, defined at @SDL3\/SDL_keycode.h 83:9@
sDLK_PERIOD :: BG.CUInt
sDLK_PERIOD = (46 :: BG.CUInt)

-- | \'\/\'
--
--     [C declaration]: @macro SDLK_SLASH@, defined at @SDL3\/SDL_keycode.h 84:9@
sDLK_SLASH :: BG.CUInt
sDLK_SLASH = (47 :: BG.CUInt)

-- | \'0\'
--
--     [C declaration]: @macro SDLK_0@, defined at @SDL3\/SDL_keycode.h 85:9@
sDLK_0 :: BG.CUInt
sDLK_0 = (48 :: BG.CUInt)

-- | \'1\'
--
--     [C declaration]: @macro SDLK_1@, defined at @SDL3\/SDL_keycode.h 86:9@
sDLK_1 :: BG.CUInt
sDLK_1 = (49 :: BG.CUInt)

-- | \'2\'
--
--     [C declaration]: @macro SDLK_2@, defined at @SDL3\/SDL_keycode.h 87:9@
sDLK_2 :: BG.CUInt
sDLK_2 = (50 :: BG.CUInt)

-- | \'3\'
--
--     [C declaration]: @macro SDLK_3@, defined at @SDL3\/SDL_keycode.h 88:9@
sDLK_3 :: BG.CUInt
sDLK_3 = (51 :: BG.CUInt)

-- | \'4\'
--
--     [C declaration]: @macro SDLK_4@, defined at @SDL3\/SDL_keycode.h 89:9@
sDLK_4 :: BG.CUInt
sDLK_4 = (52 :: BG.CUInt)

-- | \'5\'
--
--     [C declaration]: @macro SDLK_5@, defined at @SDL3\/SDL_keycode.h 90:9@
sDLK_5 :: BG.CUInt
sDLK_5 = (53 :: BG.CUInt)

-- | \'6\'
--
--     [C declaration]: @macro SDLK_6@, defined at @SDL3\/SDL_keycode.h 91:9@
sDLK_6 :: BG.CUInt
sDLK_6 = (54 :: BG.CUInt)

-- | \'7\'
--
--     [C declaration]: @macro SDLK_7@, defined at @SDL3\/SDL_keycode.h 92:9@
sDLK_7 :: BG.CUInt
sDLK_7 = (55 :: BG.CUInt)

-- | \'8\'
--
--     [C declaration]: @macro SDLK_8@, defined at @SDL3\/SDL_keycode.h 93:9@
sDLK_8 :: BG.CUInt
sDLK_8 = (56 :: BG.CUInt)

-- | \'9\'
--
--     [C declaration]: @macro SDLK_9@, defined at @SDL3\/SDL_keycode.h 94:9@
sDLK_9 :: BG.CUInt
sDLK_9 = (57 :: BG.CUInt)

-- | \':\'
--
--     [C declaration]: @macro SDLK_COLON@, defined at @SDL3\/SDL_keycode.h 95:9@
sDLK_COLON :: BG.CUInt
sDLK_COLON = (58 :: BG.CUInt)

-- | \';\'
--
--     [C declaration]: @macro SDLK_SEMICOLON@, defined at @SDL3\/SDL_keycode.h 96:9@
sDLK_SEMICOLON :: BG.CUInt
sDLK_SEMICOLON = (59 :: BG.CUInt)

-- | \'\<\'
--
--     [C declaration]: @macro SDLK_LESS@, defined at @SDL3\/SDL_keycode.h 97:9@
sDLK_LESS :: BG.CUInt
sDLK_LESS = (60 :: BG.CUInt)

-- | \'=\'
--
--     [C declaration]: @macro SDLK_EQUALS@, defined at @SDL3\/SDL_keycode.h 98:9@
sDLK_EQUALS :: BG.CUInt
sDLK_EQUALS = (61 :: BG.CUInt)

-- | \'>\'
--
--     [C declaration]: @macro SDLK_GREATER@, defined at @SDL3\/SDL_keycode.h 99:9@
sDLK_GREATER :: BG.CUInt
sDLK_GREATER = (62 :: BG.CUInt)

-- | \'?\'
--
--     [C declaration]: @macro SDLK_QUESTION@, defined at @SDL3\/SDL_keycode.h 100:9@
sDLK_QUESTION :: BG.CUInt
sDLK_QUESTION = (63 :: BG.CUInt)

-- | \'\@\'
--
--     [C declaration]: @macro SDLK_AT@, defined at @SDL3\/SDL_keycode.h 101:9@
sDLK_AT :: BG.CUInt
sDLK_AT = (64 :: BG.CUInt)

-- | \'[\'
--
--     [C declaration]: @macro SDLK_LEFTBRACKET@, defined at @SDL3\/SDL_keycode.h 102:9@
sDLK_LEFTBRACKET :: BG.CUInt
sDLK_LEFTBRACKET = (91 :: BG.CUInt)

-- | \'\\\'
--
--     [C declaration]: @macro SDLK_BACKSLASH@, defined at @SDL3\/SDL_keycode.h 103:9@
sDLK_BACKSLASH :: BG.CUInt
sDLK_BACKSLASH = (92 :: BG.CUInt)

-- | \']\'
--
--     [C declaration]: @macro SDLK_RIGHTBRACKET@, defined at @SDL3\/SDL_keycode.h 104:9@
sDLK_RIGHTBRACKET :: BG.CUInt
sDLK_RIGHTBRACKET = (93 :: BG.CUInt)

-- | \'^\'
--
--     [C declaration]: @macro SDLK_CARET@, defined at @SDL3\/SDL_keycode.h 105:9@
sDLK_CARET :: BG.CUInt
sDLK_CARET = (94 :: BG.CUInt)

-- | \'_\'
--
--     [C declaration]: @macro SDLK_UNDERSCORE@, defined at @SDL3\/SDL_keycode.h 106:9@
sDLK_UNDERSCORE :: BG.CUInt
sDLK_UNDERSCORE = (95 :: BG.CUInt)

-- | \'\`\' *\/ \#define SDLK_A \/**\< \'a\'
--
--     [C declaration]: @macro SDLK_GRAVE@, defined at @SDL3\/SDL_keycode.h 107:9@
sDLK_GRAVE :: BG.CUInt
sDLK_GRAVE = (96 :: BG.CUInt)

-- | [C declaration]: @macro SDLK_A@, defined at @SDL3\/SDL_keycode.h 108:9@
sDLK_A :: BG.CUInt
sDLK_A = (97 :: BG.CUInt)

-- | \'b\'
--
--     [C declaration]: @macro SDLK_B@, defined at @SDL3\/SDL_keycode.h 109:9@
sDLK_B :: BG.CUInt
sDLK_B = (98 :: BG.CUInt)

-- | \'c\'
--
--     [C declaration]: @macro SDLK_C@, defined at @SDL3\/SDL_keycode.h 110:9@
sDLK_C :: BG.CUInt
sDLK_C = (99 :: BG.CUInt)

-- | \'d\'
--
--     [C declaration]: @macro SDLK_D@, defined at @SDL3\/SDL_keycode.h 111:9@
sDLK_D :: BG.CUInt
sDLK_D = (100 :: BG.CUInt)

-- | \'e\'
--
--     [C declaration]: @macro SDLK_E@, defined at @SDL3\/SDL_keycode.h 112:9@
sDLK_E :: BG.CUInt
sDLK_E = (101 :: BG.CUInt)

-- | \'f\'
--
--     [C declaration]: @macro SDLK_F@, defined at @SDL3\/SDL_keycode.h 113:9@
sDLK_F :: BG.CUInt
sDLK_F = (102 :: BG.CUInt)

-- | \'g\'
--
--     [C declaration]: @macro SDLK_G@, defined at @SDL3\/SDL_keycode.h 114:9@
sDLK_G :: BG.CUInt
sDLK_G = (103 :: BG.CUInt)

-- | \'h\'
--
--     [C declaration]: @macro SDLK_H@, defined at @SDL3\/SDL_keycode.h 115:9@
sDLK_H :: BG.CUInt
sDLK_H = (104 :: BG.CUInt)

-- | \'i\'
--
--     [C declaration]: @macro SDLK_I@, defined at @SDL3\/SDL_keycode.h 116:9@
sDLK_I :: BG.CUInt
sDLK_I = (105 :: BG.CUInt)

-- | \'j\'
--
--     [C declaration]: @macro SDLK_J@, defined at @SDL3\/SDL_keycode.h 117:9@
sDLK_J :: BG.CUInt
sDLK_J = (106 :: BG.CUInt)

-- | \'k\'
--
--     [C declaration]: @macro SDLK_K@, defined at @SDL3\/SDL_keycode.h 118:9@
sDLK_K :: BG.CUInt
sDLK_K = (107 :: BG.CUInt)

-- | \'l\'
--
--     [C declaration]: @macro SDLK_L@, defined at @SDL3\/SDL_keycode.h 119:9@
sDLK_L :: BG.CUInt
sDLK_L = (108 :: BG.CUInt)

-- | \'m\'
--
--     [C declaration]: @macro SDLK_M@, defined at @SDL3\/SDL_keycode.h 120:9@
sDLK_M :: BG.CUInt
sDLK_M = (109 :: BG.CUInt)

-- | \'n\'
--
--     [C declaration]: @macro SDLK_N@, defined at @SDL3\/SDL_keycode.h 121:9@
sDLK_N :: BG.CUInt
sDLK_N = (110 :: BG.CUInt)

-- | \'o\'
--
--     [C declaration]: @macro SDLK_O@, defined at @SDL3\/SDL_keycode.h 122:9@
sDLK_O :: BG.CUInt
sDLK_O = (111 :: BG.CUInt)

-- | \'p\'
--
--     [C declaration]: @macro SDLK_P@, defined at @SDL3\/SDL_keycode.h 123:9@
sDLK_P :: BG.CUInt
sDLK_P = (112 :: BG.CUInt)

-- | \'q\'
--
--     [C declaration]: @macro SDLK_Q@, defined at @SDL3\/SDL_keycode.h 124:9@
sDLK_Q :: BG.CUInt
sDLK_Q = (113 :: BG.CUInt)

-- | \'r\'
--
--     [C declaration]: @macro SDLK_R@, defined at @SDL3\/SDL_keycode.h 125:9@
sDLK_R :: BG.CUInt
sDLK_R = (114 :: BG.CUInt)

-- | \'s\'
--
--     [C declaration]: @macro SDLK_S@, defined at @SDL3\/SDL_keycode.h 126:9@
sDLK_S :: BG.CUInt
sDLK_S = (115 :: BG.CUInt)

-- | \'t\'
--
--     [C declaration]: @macro SDLK_T@, defined at @SDL3\/SDL_keycode.h 127:9@
sDLK_T :: BG.CUInt
sDLK_T = (116 :: BG.CUInt)

-- | \'u\'
--
--     [C declaration]: @macro SDLK_U@, defined at @SDL3\/SDL_keycode.h 128:9@
sDLK_U :: BG.CUInt
sDLK_U = (117 :: BG.CUInt)

-- | \'v\'
--
--     [C declaration]: @macro SDLK_V@, defined at @SDL3\/SDL_keycode.h 129:9@
sDLK_V :: BG.CUInt
sDLK_V = (118 :: BG.CUInt)

-- | \'w\'
--
--     [C declaration]: @macro SDLK_W@, defined at @SDL3\/SDL_keycode.h 130:9@
sDLK_W :: BG.CUInt
sDLK_W = (119 :: BG.CUInt)

-- | \'x\'
--
--     [C declaration]: @macro SDLK_X@, defined at @SDL3\/SDL_keycode.h 131:9@
sDLK_X :: BG.CUInt
sDLK_X = (120 :: BG.CUInt)

-- | \'y\'
--
--     [C declaration]: @macro SDLK_Y@, defined at @SDL3\/SDL_keycode.h 132:9@
sDLK_Y :: BG.CUInt
sDLK_Y = (121 :: BG.CUInt)

-- | \'z\'
--
--     [C declaration]: @macro SDLK_Z@, defined at @SDL3\/SDL_keycode.h 133:9@
sDLK_Z :: BG.CUInt
sDLK_Z = (122 :: BG.CUInt)

-- | \'{\'
--
--     [C declaration]: @macro SDLK_LEFTBRACE@, defined at @SDL3\/SDL_keycode.h 134:9@
sDLK_LEFTBRACE :: BG.CUInt
sDLK_LEFTBRACE = (123 :: BG.CUInt)

-- | \'|\'
--
--     [C declaration]: @macro SDLK_PIPE@, defined at @SDL3\/SDL_keycode.h 135:9@
sDLK_PIPE :: BG.CUInt
sDLK_PIPE = (124 :: BG.CUInt)

-- | \'}\'
--
--     [C declaration]: @macro SDLK_RIGHTBRACE@, defined at @SDL3\/SDL_keycode.h 136:9@
sDLK_RIGHTBRACE :: BG.CUInt
sDLK_RIGHTBRACE = (125 :: BG.CUInt)

-- | \'~\'
--
--     [C declaration]: @macro SDLK_TILDE@, defined at @SDL3\/SDL_keycode.h 137:9@
sDLK_TILDE :: BG.CUInt
sDLK_TILDE = (126 :: BG.CUInt)

-- | \'\\x7F\'
--
--     [C declaration]: @macro SDLK_DELETE@, defined at @SDL3\/SDL_keycode.h 138:9@
sDLK_DELETE :: BG.CUInt
sDLK_DELETE = (127 :: BG.CUInt)

-- | \'\\xB1\'
--
--     [C declaration]: @macro SDLK_PLUSMINUS@, defined at @SDL3\/SDL_keycode.h 139:9@
sDLK_PLUSMINUS :: BG.CUInt
sDLK_PLUSMINUS = (177 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK)@
--
--     [C declaration]: @macro SDLK_CAPSLOCK@, defined at @SDL3\/SDL_keycode.h 140:9@
sDLK_CAPSLOCK :: BG.CUInt
sDLK_CAPSLOCK = (1073741881 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1)@
--
--     [C declaration]: @macro SDLK_F1@, defined at @SDL3\/SDL_keycode.h 141:9@
sDLK_F1 :: BG.CUInt
sDLK_F1 = (1073741882 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2)@
--
--     [C declaration]: @macro SDLK_F2@, defined at @SDL3\/SDL_keycode.h 142:9@
sDLK_F2 :: BG.CUInt
sDLK_F2 = (1073741883 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3)@
--
--     [C declaration]: @macro SDLK_F3@, defined at @SDL3\/SDL_keycode.h 143:9@
sDLK_F3 :: BG.CUInt
sDLK_F3 = (1073741884 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4)@
--
--     [C declaration]: @macro SDLK_F4@, defined at @SDL3\/SDL_keycode.h 144:9@
sDLK_F4 :: BG.CUInt
sDLK_F4 = (1073741885 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5)@
--
--     [C declaration]: @macro SDLK_F5@, defined at @SDL3\/SDL_keycode.h 145:9@
sDLK_F5 :: BG.CUInt
sDLK_F5 = (1073741886 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6)@
--
--     [C declaration]: @macro SDLK_F6@, defined at @SDL3\/SDL_keycode.h 146:9@
sDLK_F6 :: BG.CUInt
sDLK_F6 = (1073741887 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7)@
--
--     [C declaration]: @macro SDLK_F7@, defined at @SDL3\/SDL_keycode.h 147:9@
sDLK_F7 :: BG.CUInt
sDLK_F7 = (1073741888 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8)@
--
--     [C declaration]: @macro SDLK_F8@, defined at @SDL3\/SDL_keycode.h 148:9@
sDLK_F8 :: BG.CUInt
sDLK_F8 = (1073741889 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9)@
--
--     [C declaration]: @macro SDLK_F9@, defined at @SDL3\/SDL_keycode.h 149:9@
sDLK_F9 :: BG.CUInt
sDLK_F9 = (1073741890 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10)@
--
--     [C declaration]: @macro SDLK_F10@, defined at @SDL3\/SDL_keycode.h 150:9@
sDLK_F10 :: BG.CUInt
sDLK_F10 = (1073741891 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11)@
--
--     [C declaration]: @macro SDLK_F11@, defined at @SDL3\/SDL_keycode.h 151:9@
sDLK_F11 :: BG.CUInt
sDLK_F11 = (1073741892 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12)@
--
--     [C declaration]: @macro SDLK_F12@, defined at @SDL3\/SDL_keycode.h 152:9@
sDLK_F12 :: BG.CUInt
sDLK_F12 = (1073741893 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)@
--
--     [C declaration]: @macro SDLK_PRINTSCREEN@, defined at @SDL3\/SDL_keycode.h 153:9@
sDLK_PRINTSCREEN :: BG.CUInt
sDLK_PRINTSCREEN = (1073741894 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK)@
--
--     [C declaration]: @macro SDLK_SCROLLLOCK@, defined at @SDL3\/SDL_keycode.h 154:9@
sDLK_SCROLLLOCK :: BG.CUInt
sDLK_SCROLLLOCK = (1073741895 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE)@
--
--     [C declaration]: @macro SDLK_PAUSE@, defined at @SDL3\/SDL_keycode.h 155:9@
sDLK_PAUSE :: BG.CUInt
sDLK_PAUSE = (1073741896 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT)@
--
--     [C declaration]: @macro SDLK_INSERT@, defined at @SDL3\/SDL_keycode.h 156:9@
sDLK_INSERT :: BG.CUInt
sDLK_INSERT = (1073741897 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME)@
--
--     [C declaration]: @macro SDLK_HOME@, defined at @SDL3\/SDL_keycode.h 157:9@
sDLK_HOME :: BG.CUInt
sDLK_HOME = (1073741898 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP)@
--
--     [C declaration]: @macro SDLK_PAGEUP@, defined at @SDL3\/SDL_keycode.h 158:9@
sDLK_PAGEUP :: BG.CUInt
sDLK_PAGEUP = (1073741899 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END)@
--
--     [C declaration]: @macro SDLK_END@, defined at @SDL3\/SDL_keycode.h 159:9@
sDLK_END :: BG.CUInt
sDLK_END = (1073741901 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN)@
--
--     [C declaration]: @macro SDLK_PAGEDOWN@, defined at @SDL3\/SDL_keycode.h 160:9@
sDLK_PAGEDOWN :: BG.CUInt
sDLK_PAGEDOWN = (1073741902 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT)@
--
--     [C declaration]: @macro SDLK_RIGHT@, defined at @SDL3\/SDL_keycode.h 161:9@
sDLK_RIGHT :: BG.CUInt
sDLK_RIGHT = (1073741903 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT)@
--
--     [C declaration]: @macro SDLK_LEFT@, defined at @SDL3\/SDL_keycode.h 162:9@
sDLK_LEFT :: BG.CUInt
sDLK_LEFT = (1073741904 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN)@
--
--     [C declaration]: @macro SDLK_DOWN@, defined at @SDL3\/SDL_keycode.h 163:9@
sDLK_DOWN :: BG.CUInt
sDLK_DOWN = (1073741905 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP)@
--
--     [C declaration]: @macro SDLK_UP@, defined at @SDL3\/SDL_keycode.h 164:9@
sDLK_UP :: BG.CUInt
sDLK_UP = (1073741906 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)@
--
--     [C declaration]: @macro SDLK_NUMLOCKCLEAR@, defined at @SDL3\/SDL_keycode.h 165:9@
sDLK_NUMLOCKCLEAR :: BG.CUInt
sDLK_NUMLOCKCLEAR = (1073741907 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)@
--
--     [C declaration]: @macro SDLK_KP_DIVIDE@, defined at @SDL3\/SDL_keycode.h 166:9@
sDLK_KP_DIVIDE :: BG.CUInt
sDLK_KP_DIVIDE = (1073741908 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)@
--
--     [C declaration]: @macro SDLK_KP_MULTIPLY@, defined at @SDL3\/SDL_keycode.h 167:9@
sDLK_KP_MULTIPLY :: BG.CUInt
sDLK_KP_MULTIPLY = (1073741909 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)@
--
--     [C declaration]: @macro SDLK_KP_MINUS@, defined at @SDL3\/SDL_keycode.h 168:9@
sDLK_KP_MINUS :: BG.CUInt
sDLK_KP_MINUS = (1073741910 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)@
--
--     [C declaration]: @macro SDLK_KP_PLUS@, defined at @SDL3\/SDL_keycode.h 169:9@
sDLK_KP_PLUS :: BG.CUInt
sDLK_KP_PLUS = (1073741911 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER)@
--
--     [C declaration]: @macro SDLK_KP_ENTER@, defined at @SDL3\/SDL_keycode.h 170:9@
sDLK_KP_ENTER :: BG.CUInt
sDLK_KP_ENTER = (1073741912 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1)@
--
--     [C declaration]: @macro SDLK_KP_1@, defined at @SDL3\/SDL_keycode.h 171:9@
sDLK_KP_1 :: BG.CUInt
sDLK_KP_1 = (1073741913 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2)@
--
--     [C declaration]: @macro SDLK_KP_2@, defined at @SDL3\/SDL_keycode.h 172:9@
sDLK_KP_2 :: BG.CUInt
sDLK_KP_2 = (1073741914 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3)@
--
--     [C declaration]: @macro SDLK_KP_3@, defined at @SDL3\/SDL_keycode.h 173:9@
sDLK_KP_3 :: BG.CUInt
sDLK_KP_3 = (1073741915 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4)@
--
--     [C declaration]: @macro SDLK_KP_4@, defined at @SDL3\/SDL_keycode.h 174:9@
sDLK_KP_4 :: BG.CUInt
sDLK_KP_4 = (1073741916 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5)@
--
--     [C declaration]: @macro SDLK_KP_5@, defined at @SDL3\/SDL_keycode.h 175:9@
sDLK_KP_5 :: BG.CUInt
sDLK_KP_5 = (1073741917 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6)@
--
--     [C declaration]: @macro SDLK_KP_6@, defined at @SDL3\/SDL_keycode.h 176:9@
sDLK_KP_6 :: BG.CUInt
sDLK_KP_6 = (1073741918 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7)@
--
--     [C declaration]: @macro SDLK_KP_7@, defined at @SDL3\/SDL_keycode.h 177:9@
sDLK_KP_7 :: BG.CUInt
sDLK_KP_7 = (1073741919 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8)@
--
--     [C declaration]: @macro SDLK_KP_8@, defined at @SDL3\/SDL_keycode.h 178:9@
sDLK_KP_8 :: BG.CUInt
sDLK_KP_8 = (1073741920 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9)@
--
--     [C declaration]: @macro SDLK_KP_9@, defined at @SDL3\/SDL_keycode.h 179:9@
sDLK_KP_9 :: BG.CUInt
sDLK_KP_9 = (1073741921 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0)@
--
--     [C declaration]: @macro SDLK_KP_0@, defined at @SDL3\/SDL_keycode.h 180:9@
sDLK_KP_0 :: BG.CUInt
sDLK_KP_0 = (1073741922 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)@
--
--     [C declaration]: @macro SDLK_KP_PERIOD@, defined at @SDL3\/SDL_keycode.h 181:9@
sDLK_KP_PERIOD :: BG.CUInt
sDLK_KP_PERIOD = (1073741923 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)@
--
--     [C declaration]: @macro SDLK_APPLICATION@, defined at @SDL3\/SDL_keycode.h 182:9@
sDLK_APPLICATION :: BG.CUInt
sDLK_APPLICATION = (1073741925 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)@
--
--     [C declaration]: @macro SDLK_POWER@, defined at @SDL3\/SDL_keycode.h 183:9@
sDLK_POWER :: BG.CUInt
sDLK_POWER = (1073741926 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)@
--
--     [C declaration]: @macro SDLK_KP_EQUALS@, defined at @SDL3\/SDL_keycode.h 184:9@
sDLK_KP_EQUALS :: BG.CUInt
sDLK_KP_EQUALS = (1073741927 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13)@
--
--     [C declaration]: @macro SDLK_F13@, defined at @SDL3\/SDL_keycode.h 185:9@
sDLK_F13 :: BG.CUInt
sDLK_F13 = (1073741928 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14)@
--
--     [C declaration]: @macro SDLK_F14@, defined at @SDL3\/SDL_keycode.h 186:9@
sDLK_F14 :: BG.CUInt
sDLK_F14 = (1073741929 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15)@
--
--     [C declaration]: @macro SDLK_F15@, defined at @SDL3\/SDL_keycode.h 187:9@
sDLK_F15 :: BG.CUInt
sDLK_F15 = (1073741930 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16)@
--
--     [C declaration]: @macro SDLK_F16@, defined at @SDL3\/SDL_keycode.h 188:9@
sDLK_F16 :: BG.CUInt
sDLK_F16 = (1073741931 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17)@
--
--     [C declaration]: @macro SDLK_F17@, defined at @SDL3\/SDL_keycode.h 189:9@
sDLK_F17 :: BG.CUInt
sDLK_F17 = (1073741932 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18)@
--
--     [C declaration]: @macro SDLK_F18@, defined at @SDL3\/SDL_keycode.h 190:9@
sDLK_F18 :: BG.CUInt
sDLK_F18 = (1073741933 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19)@
--
--     [C declaration]: @macro SDLK_F19@, defined at @SDL3\/SDL_keycode.h 191:9@
sDLK_F19 :: BG.CUInt
sDLK_F19 = (1073741934 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20)@
--
--     [C declaration]: @macro SDLK_F20@, defined at @SDL3\/SDL_keycode.h 192:9@
sDLK_F20 :: BG.CUInt
sDLK_F20 = (1073741935 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21)@
--
--     [C declaration]: @macro SDLK_F21@, defined at @SDL3\/SDL_keycode.h 193:9@
sDLK_F21 :: BG.CUInt
sDLK_F21 = (1073741936 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22)@
--
--     [C declaration]: @macro SDLK_F22@, defined at @SDL3\/SDL_keycode.h 194:9@
sDLK_F22 :: BG.CUInt
sDLK_F22 = (1073741937 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23)@
--
--     [C declaration]: @macro SDLK_F23@, defined at @SDL3\/SDL_keycode.h 195:9@
sDLK_F23 :: BG.CUInt
sDLK_F23 = (1073741938 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24)@
--
--     [C declaration]: @macro SDLK_F24@, defined at @SDL3\/SDL_keycode.h 196:9@
sDLK_F24 :: BG.CUInt
sDLK_F24 = (1073741939 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE)@
--
--     [C declaration]: @macro SDLK_EXECUTE@, defined at @SDL3\/SDL_keycode.h 197:9@
sDLK_EXECUTE :: BG.CUInt
sDLK_EXECUTE = (1073741940 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP)@
--
--     [C declaration]: @macro SDLK_HELP@, defined at @SDL3\/SDL_keycode.h 198:9@
sDLK_HELP :: BG.CUInt
sDLK_HELP = (1073741941 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU)@
--
--     [C declaration]: @macro SDLK_MENU@, defined at @SDL3\/SDL_keycode.h 199:9@
sDLK_MENU :: BG.CUInt
sDLK_MENU = (1073741942 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT)@
--
--     [C declaration]: @macro SDLK_SELECT@, defined at @SDL3\/SDL_keycode.h 200:9@
sDLK_SELECT :: BG.CUInt
sDLK_SELECT = (1073741943 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP)@
--
--     [C declaration]: @macro SDLK_STOP@, defined at @SDL3\/SDL_keycode.h 201:9@
sDLK_STOP :: BG.CUInt
sDLK_STOP = (1073741944 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)@
--
--     [C declaration]: @macro SDLK_AGAIN@, defined at @SDL3\/SDL_keycode.h 202:9@
sDLK_AGAIN :: BG.CUInt
sDLK_AGAIN = (1073741945 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO)@
--
--     [C declaration]: @macro SDLK_UNDO@, defined at @SDL3\/SDL_keycode.h 203:9@
sDLK_UNDO :: BG.CUInt
sDLK_UNDO = (1073741946 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)@
--
--     [C declaration]: @macro SDLK_CUT@, defined at @SDL3\/SDL_keycode.h 204:9@
sDLK_CUT :: BG.CUInt
sDLK_CUT = (1073741947 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)@
--
--     [C declaration]: @macro SDLK_COPY@, defined at @SDL3\/SDL_keycode.h 205:9@
sDLK_COPY :: BG.CUInt
sDLK_COPY = (1073741948 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)@
--
--     [C declaration]: @macro SDLK_PASTE@, defined at @SDL3\/SDL_keycode.h 206:9@
sDLK_PASTE :: BG.CUInt
sDLK_PASTE = (1073741949 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND)@
--
--     [C declaration]: @macro SDLK_FIND@, defined at @SDL3\/SDL_keycode.h 207:9@
sDLK_FIND :: BG.CUInt
sDLK_FIND = (1073741950 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)@
--
--     [C declaration]: @macro SDLK_MUTE@, defined at @SDL3\/SDL_keycode.h 208:9@
sDLK_MUTE :: BG.CUInt
sDLK_MUTE = (1073741951 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)@
--
--     [C declaration]: @macro SDLK_VOLUMEUP@, defined at @SDL3\/SDL_keycode.h 209:9@
sDLK_VOLUMEUP :: BG.CUInt
sDLK_VOLUMEUP = (1073741952 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)@
--
--     [C declaration]: @macro SDLK_VOLUMEDOWN@, defined at @SDL3\/SDL_keycode.h 210:9@
sDLK_VOLUMEDOWN :: BG.CUInt
sDLK_VOLUMEDOWN = (1073741953 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)@
--
--     [C declaration]: @macro SDLK_KP_COMMA@, defined at @SDL3\/SDL_keycode.h 211:9@
sDLK_KP_COMMA :: BG.CUInt
sDLK_KP_COMMA = (1073741957 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)@
--
--     [C declaration]: @macro SDLK_KP_EQUALSAS400@, defined at @SDL3\/SDL_keycode.h 212:9@
sDLK_KP_EQUALSAS400 :: BG.CUInt
sDLK_KP_EQUALSAS400 = (1073741958 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)@
--
--     [C declaration]: @macro SDLK_ALTERASE@, defined at @SDL3\/SDL_keycode.h 213:9@
sDLK_ALTERASE :: BG.CUInt
sDLK_ALTERASE = (1073741977 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)@
--
--     [C declaration]: @macro SDLK_SYSREQ@, defined at @SDL3\/SDL_keycode.h 214:9@
sDLK_SYSREQ :: BG.CUInt
sDLK_SYSREQ = (1073741978 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL)@
--
--     [C declaration]: @macro SDLK_CANCEL@, defined at @SDL3\/SDL_keycode.h 215:9@
sDLK_CANCEL :: BG.CUInt
sDLK_CANCEL = (1073741979 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR)@
--
--     [C declaration]: @macro SDLK_CLEAR@, defined at @SDL3\/SDL_keycode.h 216:9@
sDLK_CLEAR :: BG.CUInt
sDLK_CLEAR = (1073741980 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR)@
--
--     [C declaration]: @macro SDLK_PRIOR@, defined at @SDL3\/SDL_keycode.h 217:9@
sDLK_PRIOR :: BG.CUInt
sDLK_PRIOR = (1073741981 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)@
--
--     [C declaration]: @macro SDLK_RETURN2@, defined at @SDL3\/SDL_keycode.h 218:9@
sDLK_RETURN2 :: BG.CUInt
sDLK_RETURN2 = (1073741982 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR)@
--
--     [C declaration]: @macro SDLK_SEPARATOR@, defined at @SDL3\/SDL_keycode.h 219:9@
sDLK_SEPARATOR :: BG.CUInt
sDLK_SEPARATOR = (1073741983 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)@
--
--     [C declaration]: @macro SDLK_OUT@, defined at @SDL3\/SDL_keycode.h 220:9@
sDLK_OUT :: BG.CUInt
sDLK_OUT = (1073741984 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)@
--
--     [C declaration]: @macro SDLK_OPER@, defined at @SDL3\/SDL_keycode.h 221:9@
sDLK_OPER :: BG.CUInt
sDLK_OPER = (1073741985 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)@
--
--     [C declaration]: @macro SDLK_CLEARAGAIN@, defined at @SDL3\/SDL_keycode.h 222:9@
sDLK_CLEARAGAIN :: BG.CUInt
sDLK_CLEARAGAIN = (1073741986 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)@
--
--     [C declaration]: @macro SDLK_CRSEL@, defined at @SDL3\/SDL_keycode.h 223:9@
sDLK_CRSEL :: BG.CUInt
sDLK_CRSEL = (1073741987 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)@
--
--     [C declaration]: @macro SDLK_EXSEL@, defined at @SDL3\/SDL_keycode.h 224:9@
sDLK_EXSEL :: BG.CUInt
sDLK_EXSEL = (1073741988 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)@
--
--     [C declaration]: @macro SDLK_KP_00@, defined at @SDL3\/SDL_keycode.h 225:9@
sDLK_KP_00 :: BG.CUInt
sDLK_KP_00 = (1073742000 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)@
--
--     [C declaration]: @macro SDLK_KP_000@, defined at @SDL3\/SDL_keycode.h 226:9@
sDLK_KP_000 :: BG.CUInt
sDLK_KP_000 = (1073742001 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)@
--
--     [C declaration]: @macro SDLK_THOUSANDSSEPARATOR@, defined at @SDL3\/SDL_keycode.h 227:9@
sDLK_THOUSANDSSEPARATOR :: BG.CUInt
sDLK_THOUSANDSSEPARATOR = (1073742002 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)@
--
--     [C declaration]: @macro SDLK_DECIMALSEPARATOR@, defined at @SDL3\/SDL_keycode.h 228:9@
sDLK_DECIMALSEPARATOR :: BG.CUInt
sDLK_DECIMALSEPARATOR = (1073742003 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)@
--
--     [C declaration]: @macro SDLK_CURRENCYUNIT@, defined at @SDL3\/SDL_keycode.h 229:9@
sDLK_CURRENCYUNIT :: BG.CUInt
sDLK_CURRENCYUNIT = (1073742004 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)@
--
--     [C declaration]: @macro SDLK_CURRENCYSUBUNIT@, defined at @SDL3\/SDL_keycode.h 230:9@
sDLK_CURRENCYSUBUNIT :: BG.CUInt
sDLK_CURRENCYSUBUNIT = (1073742005 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)@
--
--     [C declaration]: @macro SDLK_KP_LEFTPAREN@, defined at @SDL3\/SDL_keycode.h 231:9@
sDLK_KP_LEFTPAREN :: BG.CUInt
sDLK_KP_LEFTPAREN = (1073742006 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)@
--
--     [C declaration]: @macro SDLK_KP_RIGHTPAREN@, defined at @SDL3\/SDL_keycode.h 232:9@
sDLK_KP_RIGHTPAREN :: BG.CUInt
sDLK_KP_RIGHTPAREN = (1073742007 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)@
--
--     [C declaration]: @macro SDLK_KP_LEFTBRACE@, defined at @SDL3\/SDL_keycode.h 233:9@
sDLK_KP_LEFTBRACE :: BG.CUInt
sDLK_KP_LEFTBRACE = (1073742008 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)@
--
--     [C declaration]: @macro SDLK_KP_RIGHTBRACE@, defined at @SDL3\/SDL_keycode.h 234:9@
sDLK_KP_RIGHTBRACE :: BG.CUInt
sDLK_KP_RIGHTBRACE = (1073742009 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB)@
--
--     [C declaration]: @macro SDLK_KP_TAB@, defined at @SDL3\/SDL_keycode.h 235:9@
sDLK_KP_TAB :: BG.CUInt
sDLK_KP_TAB = (1073742010 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)@
--
--     [C declaration]: @macro SDLK_KP_BACKSPACE@, defined at @SDL3\/SDL_keycode.h 236:9@
sDLK_KP_BACKSPACE :: BG.CUInt
sDLK_KP_BACKSPACE = (1073742011 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)@
--
--     [C declaration]: @macro SDLK_KP_A@, defined at @SDL3\/SDL_keycode.h 237:9@
sDLK_KP_A :: BG.CUInt
sDLK_KP_A = (1073742012 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)@
--
--     [C declaration]: @macro SDLK_KP_B@, defined at @SDL3\/SDL_keycode.h 238:9@
sDLK_KP_B :: BG.CUInt
sDLK_KP_B = (1073742013 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)@
--
--     [C declaration]: @macro SDLK_KP_C@, defined at @SDL3\/SDL_keycode.h 239:9@
sDLK_KP_C :: BG.CUInt
sDLK_KP_C = (1073742014 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)@
--
--     [C declaration]: @macro SDLK_KP_D@, defined at @SDL3\/SDL_keycode.h 240:9@
sDLK_KP_D :: BG.CUInt
sDLK_KP_D = (1073742015 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)@
--
--     [C declaration]: @macro SDLK_KP_E@, defined at @SDL3\/SDL_keycode.h 241:9@
sDLK_KP_E :: BG.CUInt
sDLK_KP_E = (1073742016 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)@
--
--     [C declaration]: @macro SDLK_KP_F@, defined at @SDL3\/SDL_keycode.h 242:9@
sDLK_KP_F :: BG.CUInt
sDLK_KP_F = (1073742017 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)@
--
--     [C declaration]: @macro SDLK_KP_XOR@, defined at @SDL3\/SDL_keycode.h 243:9@
sDLK_KP_XOR :: BG.CUInt
sDLK_KP_XOR = (1073742018 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)@
--
--     [C declaration]: @macro SDLK_KP_POWER@, defined at @SDL3\/SDL_keycode.h 244:9@
sDLK_KP_POWER :: BG.CUInt
sDLK_KP_POWER = (1073742019 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)@
--
--     [C declaration]: @macro SDLK_KP_PERCENT@, defined at @SDL3\/SDL_keycode.h 245:9@
sDLK_KP_PERCENT :: BG.CUInt
sDLK_KP_PERCENT = (1073742020 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)@
--
--     [C declaration]: @macro SDLK_KP_LESS@, defined at @SDL3\/SDL_keycode.h 246:9@
sDLK_KP_LESS :: BG.CUInt
sDLK_KP_LESS = (1073742021 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)@
--
--     [C declaration]: @macro SDLK_KP_GREATER@, defined at @SDL3\/SDL_keycode.h 247:9@
sDLK_KP_GREATER :: BG.CUInt
sDLK_KP_GREATER = (1073742022 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)@
--
--     [C declaration]: @macro SDLK_KP_AMPERSAND@, defined at @SDL3\/SDL_keycode.h 248:9@
sDLK_KP_AMPERSAND :: BG.CUInt
sDLK_KP_AMPERSAND = (1073742023 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)@
--
--     [C declaration]: @macro SDLK_KP_DBLAMPERSAND@, defined at @SDL3\/SDL_keycode.h 249:9@
sDLK_KP_DBLAMPERSAND :: BG.CUInt
sDLK_KP_DBLAMPERSAND = (1073742024 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)@
--
--     [C declaration]: @macro SDLK_KP_VERTICALBAR@, defined at @SDL3\/SDL_keycode.h 250:9@
sDLK_KP_VERTICALBAR :: BG.CUInt
sDLK_KP_VERTICALBAR = (1073742025 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)@
--
--     [C declaration]: @macro SDLK_KP_DBLVERTICALBAR@, defined at @SDL3\/SDL_keycode.h 251:9@
sDLK_KP_DBLVERTICALBAR :: BG.CUInt
sDLK_KP_DBLVERTICALBAR = (1073742026 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)@
--
--     [C declaration]: @macro SDLK_KP_COLON@, defined at @SDL3\/SDL_keycode.h 252:9@
sDLK_KP_COLON :: BG.CUInt
sDLK_KP_COLON = (1073742027 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)@
--
--     [C declaration]: @macro SDLK_KP_HASH@, defined at @SDL3\/SDL_keycode.h 253:9@
sDLK_KP_HASH :: BG.CUInt
sDLK_KP_HASH = (1073742028 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)@
--
--     [C declaration]: @macro SDLK_KP_SPACE@, defined at @SDL3\/SDL_keycode.h 254:9@
sDLK_KP_SPACE :: BG.CUInt
sDLK_KP_SPACE = (1073742029 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)@
--
--     [C declaration]: @macro SDLK_KP_AT@, defined at @SDL3\/SDL_keycode.h 255:9@
sDLK_KP_AT :: BG.CUInt
sDLK_KP_AT = (1073742030 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)@
--
--     [C declaration]: @macro SDLK_KP_EXCLAM@, defined at @SDL3\/SDL_keycode.h 256:9@
sDLK_KP_EXCLAM :: BG.CUInt
sDLK_KP_EXCLAM = (1073742031 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)@
--
--     [C declaration]: @macro SDLK_KP_MEMSTORE@, defined at @SDL3\/SDL_keycode.h 257:9@
sDLK_KP_MEMSTORE :: BG.CUInt
sDLK_KP_MEMSTORE = (1073742032 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)@
--
--     [C declaration]: @macro SDLK_KP_MEMRECALL@, defined at @SDL3\/SDL_keycode.h 258:9@
sDLK_KP_MEMRECALL :: BG.CUInt
sDLK_KP_MEMRECALL = (1073742033 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)@
--
--     [C declaration]: @macro SDLK_KP_MEMCLEAR@, defined at @SDL3\/SDL_keycode.h 259:9@
sDLK_KP_MEMCLEAR :: BG.CUInt
sDLK_KP_MEMCLEAR = (1073742034 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)@
--
--     [C declaration]: @macro SDLK_KP_MEMADD@, defined at @SDL3\/SDL_keycode.h 260:9@
sDLK_KP_MEMADD :: BG.CUInt
sDLK_KP_MEMADD = (1073742035 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)@
--
--     [C declaration]: @macro SDLK_KP_MEMSUBTRACT@, defined at @SDL3\/SDL_keycode.h 261:9@
sDLK_KP_MEMSUBTRACT :: BG.CUInt
sDLK_KP_MEMSUBTRACT = (1073742036 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)@
--
--     [C declaration]: @macro SDLK_KP_MEMMULTIPLY@, defined at @SDL3\/SDL_keycode.h 262:9@
sDLK_KP_MEMMULTIPLY :: BG.CUInt
sDLK_KP_MEMMULTIPLY = (1073742037 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)@
--
--     [C declaration]: @macro SDLK_KP_MEMDIVIDE@, defined at @SDL3\/SDL_keycode.h 263:9@
sDLK_KP_MEMDIVIDE :: BG.CUInt
sDLK_KP_MEMDIVIDE = (1073742038 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)@
--
--     [C declaration]: @macro SDLK_KP_PLUSMINUS@, defined at @SDL3\/SDL_keycode.h 264:9@
sDLK_KP_PLUSMINUS :: BG.CUInt
sDLK_KP_PLUSMINUS = (1073742039 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)@
--
--     [C declaration]: @macro SDLK_KP_CLEAR@, defined at @SDL3\/SDL_keycode.h 265:9@
sDLK_KP_CLEAR :: BG.CUInt
sDLK_KP_CLEAR = (1073742040 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)@
--
--     [C declaration]: @macro SDLK_KP_CLEARENTRY@, defined at @SDL3\/SDL_keycode.h 266:9@
sDLK_KP_CLEARENTRY :: BG.CUInt
sDLK_KP_CLEARENTRY = (1073742041 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)@
--
--     [C declaration]: @macro SDLK_KP_BINARY@, defined at @SDL3\/SDL_keycode.h 267:9@
sDLK_KP_BINARY :: BG.CUInt
sDLK_KP_BINARY = (1073742042 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)@
--
--     [C declaration]: @macro SDLK_KP_OCTAL@, defined at @SDL3\/SDL_keycode.h 268:9@
sDLK_KP_OCTAL :: BG.CUInt
sDLK_KP_OCTAL = (1073742043 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)@
--
--     [C declaration]: @macro SDLK_KP_DECIMAL@, defined at @SDL3\/SDL_keycode.h 269:9@
sDLK_KP_DECIMAL :: BG.CUInt
sDLK_KP_DECIMAL = (1073742044 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)@
--
--     [C declaration]: @macro SDLK_KP_HEXADECIMAL@, defined at @SDL3\/SDL_keycode.h 270:9@
sDLK_KP_HEXADECIMAL :: BG.CUInt
sDLK_KP_HEXADECIMAL = (1073742045 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL)@
--
--     [C declaration]: @macro SDLK_LCTRL@, defined at @SDL3\/SDL_keycode.h 271:9@
sDLK_LCTRL :: BG.CUInt
sDLK_LCTRL = (1073742048 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT)@
--
--     [C declaration]: @macro SDLK_LSHIFT@, defined at @SDL3\/SDL_keycode.h 272:9@
sDLK_LSHIFT :: BG.CUInt
sDLK_LSHIFT = (1073742049 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT)@
--
--     [C declaration]: @macro SDLK_LALT@, defined at @SDL3\/SDL_keycode.h 273:9@
sDLK_LALT :: BG.CUInt
sDLK_LALT = (1073742050 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI)@
--
--     [C declaration]: @macro SDLK_LGUI@, defined at @SDL3\/SDL_keycode.h 274:9@
sDLK_LGUI :: BG.CUInt
sDLK_LGUI = (1073742051 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL)@
--
--     [C declaration]: @macro SDLK_RCTRL@, defined at @SDL3\/SDL_keycode.h 275:9@
sDLK_RCTRL :: BG.CUInt
sDLK_RCTRL = (1073742052 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT)@
--
--     [C declaration]: @macro SDLK_RSHIFT@, defined at @SDL3\/SDL_keycode.h 276:9@
sDLK_RSHIFT :: BG.CUInt
sDLK_RSHIFT = (1073742053 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT)@
--
--     [C declaration]: @macro SDLK_RALT@, defined at @SDL3\/SDL_keycode.h 277:9@
sDLK_RALT :: BG.CUInt
sDLK_RALT = (1073742054 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI)@
--
--     [C declaration]: @macro SDLK_RGUI@, defined at @SDL3\/SDL_keycode.h 278:9@
sDLK_RGUI :: BG.CUInt
sDLK_RGUI = (1073742055 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE)@
--
--     [C declaration]: @macro SDLK_MODE@, defined at @SDL3\/SDL_keycode.h 279:9@
sDLK_MODE :: BG.CUInt
sDLK_MODE = (1073742081 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)@
--
--     [C declaration]: @macro SDLK_SLEEP@, defined at @SDL3\/SDL_keycode.h 280:9@
sDLK_SLEEP :: BG.CUInt
sDLK_SLEEP = (1073742082 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE)@
--
--     [C declaration]: @macro SDLK_WAKE@, defined at @SDL3\/SDL_keycode.h 281:9@
sDLK_WAKE :: BG.CUInt
sDLK_WAKE = (1073742083 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT)@
--
--     [C declaration]: @macro SDLK_CHANNEL_INCREMENT@, defined at @SDL3\/SDL_keycode.h 282:9@
sDLK_CHANNEL_INCREMENT :: BG.CUInt
sDLK_CHANNEL_INCREMENT = (1073742084 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT)@
--
--     [C declaration]: @macro SDLK_CHANNEL_DECREMENT@, defined at @SDL3\/SDL_keycode.h 283:9@
sDLK_CHANNEL_DECREMENT :: BG.CUInt
sDLK_CHANNEL_DECREMENT = (1073742085 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY)@
--
--     [C declaration]: @macro SDLK_MEDIA_PLAY@, defined at @SDL3\/SDL_keycode.h 284:9@
sDLK_MEDIA_PLAY :: BG.CUInt
sDLK_MEDIA_PLAY = (1073742086 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE)@
--
--     [C declaration]: @macro SDLK_MEDIA_PAUSE@, defined at @SDL3\/SDL_keycode.h 285:9@
sDLK_MEDIA_PAUSE :: BG.CUInt
sDLK_MEDIA_PAUSE = (1073742087 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD)@
--
--     [C declaration]: @macro SDLK_MEDIA_RECORD@, defined at @SDL3\/SDL_keycode.h 286:9@
sDLK_MEDIA_RECORD :: BG.CUInt
sDLK_MEDIA_RECORD = (1073742088 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD)@
--
--     [C declaration]: @macro SDLK_MEDIA_FAST_FORWARD@, defined at @SDL3\/SDL_keycode.h 287:9@
sDLK_MEDIA_FAST_FORWARD :: BG.CUInt
sDLK_MEDIA_FAST_FORWARD = (1073742089 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND)@
--
--     [C declaration]: @macro SDLK_MEDIA_REWIND@, defined at @SDL3\/SDL_keycode.h 288:9@
sDLK_MEDIA_REWIND :: BG.CUInt
sDLK_MEDIA_REWIND = (1073742090 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK)@
--
--     [C declaration]: @macro SDLK_MEDIA_NEXT_TRACK@, defined at @SDL3\/SDL_keycode.h 289:9@
sDLK_MEDIA_NEXT_TRACK :: BG.CUInt
sDLK_MEDIA_NEXT_TRACK = (1073742091 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK)@
--
--     [C declaration]: @macro SDLK_MEDIA_PREVIOUS_TRACK@, defined at @SDL3\/SDL_keycode.h 290:9@
sDLK_MEDIA_PREVIOUS_TRACK :: BG.CUInt
sDLK_MEDIA_PREVIOUS_TRACK = (1073742092 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP)@
--
--     [C declaration]: @macro SDLK_MEDIA_STOP@, defined at @SDL3\/SDL_keycode.h 291:9@
sDLK_MEDIA_STOP :: BG.CUInt
sDLK_MEDIA_STOP = (1073742093 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT)@
--
--     [C declaration]: @macro SDLK_MEDIA_EJECT@, defined at @SDL3\/SDL_keycode.h 292:9@
sDLK_MEDIA_EJECT :: BG.CUInt
sDLK_MEDIA_EJECT = (1073742094 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE)@
--
--     [C declaration]: @macro SDLK_MEDIA_PLAY_PAUSE@, defined at @SDL3\/SDL_keycode.h 293:9@
sDLK_MEDIA_PLAY_PAUSE :: BG.CUInt
sDLK_MEDIA_PLAY_PAUSE = (1073742095 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT)@
--
--     [C declaration]: @macro SDLK_MEDIA_SELECT@, defined at @SDL3\/SDL_keycode.h 294:9@
sDLK_MEDIA_SELECT :: BG.CUInt
sDLK_MEDIA_SELECT = (1073742096 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW)@
--
--     [C declaration]: @macro SDLK_AC_NEW@, defined at @SDL3\/SDL_keycode.h 295:9@
sDLK_AC_NEW :: BG.CUInt
sDLK_AC_NEW = (1073742097 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN)@
--
--     [C declaration]: @macro SDLK_AC_OPEN@, defined at @SDL3\/SDL_keycode.h 296:9@
sDLK_AC_OPEN :: BG.CUInt
sDLK_AC_OPEN = (1073742098 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE)@
--
--     [C declaration]: @macro SDLK_AC_CLOSE@, defined at @SDL3\/SDL_keycode.h 297:9@
sDLK_AC_CLOSE :: BG.CUInt
sDLK_AC_CLOSE = (1073742099 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT)@
--
--     [C declaration]: @macro SDLK_AC_EXIT@, defined at @SDL3\/SDL_keycode.h 298:9@
sDLK_AC_EXIT :: BG.CUInt
sDLK_AC_EXIT = (1073742100 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE)@
--
--     [C declaration]: @macro SDLK_AC_SAVE@, defined at @SDL3\/SDL_keycode.h 299:9@
sDLK_AC_SAVE :: BG.CUInt
sDLK_AC_SAVE = (1073742101 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT)@
--
--     [C declaration]: @macro SDLK_AC_PRINT@, defined at @SDL3\/SDL_keycode.h 300:9@
sDLK_AC_PRINT :: BG.CUInt
sDLK_AC_PRINT = (1073742102 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES)@
--
--     [C declaration]: @macro SDLK_AC_PROPERTIES@, defined at @SDL3\/SDL_keycode.h 301:9@
sDLK_AC_PROPERTIES :: BG.CUInt
sDLK_AC_PROPERTIES = (1073742103 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)@
--
--     [C declaration]: @macro SDLK_AC_SEARCH@, defined at @SDL3\/SDL_keycode.h 302:9@
sDLK_AC_SEARCH :: BG.CUInt
sDLK_AC_SEARCH = (1073742104 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)@
--
--     [C declaration]: @macro SDLK_AC_HOME@, defined at @SDL3\/SDL_keycode.h 303:9@
sDLK_AC_HOME :: BG.CUInt
sDLK_AC_HOME = (1073742105 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)@
--
--     [C declaration]: @macro SDLK_AC_BACK@, defined at @SDL3\/SDL_keycode.h 304:9@
sDLK_AC_BACK :: BG.CUInt
sDLK_AC_BACK = (1073742106 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)@
--
--     [C declaration]: @macro SDLK_AC_FORWARD@, defined at @SDL3\/SDL_keycode.h 305:9@
sDLK_AC_FORWARD :: BG.CUInt
sDLK_AC_FORWARD = (1073742107 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)@
--
--     [C declaration]: @macro SDLK_AC_STOP@, defined at @SDL3\/SDL_keycode.h 306:9@
sDLK_AC_STOP :: BG.CUInt
sDLK_AC_STOP = (1073742108 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)@
--
--     [C declaration]: @macro SDLK_AC_REFRESH@, defined at @SDL3\/SDL_keycode.h 307:9@
sDLK_AC_REFRESH :: BG.CUInt
sDLK_AC_REFRESH = (1073742109 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)@
--
--     [C declaration]: @macro SDLK_AC_BOOKMARKS@, defined at @SDL3\/SDL_keycode.h 308:9@
sDLK_AC_BOOKMARKS :: BG.CUInt
sDLK_AC_BOOKMARKS = (1073742110 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT)@
--
--     [C declaration]: @macro SDLK_SOFTLEFT@, defined at @SDL3\/SDL_keycode.h 309:9@
sDLK_SOFTLEFT :: BG.CUInt
sDLK_SOFTLEFT = (1073742111 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT)@
--
--     [C declaration]: @macro SDLK_SOFTRIGHT@, defined at @SDL3\/SDL_keycode.h 310:9@
sDLK_SOFTRIGHT :: BG.CUInt
sDLK_SOFTRIGHT = (1073742112 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL)@
--
--     [C declaration]: @macro SDLK_CALL@, defined at @SDL3\/SDL_keycode.h 311:9@
sDLK_CALL :: BG.CUInt
sDLK_CALL = (1073742113 :: BG.CUInt)

-- | @SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL)@
--
--     [C declaration]: @macro SDLK_ENDCALL@, defined at @SDL3\/SDL_keycode.h 312:9@
sDLK_ENDCALL :: BG.CUInt
sDLK_ENDCALL = (1073742114 :: BG.CUInt)

-- | Extended key Left Tab
--
--     [C declaration]: @macro SDLK_LEFT_TAB@, defined at @SDL3\/SDL_keycode.h 313:9@
sDLK_LEFT_TAB :: BG.CUInt
sDLK_LEFT_TAB = (536870913 :: BG.CUInt)

-- | Extended key Level 5 Shift
--
--     [C declaration]: @macro SDLK_LEVEL5_SHIFT@, defined at @SDL3\/SDL_keycode.h 314:9@
sDLK_LEVEL5_SHIFT :: BG.CUInt
sDLK_LEVEL5_SHIFT = (536870914 :: BG.CUInt)

-- | Extended key Multi-key Compose
--
--     [C declaration]: @macro SDLK_MULTI_KEY_COMPOSE@, defined at @SDL3\/SDL_keycode.h 315:9@
sDLK_MULTI_KEY_COMPOSE :: BG.CUInt
sDLK_MULTI_KEY_COMPOSE = (536870915 :: BG.CUInt)

-- | Extended key Left Meta
--
--     [C declaration]: @macro SDLK_LMETA@, defined at @SDL3\/SDL_keycode.h 316:9@
sDLK_LMETA :: BG.CUInt
sDLK_LMETA = (536870916 :: BG.CUInt)

-- | Extended key Right Meta
--
--     [C declaration]: @macro SDLK_RMETA@, defined at @SDL3\/SDL_keycode.h 317:9@
sDLK_RMETA :: BG.CUInt
sDLK_RMETA = (536870917 :: BG.CUInt)

-- | Extended key Left Hyper
--
--     [C declaration]: @macro SDLK_LHYPER@, defined at @SDL3\/SDL_keycode.h 318:9@
sDLK_LHYPER :: BG.CUInt
sDLK_LHYPER = (536870918 :: BG.CUInt)

-- | Extended key Right Hyper
--
--     [C declaration]: @macro SDLK_RHYPER@, defined at @SDL3\/SDL_keycode.h 319:9@
sDLK_RHYPER :: BG.CUInt
sDLK_RHYPER = (536870919 :: BG.CUInt)

-- | Valid key modifiers (possibly OR\'d together).
--
--     @since 3.2.0
--
--     [C declaration]: @SDL_Keymod@, defined at @SDL3\/SDL_keycode.h 326:16@
newtype SDL_Keymod = SDL_Keymod
  { unwrap :: SDL3.Sys.Bindgen.Stdinc.Uint16
  }
  deriving stock (BG.Generic, Eq, Ord, Read, Show)
  deriving newtype
    ( BG.Bitfield
    , BG.Bits
    , BG.FiniteBits
    , BG.HasFFIType
    , BG.Ix
    , BG.Prim
    , BG.Storable
    , Bounded
    , Enum
    , Integral
    , Marshal.ReadRaw
    , Marshal.StaticSize
    , Marshal.WriteRaw
    , Num
    , Real
    )

instance
  (ty ~ SDL3.Sys.Bindgen.Stdinc.Uint16)
  => BG.CompatHasField.HasField "unwrap" SDL_Keymod ty
  where
  hasField =
    \x0 ->
      ( \y1 ->
          SDL_Keymod{unwrap = y1}
      , BG.getField @"unwrap" x0
      )

instance
  (ty ~ SDL3.Sys.Bindgen.Stdinc.Uint16)
  => BG.HasField "unwrap" (BG.Ptr SDL_Keymod) (BG.Ptr ty)
  where
  getField = HasCField.fromPtr (BG.Proxy @"unwrap")

instance HasCField.HasCField SDL_Keymod "unwrap" where
  type
    CFieldType SDL_Keymod "unwrap" =
      SDL3.Sys.Bindgen.Stdinc.Uint16

  offset# = \_ -> \_ -> 0

-- | no modifier is applicable.
--
--     [C declaration]: @macro SDL_KMOD_NONE@, defined at @SDL3\/SDL_keycode.h 328:9@
sDL_KMOD_NONE :: BG.CUInt
sDL_KMOD_NONE = (0 :: BG.CUInt)

-- | the left Shift key is down.
--
--     [C declaration]: @macro SDL_KMOD_LSHIFT@, defined at @SDL3\/SDL_keycode.h 329:9@
sDL_KMOD_LSHIFT :: BG.CUInt
sDL_KMOD_LSHIFT = (1 :: BG.CUInt)

-- | the right Shift key is down.
--
--     [C declaration]: @macro SDL_KMOD_RSHIFT@, defined at @SDL3\/SDL_keycode.h 330:9@
sDL_KMOD_RSHIFT :: BG.CUInt
sDL_KMOD_RSHIFT = (2 :: BG.CUInt)

-- | the Level 5 Shift key is down.
--
--     [C declaration]: @macro SDL_KMOD_LEVEL5@, defined at @SDL3\/SDL_keycode.h 331:9@
sDL_KMOD_LEVEL5 :: BG.CUInt
sDL_KMOD_LEVEL5 = (4 :: BG.CUInt)

-- | the left Ctrl (Control) key is down.
--
--     [C declaration]: @macro SDL_KMOD_LCTRL@, defined at @SDL3\/SDL_keycode.h 332:9@
sDL_KMOD_LCTRL :: BG.CUInt
sDL_KMOD_LCTRL = (64 :: BG.CUInt)

-- | the right Ctrl (Control) key is down.
--
--     [C declaration]: @macro SDL_KMOD_RCTRL@, defined at @SDL3\/SDL_keycode.h 333:9@
sDL_KMOD_RCTRL :: BG.CUInt
sDL_KMOD_RCTRL = (128 :: BG.CUInt)

-- | the left Alt key is down.
--
--     [C declaration]: @macro SDL_KMOD_LALT@, defined at @SDL3\/SDL_keycode.h 334:9@
sDL_KMOD_LALT :: BG.CUInt
sDL_KMOD_LALT = (256 :: BG.CUInt)

-- | the right Alt key is down.
--
--     [C declaration]: @macro SDL_KMOD_RALT@, defined at @SDL3\/SDL_keycode.h 335:9@
sDL_KMOD_RALT :: BG.CUInt
sDL_KMOD_RALT = (512 :: BG.CUInt)

-- | the left GUI key (often the Windows key) is down.
--
--     [C declaration]: @macro SDL_KMOD_LGUI@, defined at @SDL3\/SDL_keycode.h 336:9@
sDL_KMOD_LGUI :: BG.CUInt
sDL_KMOD_LGUI = (1024 :: BG.CUInt)

-- | the right GUI key (often the Windows key) is down.
--
--     [C declaration]: @macro SDL_KMOD_RGUI@, defined at @SDL3\/SDL_keycode.h 337:9@
sDL_KMOD_RGUI :: BG.CUInt
sDL_KMOD_RGUI = (2048 :: BG.CUInt)

-- | the Num Lock key (may be located on an extended keypad) is down.
--
--     [C declaration]: @macro SDL_KMOD_NUM@, defined at @SDL3\/SDL_keycode.h 338:9@
sDL_KMOD_NUM :: BG.CUInt
sDL_KMOD_NUM = (4096 :: BG.CUInt)

-- | the Caps Lock key is down.
--
--     [C declaration]: @macro SDL_KMOD_CAPS@, defined at @SDL3\/SDL_keycode.h 339:9@
sDL_KMOD_CAPS :: BG.CUInt
sDL_KMOD_CAPS = (8192 :: BG.CUInt)

-- | the !AltGr key is down.
--
--     [C declaration]: @macro SDL_KMOD_MODE@, defined at @SDL3\/SDL_keycode.h 340:9@
sDL_KMOD_MODE :: BG.CUInt
sDL_KMOD_MODE = (16384 :: BG.CUInt)

-- | the Scroll Lock key is down.
--
--     [C declaration]: @macro SDL_KMOD_SCROLL@, defined at @SDL3\/SDL_keycode.h 341:9@
sDL_KMOD_SCROLL :: BG.CUInt
sDL_KMOD_SCROLL = (32768 :: BG.CUInt)

-- | Any Ctrl key is down.
--
--     [C declaration]: @macro SDL_KMOD_CTRL@, defined at @SDL3\/SDL_keycode.h 342:9@
sDL_KMOD_CTRL :: BG.CUInt
sDL_KMOD_CTRL =
  (C.Expr.HostPlatform..|.) sDL_KMOD_LCTRL sDL_KMOD_RCTRL

-- | Any Shift key is down.
--
--     [C declaration]: @macro SDL_KMOD_SHIFT@, defined at @SDL3\/SDL_keycode.h 343:9@
sDL_KMOD_SHIFT :: BG.CUInt
sDL_KMOD_SHIFT =
  (C.Expr.HostPlatform..|.) sDL_KMOD_LSHIFT sDL_KMOD_RSHIFT

-- | Any Alt key is down.
--
--     [C declaration]: @macro SDL_KMOD_ALT@, defined at @SDL3\/SDL_keycode.h 344:9@
sDL_KMOD_ALT :: BG.CUInt
sDL_KMOD_ALT =
  (C.Expr.HostPlatform..|.) sDL_KMOD_LALT sDL_KMOD_RALT

-- | Any GUI key is down.
--
--     [C declaration]: @macro SDL_KMOD_GUI@, defined at @SDL3\/SDL_keycode.h 345:9@
sDL_KMOD_GUI :: BG.CUInt
sDL_KMOD_GUI =
  (C.Expr.HostPlatform..|.) sDL_KMOD_LGUI sDL_KMOD_RGUI
