-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Enums.BufferUsageFlagBits2 (
  BufferUsageFlagBits2 (..),
  BufferUsageFlags2,
) where

import Data.Word (Word64)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkBufferUsageFlagBits2.html VkBufferUsageFlagBits2>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkBufferUsageFlagBits2KHR
data BufferUsageFlagBits2
  = BufferUsage2TransferSrcBit
  | BufferUsage2TransferDstBit
  | BufferUsage2UniformTexelBufferBit
  | BufferUsage2StorageTexelBufferBit
  | BufferUsage2UniformBufferBit
  | BufferUsage2StorageBufferBit
  | BufferUsage2IndexBufferBit
  | BufferUsage2VertexBufferBit
  | BufferUsage2IndirectBufferBit
  | BufferUsage2ShaderBindingTableBitKHR
  | BufferUsage2ShaderDeviceAddressBit
  | BufferUsage2AccelerationStructureBuildInputReadOnlyBitKHR
  | BufferUsage2AccelerationStructureStorageBitKHR
  | BufferUsage2SamplerDescriptorBufferBitEXT
  | BufferUsage2ResourceDescriptorBufferBitEXT
  | BufferUsage2MicromapBuildInputReadOnlyBitEXT
  | BufferUsage2MicromapStorageBitEXT
  | BufferUsage2PushDescriptorsDescriptorBufferBitEXT
  deriving stock (Eq, Ord, Show)

type instance FlagsWire BufferUsageFlagBits2 = Word64

instance BitPos BufferUsageFlagBits2 where
  bitOf = \case
    BufferUsage2TransferSrcBit -> Flags 0x1
    BufferUsage2TransferDstBit -> Flags 0x2
    BufferUsage2UniformTexelBufferBit -> Flags 0x4
    BufferUsage2StorageTexelBufferBit -> Flags 0x8
    BufferUsage2UniformBufferBit -> Flags 0x10
    BufferUsage2StorageBufferBit -> Flags 0x20
    BufferUsage2IndexBufferBit -> Flags 0x40
    BufferUsage2VertexBufferBit -> Flags 0x80
    BufferUsage2IndirectBufferBit -> Flags 0x100
    BufferUsage2ShaderBindingTableBitKHR -> Flags 0x400
    BufferUsage2ShaderDeviceAddressBit -> Flags 0x20000
    BufferUsage2AccelerationStructureBuildInputReadOnlyBitKHR -> Flags 0x80000
    BufferUsage2AccelerationStructureStorageBitKHR -> Flags 0x100000
    BufferUsage2SamplerDescriptorBufferBitEXT -> Flags 0x200000
    BufferUsage2ResourceDescriptorBufferBitEXT -> Flags 0x400000
    BufferUsage2MicromapBuildInputReadOnlyBitEXT -> Flags 0x800000
    BufferUsage2MicromapStorageBitEXT -> Flags 0x1000000
    BufferUsage2PushDescriptorsDescriptorBufferBitEXT -> Flags 0x4000000
  allBits =
    [ BufferUsage2TransferSrcBit
    , BufferUsage2TransferDstBit
    , BufferUsage2UniformTexelBufferBit
    , BufferUsage2StorageTexelBufferBit
    , BufferUsage2UniformBufferBit
    , BufferUsage2StorageBufferBit
    , BufferUsage2IndexBufferBit
    , BufferUsage2VertexBufferBit
    , BufferUsage2IndirectBufferBit
    , BufferUsage2ShaderBindingTableBitKHR
    , BufferUsage2ShaderDeviceAddressBit
    , BufferUsage2AccelerationStructureBuildInputReadOnlyBitKHR
    , BufferUsage2AccelerationStructureStorageBitKHR
    , BufferUsage2SamplerDescriptorBufferBitEXT
    , BufferUsage2ResourceDescriptorBufferBitEXT
    , BufferUsage2MicromapBuildInputReadOnlyBitEXT
    , BufferUsage2MicromapStorageBitEXT
    , BufferUsage2PushDescriptorsDescriptorBufferBitEXT
    ]

type BufferUsageFlags2 = Flags BufferUsageFlagBits2
