-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Enums.PipelineRobustnessBufferBehavior (
  PipelineRobustnessBufferBehavior (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineRobustnessBufferBehavior.html VkPipelineRobustnessBufferBehavior>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPipelineRobustnessBufferBehaviorEXT
data PipelineRobustnessBufferBehavior
  = PipelineRobustnessBufferBehaviorDeviceDefault
  | PipelineRobustnessBufferBehaviorDisabled
  | PipelineRobustnessBufferBehaviorRobustBufferAccess
  | PipelineRobustnessBufferBehaviorRobustBufferAccess2
  deriving stock (Eq, Ord, Show)

instance HasWire PipelineRobustnessBufferBehavior where
  toWire = \case
    PipelineRobustnessBufferBehaviorDeviceDefault -> 0
    PipelineRobustnessBufferBehaviorDisabled -> 1
    PipelineRobustnessBufferBehaviorRobustBufferAccess -> 2
    PipelineRobustnessBufferBehaviorRobustBufferAccess2 -> 3
  fromWire = \case
    0 -> Just PipelineRobustnessBufferBehaviorDeviceDefault
    1 -> Just PipelineRobustnessBufferBehaviorDisabled
    2 -> Just PipelineRobustnessBufferBehaviorRobustBufferAccess
    3 -> Just PipelineRobustnessBufferBehaviorRobustBufferAccess2
    _ -> Nothing
