-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core14.Enums.PipelineCreateFlagBits2 (
  PipelineCreateFlagBits2 (..),
  PipelineCreateFlags2,
) where

import Data.Word (Word64)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineCreateFlagBits2.html VkPipelineCreateFlagBits2>
-- Available: VK_VERSION_1_4
-- Alias spellings: VkPipelineCreateFlagBits2KHR
data PipelineCreateFlagBits2
  = PipelineCreate2DisableOptimizationBit
  | PipelineCreate2AllowDerivativesBit
  | PipelineCreate2DerivativeBit
  | PipelineCreate2ViewIndexFromDeviceIndexBit
  | PipelineCreate2DispatchBaseBit
  | PipelineCreate2CaptureStatisticsBitKHR
  | PipelineCreate2CaptureInternalRepresentationsBitKHR
  | PipelineCreate2FailOnPipelineCompileRequiredBit
  | PipelineCreate2EarlyReturnOnFailureBit
  | PipelineCreate2LinkTimeOptimizationBitEXT
  | PipelineCreate2LibraryBitKHR
  | PipelineCreate2RayTracingSkipTrianglesBitKHR
  | PipelineCreate2RayTracingSkipAabbsBitKHR
  | PipelineCreate2RayTracingNoNullAnyHitShadersBitKHR
  | PipelineCreate2RayTracingNoNullClosestHitShadersBitKHR
  | PipelineCreate2RayTracingNoNullMissShadersBitKHR
  | PipelineCreate2RayTracingNoNullIntersectionShadersBitKHR
  | PipelineCreate2RayTracingShaderGroupHandleCaptureReplayBitKHR
  | PipelineCreate2RenderingFragmentShadingRateAttachmentBitKHR
  | PipelineCreate2RetainLinkTimeOptimizationInfoBitEXT
  | PipelineCreate2NoProtectedAccessBit
  | PipelineCreate2DescriptorBufferBitEXT
  | PipelineCreate2ProtectedAccessOnlyBit
  | PipelineCreate2CaptureDataBitKHR
  deriving stock (Eq, Ord, Show)

type instance FlagsWire PipelineCreateFlagBits2 = Word64

instance BitPos PipelineCreateFlagBits2 where
  bitOf = \case
    PipelineCreate2DisableOptimizationBit -> Flags 0x1
    PipelineCreate2AllowDerivativesBit -> Flags 0x2
    PipelineCreate2DerivativeBit -> Flags 0x4
    PipelineCreate2ViewIndexFromDeviceIndexBit -> Flags 0x8
    PipelineCreate2DispatchBaseBit -> Flags 0x10
    PipelineCreate2CaptureStatisticsBitKHR -> Flags 0x40
    PipelineCreate2CaptureInternalRepresentationsBitKHR -> Flags 0x80
    PipelineCreate2FailOnPipelineCompileRequiredBit -> Flags 0x100
    PipelineCreate2EarlyReturnOnFailureBit -> Flags 0x200
    PipelineCreate2LinkTimeOptimizationBitEXT -> Flags 0x400
    PipelineCreate2LibraryBitKHR -> Flags 0x800
    PipelineCreate2RayTracingSkipTrianglesBitKHR -> Flags 0x1000
    PipelineCreate2RayTracingSkipAabbsBitKHR -> Flags 0x2000
    PipelineCreate2RayTracingNoNullAnyHitShadersBitKHR -> Flags 0x4000
    PipelineCreate2RayTracingNoNullClosestHitShadersBitKHR -> Flags 0x8000
    PipelineCreate2RayTracingNoNullMissShadersBitKHR -> Flags 0x10000
    PipelineCreate2RayTracingNoNullIntersectionShadersBitKHR -> Flags 0x20000
    PipelineCreate2RayTracingShaderGroupHandleCaptureReplayBitKHR -> Flags 0x80000
    PipelineCreate2RenderingFragmentShadingRateAttachmentBitKHR -> Flags 0x200000
    PipelineCreate2RetainLinkTimeOptimizationInfoBitEXT -> Flags 0x800000
    PipelineCreate2NoProtectedAccessBit -> Flags 0x8000000
    PipelineCreate2DescriptorBufferBitEXT -> Flags 0x20000000
    PipelineCreate2ProtectedAccessOnlyBit -> Flags 0x40000000
    PipelineCreate2CaptureDataBitKHR -> Flags 0x80000000
  allBits =
    [ PipelineCreate2DisableOptimizationBit
    , PipelineCreate2AllowDerivativesBit
    , PipelineCreate2DerivativeBit
    , PipelineCreate2ViewIndexFromDeviceIndexBit
    , PipelineCreate2DispatchBaseBit
    , PipelineCreate2CaptureStatisticsBitKHR
    , PipelineCreate2CaptureInternalRepresentationsBitKHR
    , PipelineCreate2FailOnPipelineCompileRequiredBit
    , PipelineCreate2EarlyReturnOnFailureBit
    , PipelineCreate2LinkTimeOptimizationBitEXT
    , PipelineCreate2LibraryBitKHR
    , PipelineCreate2RayTracingSkipTrianglesBitKHR
    , PipelineCreate2RayTracingSkipAabbsBitKHR
    , PipelineCreate2RayTracingNoNullAnyHitShadersBitKHR
    , PipelineCreate2RayTracingNoNullClosestHitShadersBitKHR
    , PipelineCreate2RayTracingNoNullMissShadersBitKHR
    , PipelineCreate2RayTracingNoNullIntersectionShadersBitKHR
    , PipelineCreate2RayTracingShaderGroupHandleCaptureReplayBitKHR
    , PipelineCreate2RenderingFragmentShadingRateAttachmentBitKHR
    , PipelineCreate2RetainLinkTimeOptimizationInfoBitEXT
    , PipelineCreate2NoProtectedAccessBit
    , PipelineCreate2DescriptorBufferBitEXT
    , PipelineCreate2ProtectedAccessOnlyBit
    , PipelineCreate2CaptureDataBitKHR
    ]

type PipelineCreateFlags2 = Flags PipelineCreateFlagBits2
