-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.CommandPoolCommands (
  CommandPoolCreateInfo (..),
  createCommandPool,
  withCommandPool,
  destroyCommandPool,
  resetCommandPool,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.CommandPoolCreateFlagBits
import Lithon.Vk.Core10.Enums.CommandPoolResetFlagBits
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkCommandPoolCreateInfo.html VkCommandPoolCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data CommandPoolCreateInfo = CommandPoolCreateInfo
  { flags :: CommandPoolCreateFlags
  , queueFamilyIndex :: Word32
  }

instance CStruct CommandPoolCreateInfo where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (39 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 x.queueFamilyIndex)
    pure ()

instance FromCStruct CommandPoolCreateInfo where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_queueFamilyIndex <- (peekByteOff p 20)
    pure CommandPoolCreateInfo{flags = v_flags, queueFamilyIndex = v_queueFamilyIndex}

instance Nil CommandPoolCreateInfo where
  nil =
    CommandPoolCreateInfo
      { flags = mempty
      , queueFamilyIndex = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateCommandPool.html vkCreateCommandPool>
-- Available: VK_VERSION_1_0
createCommandPool
  :: forall m
   . (MonadIO m)
  => Device
  -> CommandPoolCreateInfo
  -> Maybe AllocationCallbacks
  -> m (Outcome CommandPool)
createCommandPool device createInfo allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_createInfo :: Ptr () <- castPtr <$> new createInfo
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_commandPool <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateCommandPool
            (checkCommandPtr "vkCreateCommandPool" device.cmds.pCreateCommandPool)
            (castPtr device.handle)
            p_createInfo
            p_allocator
            (castPtr p_o_commandPool)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_commandPool <- liftIO (peekByteOff p_o_commandPool 0 :: IO Word64)
      let o_commandPool = CommandPool w_o_commandPool
      pure (Ok (openFromWire r_) o_commandPool)

withCommandPool
  :: forall m r
   . (MonadUnliftIO m)
  => Device
  -> CommandPoolCreateInfo
  -> Maybe AllocationCallbacks
  -> (Outcome CommandPool -> m r)
  -> m r
withCommandPool device createInfo allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createCommandPool device createInfo allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroyCommandPool device h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroyCommandPool.html vkDestroyCommandPool>
-- Available: VK_VERSION_1_0
destroyCommandPool
  :: forall m
   . (MonadIO m)
  => Device
  -> CommandPool
  -> Maybe AllocationCallbacks
  -> m ()
destroyCommandPool device commandPool allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroyCommandPool
          (checkCommandPtr "vkDestroyCommandPool" device.cmds.pDestroyCommandPool)
          (castPtr device.handle)
          (case commandPool of CommandPool w_ -> w_)
          p_allocator
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkResetCommandPool.html vkResetCommandPool>
-- Available: VK_VERSION_1_0
resetCommandPool
  :: forall m
   . (MonadIO m)
  => Device
  -> CommandPool
  -> CommandPoolResetFlags
  -> m (Outcome ())
resetCommandPool device commandPool flags =
  liftIO do
    r_ <-
      liftIO
        ( mkResetCommandPool
            (checkCommandPtr "vkResetCommandPool" device.cmds.pResetCommandPool)
            (castPtr device.handle)
            (case commandPool of CommandPool w_ -> w_)
            ((\(Flags w) -> w) flags)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())
