-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.CommandBufferBuildingCommands (
  BufferCopy (..),
  BufferImageCopy (..),
  ClearAttachment (..),
  ClearColorValue (..),
  ClearDepthStencilValue (..),
  ClearRect (..),
  ClearValue (..),
  ImageBlit (..),
  ImageCopy (..),
  ImageResolve (..),
  ImageSubresourceLayers (..),
  ImageMemoryBarrier (..),
  RenderPassBeginInfo (..),
  cmdBeginQuery,
  cmdBindDescriptorSets,
  cmdBindIndexBuffer,
  cmdBindPipeline,
  cmdBindVertexBuffers,
  cmdBlitImage,
  cmdClearAttachments,
  cmdClearColorImage,
  cmdClearDepthStencilImage,
  cmdCopyBuffer,
  cmdCopyBufferToImage,
  cmdCopyImage,
  cmdCopyImageToBuffer,
  cmdCopyQueryPoolResults,
  cmdDispatch,
  cmdDispatchIndirect,
  cmdDraw,
  cmdDrawIndexed,
  cmdDrawIndexedIndirect,
  cmdDrawIndirect,
  cmdEndQuery,
  cmdExecuteCommands,
  cmdFillBuffer,
  cmdPushConstants,
  cmdResetQueryPool,
  cmdResolveImage,
  cmdSetBlendConstants,
  cmdSetDepthBias,
  cmdSetDepthBounds,
  cmdSetLineWidth,
  cmdSetScissor,
  cmdSetStencilCompareMask,
  cmdSetStencilReference,
  cmdSetStencilWriteMask,
  cmdSetViewport,
  cmdUpdateBuffer,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Vector.Storable.Sized qualified as VSS
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Marshal.Utils (fillBytes)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), DeviceAddress (..), DeviceSize (..), SampleMask (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Enums.AccessFlagBits
import Lithon.Vk.Core10.Enums.Filter
import Lithon.Vk.Core10.Enums.ImageAspectFlagBits
import Lithon.Vk.Core10.Enums.ImageLayout
import Lithon.Vk.Core10.Enums.IndexType
import Lithon.Vk.Core10.Enums.PipelineBindPoint
import Lithon.Vk.Core10.Enums.QueryControlFlagBits
import Lithon.Vk.Core10.Enums.QueryResultFlagBits
import Lithon.Vk.Core10.Enums.ShaderStageFlagBits
import Lithon.Vk.Core10.Enums.StencilFaceFlagBits
import Lithon.Vk.Core10.FundamentalTypesUsedByManyCommandsAndStructures
import Lithon.Vk.Core10.GraphicsPipelineCommands
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Core10.ImageViewCommands
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkBufferCopy.html VkBufferCopy>
-- Available: VK_VERSION_1_0
data BufferCopy = BufferCopy
  { srcOffset :: !Word64
  , dstOffset :: !Word64
  , size :: !Word64
  }
  deriving stock (Eq, Show)

instance Storable BufferCopy where
  sizeOf _ = 24
  alignment _ = 8
  peek p =
    BufferCopy
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 16)
  poke p x = do
    pokeByteOff p 0 x.srcOffset
    pokeByteOff p 8 x.dstOffset
    pokeByteOff p 16 x.size

instance CStruct BufferCopy where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct BufferCopy where
  peekCStruct = peek

instance Nil BufferCopy where
  nil =
    BufferCopy
      { srcOffset = 0
      , dstOffset = 0
      , size = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkBufferImageCopy.html VkBufferImageCopy>
-- Available: VK_VERSION_1_0
data BufferImageCopy = BufferImageCopy
  { bufferOffset :: !Word64
  , bufferRowLength :: !Word32
  , bufferImageHeight :: !Word32
  , imageSubresource :: !ImageSubresourceLayers
  , imageOffset :: !Offset3D
  , imageExtent :: !Extent3D
  }
  deriving stock (Eq, Show)

instance Storable BufferImageCopy where
  sizeOf _ = 56
  alignment _ = 8
  peek p =
    BufferImageCopy
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 32)
      <*> (peekByteOff p 44)
  poke p x = do
    pokeByteOff p 0 x.bufferOffset
    pokeByteOff p 8 x.bufferRowLength
    pokeByteOff p 12 x.bufferImageHeight
    pokeByteOff p 16 x.imageSubresource
    pokeByteOff p 32 x.imageOffset
    pokeByteOff p 44 x.imageExtent

instance CStruct BufferImageCopy where
  cSize = 56
  cAlign = 8
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct BufferImageCopy where
  peekCStruct = peek

instance Nil BufferImageCopy where
  nil =
    BufferImageCopy
      { bufferOffset = 0
      , bufferRowLength = 0
      , bufferImageHeight = 0
      , imageSubresource = nil
      , imageOffset = nil
      , imageExtent = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkClearAttachment.html VkClearAttachment>
-- Available: VK_VERSION_1_0
data ClearAttachment = ClearAttachment
  { aspectMask :: !ImageAspectFlags
  , colorAttachment :: !Word32
  , clearValue :: !ClearValue
  }
  deriving stock (Eq, Show)

instance Storable ClearAttachment where
  sizeOf _ = 24
  alignment _ = 4
  peek p =
    ClearAttachment
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
  poke p x = do
    pokeByteOff p 0 x.aspectMask
    pokeByteOff p 4 x.colorAttachment
    pokeByteOff p 8 x.clearValue

instance CStruct ClearAttachment where
  cSize = 24
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ClearAttachment where
  peekCStruct = peek

instance Nil ClearAttachment where
  nil =
    ClearAttachment
      { aspectMask = mempty
      , colorAttachment = 0
      , clearValue = nil
      }

-- | \/\/ Union allowing specification of floating-point, integer, or unsigned integer color data. Actual value selected is based on image\/attachment being cleared.
-- Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkClearColorValue.html VkClearColorValue>
-- Available: VK_VERSION_1_0
data ClearColorValue
  = ClearColorValueFloat32 !(VSS.Vector 4 Float)
  | ClearColorValueInt32 !(VSS.Vector 4 Int32)
  | ClearColorValueUint32 !(VSS.Vector 4 Word32)
  | -- | What 'Foreign.Storable.peek' returns: the union's bytes
    -- verbatim (the wire carries no discriminant). Re-poking them
    -- reproduces the value exactly; reinterpret via the typed arms'
    -- layout when the active arm is known.
    ClearColorValueRaw !(VSS.Vector 16 Word8)
  deriving stock (Eq, Show)

instance Storable ClearColorValue where
  sizeOf _ = 16
  alignment _ = 4
  peek p = ClearColorValueRaw <$> peekByteOff p 0
  poke p x = do
    fillBytes (castPtr p) 0 16
    case x of
      ClearColorValueFloat32 v -> pokeByteOff p 0 v
      ClearColorValueInt32 v -> pokeByteOff p 0 v
      ClearColorValueUint32 v -> pokeByteOff p 0 v
      ClearColorValueRaw v -> pokeByteOff p 0 v

instance CStruct ClearColorValue where
  cSize = 16
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ClearColorValue where
  peekCStruct = peek

instance Nil ClearColorValue where
  nil = ClearColorValueFloat32 (VSS.replicate 0)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkClearDepthStencilValue.html VkClearDepthStencilValue>
-- Available: VK_VERSION_1_0
data ClearDepthStencilValue = ClearDepthStencilValue
  { depth :: !Float
  , stencil :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable ClearDepthStencilValue where
  sizeOf _ = 8
  alignment _ = 4
  peek p =
    ClearDepthStencilValue
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
  poke p x = do
    pokeByteOff p 0 x.depth
    pokeByteOff p 4 x.stencil

instance CStruct ClearDepthStencilValue where
  cSize = 8
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ClearDepthStencilValue where
  peekCStruct = peek

instance Nil ClearDepthStencilValue where
  nil =
    ClearDepthStencilValue
      { depth = 0
      , stencil = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkClearRect.html VkClearRect>
-- Available: VK_VERSION_1_0
data ClearRect = ClearRect
  { rect :: !Rect2D
  , baseArrayLayer :: !Word32
  , layerCount :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable ClearRect where
  sizeOf _ = 24
  alignment _ = 4
  peek p =
    ClearRect
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 20)
  poke p x = do
    pokeByteOff p 0 x.rect
    pokeByteOff p 16 x.baseArrayLayer
    pokeByteOff p 20 x.layerCount

instance CStruct ClearRect where
  cSize = 24
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ClearRect where
  peekCStruct = peek

instance Nil ClearRect where
  nil =
    ClearRect
      { rect = nil
      , baseArrayLayer = 0
      , layerCount = 0
      }

-- | \/\/ Union allowing specification of color or depth and stencil values. Actual value selected is based on attachment being cleared.
-- Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkClearValue.html VkClearValue>
-- Available: VK_VERSION_1_0
data ClearValue
  = ClearValueColor !ClearColorValue
  | ClearValueDepthStencil !ClearDepthStencilValue
  | -- | What 'Foreign.Storable.peek' returns: the union's bytes
    -- verbatim (the wire carries no discriminant). Re-poking them
    -- reproduces the value exactly; reinterpret via the typed arms'
    -- layout when the active arm is known.
    ClearValueRaw !(VSS.Vector 16 Word8)
  deriving stock (Eq, Show)

instance Storable ClearValue where
  sizeOf _ = 16
  alignment _ = 4
  peek p = ClearValueRaw <$> peekByteOff p 0
  poke p x = do
    fillBytes (castPtr p) 0 16
    case x of
      ClearValueColor v -> pokeByteOff p 0 v
      ClearValueDepthStencil v -> pokeByteOff p 0 v
      ClearValueRaw v -> pokeByteOff p 0 v

instance CStruct ClearValue where
  cSize = 16
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ClearValue where
  peekCStruct = peek

instance Nil ClearValue where
  nil = ClearValueColor nil

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageBlit.html VkImageBlit>
-- Available: VK_VERSION_1_0
data ImageBlit = ImageBlit
  { srcSubresource :: !ImageSubresourceLayers
  , srcOffsets :: !(VSS.Vector 2 Offset3D)
  , dstSubresource :: !ImageSubresourceLayers
  , dstOffsets :: !(VSS.Vector 2 Offset3D)
  }
  deriving stock (Eq, Show)

instance Storable ImageBlit where
  sizeOf _ = 80
  alignment _ = 4
  peek p =
    ImageBlit
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 40)
      <*> (peekByteOff p 56)
  poke p x = do
    pokeByteOff p 0 x.srcSubresource
    pokeByteOff p 16 x.srcOffsets
    pokeByteOff p 40 x.dstSubresource
    pokeByteOff p 56 x.dstOffsets

instance CStruct ImageBlit where
  cSize = 80
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ImageBlit where
  peekCStruct = peek

instance Nil ImageBlit where
  nil =
    ImageBlit
      { srcSubresource = nil
      , srcOffsets = VSS.replicate nil
      , dstSubresource = nil
      , dstOffsets = VSS.replicate nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageCopy.html VkImageCopy>
-- Available: VK_VERSION_1_0
data ImageCopy = ImageCopy
  { srcSubresource :: !ImageSubresourceLayers
  , srcOffset :: !Offset3D
  , dstSubresource :: !ImageSubresourceLayers
  , dstOffset :: !Offset3D
  , extent :: !Extent3D
  }
  deriving stock (Eq, Show)

instance Storable ImageCopy where
  sizeOf _ = 68
  alignment _ = 4
  peek p =
    ImageCopy
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 28)
      <*> (peekByteOff p 44)
      <*> (peekByteOff p 56)
  poke p x = do
    pokeByteOff p 0 x.srcSubresource
    pokeByteOff p 16 x.srcOffset
    pokeByteOff p 28 x.dstSubresource
    pokeByteOff p 44 x.dstOffset
    pokeByteOff p 56 x.extent

instance CStruct ImageCopy where
  cSize = 68
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ImageCopy where
  peekCStruct = peek

instance Nil ImageCopy where
  nil =
    ImageCopy
      { srcSubresource = nil
      , srcOffset = nil
      , dstSubresource = nil
      , dstOffset = nil
      , extent = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageResolve.html VkImageResolve>
-- Available: VK_VERSION_1_0
data ImageResolve = ImageResolve
  { srcSubresource :: !ImageSubresourceLayers
  , srcOffset :: !Offset3D
  , dstSubresource :: !ImageSubresourceLayers
  , dstOffset :: !Offset3D
  , extent :: !Extent3D
  }
  deriving stock (Eq, Show)

instance Storable ImageResolve where
  sizeOf _ = 68
  alignment _ = 4
  peek p =
    ImageResolve
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 28)
      <*> (peekByteOff p 44)
      <*> (peekByteOff p 56)
  poke p x = do
    pokeByteOff p 0 x.srcSubresource
    pokeByteOff p 16 x.srcOffset
    pokeByteOff p 28 x.dstSubresource
    pokeByteOff p 44 x.dstOffset
    pokeByteOff p 56 x.extent

instance CStruct ImageResolve where
  cSize = 68
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ImageResolve where
  peekCStruct = peek

instance Nil ImageResolve where
  nil =
    ImageResolve
      { srcSubresource = nil
      , srcOffset = nil
      , dstSubresource = nil
      , dstOffset = nil
      , extent = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageSubresourceLayers.html VkImageSubresourceLayers>
-- Available: VK_VERSION_1_0
data ImageSubresourceLayers = ImageSubresourceLayers
  { aspectMask :: !ImageAspectFlags
  , mipLevel :: !Word32
  , baseArrayLayer :: !Word32
  , layerCount :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable ImageSubresourceLayers where
  sizeOf _ = 16
  alignment _ = 4
  peek p =
    ImageSubresourceLayers
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
  poke p x = do
    pokeByteOff p 0 x.aspectMask
    pokeByteOff p 4 x.mipLevel
    pokeByteOff p 8 x.baseArrayLayer
    pokeByteOff p 12 x.layerCount

instance CStruct ImageSubresourceLayers where
  cSize = 16
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ImageSubresourceLayers where
  peekCStruct = peek

instance Nil ImageSubresourceLayers where
  nil =
    ImageSubresourceLayers
      { aspectMask = mempty
      , mipLevel = 0
      , baseArrayLayer = 0
      , layerCount = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageMemoryBarrier.html VkImageMemoryBarrier>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by VkImageMemoryBarrier2.
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data ImageMemoryBarrier (es :: [Type]) = ImageMemoryBarrier
  { next :: Chain es
  , srcAccessMask :: AccessFlags
  , dstAccessMask :: AccessFlags
  , oldLayout :: Open ImageLayout
  , newLayout :: Open ImageLayout
  , srcQueueFamilyIndex :: Word32
  , dstQueueFamilyIndex :: Word32
  , image :: Image
  , subresourceRange :: ImageSubresourceRange
  }

instance (AllExtends ImageMemoryBarrier es, PokeChain es) => CStruct (ImageMemoryBarrier es) where
  cSize = 72
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (45 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.srcAccessMask)
    liftIO (pokeByteOff p 20 x.dstAccessMask)
    liftIO (pokeByteOff p 24 (openToWire x.oldLayout))
    liftIO (pokeByteOff p 28 (openToWire x.newLayout))
    liftIO (pokeByteOff p 32 x.srcQueueFamilyIndex)
    liftIO (pokeByteOff p 36 x.dstQueueFamilyIndex)
    liftIO (pokeByteOff p 40 x.image)
    liftIO (pokeByteOff p 48 x.subresourceRange)
    pure ()

instance
  (AllExtends ImageMemoryBarrier es, PokeChain es, PeekChain es)
  => FromCStruct (ImageMemoryBarrier es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_srcAccessMask <- (peekByteOff p 16)
    v_dstAccessMask <- (peekByteOff p 20)
    v_oldLayout <- (openFromWire <$> peekByteOff p 24)
    v_newLayout <- (openFromWire <$> peekByteOff p 28)
    v_srcQueueFamilyIndex <- (peekByteOff p 32)
    v_dstQueueFamilyIndex <- (peekByteOff p 36)
    v_image <- (peekByteOff p 40)
    v_subresourceRange <- (peekByteOff p 48)
    pure
      ImageMemoryBarrier
        { next = v_next
        , srcAccessMask = v_srcAccessMask
        , dstAccessMask = v_dstAccessMask
        , oldLayout = v_oldLayout
        , newLayout = v_newLayout
        , srcQueueFamilyIndex = v_srcQueueFamilyIndex
        , dstQueueFamilyIndex = v_dstQueueFamilyIndex
        , image = v_image
        , subresourceRange = v_subresourceRange
        }

instance (NilChain es) => Nil (ImageMemoryBarrier es) where
  nil =
    ImageMemoryBarrier
      { next = nilChain
      , srcAccessMask = mempty
      , dstAccessMask = mempty
      , oldLayout = Known ImageLayoutUndefined
      , newLayout = Known ImageLayoutUndefined
      , srcQueueFamilyIndex = 0
      , dstQueueFamilyIndex = 0
      , image = nil
      , subresourceRange = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkRenderPassBeginInfo.html VkRenderPassBeginInfo>
-- Available: VK_VERSION_1_0
-- __Deprecated__.
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @clearValueCount@ is derived from @clearValues@'s length.
data RenderPassBeginInfo (es :: [Type]) = RenderPassBeginInfo
  { next :: Chain es
  , renderPass :: RenderPass
  , framebuffer :: Framebuffer
  , renderArea :: Rect2D
  , clearValues :: V.Vector ClearValue
  }

instance (AllExtends RenderPassBeginInfo es, PokeChain es) => CStruct (RenderPassBeginInfo es) where
  cSize = 64
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (43 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.renderPass)
    liftIO (pokeByteOff p 24 x.framebuffer)
    liftIO (pokeByteOff p 32 x.renderArea)
    p_clearValues <- if V.null x.clearValues then pure nullPtr else newVector x.clearValues
    liftIO (pokeByteOff p 56 p_clearValues)
    liftIO (pokeByteOff p 48 (fromIntegral (V.length x.clearValues) :: Word32))
    pure ()

instance
  (AllExtends RenderPassBeginInfo es, PokeChain es, PeekChain es)
  => FromCStruct (RenderPassBeginInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_renderPass <- (peekByteOff p 16)
    v_framebuffer <- (peekByteOff p 24)
    v_renderArea <- (peekByteOff p 32)
    v_clearValues <- do
      n <- (peekByteOff p 48 :: IO Word32)
      q <- peekByteOff p 56
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    pure
      RenderPassBeginInfo
        { next = v_next
        , renderPass = v_renderPass
        , framebuffer = v_framebuffer
        , renderArea = v_renderArea
        , clearValues = v_clearValues
        }

instance (NilChain es) => Nil (RenderPassBeginInfo es) where
  nil =
    RenderPassBeginInfo
      { next = nilChain
      , renderPass = nil
      , framebuffer = nil
      , renderArea = nil
      , clearValues = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBeginQuery.html vkCmdBeginQuery>
-- Available: VK_VERSION_1_0
cmdBeginQuery
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> QueryPool
  -> Word32
  -> QueryControlFlags
  -> m ()
cmdBeginQuery commandBuffer queryPool query flags =
  liftIO do
    liftIO
      ( mkCmdBeginQuery
          (checkCommandPtr "vkCmdBeginQuery" commandBuffer.cmds.pCmdBeginQuery)
          (castPtr commandBuffer.handle)
          (case queryPool of QueryPool w_ -> w_)
          query
          ((\(Flags w) -> w) flags)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBindDescriptorSets.html vkCmdBindDescriptorSets>
-- Available: VK_VERSION_1_0
-- __Deprecated__.
cmdBindDescriptorSets
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> PipelineBindPoint
  -> PipelineLayout
  -> Word32
  -> V.Vector DescriptorSet
  -> V.Vector Word32
  -> m ()
cmdBindDescriptorSets commandBuffer pipelineBindPoint layout firstSet descriptorSets dynamicOffsets =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_descriptorSetCount = fromIntegral (V.length descriptorSets) :: Word32
    let n_dynamicOffsetCount = fromIntegral (V.length dynamicOffsets) :: Word32
    p_descriptorSets <- do
      pv_ <- arenaBytes (8 * max 1 (V.length descriptorSets)) 8
      liftIO
        (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 8) (case v_e of DescriptorSet w_ -> w_)) descriptorSets)
      pure (castPtr pv_ :: Ptr ())
    p_dynamicOffsets <- do
      pv_ <- arenaBytes (4 * max 1 (V.length dynamicOffsets)) 4
      liftIO (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 4) v_e) dynamicOffsets)
      pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdBindDescriptorSets
          (checkCommandPtr "vkCmdBindDescriptorSets" commandBuffer.cmds.pCmdBindDescriptorSets)
          (castPtr commandBuffer.handle)
          (toWire pipelineBindPoint)
          (case layout of PipelineLayout w_ -> w_)
          firstSet
          n_descriptorSetCount
          p_descriptorSets
          n_dynamicOffsetCount
          p_dynamicOffsets
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBindIndexBuffer.html vkCmdBindIndexBuffer>
-- Available: VK_VERSION_1_0
cmdBindIndexBuffer
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> DeviceSize
  -> IndexType
  -> m ()
cmdBindIndexBuffer commandBuffer buffer offset indexType =
  liftIO do
    liftIO
      ( mkCmdBindIndexBuffer
          (checkCommandPtr "vkCmdBindIndexBuffer" commandBuffer.cmds.pCmdBindIndexBuffer)
          (castPtr commandBuffer.handle)
          (case buffer of Buffer w_ -> w_)
          (fromIntegral offset :: Word64)
          (toWire indexType)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBindPipeline.html vkCmdBindPipeline>
-- Available: VK_VERSION_1_0
cmdBindPipeline
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> PipelineBindPoint
  -> Pipeline
  -> m ()
cmdBindPipeline commandBuffer pipelineBindPoint pipeline =
  liftIO do
    liftIO
      ( mkCmdBindPipeline
          (checkCommandPtr "vkCmdBindPipeline" commandBuffer.cmds.pCmdBindPipeline)
          (castPtr commandBuffer.handle)
          (toWire pipelineBindPoint)
          (case pipeline of Pipeline w_ -> w_)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBindVertexBuffers.html vkCmdBindVertexBuffers>
-- Available: VK_VERSION_1_0
cmdBindVertexBuffers
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Word32
  -> V.Vector Buffer
  -> V.Vector DeviceSize
  -> m ()
cmdBindVertexBuffers commandBuffer firstBinding buffers offsets =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_bindingCount = fromIntegral (V.length buffers) :: Word32
    p_buffers <- do
      pv_ <- arenaBytes (8 * max 1 (V.length buffers)) 8
      liftIO (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 8) (case v_e of Buffer w_ -> w_)) buffers)
      pure (castPtr pv_ :: Ptr ())
    p_offsets <- do
      unless
        (V.length offsets == fromIntegral n_bindingCount)
        (error "lithon: vkCmdBindVertexBuffers: offsets length must match the count source")
      pv_ <- arenaBytes (8 * max 1 (V.length offsets)) 8
      liftIO (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 8) (fromIntegral v_e :: Word64)) offsets)
      pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdBindVertexBuffers
          (checkCommandPtr "vkCmdBindVertexBuffers" commandBuffer.cmds.pCmdBindVertexBuffers)
          (castPtr commandBuffer.handle)
          firstBinding
          n_bindingCount
          p_buffers
          p_offsets
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBlitImage.html vkCmdBlitImage>
-- Available: VK_VERSION_1_0
cmdBlitImage
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Image
  -> Open ImageLayout
  -> Image
  -> Open ImageLayout
  -> V.Vector ImageBlit
  -> Filter
  -> m ()
cmdBlitImage commandBuffer srcImage srcImageLayout dstImage dstImageLayout regions filter =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_regionCount = fromIntegral (V.length regions) :: Word32
    p_regions <- do pv_ <- newVector regions; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdBlitImage
          (checkCommandPtr "vkCmdBlitImage" commandBuffer.cmds.pCmdBlitImage)
          (castPtr commandBuffer.handle)
          (case srcImage of Image w_ -> w_)
          (openToWire srcImageLayout)
          (case dstImage of Image w_ -> w_)
          (openToWire dstImageLayout)
          n_regionCount
          p_regions
          (toWire filter)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdClearAttachments.html vkCmdClearAttachments>
-- Available: VK_VERSION_1_0
cmdClearAttachments
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> V.Vector ClearAttachment
  -> V.Vector ClearRect
  -> m ()
cmdClearAttachments commandBuffer attachments rects =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_attachmentCount = fromIntegral (V.length attachments) :: Word32
    let n_rectCount = fromIntegral (V.length rects) :: Word32
    p_attachments <- do pv_ <- newVector attachments; pure (castPtr pv_ :: Ptr ())
    p_rects <- do pv_ <- newVector rects; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdClearAttachments
          (checkCommandPtr "vkCmdClearAttachments" commandBuffer.cmds.pCmdClearAttachments)
          (castPtr commandBuffer.handle)
          n_attachmentCount
          p_attachments
          n_rectCount
          p_rects
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdClearColorImage.html vkCmdClearColorImage>
-- Available: VK_VERSION_1_0
cmdClearColorImage
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Image
  -> Open ImageLayout
  -> ClearColorValue
  -> V.Vector ImageSubresourceRange
  -> m ()
cmdClearColorImage commandBuffer image imageLayout color ranges =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_rangeCount = fromIntegral (V.length ranges) :: Word32
    p_color :: Ptr () <- castPtr <$> new color
    p_ranges <- do pv_ <- newVector ranges; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdClearColorImage
          (checkCommandPtr "vkCmdClearColorImage" commandBuffer.cmds.pCmdClearColorImage)
          (castPtr commandBuffer.handle)
          (case image of Image w_ -> w_)
          (openToWire imageLayout)
          p_color
          n_rangeCount
          p_ranges
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdClearDepthStencilImage.html vkCmdClearDepthStencilImage>
-- Available: VK_VERSION_1_0
cmdClearDepthStencilImage
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Image
  -> Open ImageLayout
  -> ClearDepthStencilValue
  -> V.Vector ImageSubresourceRange
  -> m ()
cmdClearDepthStencilImage commandBuffer image imageLayout depthStencil ranges =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_rangeCount = fromIntegral (V.length ranges) :: Word32
    p_depthStencil :: Ptr () <- castPtr <$> new depthStencil
    p_ranges <- do pv_ <- newVector ranges; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdClearDepthStencilImage
          (checkCommandPtr "vkCmdClearDepthStencilImage" commandBuffer.cmds.pCmdClearDepthStencilImage)
          (castPtr commandBuffer.handle)
          (case image of Image w_ -> w_)
          (openToWire imageLayout)
          p_depthStencil
          n_rangeCount
          p_ranges
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdCopyBuffer.html vkCmdCopyBuffer>
-- Available: VK_VERSION_1_0
cmdCopyBuffer
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> Buffer
  -> V.Vector BufferCopy
  -> m ()
cmdCopyBuffer commandBuffer srcBuffer dstBuffer regions =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_regionCount = fromIntegral (V.length regions) :: Word32
    p_regions <- do pv_ <- newVector regions; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdCopyBuffer
          (checkCommandPtr "vkCmdCopyBuffer" commandBuffer.cmds.pCmdCopyBuffer)
          (castPtr commandBuffer.handle)
          (case srcBuffer of Buffer w_ -> w_)
          (case dstBuffer of Buffer w_ -> w_)
          n_regionCount
          p_regions
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdCopyBufferToImage.html vkCmdCopyBufferToImage>
-- Available: VK_VERSION_1_0
cmdCopyBufferToImage
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> Image
  -> Open ImageLayout
  -> V.Vector BufferImageCopy
  -> m ()
cmdCopyBufferToImage commandBuffer srcBuffer dstImage dstImageLayout regions =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_regionCount = fromIntegral (V.length regions) :: Word32
    p_regions <- do pv_ <- newVector regions; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdCopyBufferToImage
          (checkCommandPtr "vkCmdCopyBufferToImage" commandBuffer.cmds.pCmdCopyBufferToImage)
          (castPtr commandBuffer.handle)
          (case srcBuffer of Buffer w_ -> w_)
          (case dstImage of Image w_ -> w_)
          (openToWire dstImageLayout)
          n_regionCount
          p_regions
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdCopyImage.html vkCmdCopyImage>
-- Available: VK_VERSION_1_0
cmdCopyImage
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Image
  -> Open ImageLayout
  -> Image
  -> Open ImageLayout
  -> V.Vector ImageCopy
  -> m ()
cmdCopyImage commandBuffer srcImage srcImageLayout dstImage dstImageLayout regions =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_regionCount = fromIntegral (V.length regions) :: Word32
    p_regions <- do pv_ <- newVector regions; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdCopyImage
          (checkCommandPtr "vkCmdCopyImage" commandBuffer.cmds.pCmdCopyImage)
          (castPtr commandBuffer.handle)
          (case srcImage of Image w_ -> w_)
          (openToWire srcImageLayout)
          (case dstImage of Image w_ -> w_)
          (openToWire dstImageLayout)
          n_regionCount
          p_regions
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdCopyImageToBuffer.html vkCmdCopyImageToBuffer>
-- Available: VK_VERSION_1_0
cmdCopyImageToBuffer
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Image
  -> Open ImageLayout
  -> Buffer
  -> V.Vector BufferImageCopy
  -> m ()
cmdCopyImageToBuffer commandBuffer srcImage srcImageLayout dstBuffer regions =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_regionCount = fromIntegral (V.length regions) :: Word32
    p_regions <- do pv_ <- newVector regions; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdCopyImageToBuffer
          (checkCommandPtr "vkCmdCopyImageToBuffer" commandBuffer.cmds.pCmdCopyImageToBuffer)
          (castPtr commandBuffer.handle)
          (case srcImage of Image w_ -> w_)
          (openToWire srcImageLayout)
          (case dstBuffer of Buffer w_ -> w_)
          n_regionCount
          p_regions
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdCopyQueryPoolResults.html vkCmdCopyQueryPoolResults>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by vkCmdCopyQueryPoolResultsToMemoryKHR.
cmdCopyQueryPoolResults
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> QueryPool
  -> Word32
  -> Word32
  -> Buffer
  -> DeviceSize
  -> DeviceSize
  -> QueryResultFlags
  -> m ()
cmdCopyQueryPoolResults commandBuffer queryPool firstQuery queryCount dstBuffer dstOffset stride flags =
  liftIO do
    liftIO
      ( mkCmdCopyQueryPoolResults
          (checkCommandPtr "vkCmdCopyQueryPoolResults" commandBuffer.cmds.pCmdCopyQueryPoolResults)
          (castPtr commandBuffer.handle)
          (case queryPool of QueryPool w_ -> w_)
          firstQuery
          queryCount
          (case dstBuffer of Buffer w_ -> w_)
          (fromIntegral dstOffset :: Word64)
          (fromIntegral stride :: Word64)
          ((\(Flags w) -> w) flags)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdDispatch.html vkCmdDispatch>
-- Available: VK_VERSION_1_0
cmdDispatch
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Word32
  -> Word32
  -> Word32
  -> m ()
cmdDispatch commandBuffer groupCountX groupCountY groupCountZ =
  liftIO do
    liftIO
      ( mkCmdDispatch
          (checkCommandPtr "vkCmdDispatch" commandBuffer.cmds.pCmdDispatch)
          (castPtr commandBuffer.handle)
          groupCountX
          groupCountY
          groupCountZ
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdDispatchIndirect.html vkCmdDispatchIndirect>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by vkCmdDispatchIndirect2KHR.
cmdDispatchIndirect
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> DeviceSize
  -> m ()
cmdDispatchIndirect commandBuffer buffer offset =
  liftIO do
    liftIO
      ( mkCmdDispatchIndirect
          (checkCommandPtr "vkCmdDispatchIndirect" commandBuffer.cmds.pCmdDispatchIndirect)
          (castPtr commandBuffer.handle)
          (case buffer of Buffer w_ -> w_)
          (fromIntegral offset :: Word64)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdDraw.html vkCmdDraw>
-- Available: VK_VERSION_1_0
cmdDraw
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Word32
  -> Word32
  -> Word32
  -> Word32
  -> m ()
cmdDraw commandBuffer vertexCount instanceCount firstVertex firstInstance =
  liftIO do
    liftIO
      ( mkCmdDraw
          (checkCommandPtr "vkCmdDraw" commandBuffer.cmds.pCmdDraw)
          (castPtr commandBuffer.handle)
          vertexCount
          instanceCount
          firstVertex
          firstInstance
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdDrawIndexed.html vkCmdDrawIndexed>
-- Available: VK_VERSION_1_0
cmdDrawIndexed
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Word32
  -> Word32
  -> Word32
  -> Int32
  -> Word32
  -> m ()
cmdDrawIndexed commandBuffer indexCount instanceCount firstIndex vertexOffset firstInstance =
  liftIO do
    liftIO
      ( mkCmdDrawIndexed
          (checkCommandPtr "vkCmdDrawIndexed" commandBuffer.cmds.pCmdDrawIndexed)
          (castPtr commandBuffer.handle)
          indexCount
          instanceCount
          firstIndex
          vertexOffset
          firstInstance
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdDrawIndexedIndirect.html vkCmdDrawIndexedIndirect>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by vkCmdDrawIndexedIndirect2KHR.
cmdDrawIndexedIndirect
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> DeviceSize
  -> Word32
  -> Word32
  -> m ()
cmdDrawIndexedIndirect commandBuffer buffer offset drawCount stride =
  liftIO do
    liftIO
      ( mkCmdDrawIndexedIndirect
          (checkCommandPtr "vkCmdDrawIndexedIndirect" commandBuffer.cmds.pCmdDrawIndexedIndirect)
          (castPtr commandBuffer.handle)
          (case buffer of Buffer w_ -> w_)
          (fromIntegral offset :: Word64)
          drawCount
          stride
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdDrawIndirect.html vkCmdDrawIndirect>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by vkCmdDrawIndirect2KHR.
cmdDrawIndirect
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> DeviceSize
  -> Word32
  -> Word32
  -> m ()
cmdDrawIndirect commandBuffer buffer offset drawCount stride =
  liftIO do
    liftIO
      ( mkCmdDrawIndirect
          (checkCommandPtr "vkCmdDrawIndirect" commandBuffer.cmds.pCmdDrawIndirect)
          (castPtr commandBuffer.handle)
          (case buffer of Buffer w_ -> w_)
          (fromIntegral offset :: Word64)
          drawCount
          stride
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdEndQuery.html vkCmdEndQuery>
-- Available: VK_VERSION_1_0
cmdEndQuery
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> QueryPool
  -> Word32
  -> m ()
cmdEndQuery commandBuffer queryPool query =
  liftIO do
    liftIO
      ( mkCmdEndQuery
          (checkCommandPtr "vkCmdEndQuery" commandBuffer.cmds.pCmdEndQuery)
          (castPtr commandBuffer.handle)
          (case queryPool of QueryPool w_ -> w_)
          query
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdExecuteCommands.html vkCmdExecuteCommands>
-- Available: VK_VERSION_1_0
cmdExecuteCommands
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> V.Vector CommandBuffer
  -> m ()
cmdExecuteCommands commandBuffer commandBuffers =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_commandBufferCount = fromIntegral (V.length commandBuffers) :: Word32
    p_commandBuffers <- do
      pv_ <- arenaBytes (8 * max 1 (V.length commandBuffers)) 8
      liftIO (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 8) (castPtr v_e.handle :: Ptr ())) commandBuffers)
      pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdExecuteCommands
          (checkCommandPtr "vkCmdExecuteCommands" commandBuffer.cmds.pCmdExecuteCommands)
          (castPtr commandBuffer.handle)
          n_commandBufferCount
          p_commandBuffers
      )
    pure ()

-- | transfer support is only available when VK_KHR_maintenance1 is enabled, as documented in valid usage language in the specification
-- Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdFillBuffer.html vkCmdFillBuffer>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by vkCmdFillMemoryKHR.
cmdFillBuffer
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> DeviceSize
  -> DeviceSize
  -> Word32
  -> m ()
cmdFillBuffer commandBuffer dstBuffer dstOffset size data' =
  liftIO do
    liftIO
      ( mkCmdFillBuffer
          (checkCommandPtr "vkCmdFillBuffer" commandBuffer.cmds.pCmdFillBuffer)
          (castPtr commandBuffer.handle)
          (case dstBuffer of Buffer w_ -> w_)
          (fromIntegral dstOffset :: Word64)
          (fromIntegral size :: Word64)
          data'
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdPushConstants.html vkCmdPushConstants>
-- Available: VK_VERSION_1_0
-- __Deprecated__.
cmdPushConstants
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> PipelineLayout
  -> ShaderStageFlags
  -> Word32
  -> ByteString
  -> m ()
cmdPushConstants commandBuffer layout stageFlags offset values =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_size = fromIntegral (BS.length values) :: Word32
    p_values :: Ptr () <- castPtr <$> newBytes values
    liftIO
      ( mkCmdPushConstants
          (checkCommandPtr "vkCmdPushConstants" commandBuffer.cmds.pCmdPushConstants)
          (castPtr commandBuffer.handle)
          (case layout of PipelineLayout w_ -> w_)
          ((\(Flags w) -> w) stageFlags)
          offset
          n_size
          p_values
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdResetQueryPool.html vkCmdResetQueryPool>
-- Available: VK_VERSION_1_0
cmdResetQueryPool
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> QueryPool
  -> Word32
  -> Word32
  -> m ()
cmdResetQueryPool commandBuffer queryPool firstQuery queryCount =
  liftIO do
    liftIO
      ( mkCmdResetQueryPool
          (checkCommandPtr "vkCmdResetQueryPool" commandBuffer.cmds.pCmdResetQueryPool)
          (castPtr commandBuffer.handle)
          (case queryPool of QueryPool w_ -> w_)
          firstQuery
          queryCount
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdResolveImage.html vkCmdResolveImage>
-- Available: VK_VERSION_1_0
cmdResolveImage
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Image
  -> Open ImageLayout
  -> Image
  -> Open ImageLayout
  -> V.Vector ImageResolve
  -> m ()
cmdResolveImage commandBuffer srcImage srcImageLayout dstImage dstImageLayout regions =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_regionCount = fromIntegral (V.length regions) :: Word32
    p_regions <- do pv_ <- newVector regions; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdResolveImage
          (checkCommandPtr "vkCmdResolveImage" commandBuffer.cmds.pCmdResolveImage)
          (castPtr commandBuffer.handle)
          (case srcImage of Image w_ -> w_)
          (openToWire srcImageLayout)
          (case dstImage of Image w_ -> w_)
          (openToWire dstImageLayout)
          n_regionCount
          p_regions
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetBlendConstants.html vkCmdSetBlendConstants>
-- Available: VK_VERSION_1_0
cmdSetBlendConstants
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> V.Vector Float
  -> m ()
cmdSetBlendConstants commandBuffer blendConstants =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    unless
      (V.length blendConstants == 4)
      (error "lithon: vkCmdSetBlendConstants: blendConstants must have exactly 4 elements")
    p_blendConstants <- arenaBytes 16 4
    liftIO (V.imapM_ (\i v_ -> pokeByteOff p_blendConstants (i * 4) v_) blendConstants)
    liftIO
      ( mkCmdSetBlendConstants
          (checkCommandPtr "vkCmdSetBlendConstants" commandBuffer.cmds.pCmdSetBlendConstants)
          (castPtr commandBuffer.handle)
          (castPtr p_blendConstants)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetDepthBias.html vkCmdSetDepthBias>
-- Available: VK_VERSION_1_0
cmdSetDepthBias
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Float
  -> Float
  -> Float
  -> m ()
cmdSetDepthBias commandBuffer depthBiasConstantFactor depthBiasClamp depthBiasSlopeFactor =
  liftIO do
    liftIO
      ( mkCmdSetDepthBias
          (checkCommandPtr "vkCmdSetDepthBias" commandBuffer.cmds.pCmdSetDepthBias)
          (castPtr commandBuffer.handle)
          depthBiasConstantFactor
          depthBiasClamp
          depthBiasSlopeFactor
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetDepthBounds.html vkCmdSetDepthBounds>
-- Available: VK_VERSION_1_0
cmdSetDepthBounds
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Float
  -> Float
  -> m ()
cmdSetDepthBounds commandBuffer minDepthBounds maxDepthBounds =
  liftIO do
    liftIO
      ( mkCmdSetDepthBounds
          (checkCommandPtr "vkCmdSetDepthBounds" commandBuffer.cmds.pCmdSetDepthBounds)
          (castPtr commandBuffer.handle)
          minDepthBounds
          maxDepthBounds
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetLineWidth.html vkCmdSetLineWidth>
-- Available: VK_VERSION_1_0
cmdSetLineWidth
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Float
  -> m ()
cmdSetLineWidth commandBuffer lineWidth =
  liftIO do
    liftIO
      ( mkCmdSetLineWidth
          (checkCommandPtr "vkCmdSetLineWidth" commandBuffer.cmds.pCmdSetLineWidth)
          (castPtr commandBuffer.handle)
          lineWidth
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetScissor.html vkCmdSetScissor>
-- Available: VK_VERSION_1_0
cmdSetScissor
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Word32
  -> V.Vector Rect2D
  -> m ()
cmdSetScissor commandBuffer firstScissor scissors =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_scissorCount = fromIntegral (V.length scissors) :: Word32
    p_scissors <- do pv_ <- newVector scissors; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdSetScissor
          (checkCommandPtr "vkCmdSetScissor" commandBuffer.cmds.pCmdSetScissor)
          (castPtr commandBuffer.handle)
          firstScissor
          n_scissorCount
          p_scissors
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetStencilCompareMask.html vkCmdSetStencilCompareMask>
-- Available: VK_VERSION_1_0
cmdSetStencilCompareMask
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> StencilFaceFlags
  -> Word32
  -> m ()
cmdSetStencilCompareMask commandBuffer faceMask compareMask =
  liftIO do
    liftIO
      ( mkCmdSetStencilCompareMask
          (checkCommandPtr "vkCmdSetStencilCompareMask" commandBuffer.cmds.pCmdSetStencilCompareMask)
          (castPtr commandBuffer.handle)
          ((\(Flags w) -> w) faceMask)
          compareMask
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetStencilReference.html vkCmdSetStencilReference>
-- Available: VK_VERSION_1_0
cmdSetStencilReference
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> StencilFaceFlags
  -> Word32
  -> m ()
cmdSetStencilReference commandBuffer faceMask reference =
  liftIO do
    liftIO
      ( mkCmdSetStencilReference
          (checkCommandPtr "vkCmdSetStencilReference" commandBuffer.cmds.pCmdSetStencilReference)
          (castPtr commandBuffer.handle)
          ((\(Flags w) -> w) faceMask)
          reference
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetStencilWriteMask.html vkCmdSetStencilWriteMask>
-- Available: VK_VERSION_1_0
cmdSetStencilWriteMask
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> StencilFaceFlags
  -> Word32
  -> m ()
cmdSetStencilWriteMask commandBuffer faceMask writeMask =
  liftIO do
    liftIO
      ( mkCmdSetStencilWriteMask
          (checkCommandPtr "vkCmdSetStencilWriteMask" commandBuffer.cmds.pCmdSetStencilWriteMask)
          (castPtr commandBuffer.handle)
          ((\(Flags w) -> w) faceMask)
          writeMask
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetViewport.html vkCmdSetViewport>
-- Available: VK_VERSION_1_0
cmdSetViewport
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Word32
  -> V.Vector Viewport
  -> m ()
cmdSetViewport commandBuffer firstViewport viewports =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_viewportCount = fromIntegral (V.length viewports) :: Word32
    p_viewports <- do pv_ <- newVector viewports; pure (castPtr pv_ :: Ptr ())
    liftIO
      ( mkCmdSetViewport
          (checkCommandPtr "vkCmdSetViewport" commandBuffer.cmds.pCmdSetViewport)
          (castPtr commandBuffer.handle)
          firstViewport
          n_viewportCount
          p_viewports
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdUpdateBuffer.html vkCmdUpdateBuffer>
-- Available: VK_VERSION_1_0
-- __Deprecated__: superseded by vkCmdUpdateMemoryKHR.
cmdUpdateBuffer
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Buffer
  -> DeviceSize
  -> ByteString
  -> m ()
cmdUpdateBuffer commandBuffer dstBuffer dstOffset data' =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_dataSize = fromIntegral (BS.length data') :: Word64
    p_data' :: Ptr () <- castPtr <$> newBytes data'
    liftIO
      ( mkCmdUpdateBuffer
          (checkCommandPtr "vkCmdUpdateBuffer" commandBuffer.cmds.pCmdUpdateBuffer)
          (castPtr commandBuffer.handle)
          (case dstBuffer of Buffer w_ -> w_)
          (fromIntegral dstOffset :: Word64)
          n_dataSize
          p_data'
      )
    pure ()
