-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.DeviceCommands (
  DeviceCreateInfo (..),
  DeviceQueueCreateInfo (..),
  createDevice,
  withDevice,
  destroyDevice,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.DeviceCreateFlags
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Core11.Enums.DeviceQueueCreateFlagBits
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceCreateInfo.html VkDeviceCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @queueCreateInfoCount@ is derived from @queueCreateInfos@'s length.
--   * @enabledLayerCount@ is derived from @enabledLayerNames@'s length.
--   * @enabledExtensionCount@ is derived from @enabledExtensionNames@'s length.
data DeviceCreateInfo (es :: [Type]) = DeviceCreateInfo
  { next :: Chain es
  , flags :: DeviceCreateFlags
  , queueCreateInfos :: V.Vector (SomeStruct DeviceQueueCreateInfo)
  , enabledLayerNames :: V.Vector ByteString
  , enabledExtensionNames :: V.Vector ByteString
  , enabledFeatures :: Maybe PhysicalDeviceFeatures
  }

instance (AllExtends DeviceCreateInfo es, PokeChain es) => CStruct (DeviceCreateInfo es) where
  cSize = 72
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (3 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    p_queueCreateInfos <- arenaBytes (40 * max 1 (V.length x.queueCreateInfos)) 8
    V.imapM_
      (\i e -> withSomeStruct e (pokeCStruct (castPtr (p_queueCreateInfos `plusPtr` (i * 40)))))
      x.queueCreateInfos
    liftIO
      ( pokeByteOff
          p
          24
          (if V.null x.queueCreateInfos then nullPtr else (castPtr p_queueCreateInfos :: Ptr ()))
      )
    liftIO (pokeByteOff p 20 (fromIntegral (V.length x.queueCreateInfos) :: Word32))
    p_enabledLayerNames <- newCStrings x.enabledLayerNames
    liftIO (pokeByteOff p 40 (if V.null x.enabledLayerNames then nullPtr else p_enabledLayerNames))
    liftIO (pokeByteOff p 32 (fromIntegral (V.length x.enabledLayerNames) :: Word32))
    p_enabledExtensionNames <- newCStrings x.enabledExtensionNames
    liftIO
      (pokeByteOff p 56 (if V.null x.enabledExtensionNames then nullPtr else p_enabledExtensionNames))
    liftIO (pokeByteOff p 48 (fromIntegral (V.length x.enabledExtensionNames) :: Word32))
    p_enabledFeatures <- maybe (pure nullPtr) new x.enabledFeatures
    liftIO (pokeByteOff p 64 p_enabledFeatures)
    pure ()

instance (NilChain es) => Nil (DeviceCreateInfo es) where
  nil =
    DeviceCreateInfo
      { next = nilChain
      , flags = mempty
      , queueCreateInfos = V.empty
      , enabledLayerNames = V.empty
      , enabledExtensionNames = V.empty
      , enabledFeatures = Nothing
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceQueueCreateInfo.html VkDeviceQueueCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @queueCount@ is derived from @queuePriorities@'s length.
data DeviceQueueCreateInfo (es :: [Type]) = DeviceQueueCreateInfo
  { next :: Chain es
  , flags :: DeviceQueueCreateFlags
  , queueFamilyIndex :: Word32
  , queuePriorities :: V.Vector Float
  }

instance (AllExtends DeviceQueueCreateInfo es, PokeChain es) => CStruct (DeviceQueueCreateInfo es) where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (2 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 x.queueFamilyIndex)
    p_queuePriorities <- arenaBytes (4 * max 1 (V.length x.queuePriorities)) 4
    liftIO (V.imapM_ (\i v -> pokeByteOff p_queuePriorities (i * 4) v) x.queuePriorities)
    liftIO
      ( pokeByteOff
          p
          32
          (if V.null x.queuePriorities then nullPtr else (castPtr p_queuePriorities :: Ptr ()))
      )
    liftIO (pokeByteOff p 24 (fromIntegral (V.length x.queuePriorities) :: Word32))
    pure ()

instance
  (AllExtends DeviceQueueCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (DeviceQueueCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_queueFamilyIndex <- (peekByteOff p 20)
    v_queuePriorities <- do
      n <- (peekByteOff p 24 :: IO Word32)
      q <- peekByteOff p 32 :: IO (Ptr ())
      if q == nullPtr then pure V.empty else V.generateM (fromIntegral n) (\i -> peekByteOff q (i * 4))
    pure
      DeviceQueueCreateInfo
        { next = v_next
        , flags = v_flags
        , queueFamilyIndex = v_queueFamilyIndex
        , queuePriorities = v_queuePriorities
        }

instance (NilChain es) => Nil (DeviceQueueCreateInfo es) where
  nil =
    DeviceQueueCreateInfo
      { next = nilChain
      , flags = mempty
      , queueFamilyIndex = 0
      , queuePriorities = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateDevice.html vkCreateDevice>
-- Available: VK_VERSION_1_0
createDevice
  :: forall m es1
   . (MonadIO m, AllExtends DeviceCreateInfo es1, PokeChain es1)
  => PhysicalDevice
  -> DeviceCreateInfo es1
  -> Maybe AllocationCallbacks
  -> m (Outcome Device)
createDevice physicalDevice createInfo allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_createInfo :: Ptr () <- castPtr <$> new createInfo
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_device <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateDevice
            (checkCommandPtr "vkCreateDevice" physicalDevice.cmds.pCreateDevice)
            (castPtr physicalDevice.handle)
            p_createInfo
            p_allocator
            (castPtr p_o_device)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      hp_o_device <- liftIO (peekByteOff p_o_device 0 :: IO (Ptr ()))
      o_device <- liftIO (Device (castPtr hp_o_device) <$> initDeviceCmds physicalDevice.cmds hp_o_device)
      pure (Ok (openFromWire r_) o_device)

withDevice
  :: forall m r es1
   . (MonadUnliftIO m, AllExtends DeviceCreateInfo es1, PokeChain es1)
  => PhysicalDevice
  -> DeviceCreateInfo es1
  -> Maybe AllocationCallbacks
  -> (Outcome Device -> m r)
  -> m r
withDevice physicalDevice createInfo allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createDevice physicalDevice createInfo allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroyDevice h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroyDevice.html vkDestroyDevice>
-- Available: VK_VERSION_1_0
destroyDevice
  :: forall m
   . (MonadIO m)
  => Device
  -> Maybe AllocationCallbacks
  -> m ()
destroyDevice device allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroyDevice
          (checkCommandPtr "vkDestroyDevice" device.cmds.pDestroyDevice)
          (castPtr device.handle)
          p_allocator
      )
    pure ()
