-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.FenceCommands (
  FenceCreateInfo (..),
  createFence,
  withFence,
  destroyFence,
  getFenceStatus,
  resetFences,
  waitForFences,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.FenceCreateFlagBits
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkFenceCreateInfo.html VkFenceCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data FenceCreateInfo (es :: [Type]) = FenceCreateInfo
  { next :: Chain es
  , flags :: FenceCreateFlags
  }

instance (AllExtends FenceCreateInfo es, PokeChain es) => CStruct (FenceCreateInfo es) where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (8 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    pure ()

instance (AllExtends FenceCreateInfo es, PokeChain es, PeekChain es) => FromCStruct (FenceCreateInfo es) where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    pure FenceCreateInfo{next = v_next, flags = v_flags}

instance (NilChain es) => Nil (FenceCreateInfo es) where
  nil =
    FenceCreateInfo
      { next = nilChain
      , flags = mempty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateFence.html vkCreateFence>
-- Available: VK_VERSION_1_0
createFence
  :: forall m es1
   . (MonadIO m, AllExtends FenceCreateInfo es1, PokeChain es1)
  => Device
  -> FenceCreateInfo es1
  -> Maybe AllocationCallbacks
  -> m (Outcome Fence)
createFence device createInfo allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_createInfo :: Ptr () <- castPtr <$> new createInfo
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_fence <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateFence
            (checkCommandPtr "vkCreateFence" device.cmds.pCreateFence)
            (castPtr device.handle)
            p_createInfo
            p_allocator
            (castPtr p_o_fence)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_fence <- liftIO (peekByteOff p_o_fence 0 :: IO Word64)
      let o_fence = Fence w_o_fence
      pure (Ok (openFromWire r_) o_fence)

withFence
  :: forall m r es1
   . (MonadUnliftIO m, AllExtends FenceCreateInfo es1, PokeChain es1)
  => Device
  -> FenceCreateInfo es1
  -> Maybe AllocationCallbacks
  -> (Outcome Fence -> m r)
  -> m r
withFence device createInfo allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createFence device createInfo allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroyFence device h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroyFence.html vkDestroyFence>
-- Available: VK_VERSION_1_0
destroyFence
  :: forall m
   . (MonadIO m)
  => Device
  -> Fence
  -> Maybe AllocationCallbacks
  -> m ()
destroyFence device fence allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroyFence
          (checkCommandPtr "vkDestroyFence" device.cmds.pDestroyFence)
          (castPtr device.handle)
          (case fence of Fence w_ -> w_)
          p_allocator
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetFenceStatus.html vkGetFenceStatus>
-- Available: VK_VERSION_1_0
getFenceStatus
  :: forall m
   . (MonadIO m)
  => Device
  -> Fence
  -> m (Outcome ())
getFenceStatus device fence =
  liftIO do
    r_ <-
      liftIO
        ( mkGetFenceStatus
            (checkCommandPtr "vkGetFenceStatus" device.cmds.pGetFenceStatus)
            (castPtr device.handle)
            (case fence of Fence w_ -> w_)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkResetFences.html vkResetFences>
-- Available: VK_VERSION_1_0
resetFences
  :: forall m
   . (MonadIO m)
  => Device
  -> V.Vector Fence
  -> m (Outcome ())
resetFences device fences =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_fenceCount = fromIntegral (V.length fences) :: Word32
    p_fences <- do
      pv_ <- arenaBytes (8 * max 1 (V.length fences)) 8
      liftIO (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 8) (case v_e of Fence w_ -> w_)) fences)
      pure (castPtr pv_ :: Ptr ())
    r_ <-
      liftIO
        ( mkResetFences
            (checkCommandPtr "vkResetFences" device.cmds.pResetFences)
            (castPtr device.handle)
            n_fenceCount
            p_fences
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkWaitForFences.html vkWaitForFences>
-- Available: VK_VERSION_1_0
waitForFences
  :: forall m
   . (MonadIO m)
  => Device
  -> V.Vector Fence
  -> Bool
  -> Word64
  -> m (Outcome ())
waitForFences device fences waitAll timeout =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_fenceCount = fromIntegral (V.length fences) :: Word32
    p_fences <- do
      pv_ <- arenaBytes (8 * max 1 (V.length fences)) 8
      liftIO (V.imapM_ (\i v_e -> pokeByteOff pv_ (i * 8) (case v_e of Fence w_ -> w_)) fences)
      pure (castPtr pv_ :: Ptr ())
    r_ <-
      liftIO
        ( mkWaitForFences
            (checkCommandPtr "vkWaitForFences" device.cmds.pWaitForFences)
            (castPtr device.handle)
            n_fenceCount
            p_fences
            (if waitAll then 1 else 0 :: Word32)
            timeout
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())
