-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.GraphicsPipelineCommands (
  PipelineColorBlendAttachmentState (..),
  StencilOpState (..),
  VertexInputAttributeDescription (..),
  VertexInputBindingDescription (..),
  Viewport (..),
  GraphicsPipelineCreateInfo (..),
  PipelineColorBlendStateCreateInfo (..),
  PipelineDepthStencilStateCreateInfo (..),
  PipelineDynamicStateCreateInfo (..),
  PipelineInputAssemblyStateCreateInfo (..),
  PipelineMultisampleStateCreateInfo (..),
  PipelineRasterizationStateCreateInfo (..),
  PipelineTessellationStateCreateInfo (..),
  PipelineVertexInputStateCreateInfo (..),
  PipelineViewportStateCreateInfo (..),
  createGraphicsPipelines,
  withGraphicsPipelines,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Vector.Storable.Sized qualified as VSS
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.ComputePipelineCommands
import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.BlendFactor
import Lithon.Vk.Core10.Enums.BlendOp
import Lithon.Vk.Core10.Enums.ColorComponentFlagBits
import Lithon.Vk.Core10.Enums.CompareOp
import Lithon.Vk.Core10.Enums.CullModeFlagBits
import Lithon.Vk.Core10.Enums.DynamicState
import Lithon.Vk.Core10.Enums.Format
import Lithon.Vk.Core10.Enums.FrontFace
import Lithon.Vk.Core10.Enums.LogicOp
import Lithon.Vk.Core10.Enums.PipelineColorBlendStateCreateFlagBits
import Lithon.Vk.Core10.Enums.PipelineCreateFlagBits
import Lithon.Vk.Core10.Enums.PipelineDepthStencilStateCreateFlagBits
import Lithon.Vk.Core10.Enums.PipelineDynamicStateCreateFlags
import Lithon.Vk.Core10.Enums.PipelineInputAssemblyStateCreateFlags
import Lithon.Vk.Core10.Enums.PipelineMultisampleStateCreateFlags
import Lithon.Vk.Core10.Enums.PipelineRasterizationStateCreateFlags
import Lithon.Vk.Core10.Enums.PipelineTessellationStateCreateFlags
import Lithon.Vk.Core10.Enums.PipelineVertexInputStateCreateFlags
import Lithon.Vk.Core10.Enums.PipelineViewportStateCreateFlags
import Lithon.Vk.Core10.Enums.PolygonMode
import Lithon.Vk.Core10.Enums.PrimitiveTopology
import Lithon.Vk.Core10.Enums.SampleCountFlagBits
import Lithon.Vk.Core10.Enums.StencilOp
import Lithon.Vk.Core10.Enums.VertexInputRate
import Lithon.Vk.Core10.FundamentalTypesUsedByManyCommandsAndStructures
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineColorBlendAttachmentState.html VkPipelineColorBlendAttachmentState>
-- Available: VK_VERSION_1_0
data PipelineColorBlendAttachmentState = PipelineColorBlendAttachmentState
  { blendEnable :: !Bool
  , srcColorBlendFactor :: !BlendFactor
  , dstColorBlendFactor :: !BlendFactor
  , colorBlendOp :: !BlendOp
  , srcAlphaBlendFactor :: !BlendFactor
  , dstAlphaBlendFactor :: !BlendFactor
  , alphaBlendOp :: !BlendOp
  , colorWriteMask :: !ColorComponentFlags
  }
  deriving stock (Eq, Show)

instance Storable PipelineColorBlendAttachmentState where
  sizeOf _ = 32
  alignment _ = 4
  peek p =
    PipelineColorBlendAttachmentState
      <$> (toBool <$> peekByteOff p 0)
      <*> (unsafeFromWire <$> peekByteOff p 4)
      <*> (unsafeFromWire <$> peekByteOff p 8)
      <*> (unsafeFromWire <$> peekByteOff p 12)
      <*> (unsafeFromWire <$> peekByteOff p 16)
      <*> (unsafeFromWire <$> peekByteOff p 20)
      <*> (unsafeFromWire <$> peekByteOff p 24)
      <*> (peekByteOff p 28)
  poke p x = do
    pokeByteOff p 0 (if x.blendEnable then TRUE else FALSE)
    pokeByteOff p 4 (toWire x.srcColorBlendFactor)
    pokeByteOff p 8 (toWire x.dstColorBlendFactor)
    pokeByteOff p 12 (toWire x.colorBlendOp)
    pokeByteOff p 16 (toWire x.srcAlphaBlendFactor)
    pokeByteOff p 20 (toWire x.dstAlphaBlendFactor)
    pokeByteOff p 24 (toWire x.alphaBlendOp)
    pokeByteOff p 28 x.colorWriteMask

instance CStruct PipelineColorBlendAttachmentState where
  cSize = 32
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct PipelineColorBlendAttachmentState where
  peekCStruct = peek

instance Nil PipelineColorBlendAttachmentState where
  nil =
    PipelineColorBlendAttachmentState
      { blendEnable = False
      , srcColorBlendFactor = BlendFactorZero
      , dstColorBlendFactor = BlendFactorZero
      , colorBlendOp = BlendOpAdd
      , srcAlphaBlendFactor = BlendFactorZero
      , dstAlphaBlendFactor = BlendFactorZero
      , alphaBlendOp = BlendOpAdd
      , colorWriteMask = mempty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkStencilOpState.html VkStencilOpState>
-- Available: VK_VERSION_1_0
data StencilOpState = StencilOpState
  { failOp :: !StencilOp
  , passOp :: !StencilOp
  , depthFailOp :: !StencilOp
  , compareOp :: !CompareOp
  , compareMask :: !Word32
  , writeMask :: !Word32
  , reference :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable StencilOpState where
  sizeOf _ = 28
  alignment _ = 4
  peek p =
    StencilOpState
      <$> (unsafeFromWire <$> peekByteOff p 0)
      <*> (unsafeFromWire <$> peekByteOff p 4)
      <*> (unsafeFromWire <$> peekByteOff p 8)
      <*> (unsafeFromWire <$> peekByteOff p 12)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 20)
      <*> (peekByteOff p 24)
  poke p x = do
    pokeByteOff p 0 (toWire x.failOp)
    pokeByteOff p 4 (toWire x.passOp)
    pokeByteOff p 8 (toWire x.depthFailOp)
    pokeByteOff p 12 (toWire x.compareOp)
    pokeByteOff p 16 x.compareMask
    pokeByteOff p 20 x.writeMask
    pokeByteOff p 24 x.reference

instance CStruct StencilOpState where
  cSize = 28
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct StencilOpState where
  peekCStruct = peek

instance Nil StencilOpState where
  nil =
    StencilOpState
      { failOp = StencilOpKeep
      , passOp = StencilOpKeep
      , depthFailOp = StencilOpKeep
      , compareOp = CompareOpNever
      , compareMask = 0
      , writeMask = 0
      , reference = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkVertexInputAttributeDescription.html VkVertexInputAttributeDescription>
-- Available: VK_VERSION_1_0
data VertexInputAttributeDescription = VertexInputAttributeDescription
  { location :: !Word32
  , binding :: !Word32
  , format :: !(Open Format)
  , offset :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable VertexInputAttributeDescription where
  sizeOf _ = 16
  alignment _ = 4
  peek p =
    VertexInputAttributeDescription
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (openFromWire <$> peekByteOff p 8)
      <*> (peekByteOff p 12)
  poke p x = do
    pokeByteOff p 0 x.location
    pokeByteOff p 4 x.binding
    pokeByteOff p 8 (openToWire x.format)
    pokeByteOff p 12 x.offset

instance CStruct VertexInputAttributeDescription where
  cSize = 16
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct VertexInputAttributeDescription where
  peekCStruct = peek

instance Nil VertexInputAttributeDescription where
  nil =
    VertexInputAttributeDescription
      { location = 0
      , binding = 0
      , format = Known FormatUndefined
      , offset = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkVertexInputBindingDescription.html VkVertexInputBindingDescription>
-- Available: VK_VERSION_1_0
data VertexInputBindingDescription = VertexInputBindingDescription
  { binding :: !Word32
  , stride :: !Word32
  , inputRate :: !VertexInputRate
  }
  deriving stock (Eq, Show)

instance Storable VertexInputBindingDescription where
  sizeOf _ = 12
  alignment _ = 4
  peek p =
    VertexInputBindingDescription
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (unsafeFromWire <$> peekByteOff p 8)
  poke p x = do
    pokeByteOff p 0 x.binding
    pokeByteOff p 4 x.stride
    pokeByteOff p 8 (toWire x.inputRate)

instance CStruct VertexInputBindingDescription where
  cSize = 12
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct VertexInputBindingDescription where
  peekCStruct = peek

instance Nil VertexInputBindingDescription where
  nil =
    VertexInputBindingDescription
      { binding = 0
      , stride = 0
      , inputRate = VertexInputRateVertex
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkViewport.html VkViewport>
-- Available: VK_VERSION_1_0
data Viewport = Viewport
  { x :: !Float
  , y :: !Float
  , width :: !Float
  , height :: !Float
  , minDepth :: !Float
  , maxDepth :: !Float
  }
  deriving stock (Eq, Show)

instance Storable Viewport where
  sizeOf _ = 24
  alignment _ = 4
  peek p =
    Viewport
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 20)
  poke p x = do
    pokeByteOff p 0 x.x
    pokeByteOff p 4 x.y
    pokeByteOff p 8 x.width
    pokeByteOff p 12 x.height
    pokeByteOff p 16 x.minDepth
    pokeByteOff p 20 x.maxDepth

instance CStruct Viewport where
  cSize = 24
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct Viewport where
  peekCStruct = peek

instance Nil Viewport where
  nil =
    Viewport
      { x = 0
      , y = 0
      , width = 0
      , height = 0
      , minDepth = 0
      , maxDepth = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkGraphicsPipelineCreateInfo.html VkGraphicsPipelineCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @stageCount@ is derived from @stages@'s length.
data GraphicsPipelineCreateInfo (es :: [Type]) = GraphicsPipelineCreateInfo
  { next :: Chain es
  , flags :: PipelineCreateFlags
  , stages :: V.Vector (SomeStruct PipelineShaderStageCreateInfo)
  , vertexInputState :: Maybe (SomeStruct PipelineVertexInputStateCreateInfo)
  , inputAssemblyState :: Maybe PipelineInputAssemblyStateCreateInfo
  , tessellationState :: Maybe (SomeStruct PipelineTessellationStateCreateInfo)
  , viewportState :: Maybe PipelineViewportStateCreateInfo
  , rasterizationState :: Maybe (SomeStruct PipelineRasterizationStateCreateInfo)
  , multisampleState :: Maybe (SomeStruct PipelineMultisampleStateCreateInfo)
  , depthStencilState :: Maybe PipelineDepthStencilStateCreateInfo
  , colorBlendState :: Maybe (SomeStruct PipelineColorBlendStateCreateInfo)
  , dynamicState :: Maybe PipelineDynamicStateCreateInfo
  , layout :: PipelineLayout
  , renderPass :: RenderPass
  , subpass :: Word32
  , basePipelineHandle :: Pipeline
  , basePipelineIndex :: Int32
  }

instance (AllExtends GraphicsPipelineCreateInfo es, PokeChain es) => CStruct (GraphicsPipelineCreateInfo es) where
  cSize = 144
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (28 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    p_stages <- arenaBytes (48 * max 1 (V.length x.stages)) 8
    V.imapM_ (\i e -> withSomeStruct e (pokeCStruct (castPtr (p_stages `plusPtr` (i * 48))))) x.stages
    liftIO (pokeByteOff p 24 (if V.null x.stages then nullPtr else (castPtr p_stages :: Ptr ())))
    liftIO (pokeByteOff p 20 (fromIntegral (V.length x.stages) :: Word32))
    p_vertexInputState <-
      maybe (pure nullPtr) (\s -> withSomeStruct s (fmap castPtr . new)) x.vertexInputState
    liftIO (pokeByteOff p 32 p_vertexInputState)
    p_inputAssemblyState <- maybe (pure nullPtr) new x.inputAssemblyState
    liftIO (pokeByteOff p 40 p_inputAssemblyState)
    p_tessellationState <-
      maybe (pure nullPtr) (\s -> withSomeStruct s (fmap castPtr . new)) x.tessellationState
    liftIO (pokeByteOff p 48 p_tessellationState)
    p_viewportState <- maybe (pure nullPtr) new x.viewportState
    liftIO (pokeByteOff p 56 p_viewportState)
    p_rasterizationState <-
      maybe (pure nullPtr) (\s -> withSomeStruct s (fmap castPtr . new)) x.rasterizationState
    liftIO (pokeByteOff p 64 p_rasterizationState)
    p_multisampleState <-
      maybe (pure nullPtr) (\s -> withSomeStruct s (fmap castPtr . new)) x.multisampleState
    liftIO (pokeByteOff p 72 p_multisampleState)
    p_depthStencilState <- maybe (pure nullPtr) new x.depthStencilState
    liftIO (pokeByteOff p 80 p_depthStencilState)
    p_colorBlendState <-
      maybe (pure nullPtr) (\s -> withSomeStruct s (fmap castPtr . new)) x.colorBlendState
    liftIO (pokeByteOff p 88 p_colorBlendState)
    p_dynamicState <- maybe (pure nullPtr) new x.dynamicState
    liftIO (pokeByteOff p 96 p_dynamicState)
    liftIO (pokeByteOff p 104 x.layout)
    liftIO (pokeByteOff p 112 x.renderPass)
    liftIO (pokeByteOff p 120 x.subpass)
    liftIO (pokeByteOff p 128 x.basePipelineHandle)
    liftIO (pokeByteOff p 136 x.basePipelineIndex)
    pure ()

instance (NilChain es) => Nil (GraphicsPipelineCreateInfo es) where
  nil =
    GraphicsPipelineCreateInfo
      { next = nilChain
      , flags = mempty
      , stages = V.empty
      , vertexInputState = Nothing
      , inputAssemblyState = Nothing
      , tessellationState = Nothing
      , viewportState = Nothing
      , rasterizationState = Nothing
      , multisampleState = Nothing
      , depthStencilState = Nothing
      , colorBlendState = Nothing
      , dynamicState = Nothing
      , layout = nil
      , renderPass = nil
      , subpass = 0
      , basePipelineHandle = nil
      , basePipelineIndex = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineColorBlendStateCreateInfo.html VkPipelineColorBlendStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @attachmentCount@ is derived from @attachments@'s length.
data PipelineColorBlendStateCreateInfo (es :: [Type]) = PipelineColorBlendStateCreateInfo
  { next :: Chain es
  , flags :: PipelineColorBlendStateCreateFlags
  , logicOpEnable :: Bool
  , logicOp :: LogicOp
  , attachments :: V.Vector PipelineColorBlendAttachmentState
  , blendConstants :: VSS.Vector 4 Float
  }

instance
  (AllExtends PipelineColorBlendStateCreateInfo es, PokeChain es)
  => CStruct (PipelineColorBlendStateCreateInfo es)
  where
  cSize = 56
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (26 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 (if x.logicOpEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 24 (toWire x.logicOp))
    p_attachments <- if V.null x.attachments then pure nullPtr else newVector x.attachments
    liftIO (pokeByteOff p 32 p_attachments)
    liftIO (pokeByteOff p 28 (fromIntegral (V.length x.attachments) :: Word32))
    liftIO (pokeByteOff p 40 x.blendConstants)
    pure ()

instance
  (AllExtends PipelineColorBlendStateCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (PipelineColorBlendStateCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_logicOpEnable <- (toBool <$> peekByteOff p 20)
    v_logicOp <- (unsafeFromWire <$> peekByteOff p 24)
    v_attachments <- do
      n <- (peekByteOff p 28 :: IO Word32)
      q <- peekByteOff p 32
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    v_blendConstants <- (peekByteOff p 40)
    pure
      PipelineColorBlendStateCreateInfo
        { next = v_next
        , flags = v_flags
        , logicOpEnable = v_logicOpEnable
        , logicOp = v_logicOp
        , attachments = v_attachments
        , blendConstants = v_blendConstants
        }

instance (NilChain es) => Nil (PipelineColorBlendStateCreateInfo es) where
  nil =
    PipelineColorBlendStateCreateInfo
      { next = nilChain
      , flags = mempty
      , logicOpEnable = False
      , logicOp = LogicOpClear
      , attachments = V.empty
      , blendConstants = VSS.replicate 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineDepthStencilStateCreateInfo.html VkPipelineDepthStencilStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PipelineDepthStencilStateCreateInfo = PipelineDepthStencilStateCreateInfo
  { flags :: PipelineDepthStencilStateCreateFlags
  , depthTestEnable :: Bool
  , depthWriteEnable :: Bool
  , depthCompareOp :: CompareOp
  , depthBoundsTestEnable :: Bool
  , stencilTestEnable :: Bool
  , front :: StencilOpState
  , back :: StencilOpState
  , minDepthBounds :: Float
  , maxDepthBounds :: Float
  }

instance CStruct PipelineDepthStencilStateCreateInfo where
  cSize = 104
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (25 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 (if x.depthTestEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 24 (if x.depthWriteEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 28 (toWire x.depthCompareOp))
    liftIO (pokeByteOff p 32 (if x.depthBoundsTestEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 36 (if x.stencilTestEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 40 x.front)
    liftIO (pokeByteOff p 68 x.back)
    liftIO (pokeByteOff p 96 x.minDepthBounds)
    liftIO (pokeByteOff p 100 x.maxDepthBounds)
    pure ()

instance FromCStruct PipelineDepthStencilStateCreateInfo where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_depthTestEnable <- (toBool <$> peekByteOff p 20)
    v_depthWriteEnable <- (toBool <$> peekByteOff p 24)
    v_depthCompareOp <- (unsafeFromWire <$> peekByteOff p 28)
    v_depthBoundsTestEnable <- (toBool <$> peekByteOff p 32)
    v_stencilTestEnable <- (toBool <$> peekByteOff p 36)
    v_front <- (peekByteOff p 40)
    v_back <- (peekByteOff p 68)
    v_minDepthBounds <- (peekByteOff p 96)
    v_maxDepthBounds <- (peekByteOff p 100)
    pure
      PipelineDepthStencilStateCreateInfo
        { flags = v_flags
        , depthTestEnable = v_depthTestEnable
        , depthWriteEnable = v_depthWriteEnable
        , depthCompareOp = v_depthCompareOp
        , depthBoundsTestEnable = v_depthBoundsTestEnable
        , stencilTestEnable = v_stencilTestEnable
        , front = v_front
        , back = v_back
        , minDepthBounds = v_minDepthBounds
        , maxDepthBounds = v_maxDepthBounds
        }

instance Nil PipelineDepthStencilStateCreateInfo where
  nil =
    PipelineDepthStencilStateCreateInfo
      { flags = mempty
      , depthTestEnable = False
      , depthWriteEnable = False
      , depthCompareOp = CompareOpNever
      , depthBoundsTestEnable = False
      , stencilTestEnable = False
      , front = nil
      , back = nil
      , minDepthBounds = 0
      , maxDepthBounds = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineDynamicStateCreateInfo.html VkPipelineDynamicStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @dynamicStateCount@ is derived from @dynamicStates@'s length.
data PipelineDynamicStateCreateInfo = PipelineDynamicStateCreateInfo
  { flags :: PipelineDynamicStateCreateFlags
  , dynamicStates :: V.Vector DynamicState
  }

instance CStruct PipelineDynamicStateCreateInfo where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (27 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    p_dynamicStates <- arenaBytes (4 * max 1 (V.length x.dynamicStates)) 4
    liftIO (V.imapM_ (\i v -> pokeByteOff p_dynamicStates (i * 4) (toWire v)) x.dynamicStates)
    liftIO
      (pokeByteOff p 24 (if V.null x.dynamicStates then nullPtr else (castPtr p_dynamicStates :: Ptr ())))
    liftIO (pokeByteOff p 20 (fromIntegral (V.length x.dynamicStates) :: Word32))
    pure ()

instance FromCStruct PipelineDynamicStateCreateInfo where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_dynamicStates <- do
      n <- (peekByteOff p 20 :: IO Word32)
      q <- peekByteOff p 24 :: IO (Ptr ())
      if q == nullPtr then
        pure V.empty
      else
        V.generateM (fromIntegral n) (\i -> unsafeFromWire <$> peekByteOff q (i * 4))
    pure PipelineDynamicStateCreateInfo{flags = v_flags, dynamicStates = v_dynamicStates}

instance Nil PipelineDynamicStateCreateInfo where
  nil =
    PipelineDynamicStateCreateInfo
      { flags = mempty
      , dynamicStates = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineInputAssemblyStateCreateInfo.html VkPipelineInputAssemblyStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PipelineInputAssemblyStateCreateInfo = PipelineInputAssemblyStateCreateInfo
  { flags :: PipelineInputAssemblyStateCreateFlags
  , topology :: PrimitiveTopology
  , primitiveRestartEnable :: Bool
  }

instance CStruct PipelineInputAssemblyStateCreateInfo where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (20 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 (toWire x.topology))
    liftIO (pokeByteOff p 24 (if x.primitiveRestartEnable then TRUE else FALSE))
    pure ()

instance FromCStruct PipelineInputAssemblyStateCreateInfo where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_topology <- (unsafeFromWire <$> peekByteOff p 20)
    v_primitiveRestartEnable <- (toBool <$> peekByteOff p 24)
    pure
      PipelineInputAssemblyStateCreateInfo
        { flags = v_flags
        , topology = v_topology
        , primitiveRestartEnable = v_primitiveRestartEnable
        }

instance Nil PipelineInputAssemblyStateCreateInfo where
  nil =
    PipelineInputAssemblyStateCreateInfo
      { flags = mempty
      , topology = PrimitiveTopologyPointList
      , primitiveRestartEnable = False
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineMultisampleStateCreateInfo.html VkPipelineMultisampleStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data PipelineMultisampleStateCreateInfo (es :: [Type]) = PipelineMultisampleStateCreateInfo
  { next :: Chain es
  , flags :: PipelineMultisampleStateCreateFlags
  , rasterizationSamples :: Flags SampleCountFlagBits
  , sampleShadingEnable :: Bool
  , minSampleShading :: Float
  , sampleMask :: V.Vector Word32
  , alphaToCoverageEnable :: Bool
  , alphaToOneEnable :: Bool
  }

instance
  (AllExtends PipelineMultisampleStateCreateInfo es, PokeChain es)
  => CStruct (PipelineMultisampleStateCreateInfo es)
  where
  cSize = 48
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (24 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 x.rasterizationSamples)
    liftIO (pokeByteOff p 24 (if x.sampleShadingEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 28 x.minSampleShading)
    p_sampleMask <- arenaBytes (4 * max 1 (V.length x.sampleMask)) 4
    liftIO (V.imapM_ (\i v -> pokeByteOff p_sampleMask (i * 4) v) x.sampleMask)
    liftIO
      (pokeByteOff p 32 (if V.null x.sampleMask then nullPtr else (castPtr p_sampleMask :: Ptr ())))
    liftIO (pokeByteOff p 40 (if x.alphaToCoverageEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 44 (if x.alphaToOneEnable then TRUE else FALSE))
    pure ()

instance
  (AllExtends PipelineMultisampleStateCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (PipelineMultisampleStateCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_rasterizationSamples <- (peekByteOff p 20)
    v_sampleShadingEnable <- (toBool <$> peekByteOff p 24)
    v_minSampleShading <- (peekByteOff p 28)
    v_sampleMask <- do
      n <- pure (0 :: Word32)
      q <- peekByteOff p 32 :: IO (Ptr ())
      if q == nullPtr then pure V.empty else V.generateM (fromIntegral n) (\i -> peekByteOff q (i * 4))
    v_alphaToCoverageEnable <- (toBool <$> peekByteOff p 40)
    v_alphaToOneEnable <- (toBool <$> peekByteOff p 44)
    pure
      PipelineMultisampleStateCreateInfo
        { next = v_next
        , flags = v_flags
        , rasterizationSamples = v_rasterizationSamples
        , sampleShadingEnable = v_sampleShadingEnable
        , minSampleShading = v_minSampleShading
        , sampleMask = v_sampleMask
        , alphaToCoverageEnable = v_alphaToCoverageEnable
        , alphaToOneEnable = v_alphaToOneEnable
        }

instance (NilChain es) => Nil (PipelineMultisampleStateCreateInfo es) where
  nil =
    PipelineMultisampleStateCreateInfo
      { next = nilChain
      , flags = mempty
      , rasterizationSamples = mempty
      , sampleShadingEnable = False
      , minSampleShading = 0
      , sampleMask = V.empty
      , alphaToCoverageEnable = False
      , alphaToOneEnable = False
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineRasterizationStateCreateInfo.html VkPipelineRasterizationStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data PipelineRasterizationStateCreateInfo (es :: [Type]) = PipelineRasterizationStateCreateInfo
  { next :: Chain es
  , flags :: PipelineRasterizationStateCreateFlags
  , depthClampEnable :: Bool
  , rasterizerDiscardEnable :: Bool
  , polygonMode :: PolygonMode
  , cullMode :: CullModeFlags
  , frontFace :: FrontFace
  , depthBiasEnable :: Bool
  , depthBiasConstantFactor :: Float
  , depthBiasClamp :: Float
  , depthBiasSlopeFactor :: Float
  , lineWidth :: Float
  }

instance
  (AllExtends PipelineRasterizationStateCreateInfo es, PokeChain es)
  => CStruct (PipelineRasterizationStateCreateInfo es)
  where
  cSize = 64
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (23 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 (if x.depthClampEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 24 (if x.rasterizerDiscardEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 28 (toWire x.polygonMode))
    liftIO (pokeByteOff p 32 x.cullMode)
    liftIO (pokeByteOff p 36 (toWire x.frontFace))
    liftIO (pokeByteOff p 40 (if x.depthBiasEnable then TRUE else FALSE))
    liftIO (pokeByteOff p 44 x.depthBiasConstantFactor)
    liftIO (pokeByteOff p 48 x.depthBiasClamp)
    liftIO (pokeByteOff p 52 x.depthBiasSlopeFactor)
    liftIO (pokeByteOff p 56 x.lineWidth)
    pure ()

instance
  (AllExtends PipelineRasterizationStateCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (PipelineRasterizationStateCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_depthClampEnable <- (toBool <$> peekByteOff p 20)
    v_rasterizerDiscardEnable <- (toBool <$> peekByteOff p 24)
    v_polygonMode <- (unsafeFromWire <$> peekByteOff p 28)
    v_cullMode <- (peekByteOff p 32)
    v_frontFace <- (unsafeFromWire <$> peekByteOff p 36)
    v_depthBiasEnable <- (toBool <$> peekByteOff p 40)
    v_depthBiasConstantFactor <- (peekByteOff p 44)
    v_depthBiasClamp <- (peekByteOff p 48)
    v_depthBiasSlopeFactor <- (peekByteOff p 52)
    v_lineWidth <- (peekByteOff p 56)
    pure
      PipelineRasterizationStateCreateInfo
        { next = v_next
        , flags = v_flags
        , depthClampEnable = v_depthClampEnable
        , rasterizerDiscardEnable = v_rasterizerDiscardEnable
        , polygonMode = v_polygonMode
        , cullMode = v_cullMode
        , frontFace = v_frontFace
        , depthBiasEnable = v_depthBiasEnable
        , depthBiasConstantFactor = v_depthBiasConstantFactor
        , depthBiasClamp = v_depthBiasClamp
        , depthBiasSlopeFactor = v_depthBiasSlopeFactor
        , lineWidth = v_lineWidth
        }

instance (NilChain es) => Nil (PipelineRasterizationStateCreateInfo es) where
  nil =
    PipelineRasterizationStateCreateInfo
      { next = nilChain
      , flags = mempty
      , depthClampEnable = False
      , rasterizerDiscardEnable = False
      , polygonMode = PolygonModeFill
      , cullMode = mempty
      , frontFace = FrontFaceCounterClockwise
      , depthBiasEnable = False
      , depthBiasConstantFactor = 0
      , depthBiasClamp = 0
      , depthBiasSlopeFactor = 0
      , lineWidth = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineTessellationStateCreateInfo.html VkPipelineTessellationStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data PipelineTessellationStateCreateInfo (es :: [Type]) = PipelineTessellationStateCreateInfo
  { next :: Chain es
  , flags :: PipelineTessellationStateCreateFlags
  , patchControlPoints :: Word32
  }

instance
  (AllExtends PipelineTessellationStateCreateInfo es, PokeChain es)
  => CStruct (PipelineTessellationStateCreateInfo es)
  where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (21 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 x.patchControlPoints)
    pure ()

instance
  (AllExtends PipelineTessellationStateCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (PipelineTessellationStateCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_patchControlPoints <- (peekByteOff p 20)
    pure
      PipelineTessellationStateCreateInfo
        { next = v_next
        , flags = v_flags
        , patchControlPoints = v_patchControlPoints
        }

instance (NilChain es) => Nil (PipelineTessellationStateCreateInfo es) where
  nil =
    PipelineTessellationStateCreateInfo
      { next = nilChain
      , flags = mempty
      , patchControlPoints = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineVertexInputStateCreateInfo.html VkPipelineVertexInputStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @vertexBindingDescriptionCount@ is derived from @vertexBindingDescriptions@'s length.
--   * @vertexAttributeDescriptionCount@ is derived from @vertexAttributeDescriptions@'s length.
data PipelineVertexInputStateCreateInfo (es :: [Type]) = PipelineVertexInputStateCreateInfo
  { next :: Chain es
  , flags :: PipelineVertexInputStateCreateFlags
  , vertexBindingDescriptions :: V.Vector VertexInputBindingDescription
  , vertexAttributeDescriptions :: V.Vector VertexInputAttributeDescription
  }

instance
  (AllExtends PipelineVertexInputStateCreateInfo es, PokeChain es)
  => CStruct (PipelineVertexInputStateCreateInfo es)
  where
  cSize = 48
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (19 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    p_vertexBindingDescriptions <-
      if V.null x.vertexBindingDescriptions then pure nullPtr else newVector x.vertexBindingDescriptions
    liftIO (pokeByteOff p 24 p_vertexBindingDescriptions)
    liftIO (pokeByteOff p 20 (fromIntegral (V.length x.vertexBindingDescriptions) :: Word32))
    p_vertexAttributeDescriptions <-
      if V.null x.vertexAttributeDescriptions then
        pure nullPtr
      else
        newVector x.vertexAttributeDescriptions
    liftIO (pokeByteOff p 40 p_vertexAttributeDescriptions)
    liftIO (pokeByteOff p 32 (fromIntegral (V.length x.vertexAttributeDescriptions) :: Word32))
    pure ()

instance
  (AllExtends PipelineVertexInputStateCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (PipelineVertexInputStateCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_vertexBindingDescriptions <- do
      n <- (peekByteOff p 20 :: IO Word32)
      q <- peekByteOff p 24
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    v_vertexAttributeDescriptions <- do
      n <- (peekByteOff p 32 :: IO Word32)
      q <- peekByteOff p 40
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    pure
      PipelineVertexInputStateCreateInfo
        { next = v_next
        , flags = v_flags
        , vertexBindingDescriptions = v_vertexBindingDescriptions
        , vertexAttributeDescriptions = v_vertexAttributeDescriptions
        }

instance (NilChain es) => Nil (PipelineVertexInputStateCreateInfo es) where
  nil =
    PipelineVertexInputStateCreateInfo
      { next = nilChain
      , flags = mempty
      , vertexBindingDescriptions = V.empty
      , vertexAttributeDescriptions = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineViewportStateCreateInfo.html VkPipelineViewportStateCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @viewportCount@ is derived from @viewports@'s length.
--   * @scissorCount@ is derived from @scissors@'s length.
data PipelineViewportStateCreateInfo = PipelineViewportStateCreateInfo
  { flags :: PipelineViewportStateCreateFlags
  , viewports :: V.Vector Viewport
  , scissors :: V.Vector Rect2D
  }

instance CStruct PipelineViewportStateCreateInfo where
  cSize = 48
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (22 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    p_viewports <- if V.null x.viewports then pure nullPtr else newVector x.viewports
    liftIO (pokeByteOff p 24 p_viewports)
    liftIO (pokeByteOff p 20 (fromIntegral (V.length x.viewports) :: Word32))
    p_scissors <- if V.null x.scissors then pure nullPtr else newVector x.scissors
    liftIO (pokeByteOff p 40 p_scissors)
    liftIO (pokeByteOff p 32 (fromIntegral (V.length x.scissors) :: Word32))
    pure ()

instance FromCStruct PipelineViewportStateCreateInfo where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_viewports <- do
      n <- (peekByteOff p 20 :: IO Word32)
      q <- peekByteOff p 24
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    v_scissors <- do
      n <- (peekByteOff p 32 :: IO Word32)
      q <- peekByteOff p 40
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    pure
      PipelineViewportStateCreateInfo{flags = v_flags, viewports = v_viewports, scissors = v_scissors}

instance Nil PipelineViewportStateCreateInfo where
  nil =
    PipelineViewportStateCreateInfo
      { flags = mempty
      , viewports = V.empty
      , scissors = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateGraphicsPipelines.html vkCreateGraphicsPipelines>
-- Available: VK_VERSION_1_0
createGraphicsPipelines
  :: forall m
   . (MonadIO m)
  => Device
  -> PipelineCache
  -> V.Vector (SomeStruct GraphicsPipelineCreateInfo)
  -> Maybe AllocationCallbacks
  -> m (Outcome (V.Vector Pipeline))
createGraphicsPipelines device pipelineCache createInfos allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    let n_createInfoCount = fromIntegral (V.length createInfos) :: Word32
        n_createInfoCount' = n_createInfoCount
    p_createInfos <- do
      pv_ <- arenaBytes (144 * max 1 (V.length createInfos)) 8
      V.imapM_ (\i e_ -> withSomeStruct e_ (pokeCStruct (castPtr (pv_ `plusPtr` (i * 144))))) createInfos
      pure (castPtr pv_ :: Ptr ())
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_pipelines <- arenaBytes (8 * max 1 (fromIntegral n_createInfoCount)) 8
    r_ <-
      liftIO
        ( mkCreateGraphicsPipelines
            (checkCommandPtr "vkCreateGraphicsPipelines" device.cmds.pCreateGraphicsPipelines)
            (castPtr device.handle)
            (case pipelineCache of PipelineCache w_ -> w_)
            n_createInfoCount
            p_createInfos
            p_allocator
            (castPtr p_o_pipelines)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      o_pipelines <-
        liftIO
          ( V.generateM
              (fromIntegral n_createInfoCount')
              (\i -> Pipeline <$> peekElemOff (castPtr p_o_pipelines :: Ptr Word64) i)
          )
      pure (Ok (openFromWire r_) o_pipelines)

withGraphicsPipelines
  :: forall m r
   . (MonadUnliftIO m)
  => Device
  -> PipelineCache
  -> V.Vector (SomeStruct GraphicsPipelineCreateInfo)
  -> Maybe AllocationCallbacks
  -> (Outcome (V.Vector Pipeline) -> m r)
  -> m r
withGraphicsPipelines device pipelineCache createInfos allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createGraphicsPipelines device pipelineCache createInfos allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (V.mapM_ (\h1_ -> destroyPipeline device h1_ allocator) h_)
          Err _ -> pure ()
      )
      (run_ . cont_)
