-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.ImageViewCommands (
  ComponentMapping (..),
  ImageSubresourceRange (..),
  ImageViewCreateInfo (..),
  createImageView,
  withImageView,
  destroyImageView,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.ComponentSwizzle
import Lithon.Vk.Core10.Enums.Format
import Lithon.Vk.Core10.Enums.ImageAspectFlagBits
import Lithon.Vk.Core10.Enums.ImageViewCreateFlagBits
import Lithon.Vk.Core10.Enums.ImageViewType
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkComponentMapping.html VkComponentMapping>
-- Available: VK_VERSION_1_0
data ComponentMapping = ComponentMapping
  { r :: !(Open ComponentSwizzle)
  , g :: !(Open ComponentSwizzle)
  , b :: !(Open ComponentSwizzle)
  , a :: !(Open ComponentSwizzle)
  }
  deriving stock (Eq, Show)

instance Storable ComponentMapping where
  sizeOf _ = 16
  alignment _ = 4
  peek p =
    ComponentMapping
      <$> (openFromWire <$> peekByteOff p 0)
      <*> (openFromWire <$> peekByteOff p 4)
      <*> (openFromWire <$> peekByteOff p 8)
      <*> (openFromWire <$> peekByteOff p 12)
  poke p x = do
    pokeByteOff p 0 (openToWire x.r)
    pokeByteOff p 4 (openToWire x.g)
    pokeByteOff p 8 (openToWire x.b)
    pokeByteOff p 12 (openToWire x.a)

instance CStruct ComponentMapping where
  cSize = 16
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ComponentMapping where
  peekCStruct = peek

instance Nil ComponentMapping where
  nil =
    ComponentMapping
      { r = Known ComponentSwizzleIdentity
      , g = Known ComponentSwizzleIdentity
      , b = Known ComponentSwizzleIdentity
      , a = Known ComponentSwizzleIdentity
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageSubresourceRange.html VkImageSubresourceRange>
-- Available: VK_VERSION_1_0
data ImageSubresourceRange = ImageSubresourceRange
  { aspectMask :: !ImageAspectFlags
  , baseMipLevel :: !Word32
  , levelCount :: !Word32
  , baseArrayLayer :: !Word32
  , layerCount :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable ImageSubresourceRange where
  sizeOf _ = 20
  alignment _ = 4
  peek p =
    ImageSubresourceRange
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
      <*> (peekByteOff p 16)
  poke p x = do
    pokeByteOff p 0 x.aspectMask
    pokeByteOff p 4 x.baseMipLevel
    pokeByteOff p 8 x.levelCount
    pokeByteOff p 12 x.baseArrayLayer
    pokeByteOff p 16 x.layerCount

instance CStruct ImageSubresourceRange where
  cSize = 20
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct ImageSubresourceRange where
  peekCStruct = peek

instance Nil ImageSubresourceRange where
  nil =
    ImageSubresourceRange
      { aspectMask = mempty
      , baseMipLevel = 0
      , levelCount = 0
      , baseArrayLayer = 0
      , layerCount = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageViewCreateInfo.html VkImageViewCreateInfo>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data ImageViewCreateInfo (es :: [Type]) = ImageViewCreateInfo
  { next :: Chain es
  , flags :: ImageViewCreateFlags
  , image :: Image
  , viewType :: ImageViewType
  , format :: Open Format
  , components :: ComponentMapping
  , subresourceRange :: ImageSubresourceRange
  }

instance (AllExtends ImageViewCreateInfo es, PokeChain es) => CStruct (ImageViewCreateInfo es) where
  cSize = 80
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (15 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 24 x.image)
    liftIO (pokeByteOff p 32 (toWire x.viewType))
    liftIO (pokeByteOff p 36 (openToWire x.format))
    liftIO (pokeByteOff p 40 x.components)
    liftIO (pokeByteOff p 56 x.subresourceRange)
    pure ()

instance
  (AllExtends ImageViewCreateInfo es, PokeChain es, PeekChain es)
  => FromCStruct (ImageViewCreateInfo es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_image <- (peekByteOff p 24)
    v_viewType <- (unsafeFromWire <$> peekByteOff p 32)
    v_format <- (openFromWire <$> peekByteOff p 36)
    v_components <- (peekByteOff p 40)
    v_subresourceRange <- (peekByteOff p 56)
    pure
      ImageViewCreateInfo
        { next = v_next
        , flags = v_flags
        , image = v_image
        , viewType = v_viewType
        , format = v_format
        , components = v_components
        , subresourceRange = v_subresourceRange
        }

instance (NilChain es) => Nil (ImageViewCreateInfo es) where
  nil =
    ImageViewCreateInfo
      { next = nilChain
      , flags = mempty
      , image = nil
      , viewType = ImageViewType1D
      , format = Known FormatUndefined
      , components = nil
      , subresourceRange = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateImageView.html vkCreateImageView>
-- Available: VK_VERSION_1_0
createImageView
  :: forall m es1
   . (MonadIO m, AllExtends ImageViewCreateInfo es1, PokeChain es1)
  => Device
  -> ImageViewCreateInfo es1
  -> Maybe AllocationCallbacks
  -> m (Outcome ImageView)
createImageView device createInfo allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_createInfo :: Ptr () <- castPtr <$> new createInfo
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_view <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateImageView
            (checkCommandPtr "vkCreateImageView" device.cmds.pCreateImageView)
            (castPtr device.handle)
            p_createInfo
            p_allocator
            (castPtr p_o_view)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_view <- liftIO (peekByteOff p_o_view 0 :: IO Word64)
      let o_view = ImageView w_o_view
      pure (Ok (openFromWire r_) o_view)

withImageView
  :: forall m r es1
   . (MonadUnliftIO m, AllExtends ImageViewCreateInfo es1, PokeChain es1)
  => Device
  -> ImageViewCreateInfo es1
  -> Maybe AllocationCallbacks
  -> (Outcome ImageView -> m r)
  -> m r
withImageView device createInfo allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createImageView device createInfo allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroyImageView device h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroyImageView.html vkDestroyImageView>
-- Available: VK_VERSION_1_0
destroyImageView
  :: forall m
   . (MonadIO m)
  => Device
  -> ImageView
  -> Maybe AllocationCallbacks
  -> m ()
destroyImageView device imageView allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroyImageView
          (checkCommandPtr "vkDestroyImageView" device.cmds.pDestroyImageView)
          (castPtr device.handle)
          (case imageView of ImageView w_ -> w_)
          p_allocator
      )
    pure ()
