-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.MemoryManagementAPICommands (
  MemoryRequirements (..),
  bindBufferMemory,
  bindImageMemory,
  getBufferMemoryRequirements,
  getImageMemoryRequirements,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), DeviceAddress (..), DeviceSize (..), SampleMask (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkMemoryRequirements.html VkMemoryRequirements>
-- Available: VK_VERSION_1_0
data MemoryRequirements = MemoryRequirements
  { size :: !Word64
  , alignment :: !Word64
  , memoryTypeBits :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable MemoryRequirements where
  sizeOf _ = 24
  alignment _ = 8
  peek p =
    MemoryRequirements
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 16)
  poke p x = do
    pokeByteOff p 0 x.size
    pokeByteOff p 8 x.alignment
    pokeByteOff p 16 x.memoryTypeBits

instance CStruct MemoryRequirements where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct MemoryRequirements where
  peekCStruct = peek

instance Nil MemoryRequirements where
  nil =
    MemoryRequirements
      { size = 0
      , alignment = 0
      , memoryTypeBits = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkBindBufferMemory.html vkBindBufferMemory>
-- Available: VK_VERSION_1_0
bindBufferMemory
  :: forall m
   . (MonadIO m)
  => Device
  -> Buffer
  -> DeviceMemory
  -> DeviceSize
  -> m (Outcome ())
bindBufferMemory device buffer memory memoryOffset =
  liftIO do
    r_ <-
      liftIO
        ( mkBindBufferMemory
            (checkCommandPtr "vkBindBufferMemory" device.cmds.pBindBufferMemory)
            (castPtr device.handle)
            (case buffer of Buffer w_ -> w_)
            (case memory of DeviceMemory w_ -> w_)
            (fromIntegral memoryOffset :: Word64)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkBindImageMemory.html vkBindImageMemory>
-- Available: VK_VERSION_1_0
bindImageMemory
  :: forall m
   . (MonadIO m)
  => Device
  -> Image
  -> DeviceMemory
  -> DeviceSize
  -> m (Outcome ())
bindImageMemory device image memory memoryOffset =
  liftIO do
    r_ <-
      liftIO
        ( mkBindImageMemory
            (checkCommandPtr "vkBindImageMemory" device.cmds.pBindImageMemory)
            (castPtr device.handle)
            (case image of Image w_ -> w_)
            (case memory of DeviceMemory w_ -> w_)
            (fromIntegral memoryOffset :: Word64)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetBufferMemoryRequirements.html vkGetBufferMemoryRequirements>
-- Available: VK_VERSION_1_0
getBufferMemoryRequirements
  :: forall m
   . (MonadIO m)
  => Device
  -> Buffer
  -> m MemoryRequirements
getBufferMemoryRequirements device buffer =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_o_memoryRequirements :: Ptr () <- castPtr <$> new (nil :: MemoryRequirements)
    liftIO
      ( mkGetBufferMemoryRequirements
          (checkCommandPtr "vkGetBufferMemoryRequirements" device.cmds.pGetBufferMemoryRequirements)
          (castPtr device.handle)
          (case buffer of Buffer w_ -> w_)
          p_o_memoryRequirements
      )
    o_memoryRequirements <- liftIO (peekCStruct (castPtr p_o_memoryRequirements))
    pure o_memoryRequirements

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetImageMemoryRequirements.html vkGetImageMemoryRequirements>
-- Available: VK_VERSION_1_0
getImageMemoryRequirements
  :: forall m
   . (MonadIO m)
  => Device
  -> Image
  -> m MemoryRequirements
getImageMemoryRequirements device image =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_o_memoryRequirements :: Ptr () <- castPtr <$> new (nil :: MemoryRequirements)
    liftIO
      ( mkGetImageMemoryRequirements
          (checkCommandPtr "vkGetImageMemoryRequirements" device.cmds.pGetImageMemoryRequirements)
          (castPtr device.handle)
          (case image of Image w_ -> w_)
          p_o_memoryRequirements
      )
    o_memoryRequirements <- liftIO (peekCStruct (castPtr p_o_memoryRequirements))
    pure o_memoryRequirements
