-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.TheseTypesArePartOfTheAPIThoughNotDirectlyUsedInAPICommandsOrDataStructures (
  DispatchIndirectCommand (..),
  DrawIndexedIndirectCommand (..),
  DrawIndirectCommand (..),
  PipelineCacheHeaderVersionOne (..),
  BaseInStructure (..),
  BaseOutStructure (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems, peekFixedBytes, pokeFixedBytes)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Enums.PipelineCacheHeaderVersion
import Lithon.Vk.Core10.Enums.StructureType

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDispatchIndirectCommand.html VkDispatchIndirectCommand>
-- Available: VK_VERSION_1_0
data DispatchIndirectCommand = DispatchIndirectCommand
  { x :: !Word32
  , y :: !Word32
  , z :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable DispatchIndirectCommand where
  sizeOf _ = 12
  alignment _ = 4
  peek p =
    DispatchIndirectCommand
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
  poke p x = do
    pokeByteOff p 0 x.x
    pokeByteOff p 4 x.y
    pokeByteOff p 8 x.z

instance CStruct DispatchIndirectCommand where
  cSize = 12
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct DispatchIndirectCommand where
  peekCStruct = peek

instance Nil DispatchIndirectCommand where
  nil =
    DispatchIndirectCommand
      { x = 0
      , y = 0
      , z = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDrawIndexedIndirectCommand.html VkDrawIndexedIndirectCommand>
-- Available: VK_VERSION_1_0
data DrawIndexedIndirectCommand = DrawIndexedIndirectCommand
  { indexCount :: !Word32
  , instanceCount :: !Word32
  , firstIndex :: !Word32
  , vertexOffset :: !Int32
  , firstInstance :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable DrawIndexedIndirectCommand where
  sizeOf _ = 20
  alignment _ = 4
  peek p =
    DrawIndexedIndirectCommand
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
      <*> (peekByteOff p 16)
  poke p x = do
    pokeByteOff p 0 x.indexCount
    pokeByteOff p 4 x.instanceCount
    pokeByteOff p 8 x.firstIndex
    pokeByteOff p 12 x.vertexOffset
    pokeByteOff p 16 x.firstInstance

instance CStruct DrawIndexedIndirectCommand where
  cSize = 20
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct DrawIndexedIndirectCommand where
  peekCStruct = peek

instance Nil DrawIndexedIndirectCommand where
  nil =
    DrawIndexedIndirectCommand
      { indexCount = 0
      , instanceCount = 0
      , firstIndex = 0
      , vertexOffset = 0
      , firstInstance = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDrawIndirectCommand.html VkDrawIndirectCommand>
-- Available: VK_VERSION_1_0
data DrawIndirectCommand = DrawIndirectCommand
  { vertexCount :: !Word32
  , instanceCount :: !Word32
  , firstVertex :: !Word32
  , firstInstance :: !Word32
  }
  deriving stock (Eq, Show)

instance Storable DrawIndirectCommand where
  sizeOf _ = 16
  alignment _ = 4
  peek p =
    DrawIndirectCommand
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
  poke p x = do
    pokeByteOff p 0 x.vertexCount
    pokeByteOff p 4 x.instanceCount
    pokeByteOff p 8 x.firstVertex
    pokeByteOff p 12 x.firstInstance

instance CStruct DrawIndirectCommand where
  cSize = 16
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct DrawIndirectCommand where
  peekCStruct = peek

instance Nil DrawIndirectCommand where
  nil =
    DrawIndirectCommand
      { vertexCount = 0
      , instanceCount = 0
      , firstVertex = 0
      , firstInstance = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineCacheHeaderVersionOne.html VkPipelineCacheHeaderVersionOne>
-- Available: VK_VERSION_1_0
data PipelineCacheHeaderVersionOne = MkPipelineCacheHeaderVersionOne
  { headerSize :: !Word32
  , headerVersion :: !PipelineCacheHeaderVersion
  , vendorID :: !Word32
  , deviceID :: !Word32
  , pipelineCacheUUID :: !ByteString
  }
  deriving stock (Eq, Show)

instance Storable PipelineCacheHeaderVersionOne where
  sizeOf _ = 32
  alignment _ = 4
  peek p =
    MkPipelineCacheHeaderVersionOne
      <$> (peekByteOff p 0)
      <*> (unsafeFromWire <$> peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 12)
      <*> (peekFixedBytes 16 p 16)
  poke p x = do
    pokeByteOff p 0 x.headerSize
    pokeByteOff p 4 (toWire x.headerVersion)
    pokeByteOff p 8 x.vendorID
    pokeByteOff p 12 x.deviceID
    pokeFixedBytes 16 p 16 x.pipelineCacheUUID

instance CStruct PipelineCacheHeaderVersionOne where
  cSize = 32
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct PipelineCacheHeaderVersionOne where
  peekCStruct = peek

instance Nil PipelineCacheHeaderVersionOne where
  nil =
    MkPipelineCacheHeaderVersionOne
      { headerSize = 0
      , headerVersion = PipelineCacheHeaderVersionOne
      , vendorID = 0
      , deviceID = 0
      , pipelineCacheUUID = ""
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkBaseInStructure.html VkBaseInStructure>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @pNext@ is reserved and written as null.
data BaseInStructure = BaseInStructure
  { sType :: Open StructureType
  }

instance CStruct BaseInStructure where
  cSize = 16
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (openToWire x.sType))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    pure ()

instance FromCStruct BaseInStructure where
  peekCStruct p = do
    v_sType <- (openFromWire <$> peekByteOff p 0)
    pure BaseInStructure{sType = v_sType}

instance Nil BaseInStructure where
  nil =
    BaseInStructure
      { sType = Known StructureTypeApplicationInfo
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkBaseOutStructure.html VkBaseOutStructure>
-- Available: VK_VERSION_1_0
--
-- Marshalling:
--   * @pNext@ is reserved and written as null.
data BaseOutStructure = BaseOutStructure
  { sType :: Open StructureType
  }

instance CStruct BaseOutStructure where
  cSize = 16
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (openToWire x.sType))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    pure ()

instance FromCStruct BaseOutStructure where
  peekCStruct p = do
    v_sType <- (openFromWire <$> peekByteOff p 0)
    pure BaseOutStructure{sType = v_sType}

instance Nil BaseOutStructure where
  nil =
    BaseOutStructure
      { sType = Known StructureTypeApplicationInfo
      }
