-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core12.Enums.DescriptorBindingFlagBits (
  DescriptorBindingFlagBits (..),
  DescriptorBindingFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorBindingFlagBits.html VkDescriptorBindingFlagBits>
-- Available: VK_VERSION_1_2
data DescriptorBindingFlagBits
  = DescriptorBindingUpdateAfterBindBit
  | DescriptorBindingUpdateUnusedWhilePendingBit
  | DescriptorBindingPartiallyBoundBit
  | DescriptorBindingVariableDescriptorCountBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire DescriptorBindingFlagBits = Word32

instance BitPos DescriptorBindingFlagBits where
  bitOf = \case
    DescriptorBindingUpdateAfterBindBit -> Flags 0x1
    DescriptorBindingUpdateUnusedWhilePendingBit -> Flags 0x2
    DescriptorBindingPartiallyBoundBit -> Flags 0x4
    DescriptorBindingVariableDescriptorCountBit -> Flags 0x8
  allBits =
    [ DescriptorBindingUpdateAfterBindBit
    , DescriptorBindingUpdateUnusedWhilePendingBit
    , DescriptorBindingPartiallyBoundBit
    , DescriptorBindingVariableDescriptorCountBit
    ]

type DescriptorBindingFlags = Flags DescriptorBindingFlagBits
