-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core12.Enums.ResolveModeFlagBits (
  ResolveModeFlagBits (..),
  pattern ResolveModeNone,
  ResolveModeFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkResolveModeFlagBits.html VkResolveModeFlagBits>
-- Available: VK_VERSION_1_2
data ResolveModeFlagBits
  = ResolveModeSampleZeroBit
  | ResolveModeAverageBit
  | ResolveModeMinBit
  | ResolveModeMaxBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire ResolveModeFlagBits = Word32

instance BitPos ResolveModeFlagBits where
  bitOf = \case
    ResolveModeSampleZeroBit -> Flags 0x1
    ResolveModeAverageBit -> Flags 0x2
    ResolveModeMinBit -> Flags 0x4
    ResolveModeMaxBit -> Flags 0x8
  allBits =
    [ ResolveModeSampleZeroBit
    , ResolveModeAverageBit
    , ResolveModeMinBit
    , ResolveModeMaxBit
    ]

pattern ResolveModeNone :: Flags ResolveModeFlagBits
pattern ResolveModeNone = Flags 0x0

type ResolveModeFlags = Flags ResolveModeFlagBits
