-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core13.Enums.ToolPurposeFlagBits (
  ToolPurposeFlagBits (..),
  ToolPurposeFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkToolPurposeFlagBits.html VkToolPurposeFlagBits>
-- Available: VK_VERSION_1_3
data ToolPurposeFlagBits
  = ToolPurposeValidationBit
  | ToolPurposeProfilingBit
  | ToolPurposeTracingBit
  | ToolPurposeAdditionalFeaturesBit
  | ToolPurposeModifyingFeaturesBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire ToolPurposeFlagBits = Word32

instance BitPos ToolPurposeFlagBits where
  bitOf = \case
    ToolPurposeValidationBit -> Flags 0x1
    ToolPurposeProfilingBit -> Flags 0x2
    ToolPurposeTracingBit -> Flags 0x4
    ToolPurposeAdditionalFeaturesBit -> Flags 0x8
    ToolPurposeModifyingFeaturesBit -> Flags 0x10
  allBits =
    [ ToolPurposeValidationBit
    , ToolPurposeProfilingBit
    , ToolPurposeTracingBit
    , ToolPurposeAdditionalFeaturesBit
    , ToolPurposeModifyingFeaturesBit
    ]

type ToolPurposeFlags = Flags ToolPurposeFlagBits
