-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core11.Enums.ChromaLocation (
  ChromaLocation (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkChromaLocation.html VkChromaLocation>
-- Available: VK_VERSION_1_1
data ChromaLocation
  = ChromaLocationCositedEven
  | ChromaLocationMidpoint
  deriving stock (Eq, Ord, Show)

instance HasWire ChromaLocation where
  toWire = \case
    ChromaLocationCositedEven -> 0
    ChromaLocationMidpoint -> 1
  fromWire = \case
    0 -> Just ChromaLocationCositedEven
    1 -> Just ChromaLocationMidpoint
    _ -> Nothing
