-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core11.Enums.DescriptorUpdateTemplateType (
  DescriptorUpdateTemplateType (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDescriptorUpdateTemplateType.html VkDescriptorUpdateTemplateType>
-- Available: VK_VERSION_1_1
data DescriptorUpdateTemplateType
  = DescriptorUpdateTemplateTypeDescriptorSet
  | DescriptorUpdateTemplateTypePushDescriptors
  deriving stock (Eq, Ord, Show)

instance HasWire DescriptorUpdateTemplateType where
  toWire = \case
    DescriptorUpdateTemplateTypeDescriptorSet -> 0
    DescriptorUpdateTemplateTypePushDescriptors -> 1
  fromWire = \case
    0 -> Just DescriptorUpdateTemplateTypeDescriptorSet
    1 -> Just DescriptorUpdateTemplateTypePushDescriptors
    _ -> Nothing
