-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core11.Enums.ExternalFenceFeatureFlagBits (
  ExternalFenceFeatureFlagBits (..),
  ExternalFenceFeatureFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkExternalFenceFeatureFlagBits.html VkExternalFenceFeatureFlagBits>
-- Available: VK_VERSION_1_1
-- Alias spellings: VkExternalFenceFeatureFlagBitsKHR
data ExternalFenceFeatureFlagBits
  = ExternalFenceFeatureExportableBit
  | ExternalFenceFeatureImportableBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire ExternalFenceFeatureFlagBits = Word32

instance BitPos ExternalFenceFeatureFlagBits where
  bitOf = \case
    ExternalFenceFeatureExportableBit -> Flags 0x1
    ExternalFenceFeatureImportableBit -> Flags 0x2
  allBits =
    [ ExternalFenceFeatureExportableBit
    , ExternalFenceFeatureImportableBit
    ]

type ExternalFenceFeatureFlags = Flags ExternalFenceFeatureFlagBits
