-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core11.Enums.PointClippingBehavior (
  PointClippingBehavior (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPointClippingBehavior.html VkPointClippingBehavior>
-- Available: VK_VERSION_1_1
data PointClippingBehavior
  = PointClippingBehaviorAllClipPlanes
  | PointClippingBehaviorUserClipPlanesOnly
  deriving stock (Eq, Ord, Show)

instance HasWire PointClippingBehavior where
  toWire = \case
    PointClippingBehaviorAllClipPlanes -> 0
    PointClippingBehaviorUserClipPlanesOnly -> 1
  fromWire = \case
    0 -> Just PointClippingBehaviorAllClipPlanes
    1 -> Just PointClippingBehaviorUserClipPlanesOnly
    _ -> Nothing
