-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core11.Enums.SamplerYcbcrModelConversion (
  SamplerYcbcrModelConversion (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSamplerYcbcrModelConversion.html VkSamplerYcbcrModelConversion>
-- Available: VK_VERSION_1_1
data SamplerYcbcrModelConversion
  = SamplerYcbcrModelConversionRgbIdentity
  | SamplerYcbcrModelConversionYcbcrIdentity
  | SamplerYcbcrModelConversionYcbcr709
  | SamplerYcbcrModelConversionYcbcr601
  | SamplerYcbcrModelConversionYcbcr2020
  deriving stock (Eq, Ord, Show)

instance HasWire SamplerYcbcrModelConversion where
  toWire = \case
    SamplerYcbcrModelConversionRgbIdentity -> 0
    SamplerYcbcrModelConversionYcbcrIdentity -> 1
    SamplerYcbcrModelConversionYcbcr709 -> 2
    SamplerYcbcrModelConversionYcbcr601 -> 3
    SamplerYcbcrModelConversionYcbcr2020 -> 4
  fromWire = \case
    0 -> Just SamplerYcbcrModelConversionRgbIdentity
    1 -> Just SamplerYcbcrModelConversionYcbcrIdentity
    2 -> Just SamplerYcbcrModelConversionYcbcr709
    3 -> Just SamplerYcbcrModelConversionYcbcr601
    4 -> Just SamplerYcbcrModelConversionYcbcr2020
    _ -> Nothing
