-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core11.Enums.SemaphoreImportFlagBits (
  SemaphoreImportFlagBits (..),
  SemaphoreImportFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSemaphoreImportFlagBits.html VkSemaphoreImportFlagBits>
-- Available: VK_VERSION_1_1
-- Alias spellings: VkSemaphoreImportFlagBitsKHR
data SemaphoreImportFlagBits
  = SemaphoreImportTemporaryBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire SemaphoreImportFlagBits = Word32

instance BitPos SemaphoreImportFlagBits where
  bitOf = \case
    SemaphoreImportTemporaryBit -> Flags 0x1
  allBits =
    [ SemaphoreImportTemporaryBit
    ]

type SemaphoreImportFlags = Flags SemaphoreImportFlagBits
