-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.CommandPoolCreateFlagBits (
  CommandPoolCreateFlagBits (..),
  CommandPoolCreateFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkCommandPoolCreateFlagBits.html VkCommandPoolCreateFlagBits>
-- Available: VK_VERSION_1_0
data CommandPoolCreateFlagBits
  = CommandPoolCreateTransientBit
  | CommandPoolCreateResetCommandBufferBit
  | CommandPoolCreateProtectedBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire CommandPoolCreateFlagBits = Word32

instance BitPos CommandPoolCreateFlagBits where
  bitOf = \case
    CommandPoolCreateTransientBit -> Flags 0x1
    CommandPoolCreateResetCommandBufferBit -> Flags 0x2
    CommandPoolCreateProtectedBit -> Flags 0x4
  allBits =
    [ CommandPoolCreateTransientBit
    , CommandPoolCreateResetCommandBufferBit
    , CommandPoolCreateProtectedBit
    ]

type CommandPoolCreateFlags = Flags CommandPoolCreateFlagBits
