-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.CommandPoolResetFlagBits (
  CommandPoolResetFlagBits (..),
  CommandPoolResetFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkCommandPoolResetFlagBits.html VkCommandPoolResetFlagBits>
-- Available: VK_VERSION_1_0
data CommandPoolResetFlagBits
  = CommandPoolResetReleaseResourcesBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire CommandPoolResetFlagBits = Word32

instance BitPos CommandPoolResetFlagBits where
  bitOf = \case
    CommandPoolResetReleaseResourcesBit -> Flags 0x1
  allBits =
    [ CommandPoolResetReleaseResourcesBit
    ]

type CommandPoolResetFlags = Flags CommandPoolResetFlagBits
