-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.ComponentSwizzle (
  ComponentSwizzle (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkComponentSwizzle.html VkComponentSwizzle>
-- Available: VK_VERSION_1_0
data ComponentSwizzle
  = ComponentSwizzleIdentity
  | ComponentSwizzleZero
  | ComponentSwizzleOne
  | ComponentSwizzleR
  | ComponentSwizzleG
  | ComponentSwizzleB
  | ComponentSwizzleA
  deriving stock (Eq, Ord, Show)

instance HasWire ComponentSwizzle where
  toWire = \case
    ComponentSwizzleIdentity -> 0
    ComponentSwizzleZero -> 1
    ComponentSwizzleOne -> 2
    ComponentSwizzleR -> 3
    ComponentSwizzleG -> 4
    ComponentSwizzleB -> 5
    ComponentSwizzleA -> 6
  fromWire = \case
    0 -> Just ComponentSwizzleIdentity
    1 -> Just ComponentSwizzleZero
    2 -> Just ComponentSwizzleOne
    3 -> Just ComponentSwizzleR
    4 -> Just ComponentSwizzleG
    5 -> Just ComponentSwizzleB
    6 -> Just ComponentSwizzleA
    _ -> Nothing
