-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.DependencyFlagBits (
  DependencyFlagBits (..),
  DependencyFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDependencyFlagBits.html VkDependencyFlagBits>
-- Available: VK_VERSION_1_0
data DependencyFlagBits
  = DependencyByRegionBit
  | DependencyViewLocalBit
  | DependencyDeviceGroupBit
  | DependencyQueueFamilyOwnershipTransferUseAllStagesBitKHR
  deriving stock (Eq, Ord, Show)

type instance FlagsWire DependencyFlagBits = Word32

instance BitPos DependencyFlagBits where
  bitOf = \case
    DependencyByRegionBit -> Flags 0x1
    DependencyViewLocalBit -> Flags 0x2
    DependencyDeviceGroupBit -> Flags 0x4
    DependencyQueueFamilyOwnershipTransferUseAllStagesBitKHR -> Flags 0x20
  allBits =
    [ DependencyByRegionBit
    , DependencyViewLocalBit
    , DependencyDeviceGroupBit
    , DependencyQueueFamilyOwnershipTransferUseAllStagesBitKHR
    ]

type DependencyFlags = Flags DependencyFlagBits
