-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.Filter (
  Filter (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkFilter.html VkFilter>
-- Available: VK_VERSION_1_0
data Filter
  = FilterNearest
  | FilterLinear
  deriving stock (Eq, Ord, Show)

instance HasWire Filter where
  toWire = \case
    FilterNearest -> 0
    FilterLinear -> 1
  fromWire = \case
    0 -> Just FilterNearest
    1 -> Just FilterLinear
    _ -> Nothing
