-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.ImageCreateFlagBits (
  ImageCreateFlagBits (..),
  ImageCreateFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageCreateFlagBits.html VkImageCreateFlagBits>
-- Available: VK_VERSION_1_0
data ImageCreateFlagBits
  = ImageCreateSparseBindingBit
  | ImageCreateSparseResidencyBit
  | ImageCreateSparseAliasedBit
  | ImageCreateMutableFormatBit
  | ImageCreateCubeCompatibleBit
  | ImageCreate2DArrayCompatibleBit
  | ImageCreateSplitInstanceBindRegionsBit
  | ImageCreateBlockTexelViewCompatibleBit
  | ImageCreateExtendedUsageBit
  | ImageCreateDisjointBit
  | ImageCreateAliasBit
  | ImageCreateProtectedBit
  | ImageCreateSampleLocationsCompatibleDepthBitEXT
  deriving stock (Eq, Ord, Show)

type instance FlagsWire ImageCreateFlagBits = Word32

instance BitPos ImageCreateFlagBits where
  bitOf = \case
    ImageCreateSparseBindingBit -> Flags 0x1
    ImageCreateSparseResidencyBit -> Flags 0x2
    ImageCreateSparseAliasedBit -> Flags 0x4
    ImageCreateMutableFormatBit -> Flags 0x8
    ImageCreateCubeCompatibleBit -> Flags 0x10
    ImageCreate2DArrayCompatibleBit -> Flags 0x20
    ImageCreateSplitInstanceBindRegionsBit -> Flags 0x40
    ImageCreateBlockTexelViewCompatibleBit -> Flags 0x80
    ImageCreateExtendedUsageBit -> Flags 0x100
    ImageCreateDisjointBit -> Flags 0x200
    ImageCreateAliasBit -> Flags 0x400
    ImageCreateProtectedBit -> Flags 0x800
    ImageCreateSampleLocationsCompatibleDepthBitEXT -> Flags 0x1000
  allBits =
    [ ImageCreateSparseBindingBit
    , ImageCreateSparseResidencyBit
    , ImageCreateSparseAliasedBit
    , ImageCreateMutableFormatBit
    , ImageCreateCubeCompatibleBit
    , ImageCreate2DArrayCompatibleBit
    , ImageCreateSplitInstanceBindRegionsBit
    , ImageCreateBlockTexelViewCompatibleBit
    , ImageCreateExtendedUsageBit
    , ImageCreateDisjointBit
    , ImageCreateAliasBit
    , ImageCreateProtectedBit
    , ImageCreateSampleLocationsCompatibleDepthBitEXT
    ]

type ImageCreateFlags = Flags ImageCreateFlagBits
