-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.ImageUsageFlagBits (
  ImageUsageFlagBits (..),
  ImageUsageFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageUsageFlagBits.html VkImageUsageFlagBits>
-- Available: VK_VERSION_1_0
data ImageUsageFlagBits
  = ImageUsageTransferSrcBit
  | ImageUsageTransferDstBit
  | ImageUsageSampledBit
  | ImageUsageStorageBit
  | ImageUsageColorAttachmentBit
  | ImageUsageDepthStencilAttachmentBit
  | ImageUsageTransientAttachmentBit
  | ImageUsageInputAttachmentBit
  | ImageUsageFragmentShadingRateAttachmentBitKHR
  | ImageUsageHostTransferBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire ImageUsageFlagBits = Word32

instance BitPos ImageUsageFlagBits where
  bitOf = \case
    ImageUsageTransferSrcBit -> Flags 0x1
    ImageUsageTransferDstBit -> Flags 0x2
    ImageUsageSampledBit -> Flags 0x4
    ImageUsageStorageBit -> Flags 0x8
    ImageUsageColorAttachmentBit -> Flags 0x10
    ImageUsageDepthStencilAttachmentBit -> Flags 0x20
    ImageUsageTransientAttachmentBit -> Flags 0x40
    ImageUsageInputAttachmentBit -> Flags 0x80
    ImageUsageFragmentShadingRateAttachmentBitKHR -> Flags 0x100
    ImageUsageHostTransferBit -> Flags 0x400000
  allBits =
    [ ImageUsageTransferSrcBit
    , ImageUsageTransferDstBit
    , ImageUsageSampledBit
    , ImageUsageStorageBit
    , ImageUsageColorAttachmentBit
    , ImageUsageDepthStencilAttachmentBit
    , ImageUsageTransientAttachmentBit
    , ImageUsageInputAttachmentBit
    , ImageUsageFragmentShadingRateAttachmentBitKHR
    , ImageUsageHostTransferBit
    ]

type ImageUsageFlags = Flags ImageUsageFlagBits
