-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.InstanceCreateFlagBits (
  InstanceCreateFlagBits (..),
  InstanceCreateFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkInstanceCreateFlagBits.html VkInstanceCreateFlagBits>
-- Available: VK_VERSION_1_0
data InstanceCreateFlagBits
  = InstanceCreateEnumeratePortabilityBitKHR
  deriving stock (Eq, Ord, Show)

type instance FlagsWire InstanceCreateFlagBits = Word32

instance BitPos InstanceCreateFlagBits where
  bitOf = \case
    InstanceCreateEnumeratePortabilityBitKHR -> Flags 0x1
  allBits =
    [ InstanceCreateEnumeratePortabilityBitKHR
    ]

type InstanceCreateFlags = Flags InstanceCreateFlagBits
