-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.MemoryPropertyFlagBits (
  MemoryPropertyFlagBits (..),
  MemoryPropertyFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkMemoryPropertyFlagBits.html VkMemoryPropertyFlagBits>
-- Available: VK_VERSION_1_0
data MemoryPropertyFlagBits
  = MemoryPropertyDeviceLocalBit
  | MemoryPropertyHostVisibleBit
  | MemoryPropertyHostCoherentBit
  | MemoryPropertyHostCachedBit
  | MemoryPropertyLazilyAllocatedBit
  | MemoryPropertyProtectedBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire MemoryPropertyFlagBits = Word32

instance BitPos MemoryPropertyFlagBits where
  bitOf = \case
    MemoryPropertyDeviceLocalBit -> Flags 0x1
    MemoryPropertyHostVisibleBit -> Flags 0x2
    MemoryPropertyHostCoherentBit -> Flags 0x4
    MemoryPropertyHostCachedBit -> Flags 0x8
    MemoryPropertyLazilyAllocatedBit -> Flags 0x10
    MemoryPropertyProtectedBit -> Flags 0x20
  allBits =
    [ MemoryPropertyDeviceLocalBit
    , MemoryPropertyHostVisibleBit
    , MemoryPropertyHostCoherentBit
    , MemoryPropertyHostCachedBit
    , MemoryPropertyLazilyAllocatedBit
    , MemoryPropertyProtectedBit
    ]

type MemoryPropertyFlags = Flags MemoryPropertyFlagBits
