-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.PhysicalDeviceType (
  PhysicalDeviceType (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceType.html VkPhysicalDeviceType>
-- Available: VK_VERSION_1_0
data PhysicalDeviceType
  = PhysicalDeviceTypeOther
  | PhysicalDeviceTypeIntegratedGpu
  | PhysicalDeviceTypeDiscreteGpu
  | PhysicalDeviceTypeVirtualGpu
  | PhysicalDeviceTypeCpu
  deriving stock (Eq, Ord, Show)

instance HasWire PhysicalDeviceType where
  toWire = \case
    PhysicalDeviceTypeOther -> 0
    PhysicalDeviceTypeIntegratedGpu -> 1
    PhysicalDeviceTypeDiscreteGpu -> 2
    PhysicalDeviceTypeVirtualGpu -> 3
    PhysicalDeviceTypeCpu -> 4
  fromWire = \case
    0 -> Just PhysicalDeviceTypeOther
    1 -> Just PhysicalDeviceTypeIntegratedGpu
    2 -> Just PhysicalDeviceTypeDiscreteGpu
    3 -> Just PhysicalDeviceTypeVirtualGpu
    4 -> Just PhysicalDeviceTypeCpu
    _ -> Nothing
