-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.SparseImageFormatFlagBits (
  SparseImageFormatFlagBits (..),
  SparseImageFormatFlags,
) where

import Data.Word (Word32)
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSparseImageFormatFlagBits.html VkSparseImageFormatFlagBits>
-- Available: VK_VERSION_1_0
data SparseImageFormatFlagBits
  = SparseImageFormatSingleMiptailBit
  | SparseImageFormatAlignedMipSizeBit
  | SparseImageFormatNonstandardBlockSizeBit
  deriving stock (Eq, Ord, Show)

type instance FlagsWire SparseImageFormatFlagBits = Word32

instance BitPos SparseImageFormatFlagBits where
  bitOf = \case
    SparseImageFormatSingleMiptailBit -> Flags 0x1
    SparseImageFormatAlignedMipSizeBit -> Flags 0x2
    SparseImageFormatNonstandardBlockSizeBit -> Flags 0x4
  allBits =
    [ SparseImageFormatSingleMiptailBit
    , SparseImageFormatAlignedMipSizeBit
    , SparseImageFormatNonstandardBlockSizeBit
    ]

type SparseImageFormatFlags = Flags SparseImageFormatFlagBits
