-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Core10.Enums.StructureType (
  StructureType (..),
) where

import Lithon.Core.Open (HasWire (..))

-- | Structure type enumerant
-- Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkStructureType.html VkStructureType>
-- Available: VK_VERSION_1_0
data StructureType
  = StructureTypeApplicationInfo
  | StructureTypeInstanceCreateInfo
  | StructureTypeDeviceQueueCreateInfo
  | StructureTypeDeviceCreateInfo
  | StructureTypeSubmitInfo
  | StructureTypeMemoryAllocateInfo
  | StructureTypeMappedMemoryRange
  | StructureTypeBindSparseInfo
  | StructureTypeFenceCreateInfo
  | StructureTypeSemaphoreCreateInfo
  | StructureTypeEventCreateInfo
  | StructureTypeQueryPoolCreateInfo
  | StructureTypeBufferCreateInfo
  | StructureTypeBufferViewCreateInfo
  | StructureTypeImageCreateInfo
  | StructureTypeImageViewCreateInfo
  | StructureTypeShaderModuleCreateInfo
  | StructureTypePipelineCacheCreateInfo
  | StructureTypePipelineShaderStageCreateInfo
  | StructureTypePipelineVertexInputStateCreateInfo
  | StructureTypePipelineInputAssemblyStateCreateInfo
  | StructureTypePipelineTessellationStateCreateInfo
  | StructureTypePipelineViewportStateCreateInfo
  | StructureTypePipelineRasterizationStateCreateInfo
  | StructureTypePipelineMultisampleStateCreateInfo
  | StructureTypePipelineDepthStencilStateCreateInfo
  | StructureTypePipelineColorBlendStateCreateInfo
  | StructureTypePipelineDynamicStateCreateInfo
  | StructureTypeGraphicsPipelineCreateInfo
  | StructureTypeComputePipelineCreateInfo
  | StructureTypePipelineLayoutCreateInfo
  | StructureTypeSamplerCreateInfo
  | StructureTypeDescriptorSetLayoutCreateInfo
  | StructureTypeDescriptorPoolCreateInfo
  | StructureTypeDescriptorSetAllocateInfo
  | StructureTypeWriteDescriptorSet
  | StructureTypeCopyDescriptorSet
  | StructureTypeFramebufferCreateInfo
  | StructureTypeRenderPassCreateInfo
  | StructureTypeCommandPoolCreateInfo
  | StructureTypeCommandBufferAllocateInfo
  | StructureTypeCommandBufferInheritanceInfo
  | StructureTypeCommandBufferBeginInfo
  | StructureTypeRenderPassBeginInfo
  | StructureTypeBufferMemoryBarrier
  | StructureTypeImageMemoryBarrier
  | StructureTypeMemoryBarrier
  | StructureTypeLoaderInstanceCreateInfo
  | StructureTypeLoaderDeviceCreateInfo
  | StructureTypePhysicalDeviceVulkan11Features
  | StructureTypePhysicalDeviceVulkan11Properties
  | StructureTypePhysicalDeviceVulkan12Features
  | StructureTypePhysicalDeviceVulkan12Properties
  | StructureTypePhysicalDeviceVulkan13Features
  | StructureTypePhysicalDeviceVulkan13Properties
  | StructureTypePhysicalDeviceVulkan14Features
  | StructureTypePhysicalDeviceVulkan14Properties
  | StructureTypeSwapchainCreateInfoKHR
  | StructureTypePresentInfoKHR
  | StructureTypeDisplayModeCreateInfoKHR
  | StructureTypeDisplaySurfaceCreateInfoKHR
  | StructureTypeXlibSurfaceCreateInfoKHR
  | StructureTypeXcbSurfaceCreateInfoKHR
  | StructureTypeWaylandSurfaceCreateInfoKHR
  | StructureTypeWin32SurfaceCreateInfoKHR
  | StructureTypeRenderingInfo
  | StructureTypeRenderingAttachmentInfo
  | StructureTypePipelineRenderingCreateInfo
  | StructureTypePhysicalDeviceDynamicRenderingFeatures
  | StructureTypeCommandBufferInheritanceRenderingInfo
  | StructureTypeRenderingFragmentShadingRateAttachmentInfoKHR
  | StructureTypeRenderPassMultiviewCreateInfo
  | StructureTypePhysicalDeviceMultiviewFeatures
  | StructureTypePhysicalDeviceMultiviewProperties
  | StructureTypePhysicalDeviceFeatures2
  | StructureTypePhysicalDeviceProperties2
  | StructureTypeFormatProperties2
  | StructureTypeImageFormatProperties2
  | StructureTypePhysicalDeviceImageFormatInfo2
  | StructureTypeQueueFamilyProperties2
  | StructureTypePhysicalDeviceMemoryProperties2
  | StructureTypeSparseImageFormatProperties2
  | StructureTypePhysicalDeviceSparseImageFormatInfo2
  | StructureTypeMemoryAllocateFlagsInfo
  | StructureTypeDeviceGroupRenderPassBeginInfo
  | StructureTypeDeviceGroupCommandBufferBeginInfo
  | StructureTypeDeviceGroupSubmitInfo
  | StructureTypeDeviceGroupBindSparseInfo
  | StructureTypeDeviceGroupPresentCapabilitiesKHR
  | StructureTypeImageSwapchainCreateInfoKHR
  | StructureTypeBindImageMemorySwapchainInfoKHR
  | StructureTypeAcquireNextImageInfoKHR
  | StructureTypeDeviceGroupPresentInfoKHR
  | StructureTypeDeviceGroupSwapchainCreateInfoKHR
  | StructureTypeBindBufferMemoryDeviceGroupInfo
  | StructureTypeBindImageMemoryDeviceGroupInfo
  | StructureTypePhysicalDeviceShaderDrawParametersFeatures
  | StructureTypePhysicalDeviceTextureCompressionAstcHdrFeatures
  | StructureTypePipelineRobustnessCreateInfo
  | StructureTypePhysicalDevicePipelineRobustnessFeatures
  | StructureTypePhysicalDevicePipelineRobustnessProperties
  | StructureTypePhysicalDeviceGroupProperties
  | StructureTypeDeviceGroupDeviceCreateInfo
  | StructureTypePhysicalDeviceExternalImageFormatInfo
  | StructureTypeExternalImageFormatProperties
  | StructureTypePhysicalDeviceExternalBufferInfo
  | StructureTypeExternalBufferProperties
  | StructureTypePhysicalDeviceIdProperties
  | StructureTypeExternalMemoryBufferCreateInfo
  | StructureTypeExternalMemoryImageCreateInfo
  | StructureTypeExportMemoryAllocateInfo
  | StructureTypeImportMemoryWin32HandleInfoKHR
  | StructureTypeExportMemoryWin32HandleInfoKHR
  | StructureTypeMemoryWin32HandlePropertiesKHR
  | StructureTypeMemoryGetWin32HandleInfoKHR
  | StructureTypeImportMemoryFdInfoKHR
  | StructureTypeMemoryFdPropertiesKHR
  | StructureTypeMemoryGetFdInfoKHR
  | StructureTypePhysicalDeviceExternalSemaphoreInfo
  | StructureTypeExternalSemaphoreProperties
  | StructureTypeExportSemaphoreCreateInfo
  | StructureTypeImportSemaphoreWin32HandleInfoKHR
  | StructureTypeExportSemaphoreWin32HandleInfoKHR
  | StructureTypeD3D12FenceSubmitInfoKHR
  | StructureTypeSemaphoreGetWin32HandleInfoKHR
  | StructureTypeImportSemaphoreFdInfoKHR
  | StructureTypeSemaphoreGetFdInfoKHR
  | StructureTypePhysicalDevicePushDescriptorProperties
  | StructureTypePhysicalDeviceShaderFloat16Int8Features
  | StructureTypePhysicalDevice16BitStorageFeatures
  | StructureTypeDescriptorUpdateTemplateCreateInfo
  | StructureTypePhysicalDeviceSubgroupProperties
  | StructureTypePhysicalDeviceConservativeRasterizationPropertiesEXT
  | StructureTypePipelineRasterizationConservativeStateCreateInfoEXT
  | StructureTypeHdrMetadataEXT
  | StructureTypePhysicalDeviceImagelessFramebufferFeatures
  | StructureTypeFramebufferAttachmentsCreateInfo
  | StructureTypeFramebufferAttachmentImageInfo
  | StructureTypeRenderPassAttachmentBeginInfo
  | StructureTypeAttachmentDescription2
  | StructureTypeAttachmentReference2
  | StructureTypeSubpassDescription2
  | StructureTypeSubpassDependency2
  | StructureTypeRenderPassCreateInfo2
  | StructureTypeSubpassBeginInfo
  | StructureTypeSubpassEndInfo
  | StructureTypePhysicalDeviceExternalFenceInfo
  | StructureTypeExternalFenceProperties
  | StructureTypeExportFenceCreateInfo
  | StructureTypeImportFenceWin32HandleInfoKHR
  | StructureTypeExportFenceWin32HandleInfoKHR
  | StructureTypeFenceGetWin32HandleInfoKHR
  | StructureTypeImportFenceFdInfoKHR
  | StructureTypeFenceGetFdInfoKHR
  | StructureTypePhysicalDevicePerformanceQueryFeaturesKHR
  | StructureTypePhysicalDevicePerformanceQueryPropertiesKHR
  | StructureTypeQueryPoolPerformanceCreateInfoKHR
  | StructureTypePerformanceQuerySubmitInfoKHR
  | StructureTypeAcquireProfilingLockInfoKHR
  | StructureTypePerformanceCounterKHR
  | StructureTypePerformanceCounterDescriptionKHR
  | StructureTypePhysicalDevicePointClippingProperties
  | StructureTypeRenderPassInputAttachmentAspectCreateInfo
  | StructureTypeImageViewUsageCreateInfo
  | StructureTypePipelineTessellationDomainOriginStateCreateInfo
  | StructureTypePhysicalDeviceSurfaceInfo2KHR
  | StructureTypeSurfaceCapabilities2KHR
  | StructureTypeSurfaceFormat2KHR
  | StructureTypePhysicalDeviceVariablePointersFeatures
  | StructureTypeDisplayProperties2KHR
  | StructureTypeDisplayPlaneProperties2KHR
  | StructureTypeDisplayModeProperties2KHR
  | StructureTypeDisplayPlaneInfo2KHR
  | StructureTypeDisplayPlaneCapabilities2KHR
  | StructureTypeMemoryDedicatedRequirements
  | StructureTypeMemoryDedicatedAllocateInfo
  | StructureTypeDebugUtilsObjectNameInfoEXT
  | StructureTypeDebugUtilsObjectTagInfoEXT
  | StructureTypeDebugUtilsLabelEXT
  | StructureTypeDebugUtilsMessengerCallbackDataEXT
  | StructureTypeDebugUtilsMessengerCreateInfoEXT
  | StructureTypePhysicalDeviceSamplerFilterMinmaxProperties
  | StructureTypeSamplerReductionModeCreateInfo
  | StructureTypeExecutionGraphPipelineCreateInfoAMDX
  | StructureTypeTexelBufferDescriptorInfoEXT
  | StructureTypeImageDescriptorInfoEXT
  | StructureTypeResourceDescriptorInfoEXT
  | StructureTypePhysicalDeviceInlineUniformBlockFeatures
  | StructureTypePhysicalDeviceInlineUniformBlockProperties
  | StructureTypeWriteDescriptorSetInlineUniformBlock
  | StructureTypeDescriptorPoolInlineUniformBlockCreateInfo
  | StructureTypeSampleLocationsInfoEXT
  | StructureTypeRenderPassSampleLocationsBeginInfoEXT
  | StructureTypePipelineSampleLocationsStateCreateInfoEXT
  | StructureTypePhysicalDeviceSampleLocationsPropertiesEXT
  | StructureTypeMultisamplePropertiesEXT
  | StructureTypeProtectedSubmitInfo
  | StructureTypePhysicalDeviceProtectedMemoryFeatures
  | StructureTypePhysicalDeviceProtectedMemoryProperties
  | StructureTypeDeviceQueueInfo2
  | StructureTypeBufferMemoryRequirementsInfo2
  | StructureTypeImageMemoryRequirementsInfo2
  | StructureTypeImageSparseMemoryRequirementsInfo2
  | StructureTypeMemoryRequirements2
  | StructureTypeSparseImageMemoryRequirements2
  | StructureTypeImageFormatListCreateInfo
  | StructureTypeAccelerationStructureBuildGeometryInfoKHR
  | StructureTypeAccelerationStructureDeviceAddressInfoKHR
  | StructureTypeAccelerationStructureGeometryAabbsDataKHR
  | StructureTypeAccelerationStructureGeometryInstancesDataKHR
  | StructureTypeAccelerationStructureGeometryTrianglesDataKHR
  | StructureTypeAccelerationStructureGeometryKHR
  | StructureTypeWriteDescriptorSetAccelerationStructureKHR
  | StructureTypeAccelerationStructureVersionInfoKHR
  | StructureTypeCopyAccelerationStructureInfoKHR
  | StructureTypeCopyAccelerationStructureToMemoryInfoKHR
  | StructureTypeCopyMemoryToAccelerationStructureInfoKHR
  | StructureTypePhysicalDeviceAccelerationStructureFeaturesKHR
  | StructureTypePhysicalDeviceAccelerationStructurePropertiesKHR
  | StructureTypeRayTracingPipelineCreateInfoKHR
  | StructureTypeRayTracingShaderGroupCreateInfoKHR
  | StructureTypeAccelerationStructureCreateInfoKHR
  | StructureTypeRayTracingPipelineInterfaceCreateInfoKHR
  | StructureTypeAccelerationStructureBuildSizesInfoKHR
  | StructureTypeSamplerYcbcrConversionCreateInfo
  | StructureTypeSamplerYcbcrConversionInfo
  | StructureTypeBindImagePlaneMemoryInfo
  | StructureTypeImagePlaneMemoryRequirementsInfo
  | StructureTypePhysicalDeviceSamplerYcbcrConversionFeatures
  | StructureTypeSamplerYcbcrConversionImageFormatProperties
  | StructureTypeBindBufferMemoryInfo
  | StructureTypeBindImageMemoryInfo
  | StructureTypeDrmFormatModifierPropertiesListEXT
  | StructureTypePhysicalDeviceImageDrmFormatModifierInfoEXT
  | StructureTypeImageDrmFormatModifierListCreateInfoEXT
  | StructureTypeImageDrmFormatModifierExplicitCreateInfoEXT
  | StructureTypeImageDrmFormatModifierPropertiesEXT
  | StructureTypeDrmFormatModifierPropertiesList2EXT
  | StructureTypeDescriptorSetLayoutBindingFlagsCreateInfo
  | StructureTypePhysicalDeviceDescriptorIndexingFeatures
  | StructureTypePhysicalDeviceDescriptorIndexingProperties
  | StructureTypeDescriptorSetVariableDescriptorCountAllocateInfo
  | StructureTypeDescriptorSetVariableDescriptorCountLayoutSupport
  | StructureTypePhysicalDevicePortabilitySubsetFeaturesKHR
  | StructureTypePhysicalDevicePortabilitySubsetPropertiesKHR
  | StructureTypeRayTracingPipelineCreateInfoNV
  | StructureTypeAccelerationStructureCreateInfoNV
  | StructureTypeGeometryNV
  | StructureTypeGeometryTrianglesNV
  | StructureTypeGeometryAabbNV
  | StructureTypeRayTracingShaderGroupCreateInfoNV
  | StructureTypeAccelerationStructureInfoNV
  | StructureTypePhysicalDeviceMaintenance3Properties
  | StructureTypeDescriptorSetLayoutSupport
  | StructureTypeDeviceQueueGlobalPriorityCreateInfo
  | StructureTypePhysicalDeviceShaderSubgroupExtendedTypesFeatures
  | StructureTypePhysicalDevice8BitStorageFeatures
  | StructureTypeImportMemoryHostPointerInfoEXT
  | StructureTypeMemoryHostPointerPropertiesEXT
  | StructureTypePhysicalDeviceExternalMemoryHostPropertiesEXT
  | StructureTypePhysicalDeviceShaderAtomicInt64Features
  | StructureTypePhysicalDeviceShaderClockFeaturesKHR
  | StructureTypeCalibratedTimestampInfoKHR
  | StructureTypePipelineVertexInputDivisorStateCreateInfo
  | StructureTypePhysicalDeviceVertexAttributeDivisorFeatures
  | StructureTypePipelineCreationFeedbackCreateInfo
  | StructureTypePhysicalDeviceDriverProperties
  | StructureTypePhysicalDeviceFloatControlsProperties
  | StructureTypePhysicalDeviceDepthStencilResolveProperties
  | StructureTypeSubpassDescriptionDepthStencilResolve
  | StructureTypePhysicalDeviceComputeShaderDerivativesFeaturesKHR
  | StructureTypePhysicalDeviceFragmentShaderBarycentricFeaturesKHR
  | StructureTypePhysicalDeviceTimelineSemaphoreFeatures
  | StructureTypePhysicalDeviceTimelineSemaphoreProperties
  | StructureTypeSemaphoreTypeCreateInfo
  | StructureTypeTimelineSemaphoreSubmitInfo
  | StructureTypeSemaphoreWaitInfo
  | StructureTypeSemaphoreSignalInfo
  | StructureTypePhysicalDeviceVulkanMemoryModelFeatures
  | StructureTypePhysicalDeviceShaderTerminateInvocationFeatures
  | StructureTypeMetalSurfaceCreateInfoEXT
  | StructureTypePhysicalDeviceScalarBlockLayoutFeatures
  | StructureTypePhysicalDeviceSubgroupSizeControlProperties
  | StructureTypePipelineShaderStageRequiredSubgroupSizeCreateInfo
  | StructureTypePhysicalDeviceSubgroupSizeControlFeatures
  | StructureTypeFragmentShadingRateAttachmentInfoKHR
  | StructureTypePipelineFragmentShadingRateStateCreateInfoKHR
  | StructureTypePhysicalDeviceFragmentShadingRatePropertiesKHR
  | StructureTypePhysicalDeviceFragmentShadingRateFeaturesKHR
  | StructureTypePhysicalDeviceFragmentShadingRateKHR
  | StructureTypePhysicalDeviceDynamicRenderingLocalReadFeatures
  | StructureTypeRenderingAttachmentLocationInfo
  | StructureTypeRenderingInputAttachmentIndexInfo
  | StructureTypePhysicalDeviceShaderImageAtomicInt64FeaturesEXT
  | StructureTypePhysicalDeviceShaderQuadControlFeaturesKHR
  | StructureTypePhysicalDeviceMemoryBudgetPropertiesEXT
  | StructureTypePhysicalDeviceMemoryPriorityFeaturesEXT
  | StructureTypeMemoryPriorityAllocateInfoEXT
  | StructureTypePhysicalDeviceSeparateDepthStencilLayoutsFeatures
  | StructureTypeAttachmentReferenceStencilLayout
  | StructureTypeAttachmentDescriptionStencilLayout
  | StructureTypeBufferDeviceAddressInfo
  | StructureTypePhysicalDeviceToolProperties
  | StructureTypeImageStencilUsageCreateInfo
  | StructureTypePhysicalDevicePresentWaitFeaturesKHR
  | StructureTypePhysicalDeviceUniformBufferStandardLayoutFeatures
  | StructureTypeSurfaceFullScreenExclusiveInfoEXT
  | StructureTypeSurfaceFullScreenExclusiveWin32InfoEXT
  | StructureTypeSurfaceCapabilitiesFullScreenExclusiveEXT
  | StructureTypeHeadlessSurfaceCreateInfoEXT
  | StructureTypePhysicalDeviceBufferDeviceAddressFeatures
  | StructureTypeBufferOpaqueCaptureAddressCreateInfo
  | StructureTypeMemoryOpaqueCaptureAddressAllocateInfo
  | StructureTypeDeviceMemoryOpaqueCaptureAddressInfo
  | StructureTypePhysicalDeviceLineRasterizationFeatures
  | StructureTypePipelineRasterizationLineStateCreateInfo
  | StructureTypePhysicalDeviceLineRasterizationProperties
  | StructureTypePhysicalDeviceHostQueryResetFeatures
  | StructureTypePhysicalDeviceIndexTypeUint8Features
  | StructureTypePhysicalDevicePipelineExecutablePropertiesFeaturesKHR
  | StructureTypePipelineInfoKHR
  | StructureTypePipelineExecutablePropertiesKHR
  | StructureTypePipelineExecutableInfoKHR
  | StructureTypePipelineExecutableStatisticKHR
  | StructureTypePipelineExecutableInternalRepresentationKHR
  | StructureTypePhysicalDeviceHostImageCopyFeatures
  | StructureTypePhysicalDeviceHostImageCopyProperties
  | StructureTypeMemoryToImageCopy
  | StructureTypeImageToMemoryCopy
  | StructureTypeCopyImageToMemoryInfo
  | StructureTypeCopyMemoryToImageInfo
  | StructureTypeHostImageLayoutTransitionInfo
  | StructureTypeCopyImageToImageInfo
  | StructureTypeSubresourceHostMemcpySize
  | StructureTypeHostImageCopyDevicePerformanceQuery
  | StructureTypeMemoryMapInfo
  | StructureTypeMemoryUnmapInfo
  | StructureTypePhysicalDeviceShaderDemoteToHelperInvocationFeatures
  | StructureTypePhysicalDeviceShaderIntegerDotProductFeatures
  | StructureTypePhysicalDeviceShaderIntegerDotProductProperties
  | StructureTypePhysicalDeviceTexelBufferAlignmentProperties
  | StructureTypePipelineLibraryCreateInfoKHR
  | StructureTypePresentIdKHR
  | StructureTypePhysicalDevicePresentIdFeaturesKHR
  | StructureTypePhysicalDevicePrivateDataFeatures
  | StructureTypeDevicePrivateDataCreateInfo
  | StructureTypePrivateDataSlotCreateInfo
  | StructureTypePhysicalDevicePipelineCreationCacheControlFeatures
  | StructureTypeMemoryBarrier2
  | StructureTypeBufferMemoryBarrier2
  | StructureTypeImageMemoryBarrier2
  | StructureTypeDependencyInfo
  | StructureTypeSubmitInfo2
  | StructureTypeSemaphoreSubmitInfo
  | StructureTypeCommandBufferSubmitInfo
  | StructureTypePhysicalDeviceSynchronization2Features
  | StructureTypePhysicalDeviceDescriptorBufferPropertiesEXT
  | StructureTypePhysicalDeviceDescriptorBufferDensityMapPropertiesEXT
  | StructureTypePhysicalDeviceDescriptorBufferFeaturesEXT
  | StructureTypeDescriptorAddressInfoEXT
  | StructureTypeDescriptorGetInfoEXT
  | StructureTypeBufferCaptureDescriptorDataInfoEXT
  | StructureTypeImageCaptureDescriptorDataInfoEXT
  | StructureTypeImageViewCaptureDescriptorDataInfoEXT
  | StructureTypeSamplerCaptureDescriptorDataInfoEXT
  | StructureTypeAccelerationStructureCaptureDescriptorDataInfoEXT
  | StructureTypeOpaqueCaptureDescriptorDataCreateInfoEXT
  | StructureTypeDescriptorBufferBindingInfoEXT
  | StructureTypeDescriptorBufferBindingPushDescriptorBufferHandleEXT
  | StructureTypeMemoryRangeBarriersInfoKHR
  | StructureTypeMemoryRangeBarrierKHR
  | StructureTypeAccelerationStructureCreateInfo2KHR
  | StructureTypePhysicalDeviceGraphicsPipelineLibraryFeaturesEXT
  | StructureTypePhysicalDeviceGraphicsPipelineLibraryPropertiesEXT
  | StructureTypeGraphicsPipelineLibraryCreateInfoEXT
  | StructureTypePhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR
  | StructureTypePhysicalDeviceZeroInitializeWorkgroupMemoryFeatures
  | StructureTypePhysicalDeviceMeshShaderFeaturesEXT
  | StructureTypePhysicalDeviceMeshShaderPropertiesEXT
  | StructureTypePhysicalDeviceImageRobustnessFeatures
  | StructureTypePhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR
  | StructureTypeCopyBufferInfo2
  | StructureTypeCopyImageInfo2
  | StructureTypeCopyBufferToImageInfo2
  | StructureTypeCopyImageToBufferInfo2
  | StructureTypeBlitImageInfo2
  | StructureTypeResolveImageInfo2
  | StructureTypeBufferCopy2
  | StructureTypeImageCopy2
  | StructureTypeImageBlit2
  | StructureTypeBufferImageCopy2
  | StructureTypeImageResolve2
  | StructureTypeSubresourceLayout2
  | StructureTypeImageSubresource2
  | StructureTypePhysicalDeviceFaultFeaturesEXT
  | StructureTypeDeviceFaultCountsEXT
  | StructureTypeDeviceFaultInfoEXT
  | StructureTypePhysicalDeviceRayTracingPipelineFeaturesKHR
  | StructureTypePhysicalDeviceRayTracingPipelinePropertiesKHR
  | StructureTypePhysicalDeviceRayQueryFeaturesKHR
  | StructureTypePhysicalDeviceVertexInputDynamicStateFeaturesEXT
  | StructureTypeVertexInputBindingDescription2EXT
  | StructureTypeVertexInputAttributeDescription2EXT
  | StructureTypePhysicalDeviceAddressBindingReportFeaturesEXT
  | StructureTypeDeviceAddressBindingCallbackDataEXT
  | StructureTypeFormatProperties3
  | StructureTypePhysicalDeviceColorWriteEnableFeaturesEXT
  | StructureTypePipelineColorWriteCreateInfoEXT
  | StructureTypePhysicalDeviceRayTracingMaintenance1FeaturesKHR
  | StructureTypePhysicalDeviceGlobalPriorityQueryFeatures
  | StructureTypeQueueFamilyGlobalPriorityProperties
  | StructureTypePhysicalDeviceMultiDrawFeaturesEXT
  | StructureTypePhysicalDeviceMultiDrawPropertiesEXT
  | StructureTypeMicromapBuildInfoEXT
  | StructureTypeMicromapVersionInfoEXT
  | StructureTypeCopyMicromapInfoEXT
  | StructureTypeCopyMicromapToMemoryInfoEXT
  | StructureTypeCopyMemoryToMicromapInfoEXT
  | StructureTypePhysicalDeviceOpacityMicromapFeaturesEXT
  | StructureTypePhysicalDeviceOpacityMicromapPropertiesEXT
  | StructureTypeMicromapCreateInfoEXT
  | StructureTypeMicromapBuildSizesInfoEXT
  | StructureTypeAccelerationStructureTrianglesOpacityMicromapEXT
  | StructureTypePhysicalDevicePageableDeviceLocalMemoryFeaturesEXT
  | StructureTypePhysicalDeviceMaintenance4Features
  | StructureTypePhysicalDeviceMaintenance4Properties
  | StructureTypeDeviceBufferMemoryRequirements
  | StructureTypeDeviceImageMemoryRequirements
  | StructureTypePhysicalDeviceShaderSubgroupRotateFeatures
  | StructureTypePhysicalDeviceShaderMaximalReconvergenceFeaturesKHR
  | StructureTypePhysicalDeviceExtendedDynamicState3FeaturesEXT
  | StructureTypePhysicalDeviceExtendedDynamicState3PropertiesEXT
  | StructureTypeTensorCreateInfoARM
  | StructureTypeTensorViewCreateInfoARM
  | StructureTypeTensorDescriptionARM
  | StructureTypePhysicalDevicePipelineProtectedAccessFeatures
  | StructureTypePhysicalDeviceMaintenance5Features
  | StructureTypePhysicalDeviceMaintenance5Properties
  | StructureTypeRenderingAreaInfo
  | StructureTypeDeviceImageSubresourceInfo
  | StructureTypePipelineCreateFlags2CreateInfo
  | StructureTypeBufferUsageFlags2CreateInfo
  | StructureTypeAccelerationStructureDenseGeometryFormatTrianglesDataAMDX
  | StructureTypePhysicalDeviceRayTracingPositionFetchFeaturesKHR
  | StructureTypePhysicalDeviceShaderObjectFeaturesEXT
  | StructureTypePhysicalDeviceShaderObjectPropertiesEXT
  | StructureTypeShaderCreateInfoEXT
  | StructureTypePhysicalDevicePipelineBinaryFeaturesKHR
  | StructureTypePipelineBinaryCreateInfoKHR
  | StructureTypePipelineBinaryInfoKHR
  | StructureTypePipelineBinaryKeyKHR
  | StructureTypePhysicalDevicePipelineBinaryPropertiesKHR
  | StructureTypeReleaseCapturedPipelineDataInfoKHR
  | StructureTypePipelineBinaryDataInfoKHR
  | StructureTypePipelineCreateInfoKHR
  | StructureTypeDevicePipelineBinaryInternalCacheControlKHR
  | StructureTypePipelineBinaryHandlesInfoKHR
  | StructureTypeLayerSettingsCreateInfoEXT
  | StructureTypePhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT
  | StructureTypeDataGraphPipelineCreateInfoARM
  | StructureTypeDataGraphPipelineResourceInfoARM
  | StructureTypeDataGraphPipelineConstantARM
  | StructureTypePhysicalDeviceComputeShaderDerivativesPropertiesKHR
  | StructureTypePhysicalDeviceVertexAttributeDivisorProperties
  | StructureTypePhysicalDeviceUnifiedImageLayoutsFeaturesKHR
  | StructureTypePhysicalDeviceShaderFloatControls2Features
  | StructureTypePhysicalDeviceShaderExpectAssumeFeatures
  | StructureTypePhysicalDeviceMaintenance6Features
  | StructureTypePhysicalDeviceMaintenance6Properties
  | StructureTypeBindMemoryStatus
  | StructureTypeBindDescriptorSetsInfo
  | StructureTypePushConstantsInfo
  | StructureTypePushDescriptorSetInfo
  | StructureTypePushDescriptorSetWithTemplateInfo
  | StructureTypeSetDescriptorBufferOffsetsInfoEXT
  | StructureTypeBindDescriptorBufferEmbeddedSamplersInfoEXT
  | StructureTypePhysicalDeviceMaintenance7FeaturesKHR
  | StructureTypePhysicalDeviceMaintenance7PropertiesKHR
  | StructureTypePhysicalDeviceLayeredApiPropertiesListKHR
  | StructureTypePhysicalDeviceLayeredApiPropertiesKHR
  | StructureTypePhysicalDeviceLayeredApiVulkanPropertiesKHR
  | StructureTypeIndirectCommandsLayoutCreateInfoEXT
  | StructureTypeIndirectCommandsLayoutTokenEXT
  | StructureTypePhysicalDeviceMaintenance8FeaturesKHR
  | StructureTypeMemoryBarrierAccessFlags3KHR
  deriving stock (Eq, Ord, Show)

instance HasWire StructureType where
  toWire = \case
    StructureTypeApplicationInfo -> 0
    StructureTypeInstanceCreateInfo -> 1
    StructureTypeDeviceQueueCreateInfo -> 2
    StructureTypeDeviceCreateInfo -> 3
    StructureTypeSubmitInfo -> 4
    StructureTypeMemoryAllocateInfo -> 5
    StructureTypeMappedMemoryRange -> 6
    StructureTypeBindSparseInfo -> 7
    StructureTypeFenceCreateInfo -> 8
    StructureTypeSemaphoreCreateInfo -> 9
    StructureTypeEventCreateInfo -> 10
    StructureTypeQueryPoolCreateInfo -> 11
    StructureTypeBufferCreateInfo -> 12
    StructureTypeBufferViewCreateInfo -> 13
    StructureTypeImageCreateInfo -> 14
    StructureTypeImageViewCreateInfo -> 15
    StructureTypeShaderModuleCreateInfo -> 16
    StructureTypePipelineCacheCreateInfo -> 17
    StructureTypePipelineShaderStageCreateInfo -> 18
    StructureTypePipelineVertexInputStateCreateInfo -> 19
    StructureTypePipelineInputAssemblyStateCreateInfo -> 20
    StructureTypePipelineTessellationStateCreateInfo -> 21
    StructureTypePipelineViewportStateCreateInfo -> 22
    StructureTypePipelineRasterizationStateCreateInfo -> 23
    StructureTypePipelineMultisampleStateCreateInfo -> 24
    StructureTypePipelineDepthStencilStateCreateInfo -> 25
    StructureTypePipelineColorBlendStateCreateInfo -> 26
    StructureTypePipelineDynamicStateCreateInfo -> 27
    StructureTypeGraphicsPipelineCreateInfo -> 28
    StructureTypeComputePipelineCreateInfo -> 29
    StructureTypePipelineLayoutCreateInfo -> 30
    StructureTypeSamplerCreateInfo -> 31
    StructureTypeDescriptorSetLayoutCreateInfo -> 32
    StructureTypeDescriptorPoolCreateInfo -> 33
    StructureTypeDescriptorSetAllocateInfo -> 34
    StructureTypeWriteDescriptorSet -> 35
    StructureTypeCopyDescriptorSet -> 36
    StructureTypeFramebufferCreateInfo -> 37
    StructureTypeRenderPassCreateInfo -> 38
    StructureTypeCommandPoolCreateInfo -> 39
    StructureTypeCommandBufferAllocateInfo -> 40
    StructureTypeCommandBufferInheritanceInfo -> 41
    StructureTypeCommandBufferBeginInfo -> 42
    StructureTypeRenderPassBeginInfo -> 43
    StructureTypeBufferMemoryBarrier -> 44
    StructureTypeImageMemoryBarrier -> 45
    StructureTypeMemoryBarrier -> 46
    StructureTypeLoaderInstanceCreateInfo -> 47
    StructureTypeLoaderDeviceCreateInfo -> 48
    StructureTypePhysicalDeviceVulkan11Features -> 49
    StructureTypePhysicalDeviceVulkan11Properties -> 50
    StructureTypePhysicalDeviceVulkan12Features -> 51
    StructureTypePhysicalDeviceVulkan12Properties -> 52
    StructureTypePhysicalDeviceVulkan13Features -> 53
    StructureTypePhysicalDeviceVulkan13Properties -> 54
    StructureTypePhysicalDeviceVulkan14Features -> 55
    StructureTypePhysicalDeviceVulkan14Properties -> 56
    StructureTypeSwapchainCreateInfoKHR -> 1000001000
    StructureTypePresentInfoKHR -> 1000001001
    StructureTypeDisplayModeCreateInfoKHR -> 1000002000
    StructureTypeDisplaySurfaceCreateInfoKHR -> 1000002001
    StructureTypeXlibSurfaceCreateInfoKHR -> 1000004000
    StructureTypeXcbSurfaceCreateInfoKHR -> 1000005000
    StructureTypeWaylandSurfaceCreateInfoKHR -> 1000006000
    StructureTypeWin32SurfaceCreateInfoKHR -> 1000009000
    StructureTypeRenderingInfo -> 1000044000
    StructureTypeRenderingAttachmentInfo -> 1000044001
    StructureTypePipelineRenderingCreateInfo -> 1000044002
    StructureTypePhysicalDeviceDynamicRenderingFeatures -> 1000044003
    StructureTypeCommandBufferInheritanceRenderingInfo -> 1000044004
    StructureTypeRenderingFragmentShadingRateAttachmentInfoKHR -> 1000044006
    StructureTypeRenderPassMultiviewCreateInfo -> 1000053000
    StructureTypePhysicalDeviceMultiviewFeatures -> 1000053001
    StructureTypePhysicalDeviceMultiviewProperties -> 1000053002
    StructureTypePhysicalDeviceFeatures2 -> 1000059000
    StructureTypePhysicalDeviceProperties2 -> 1000059001
    StructureTypeFormatProperties2 -> 1000059002
    StructureTypeImageFormatProperties2 -> 1000059003
    StructureTypePhysicalDeviceImageFormatInfo2 -> 1000059004
    StructureTypeQueueFamilyProperties2 -> 1000059005
    StructureTypePhysicalDeviceMemoryProperties2 -> 1000059006
    StructureTypeSparseImageFormatProperties2 -> 1000059007
    StructureTypePhysicalDeviceSparseImageFormatInfo2 -> 1000059008
    StructureTypeMemoryAllocateFlagsInfo -> 1000060000
    StructureTypeDeviceGroupRenderPassBeginInfo -> 1000060003
    StructureTypeDeviceGroupCommandBufferBeginInfo -> 1000060004
    StructureTypeDeviceGroupSubmitInfo -> 1000060005
    StructureTypeDeviceGroupBindSparseInfo -> 1000060006
    StructureTypeDeviceGroupPresentCapabilitiesKHR -> 1000060007
    StructureTypeImageSwapchainCreateInfoKHR -> 1000060008
    StructureTypeBindImageMemorySwapchainInfoKHR -> 1000060009
    StructureTypeAcquireNextImageInfoKHR -> 1000060010
    StructureTypeDeviceGroupPresentInfoKHR -> 1000060011
    StructureTypeDeviceGroupSwapchainCreateInfoKHR -> 1000060012
    StructureTypeBindBufferMemoryDeviceGroupInfo -> 1000060013
    StructureTypeBindImageMemoryDeviceGroupInfo -> 1000060014
    StructureTypePhysicalDeviceShaderDrawParametersFeatures -> 1000063000
    StructureTypePhysicalDeviceTextureCompressionAstcHdrFeatures -> 1000066000
    StructureTypePipelineRobustnessCreateInfo -> 1000068000
    StructureTypePhysicalDevicePipelineRobustnessFeatures -> 1000068001
    StructureTypePhysicalDevicePipelineRobustnessProperties -> 1000068002
    StructureTypePhysicalDeviceGroupProperties -> 1000070000
    StructureTypeDeviceGroupDeviceCreateInfo -> 1000070001
    StructureTypePhysicalDeviceExternalImageFormatInfo -> 1000071000
    StructureTypeExternalImageFormatProperties -> 1000071001
    StructureTypePhysicalDeviceExternalBufferInfo -> 1000071002
    StructureTypeExternalBufferProperties -> 1000071003
    StructureTypePhysicalDeviceIdProperties -> 1000071004
    StructureTypeExternalMemoryBufferCreateInfo -> 1000072000
    StructureTypeExternalMemoryImageCreateInfo -> 1000072001
    StructureTypeExportMemoryAllocateInfo -> 1000072002
    StructureTypeImportMemoryWin32HandleInfoKHR -> 1000073000
    StructureTypeExportMemoryWin32HandleInfoKHR -> 1000073001
    StructureTypeMemoryWin32HandlePropertiesKHR -> 1000073002
    StructureTypeMemoryGetWin32HandleInfoKHR -> 1000073003
    StructureTypeImportMemoryFdInfoKHR -> 1000074000
    StructureTypeMemoryFdPropertiesKHR -> 1000074001
    StructureTypeMemoryGetFdInfoKHR -> 1000074002
    StructureTypePhysicalDeviceExternalSemaphoreInfo -> 1000076000
    StructureTypeExternalSemaphoreProperties -> 1000076001
    StructureTypeExportSemaphoreCreateInfo -> 1000077000
    StructureTypeImportSemaphoreWin32HandleInfoKHR -> 1000078000
    StructureTypeExportSemaphoreWin32HandleInfoKHR -> 1000078001
    StructureTypeD3D12FenceSubmitInfoKHR -> 1000078002
    StructureTypeSemaphoreGetWin32HandleInfoKHR -> 1000078003
    StructureTypeImportSemaphoreFdInfoKHR -> 1000079000
    StructureTypeSemaphoreGetFdInfoKHR -> 1000079001
    StructureTypePhysicalDevicePushDescriptorProperties -> 1000080000
    StructureTypePhysicalDeviceShaderFloat16Int8Features -> 1000082000
    StructureTypePhysicalDevice16BitStorageFeatures -> 1000083000
    StructureTypeDescriptorUpdateTemplateCreateInfo -> 1000085000
    StructureTypePhysicalDeviceSubgroupProperties -> 1000094000
    StructureTypePhysicalDeviceConservativeRasterizationPropertiesEXT -> 1000101000
    StructureTypePipelineRasterizationConservativeStateCreateInfoEXT -> 1000101001
    StructureTypeHdrMetadataEXT -> 1000105000
    StructureTypePhysicalDeviceImagelessFramebufferFeatures -> 1000108000
    StructureTypeFramebufferAttachmentsCreateInfo -> 1000108001
    StructureTypeFramebufferAttachmentImageInfo -> 1000108002
    StructureTypeRenderPassAttachmentBeginInfo -> 1000108003
    StructureTypeAttachmentDescription2 -> 1000109000
    StructureTypeAttachmentReference2 -> 1000109001
    StructureTypeSubpassDescription2 -> 1000109002
    StructureTypeSubpassDependency2 -> 1000109003
    StructureTypeRenderPassCreateInfo2 -> 1000109004
    StructureTypeSubpassBeginInfo -> 1000109005
    StructureTypeSubpassEndInfo -> 1000109006
    StructureTypePhysicalDeviceExternalFenceInfo -> 1000112000
    StructureTypeExternalFenceProperties -> 1000112001
    StructureTypeExportFenceCreateInfo -> 1000113000
    StructureTypeImportFenceWin32HandleInfoKHR -> 1000114000
    StructureTypeExportFenceWin32HandleInfoKHR -> 1000114001
    StructureTypeFenceGetWin32HandleInfoKHR -> 1000114002
    StructureTypeImportFenceFdInfoKHR -> 1000115000
    StructureTypeFenceGetFdInfoKHR -> 1000115001
    StructureTypePhysicalDevicePerformanceQueryFeaturesKHR -> 1000116000
    StructureTypePhysicalDevicePerformanceQueryPropertiesKHR -> 1000116001
    StructureTypeQueryPoolPerformanceCreateInfoKHR -> 1000116002
    StructureTypePerformanceQuerySubmitInfoKHR -> 1000116003
    StructureTypeAcquireProfilingLockInfoKHR -> 1000116004
    StructureTypePerformanceCounterKHR -> 1000116005
    StructureTypePerformanceCounterDescriptionKHR -> 1000116006
    StructureTypePhysicalDevicePointClippingProperties -> 1000117000
    StructureTypeRenderPassInputAttachmentAspectCreateInfo -> 1000117001
    StructureTypeImageViewUsageCreateInfo -> 1000117002
    StructureTypePipelineTessellationDomainOriginStateCreateInfo -> 1000117003
    StructureTypePhysicalDeviceSurfaceInfo2KHR -> 1000119000
    StructureTypeSurfaceCapabilities2KHR -> 1000119001
    StructureTypeSurfaceFormat2KHR -> 1000119002
    StructureTypePhysicalDeviceVariablePointersFeatures -> 1000120000
    StructureTypeDisplayProperties2KHR -> 1000121000
    StructureTypeDisplayPlaneProperties2KHR -> 1000121001
    StructureTypeDisplayModeProperties2KHR -> 1000121002
    StructureTypeDisplayPlaneInfo2KHR -> 1000121003
    StructureTypeDisplayPlaneCapabilities2KHR -> 1000121004
    StructureTypeMemoryDedicatedRequirements -> 1000127000
    StructureTypeMemoryDedicatedAllocateInfo -> 1000127001
    StructureTypeDebugUtilsObjectNameInfoEXT -> 1000128000
    StructureTypeDebugUtilsObjectTagInfoEXT -> 1000128001
    StructureTypeDebugUtilsLabelEXT -> 1000128002
    StructureTypeDebugUtilsMessengerCallbackDataEXT -> 1000128003
    StructureTypeDebugUtilsMessengerCreateInfoEXT -> 1000128004
    StructureTypePhysicalDeviceSamplerFilterMinmaxProperties -> 1000130000
    StructureTypeSamplerReductionModeCreateInfo -> 1000130001
    StructureTypeExecutionGraphPipelineCreateInfoAMDX -> 1000134003
    StructureTypeTexelBufferDescriptorInfoEXT -> 1000135000
    StructureTypeImageDescriptorInfoEXT -> 1000135001
    StructureTypeResourceDescriptorInfoEXT -> 1000135002
    StructureTypePhysicalDeviceInlineUniformBlockFeatures -> 1000138000
    StructureTypePhysicalDeviceInlineUniformBlockProperties -> 1000138001
    StructureTypeWriteDescriptorSetInlineUniformBlock -> 1000138002
    StructureTypeDescriptorPoolInlineUniformBlockCreateInfo -> 1000138003
    StructureTypeSampleLocationsInfoEXT -> 1000143000
    StructureTypeRenderPassSampleLocationsBeginInfoEXT -> 1000143001
    StructureTypePipelineSampleLocationsStateCreateInfoEXT -> 1000143002
    StructureTypePhysicalDeviceSampleLocationsPropertiesEXT -> 1000143003
    StructureTypeMultisamplePropertiesEXT -> 1000143004
    StructureTypeProtectedSubmitInfo -> 1000145000
    StructureTypePhysicalDeviceProtectedMemoryFeatures -> 1000145001
    StructureTypePhysicalDeviceProtectedMemoryProperties -> 1000145002
    StructureTypeDeviceQueueInfo2 -> 1000145003
    StructureTypeBufferMemoryRequirementsInfo2 -> 1000146000
    StructureTypeImageMemoryRequirementsInfo2 -> 1000146001
    StructureTypeImageSparseMemoryRequirementsInfo2 -> 1000146002
    StructureTypeMemoryRequirements2 -> 1000146003
    StructureTypeSparseImageMemoryRequirements2 -> 1000146004
    StructureTypeImageFormatListCreateInfo -> 1000147000
    StructureTypeAccelerationStructureBuildGeometryInfoKHR -> 1000150000
    StructureTypeAccelerationStructureDeviceAddressInfoKHR -> 1000150002
    StructureTypeAccelerationStructureGeometryAabbsDataKHR -> 1000150003
    StructureTypeAccelerationStructureGeometryInstancesDataKHR -> 1000150004
    StructureTypeAccelerationStructureGeometryTrianglesDataKHR -> 1000150005
    StructureTypeAccelerationStructureGeometryKHR -> 1000150006
    StructureTypeWriteDescriptorSetAccelerationStructureKHR -> 1000150007
    StructureTypeAccelerationStructureVersionInfoKHR -> 1000150009
    StructureTypeCopyAccelerationStructureInfoKHR -> 1000150010
    StructureTypeCopyAccelerationStructureToMemoryInfoKHR -> 1000150011
    StructureTypeCopyMemoryToAccelerationStructureInfoKHR -> 1000150012
    StructureTypePhysicalDeviceAccelerationStructureFeaturesKHR -> 1000150013
    StructureTypePhysicalDeviceAccelerationStructurePropertiesKHR -> 1000150014
    StructureTypeRayTracingPipelineCreateInfoKHR -> 1000150015
    StructureTypeRayTracingShaderGroupCreateInfoKHR -> 1000150016
    StructureTypeAccelerationStructureCreateInfoKHR -> 1000150017
    StructureTypeRayTracingPipelineInterfaceCreateInfoKHR -> 1000150018
    StructureTypeAccelerationStructureBuildSizesInfoKHR -> 1000150020
    StructureTypeSamplerYcbcrConversionCreateInfo -> 1000156000
    StructureTypeSamplerYcbcrConversionInfo -> 1000156001
    StructureTypeBindImagePlaneMemoryInfo -> 1000156002
    StructureTypeImagePlaneMemoryRequirementsInfo -> 1000156003
    StructureTypePhysicalDeviceSamplerYcbcrConversionFeatures -> 1000156004
    StructureTypeSamplerYcbcrConversionImageFormatProperties -> 1000156005
    StructureTypeBindBufferMemoryInfo -> 1000157000
    StructureTypeBindImageMemoryInfo -> 1000157001
    StructureTypeDrmFormatModifierPropertiesListEXT -> 1000158000
    StructureTypePhysicalDeviceImageDrmFormatModifierInfoEXT -> 1000158002
    StructureTypeImageDrmFormatModifierListCreateInfoEXT -> 1000158003
    StructureTypeImageDrmFormatModifierExplicitCreateInfoEXT -> 1000158004
    StructureTypeImageDrmFormatModifierPropertiesEXT -> 1000158005
    StructureTypeDrmFormatModifierPropertiesList2EXT -> 1000158006
    StructureTypeDescriptorSetLayoutBindingFlagsCreateInfo -> 1000161000
    StructureTypePhysicalDeviceDescriptorIndexingFeatures -> 1000161001
    StructureTypePhysicalDeviceDescriptorIndexingProperties -> 1000161002
    StructureTypeDescriptorSetVariableDescriptorCountAllocateInfo -> 1000161003
    StructureTypeDescriptorSetVariableDescriptorCountLayoutSupport -> 1000161004
    StructureTypePhysicalDevicePortabilitySubsetFeaturesKHR -> 1000163000
    StructureTypePhysicalDevicePortabilitySubsetPropertiesKHR -> 1000163001
    StructureTypeRayTracingPipelineCreateInfoNV -> 1000165000
    StructureTypeAccelerationStructureCreateInfoNV -> 1000165001
    StructureTypeGeometryNV -> 1000165003
    StructureTypeGeometryTrianglesNV -> 1000165004
    StructureTypeGeometryAabbNV -> 1000165005
    StructureTypeRayTracingShaderGroupCreateInfoNV -> 1000165011
    StructureTypeAccelerationStructureInfoNV -> 1000165012
    StructureTypePhysicalDeviceMaintenance3Properties -> 1000168000
    StructureTypeDescriptorSetLayoutSupport -> 1000168001
    StructureTypeDeviceQueueGlobalPriorityCreateInfo -> 1000174000
    StructureTypePhysicalDeviceShaderSubgroupExtendedTypesFeatures -> 1000175000
    StructureTypePhysicalDevice8BitStorageFeatures -> 1000177000
    StructureTypeImportMemoryHostPointerInfoEXT -> 1000178000
    StructureTypeMemoryHostPointerPropertiesEXT -> 1000178001
    StructureTypePhysicalDeviceExternalMemoryHostPropertiesEXT -> 1000178002
    StructureTypePhysicalDeviceShaderAtomicInt64Features -> 1000180000
    StructureTypePhysicalDeviceShaderClockFeaturesKHR -> 1000181000
    StructureTypeCalibratedTimestampInfoKHR -> 1000184000
    StructureTypePipelineVertexInputDivisorStateCreateInfo -> 1000190001
    StructureTypePhysicalDeviceVertexAttributeDivisorFeatures -> 1000190002
    StructureTypePipelineCreationFeedbackCreateInfo -> 1000192000
    StructureTypePhysicalDeviceDriverProperties -> 1000196000
    StructureTypePhysicalDeviceFloatControlsProperties -> 1000197000
    StructureTypePhysicalDeviceDepthStencilResolveProperties -> 1000199000
    StructureTypeSubpassDescriptionDepthStencilResolve -> 1000199001
    StructureTypePhysicalDeviceComputeShaderDerivativesFeaturesKHR -> 1000201000
    StructureTypePhysicalDeviceFragmentShaderBarycentricFeaturesKHR -> 1000203000
    StructureTypePhysicalDeviceTimelineSemaphoreFeatures -> 1000207000
    StructureTypePhysicalDeviceTimelineSemaphoreProperties -> 1000207001
    StructureTypeSemaphoreTypeCreateInfo -> 1000207002
    StructureTypeTimelineSemaphoreSubmitInfo -> 1000207003
    StructureTypeSemaphoreWaitInfo -> 1000207004
    StructureTypeSemaphoreSignalInfo -> 1000207005
    StructureTypePhysicalDeviceVulkanMemoryModelFeatures -> 1000211000
    StructureTypePhysicalDeviceShaderTerminateInvocationFeatures -> 1000215000
    StructureTypeMetalSurfaceCreateInfoEXT -> 1000217000
    StructureTypePhysicalDeviceScalarBlockLayoutFeatures -> 1000221000
    StructureTypePhysicalDeviceSubgroupSizeControlProperties -> 1000225000
    StructureTypePipelineShaderStageRequiredSubgroupSizeCreateInfo -> 1000225001
    StructureTypePhysicalDeviceSubgroupSizeControlFeatures -> 1000225002
    StructureTypeFragmentShadingRateAttachmentInfoKHR -> 1000226000
    StructureTypePipelineFragmentShadingRateStateCreateInfoKHR -> 1000226001
    StructureTypePhysicalDeviceFragmentShadingRatePropertiesKHR -> 1000226002
    StructureTypePhysicalDeviceFragmentShadingRateFeaturesKHR -> 1000226003
    StructureTypePhysicalDeviceFragmentShadingRateKHR -> 1000226004
    StructureTypePhysicalDeviceDynamicRenderingLocalReadFeatures -> 1000232000
    StructureTypeRenderingAttachmentLocationInfo -> 1000232001
    StructureTypeRenderingInputAttachmentIndexInfo -> 1000232002
    StructureTypePhysicalDeviceShaderImageAtomicInt64FeaturesEXT -> 1000234000
    StructureTypePhysicalDeviceShaderQuadControlFeaturesKHR -> 1000235000
    StructureTypePhysicalDeviceMemoryBudgetPropertiesEXT -> 1000237000
    StructureTypePhysicalDeviceMemoryPriorityFeaturesEXT -> 1000238000
    StructureTypeMemoryPriorityAllocateInfoEXT -> 1000238001
    StructureTypePhysicalDeviceSeparateDepthStencilLayoutsFeatures -> 1000241000
    StructureTypeAttachmentReferenceStencilLayout -> 1000241001
    StructureTypeAttachmentDescriptionStencilLayout -> 1000241002
    StructureTypeBufferDeviceAddressInfo -> 1000244001
    StructureTypePhysicalDeviceToolProperties -> 1000245000
    StructureTypeImageStencilUsageCreateInfo -> 1000246000
    StructureTypePhysicalDevicePresentWaitFeaturesKHR -> 1000248000
    StructureTypePhysicalDeviceUniformBufferStandardLayoutFeatures -> 1000253000
    StructureTypeSurfaceFullScreenExclusiveInfoEXT -> 1000255000
    StructureTypeSurfaceFullScreenExclusiveWin32InfoEXT -> 1000255001
    StructureTypeSurfaceCapabilitiesFullScreenExclusiveEXT -> 1000255002
    StructureTypeHeadlessSurfaceCreateInfoEXT -> 1000256000
    StructureTypePhysicalDeviceBufferDeviceAddressFeatures -> 1000257000
    StructureTypeBufferOpaqueCaptureAddressCreateInfo -> 1000257002
    StructureTypeMemoryOpaqueCaptureAddressAllocateInfo -> 1000257003
    StructureTypeDeviceMemoryOpaqueCaptureAddressInfo -> 1000257004
    StructureTypePhysicalDeviceLineRasterizationFeatures -> 1000259000
    StructureTypePipelineRasterizationLineStateCreateInfo -> 1000259001
    StructureTypePhysicalDeviceLineRasterizationProperties -> 1000259002
    StructureTypePhysicalDeviceHostQueryResetFeatures -> 1000261000
    StructureTypePhysicalDeviceIndexTypeUint8Features -> 1000265000
    StructureTypePhysicalDevicePipelineExecutablePropertiesFeaturesKHR -> 1000269000
    StructureTypePipelineInfoKHR -> 1000269001
    StructureTypePipelineExecutablePropertiesKHR -> 1000269002
    StructureTypePipelineExecutableInfoKHR -> 1000269003
    StructureTypePipelineExecutableStatisticKHR -> 1000269004
    StructureTypePipelineExecutableInternalRepresentationKHR -> 1000269005
    StructureTypePhysicalDeviceHostImageCopyFeatures -> 1000270000
    StructureTypePhysicalDeviceHostImageCopyProperties -> 1000270001
    StructureTypeMemoryToImageCopy -> 1000270002
    StructureTypeImageToMemoryCopy -> 1000270003
    StructureTypeCopyImageToMemoryInfo -> 1000270004
    StructureTypeCopyMemoryToImageInfo -> 1000270005
    StructureTypeHostImageLayoutTransitionInfo -> 1000270006
    StructureTypeCopyImageToImageInfo -> 1000270007
    StructureTypeSubresourceHostMemcpySize -> 1000270008
    StructureTypeHostImageCopyDevicePerformanceQuery -> 1000270009
    StructureTypeMemoryMapInfo -> 1000271000
    StructureTypeMemoryUnmapInfo -> 1000271001
    StructureTypePhysicalDeviceShaderDemoteToHelperInvocationFeatures -> 1000276000
    StructureTypePhysicalDeviceShaderIntegerDotProductFeatures -> 1000280000
    StructureTypePhysicalDeviceShaderIntegerDotProductProperties -> 1000280001
    StructureTypePhysicalDeviceTexelBufferAlignmentProperties -> 1000281001
    StructureTypePipelineLibraryCreateInfoKHR -> 1000290000
    StructureTypePresentIdKHR -> 1000294000
    StructureTypePhysicalDevicePresentIdFeaturesKHR -> 1000294001
    StructureTypePhysicalDevicePrivateDataFeatures -> 1000295000
    StructureTypeDevicePrivateDataCreateInfo -> 1000295001
    StructureTypePrivateDataSlotCreateInfo -> 1000295002
    StructureTypePhysicalDevicePipelineCreationCacheControlFeatures -> 1000297000
    StructureTypeMemoryBarrier2 -> 1000314000
    StructureTypeBufferMemoryBarrier2 -> 1000314001
    StructureTypeImageMemoryBarrier2 -> 1000314002
    StructureTypeDependencyInfo -> 1000314003
    StructureTypeSubmitInfo2 -> 1000314004
    StructureTypeSemaphoreSubmitInfo -> 1000314005
    StructureTypeCommandBufferSubmitInfo -> 1000314006
    StructureTypePhysicalDeviceSynchronization2Features -> 1000314007
    StructureTypePhysicalDeviceDescriptorBufferPropertiesEXT -> 1000316000
    StructureTypePhysicalDeviceDescriptorBufferDensityMapPropertiesEXT -> 1000316001
    StructureTypePhysicalDeviceDescriptorBufferFeaturesEXT -> 1000316002
    StructureTypeDescriptorAddressInfoEXT -> 1000316003
    StructureTypeDescriptorGetInfoEXT -> 1000316004
    StructureTypeBufferCaptureDescriptorDataInfoEXT -> 1000316005
    StructureTypeImageCaptureDescriptorDataInfoEXT -> 1000316006
    StructureTypeImageViewCaptureDescriptorDataInfoEXT -> 1000316007
    StructureTypeSamplerCaptureDescriptorDataInfoEXT -> 1000316008
    StructureTypeAccelerationStructureCaptureDescriptorDataInfoEXT -> 1000316009
    StructureTypeOpaqueCaptureDescriptorDataCreateInfoEXT -> 1000316010
    StructureTypeDescriptorBufferBindingInfoEXT -> 1000316011
    StructureTypeDescriptorBufferBindingPushDescriptorBufferHandleEXT -> 1000316012
    StructureTypeMemoryRangeBarriersInfoKHR -> 1000318004
    StructureTypeMemoryRangeBarrierKHR -> 1000318005
    StructureTypeAccelerationStructureCreateInfo2KHR -> 1000318015
    StructureTypePhysicalDeviceGraphicsPipelineLibraryFeaturesEXT -> 1000320000
    StructureTypePhysicalDeviceGraphicsPipelineLibraryPropertiesEXT -> 1000320001
    StructureTypeGraphicsPipelineLibraryCreateInfoEXT -> 1000320002
    StructureTypePhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR -> 1000323000
    StructureTypePhysicalDeviceZeroInitializeWorkgroupMemoryFeatures -> 1000325000
    StructureTypePhysicalDeviceMeshShaderFeaturesEXT -> 1000328000
    StructureTypePhysicalDeviceMeshShaderPropertiesEXT -> 1000328001
    StructureTypePhysicalDeviceImageRobustnessFeatures -> 1000335000
    StructureTypePhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR -> 1000336000
    StructureTypeCopyBufferInfo2 -> 1000337000
    StructureTypeCopyImageInfo2 -> 1000337001
    StructureTypeCopyBufferToImageInfo2 -> 1000337002
    StructureTypeCopyImageToBufferInfo2 -> 1000337003
    StructureTypeBlitImageInfo2 -> 1000337004
    StructureTypeResolveImageInfo2 -> 1000337005
    StructureTypeBufferCopy2 -> 1000337006
    StructureTypeImageCopy2 -> 1000337007
    StructureTypeImageBlit2 -> 1000337008
    StructureTypeBufferImageCopy2 -> 1000337009
    StructureTypeImageResolve2 -> 1000337010
    StructureTypeSubresourceLayout2 -> 1000338002
    StructureTypeImageSubresource2 -> 1000338003
    StructureTypePhysicalDeviceFaultFeaturesEXT -> 1000341000
    StructureTypeDeviceFaultCountsEXT -> 1000341001
    StructureTypeDeviceFaultInfoEXT -> 1000341002
    StructureTypePhysicalDeviceRayTracingPipelineFeaturesKHR -> 1000347000
    StructureTypePhysicalDeviceRayTracingPipelinePropertiesKHR -> 1000347001
    StructureTypePhysicalDeviceRayQueryFeaturesKHR -> 1000348013
    StructureTypePhysicalDeviceVertexInputDynamicStateFeaturesEXT -> 1000352000
    StructureTypeVertexInputBindingDescription2EXT -> 1000352001
    StructureTypeVertexInputAttributeDescription2EXT -> 1000352002
    StructureTypePhysicalDeviceAddressBindingReportFeaturesEXT -> 1000354000
    StructureTypeDeviceAddressBindingCallbackDataEXT -> 1000354001
    StructureTypeFormatProperties3 -> 1000360000
    StructureTypePhysicalDeviceColorWriteEnableFeaturesEXT -> 1000381000
    StructureTypePipelineColorWriteCreateInfoEXT -> 1000381001
    StructureTypePhysicalDeviceRayTracingMaintenance1FeaturesKHR -> 1000386000
    StructureTypePhysicalDeviceGlobalPriorityQueryFeatures -> 1000388000
    StructureTypeQueueFamilyGlobalPriorityProperties -> 1000388001
    StructureTypePhysicalDeviceMultiDrawFeaturesEXT -> 1000392000
    StructureTypePhysicalDeviceMultiDrawPropertiesEXT -> 1000392001
    StructureTypeMicromapBuildInfoEXT -> 1000396000
    StructureTypeMicromapVersionInfoEXT -> 1000396001
    StructureTypeCopyMicromapInfoEXT -> 1000396002
    StructureTypeCopyMicromapToMemoryInfoEXT -> 1000396003
    StructureTypeCopyMemoryToMicromapInfoEXT -> 1000396004
    StructureTypePhysicalDeviceOpacityMicromapFeaturesEXT -> 1000396005
    StructureTypePhysicalDeviceOpacityMicromapPropertiesEXT -> 1000396006
    StructureTypeMicromapCreateInfoEXT -> 1000396007
    StructureTypeMicromapBuildSizesInfoEXT -> 1000396008
    StructureTypeAccelerationStructureTrianglesOpacityMicromapEXT -> 1000396009
    StructureTypePhysicalDevicePageableDeviceLocalMemoryFeaturesEXT -> 1000412000
    StructureTypePhysicalDeviceMaintenance4Features -> 1000413000
    StructureTypePhysicalDeviceMaintenance4Properties -> 1000413001
    StructureTypeDeviceBufferMemoryRequirements -> 1000413002
    StructureTypeDeviceImageMemoryRequirements -> 1000413003
    StructureTypePhysicalDeviceShaderSubgroupRotateFeatures -> 1000416000
    StructureTypePhysicalDeviceShaderMaximalReconvergenceFeaturesKHR -> 1000434000
    StructureTypePhysicalDeviceExtendedDynamicState3FeaturesEXT -> 1000455000
    StructureTypePhysicalDeviceExtendedDynamicState3PropertiesEXT -> 1000455001
    StructureTypeTensorCreateInfoARM -> 1000460000
    StructureTypeTensorViewCreateInfoARM -> 1000460001
    StructureTypeTensorDescriptionARM -> 1000460006
    StructureTypePhysicalDevicePipelineProtectedAccessFeatures -> 1000466000
    StructureTypePhysicalDeviceMaintenance5Features -> 1000470000
    StructureTypePhysicalDeviceMaintenance5Properties -> 1000470001
    StructureTypeRenderingAreaInfo -> 1000470003
    StructureTypeDeviceImageSubresourceInfo -> 1000470004
    StructureTypePipelineCreateFlags2CreateInfo -> 1000470005
    StructureTypeBufferUsageFlags2CreateInfo -> 1000470006
    StructureTypeAccelerationStructureDenseGeometryFormatTrianglesDataAMDX -> 1000478001
    StructureTypePhysicalDeviceRayTracingPositionFetchFeaturesKHR -> 1000481000
    StructureTypePhysicalDeviceShaderObjectFeaturesEXT -> 1000482000
    StructureTypePhysicalDeviceShaderObjectPropertiesEXT -> 1000482001
    StructureTypeShaderCreateInfoEXT -> 1000482002
    StructureTypePhysicalDevicePipelineBinaryFeaturesKHR -> 1000483000
    StructureTypePipelineBinaryCreateInfoKHR -> 1000483001
    StructureTypePipelineBinaryInfoKHR -> 1000483002
    StructureTypePipelineBinaryKeyKHR -> 1000483003
    StructureTypePhysicalDevicePipelineBinaryPropertiesKHR -> 1000483004
    StructureTypeReleaseCapturedPipelineDataInfoKHR -> 1000483005
    StructureTypePipelineBinaryDataInfoKHR -> 1000483006
    StructureTypePipelineCreateInfoKHR -> 1000483007
    StructureTypeDevicePipelineBinaryInternalCacheControlKHR -> 1000483008
    StructureTypePipelineBinaryHandlesInfoKHR -> 1000483009
    StructureTypeLayerSettingsCreateInfoEXT -> 1000496000
    StructureTypePhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT -> 1000499000
    StructureTypeDataGraphPipelineCreateInfoARM -> 1000507000
    StructureTypeDataGraphPipelineResourceInfoARM -> 1000507002
    StructureTypeDataGraphPipelineConstantARM -> 1000507003
    StructureTypePhysicalDeviceComputeShaderDerivativesPropertiesKHR -> 1000511000
    StructureTypePhysicalDeviceVertexAttributeDivisorProperties -> 1000525000
    StructureTypePhysicalDeviceUnifiedImageLayoutsFeaturesKHR -> 1000527000
    StructureTypePhysicalDeviceShaderFloatControls2Features -> 1000528000
    StructureTypePhysicalDeviceShaderExpectAssumeFeatures -> 1000544000
    StructureTypePhysicalDeviceMaintenance6Features -> 1000545000
    StructureTypePhysicalDeviceMaintenance6Properties -> 1000545001
    StructureTypeBindMemoryStatus -> 1000545002
    StructureTypeBindDescriptorSetsInfo -> 1000545003
    StructureTypePushConstantsInfo -> 1000545004
    StructureTypePushDescriptorSetInfo -> 1000545005
    StructureTypePushDescriptorSetWithTemplateInfo -> 1000545006
    StructureTypeSetDescriptorBufferOffsetsInfoEXT -> 1000545007
    StructureTypeBindDescriptorBufferEmbeddedSamplersInfoEXT -> 1000545008
    StructureTypePhysicalDeviceMaintenance7FeaturesKHR -> 1000562000
    StructureTypePhysicalDeviceMaintenance7PropertiesKHR -> 1000562001
    StructureTypePhysicalDeviceLayeredApiPropertiesListKHR -> 1000562002
    StructureTypePhysicalDeviceLayeredApiPropertiesKHR -> 1000562003
    StructureTypePhysicalDeviceLayeredApiVulkanPropertiesKHR -> 1000562004
    StructureTypeIndirectCommandsLayoutCreateInfoEXT -> 1000572006
    StructureTypeIndirectCommandsLayoutTokenEXT -> 1000572007
    StructureTypePhysicalDeviceMaintenance8FeaturesKHR -> 1000574000
    StructureTypeMemoryBarrierAccessFlags3KHR -> 1000574002
  fromWire = \case
    0 -> Just StructureTypeApplicationInfo
    1 -> Just StructureTypeInstanceCreateInfo
    2 -> Just StructureTypeDeviceQueueCreateInfo
    3 -> Just StructureTypeDeviceCreateInfo
    4 -> Just StructureTypeSubmitInfo
    5 -> Just StructureTypeMemoryAllocateInfo
    6 -> Just StructureTypeMappedMemoryRange
    7 -> Just StructureTypeBindSparseInfo
    8 -> Just StructureTypeFenceCreateInfo
    9 -> Just StructureTypeSemaphoreCreateInfo
    10 -> Just StructureTypeEventCreateInfo
    11 -> Just StructureTypeQueryPoolCreateInfo
    12 -> Just StructureTypeBufferCreateInfo
    13 -> Just StructureTypeBufferViewCreateInfo
    14 -> Just StructureTypeImageCreateInfo
    15 -> Just StructureTypeImageViewCreateInfo
    16 -> Just StructureTypeShaderModuleCreateInfo
    17 -> Just StructureTypePipelineCacheCreateInfo
    18 -> Just StructureTypePipelineShaderStageCreateInfo
    19 -> Just StructureTypePipelineVertexInputStateCreateInfo
    20 -> Just StructureTypePipelineInputAssemblyStateCreateInfo
    21 -> Just StructureTypePipelineTessellationStateCreateInfo
    22 -> Just StructureTypePipelineViewportStateCreateInfo
    23 -> Just StructureTypePipelineRasterizationStateCreateInfo
    24 -> Just StructureTypePipelineMultisampleStateCreateInfo
    25 -> Just StructureTypePipelineDepthStencilStateCreateInfo
    26 -> Just StructureTypePipelineColorBlendStateCreateInfo
    27 -> Just StructureTypePipelineDynamicStateCreateInfo
    28 -> Just StructureTypeGraphicsPipelineCreateInfo
    29 -> Just StructureTypeComputePipelineCreateInfo
    30 -> Just StructureTypePipelineLayoutCreateInfo
    31 -> Just StructureTypeSamplerCreateInfo
    32 -> Just StructureTypeDescriptorSetLayoutCreateInfo
    33 -> Just StructureTypeDescriptorPoolCreateInfo
    34 -> Just StructureTypeDescriptorSetAllocateInfo
    35 -> Just StructureTypeWriteDescriptorSet
    36 -> Just StructureTypeCopyDescriptorSet
    37 -> Just StructureTypeFramebufferCreateInfo
    38 -> Just StructureTypeRenderPassCreateInfo
    39 -> Just StructureTypeCommandPoolCreateInfo
    40 -> Just StructureTypeCommandBufferAllocateInfo
    41 -> Just StructureTypeCommandBufferInheritanceInfo
    42 -> Just StructureTypeCommandBufferBeginInfo
    43 -> Just StructureTypeRenderPassBeginInfo
    44 -> Just StructureTypeBufferMemoryBarrier
    45 -> Just StructureTypeImageMemoryBarrier
    46 -> Just StructureTypeMemoryBarrier
    47 -> Just StructureTypeLoaderInstanceCreateInfo
    48 -> Just StructureTypeLoaderDeviceCreateInfo
    49 -> Just StructureTypePhysicalDeviceVulkan11Features
    50 -> Just StructureTypePhysicalDeviceVulkan11Properties
    51 -> Just StructureTypePhysicalDeviceVulkan12Features
    52 -> Just StructureTypePhysicalDeviceVulkan12Properties
    53 -> Just StructureTypePhysicalDeviceVulkan13Features
    54 -> Just StructureTypePhysicalDeviceVulkan13Properties
    55 -> Just StructureTypePhysicalDeviceVulkan14Features
    56 -> Just StructureTypePhysicalDeviceVulkan14Properties
    1000001000 -> Just StructureTypeSwapchainCreateInfoKHR
    1000001001 -> Just StructureTypePresentInfoKHR
    1000002000 -> Just StructureTypeDisplayModeCreateInfoKHR
    1000002001 -> Just StructureTypeDisplaySurfaceCreateInfoKHR
    1000004000 -> Just StructureTypeXlibSurfaceCreateInfoKHR
    1000005000 -> Just StructureTypeXcbSurfaceCreateInfoKHR
    1000006000 -> Just StructureTypeWaylandSurfaceCreateInfoKHR
    1000009000 -> Just StructureTypeWin32SurfaceCreateInfoKHR
    1000044000 -> Just StructureTypeRenderingInfo
    1000044001 -> Just StructureTypeRenderingAttachmentInfo
    1000044002 -> Just StructureTypePipelineRenderingCreateInfo
    1000044003 -> Just StructureTypePhysicalDeviceDynamicRenderingFeatures
    1000044004 -> Just StructureTypeCommandBufferInheritanceRenderingInfo
    1000044006 -> Just StructureTypeRenderingFragmentShadingRateAttachmentInfoKHR
    1000053000 -> Just StructureTypeRenderPassMultiviewCreateInfo
    1000053001 -> Just StructureTypePhysicalDeviceMultiviewFeatures
    1000053002 -> Just StructureTypePhysicalDeviceMultiviewProperties
    1000059000 -> Just StructureTypePhysicalDeviceFeatures2
    1000059001 -> Just StructureTypePhysicalDeviceProperties2
    1000059002 -> Just StructureTypeFormatProperties2
    1000059003 -> Just StructureTypeImageFormatProperties2
    1000059004 -> Just StructureTypePhysicalDeviceImageFormatInfo2
    1000059005 -> Just StructureTypeQueueFamilyProperties2
    1000059006 -> Just StructureTypePhysicalDeviceMemoryProperties2
    1000059007 -> Just StructureTypeSparseImageFormatProperties2
    1000059008 -> Just StructureTypePhysicalDeviceSparseImageFormatInfo2
    1000060000 -> Just StructureTypeMemoryAllocateFlagsInfo
    1000060003 -> Just StructureTypeDeviceGroupRenderPassBeginInfo
    1000060004 -> Just StructureTypeDeviceGroupCommandBufferBeginInfo
    1000060005 -> Just StructureTypeDeviceGroupSubmitInfo
    1000060006 -> Just StructureTypeDeviceGroupBindSparseInfo
    1000060007 -> Just StructureTypeDeviceGroupPresentCapabilitiesKHR
    1000060008 -> Just StructureTypeImageSwapchainCreateInfoKHR
    1000060009 -> Just StructureTypeBindImageMemorySwapchainInfoKHR
    1000060010 -> Just StructureTypeAcquireNextImageInfoKHR
    1000060011 -> Just StructureTypeDeviceGroupPresentInfoKHR
    1000060012 -> Just StructureTypeDeviceGroupSwapchainCreateInfoKHR
    1000060013 -> Just StructureTypeBindBufferMemoryDeviceGroupInfo
    1000060014 -> Just StructureTypeBindImageMemoryDeviceGroupInfo
    1000063000 -> Just StructureTypePhysicalDeviceShaderDrawParametersFeatures
    1000066000 -> Just StructureTypePhysicalDeviceTextureCompressionAstcHdrFeatures
    1000068000 -> Just StructureTypePipelineRobustnessCreateInfo
    1000068001 -> Just StructureTypePhysicalDevicePipelineRobustnessFeatures
    1000068002 -> Just StructureTypePhysicalDevicePipelineRobustnessProperties
    1000070000 -> Just StructureTypePhysicalDeviceGroupProperties
    1000070001 -> Just StructureTypeDeviceGroupDeviceCreateInfo
    1000071000 -> Just StructureTypePhysicalDeviceExternalImageFormatInfo
    1000071001 -> Just StructureTypeExternalImageFormatProperties
    1000071002 -> Just StructureTypePhysicalDeviceExternalBufferInfo
    1000071003 -> Just StructureTypeExternalBufferProperties
    1000071004 -> Just StructureTypePhysicalDeviceIdProperties
    1000072000 -> Just StructureTypeExternalMemoryBufferCreateInfo
    1000072001 -> Just StructureTypeExternalMemoryImageCreateInfo
    1000072002 -> Just StructureTypeExportMemoryAllocateInfo
    1000073000 -> Just StructureTypeImportMemoryWin32HandleInfoKHR
    1000073001 -> Just StructureTypeExportMemoryWin32HandleInfoKHR
    1000073002 -> Just StructureTypeMemoryWin32HandlePropertiesKHR
    1000073003 -> Just StructureTypeMemoryGetWin32HandleInfoKHR
    1000074000 -> Just StructureTypeImportMemoryFdInfoKHR
    1000074001 -> Just StructureTypeMemoryFdPropertiesKHR
    1000074002 -> Just StructureTypeMemoryGetFdInfoKHR
    1000076000 -> Just StructureTypePhysicalDeviceExternalSemaphoreInfo
    1000076001 -> Just StructureTypeExternalSemaphoreProperties
    1000077000 -> Just StructureTypeExportSemaphoreCreateInfo
    1000078000 -> Just StructureTypeImportSemaphoreWin32HandleInfoKHR
    1000078001 -> Just StructureTypeExportSemaphoreWin32HandleInfoKHR
    1000078002 -> Just StructureTypeD3D12FenceSubmitInfoKHR
    1000078003 -> Just StructureTypeSemaphoreGetWin32HandleInfoKHR
    1000079000 -> Just StructureTypeImportSemaphoreFdInfoKHR
    1000079001 -> Just StructureTypeSemaphoreGetFdInfoKHR
    1000080000 -> Just StructureTypePhysicalDevicePushDescriptorProperties
    1000082000 -> Just StructureTypePhysicalDeviceShaderFloat16Int8Features
    1000083000 -> Just StructureTypePhysicalDevice16BitStorageFeatures
    1000085000 -> Just StructureTypeDescriptorUpdateTemplateCreateInfo
    1000094000 -> Just StructureTypePhysicalDeviceSubgroupProperties
    1000101000 -> Just StructureTypePhysicalDeviceConservativeRasterizationPropertiesEXT
    1000101001 -> Just StructureTypePipelineRasterizationConservativeStateCreateInfoEXT
    1000105000 -> Just StructureTypeHdrMetadataEXT
    1000108000 -> Just StructureTypePhysicalDeviceImagelessFramebufferFeatures
    1000108001 -> Just StructureTypeFramebufferAttachmentsCreateInfo
    1000108002 -> Just StructureTypeFramebufferAttachmentImageInfo
    1000108003 -> Just StructureTypeRenderPassAttachmentBeginInfo
    1000109000 -> Just StructureTypeAttachmentDescription2
    1000109001 -> Just StructureTypeAttachmentReference2
    1000109002 -> Just StructureTypeSubpassDescription2
    1000109003 -> Just StructureTypeSubpassDependency2
    1000109004 -> Just StructureTypeRenderPassCreateInfo2
    1000109005 -> Just StructureTypeSubpassBeginInfo
    1000109006 -> Just StructureTypeSubpassEndInfo
    1000112000 -> Just StructureTypePhysicalDeviceExternalFenceInfo
    1000112001 -> Just StructureTypeExternalFenceProperties
    1000113000 -> Just StructureTypeExportFenceCreateInfo
    1000114000 -> Just StructureTypeImportFenceWin32HandleInfoKHR
    1000114001 -> Just StructureTypeExportFenceWin32HandleInfoKHR
    1000114002 -> Just StructureTypeFenceGetWin32HandleInfoKHR
    1000115000 -> Just StructureTypeImportFenceFdInfoKHR
    1000115001 -> Just StructureTypeFenceGetFdInfoKHR
    1000116000 -> Just StructureTypePhysicalDevicePerformanceQueryFeaturesKHR
    1000116001 -> Just StructureTypePhysicalDevicePerformanceQueryPropertiesKHR
    1000116002 -> Just StructureTypeQueryPoolPerformanceCreateInfoKHR
    1000116003 -> Just StructureTypePerformanceQuerySubmitInfoKHR
    1000116004 -> Just StructureTypeAcquireProfilingLockInfoKHR
    1000116005 -> Just StructureTypePerformanceCounterKHR
    1000116006 -> Just StructureTypePerformanceCounterDescriptionKHR
    1000117000 -> Just StructureTypePhysicalDevicePointClippingProperties
    1000117001 -> Just StructureTypeRenderPassInputAttachmentAspectCreateInfo
    1000117002 -> Just StructureTypeImageViewUsageCreateInfo
    1000117003 -> Just StructureTypePipelineTessellationDomainOriginStateCreateInfo
    1000119000 -> Just StructureTypePhysicalDeviceSurfaceInfo2KHR
    1000119001 -> Just StructureTypeSurfaceCapabilities2KHR
    1000119002 -> Just StructureTypeSurfaceFormat2KHR
    1000120000 -> Just StructureTypePhysicalDeviceVariablePointersFeatures
    1000121000 -> Just StructureTypeDisplayProperties2KHR
    1000121001 -> Just StructureTypeDisplayPlaneProperties2KHR
    1000121002 -> Just StructureTypeDisplayModeProperties2KHR
    1000121003 -> Just StructureTypeDisplayPlaneInfo2KHR
    1000121004 -> Just StructureTypeDisplayPlaneCapabilities2KHR
    1000127000 -> Just StructureTypeMemoryDedicatedRequirements
    1000127001 -> Just StructureTypeMemoryDedicatedAllocateInfo
    1000128000 -> Just StructureTypeDebugUtilsObjectNameInfoEXT
    1000128001 -> Just StructureTypeDebugUtilsObjectTagInfoEXT
    1000128002 -> Just StructureTypeDebugUtilsLabelEXT
    1000128003 -> Just StructureTypeDebugUtilsMessengerCallbackDataEXT
    1000128004 -> Just StructureTypeDebugUtilsMessengerCreateInfoEXT
    1000130000 -> Just StructureTypePhysicalDeviceSamplerFilterMinmaxProperties
    1000130001 -> Just StructureTypeSamplerReductionModeCreateInfo
    1000134003 -> Just StructureTypeExecutionGraphPipelineCreateInfoAMDX
    1000135000 -> Just StructureTypeTexelBufferDescriptorInfoEXT
    1000135001 -> Just StructureTypeImageDescriptorInfoEXT
    1000135002 -> Just StructureTypeResourceDescriptorInfoEXT
    1000138000 -> Just StructureTypePhysicalDeviceInlineUniformBlockFeatures
    1000138001 -> Just StructureTypePhysicalDeviceInlineUniformBlockProperties
    1000138002 -> Just StructureTypeWriteDescriptorSetInlineUniformBlock
    1000138003 -> Just StructureTypeDescriptorPoolInlineUniformBlockCreateInfo
    1000143000 -> Just StructureTypeSampleLocationsInfoEXT
    1000143001 -> Just StructureTypeRenderPassSampleLocationsBeginInfoEXT
    1000143002 -> Just StructureTypePipelineSampleLocationsStateCreateInfoEXT
    1000143003 -> Just StructureTypePhysicalDeviceSampleLocationsPropertiesEXT
    1000143004 -> Just StructureTypeMultisamplePropertiesEXT
    1000145000 -> Just StructureTypeProtectedSubmitInfo
    1000145001 -> Just StructureTypePhysicalDeviceProtectedMemoryFeatures
    1000145002 -> Just StructureTypePhysicalDeviceProtectedMemoryProperties
    1000145003 -> Just StructureTypeDeviceQueueInfo2
    1000146000 -> Just StructureTypeBufferMemoryRequirementsInfo2
    1000146001 -> Just StructureTypeImageMemoryRequirementsInfo2
    1000146002 -> Just StructureTypeImageSparseMemoryRequirementsInfo2
    1000146003 -> Just StructureTypeMemoryRequirements2
    1000146004 -> Just StructureTypeSparseImageMemoryRequirements2
    1000147000 -> Just StructureTypeImageFormatListCreateInfo
    1000150000 -> Just StructureTypeAccelerationStructureBuildGeometryInfoKHR
    1000150002 -> Just StructureTypeAccelerationStructureDeviceAddressInfoKHR
    1000150003 -> Just StructureTypeAccelerationStructureGeometryAabbsDataKHR
    1000150004 -> Just StructureTypeAccelerationStructureGeometryInstancesDataKHR
    1000150005 -> Just StructureTypeAccelerationStructureGeometryTrianglesDataKHR
    1000150006 -> Just StructureTypeAccelerationStructureGeometryKHR
    1000150007 -> Just StructureTypeWriteDescriptorSetAccelerationStructureKHR
    1000150009 -> Just StructureTypeAccelerationStructureVersionInfoKHR
    1000150010 -> Just StructureTypeCopyAccelerationStructureInfoKHR
    1000150011 -> Just StructureTypeCopyAccelerationStructureToMemoryInfoKHR
    1000150012 -> Just StructureTypeCopyMemoryToAccelerationStructureInfoKHR
    1000150013 -> Just StructureTypePhysicalDeviceAccelerationStructureFeaturesKHR
    1000150014 -> Just StructureTypePhysicalDeviceAccelerationStructurePropertiesKHR
    1000150015 -> Just StructureTypeRayTracingPipelineCreateInfoKHR
    1000150016 -> Just StructureTypeRayTracingShaderGroupCreateInfoKHR
    1000150017 -> Just StructureTypeAccelerationStructureCreateInfoKHR
    1000150018 -> Just StructureTypeRayTracingPipelineInterfaceCreateInfoKHR
    1000150020 -> Just StructureTypeAccelerationStructureBuildSizesInfoKHR
    1000156000 -> Just StructureTypeSamplerYcbcrConversionCreateInfo
    1000156001 -> Just StructureTypeSamplerYcbcrConversionInfo
    1000156002 -> Just StructureTypeBindImagePlaneMemoryInfo
    1000156003 -> Just StructureTypeImagePlaneMemoryRequirementsInfo
    1000156004 -> Just StructureTypePhysicalDeviceSamplerYcbcrConversionFeatures
    1000156005 -> Just StructureTypeSamplerYcbcrConversionImageFormatProperties
    1000157000 -> Just StructureTypeBindBufferMemoryInfo
    1000157001 -> Just StructureTypeBindImageMemoryInfo
    1000158000 -> Just StructureTypeDrmFormatModifierPropertiesListEXT
    1000158002 -> Just StructureTypePhysicalDeviceImageDrmFormatModifierInfoEXT
    1000158003 -> Just StructureTypeImageDrmFormatModifierListCreateInfoEXT
    1000158004 -> Just StructureTypeImageDrmFormatModifierExplicitCreateInfoEXT
    1000158005 -> Just StructureTypeImageDrmFormatModifierPropertiesEXT
    1000158006 -> Just StructureTypeDrmFormatModifierPropertiesList2EXT
    1000161000 -> Just StructureTypeDescriptorSetLayoutBindingFlagsCreateInfo
    1000161001 -> Just StructureTypePhysicalDeviceDescriptorIndexingFeatures
    1000161002 -> Just StructureTypePhysicalDeviceDescriptorIndexingProperties
    1000161003 -> Just StructureTypeDescriptorSetVariableDescriptorCountAllocateInfo
    1000161004 -> Just StructureTypeDescriptorSetVariableDescriptorCountLayoutSupport
    1000163000 -> Just StructureTypePhysicalDevicePortabilitySubsetFeaturesKHR
    1000163001 -> Just StructureTypePhysicalDevicePortabilitySubsetPropertiesKHR
    1000165000 -> Just StructureTypeRayTracingPipelineCreateInfoNV
    1000165001 -> Just StructureTypeAccelerationStructureCreateInfoNV
    1000165003 -> Just StructureTypeGeometryNV
    1000165004 -> Just StructureTypeGeometryTrianglesNV
    1000165005 -> Just StructureTypeGeometryAabbNV
    1000165011 -> Just StructureTypeRayTracingShaderGroupCreateInfoNV
    1000165012 -> Just StructureTypeAccelerationStructureInfoNV
    1000168000 -> Just StructureTypePhysicalDeviceMaintenance3Properties
    1000168001 -> Just StructureTypeDescriptorSetLayoutSupport
    1000174000 -> Just StructureTypeDeviceQueueGlobalPriorityCreateInfo
    1000175000 -> Just StructureTypePhysicalDeviceShaderSubgroupExtendedTypesFeatures
    1000177000 -> Just StructureTypePhysicalDevice8BitStorageFeatures
    1000178000 -> Just StructureTypeImportMemoryHostPointerInfoEXT
    1000178001 -> Just StructureTypeMemoryHostPointerPropertiesEXT
    1000178002 -> Just StructureTypePhysicalDeviceExternalMemoryHostPropertiesEXT
    1000180000 -> Just StructureTypePhysicalDeviceShaderAtomicInt64Features
    1000181000 -> Just StructureTypePhysicalDeviceShaderClockFeaturesKHR
    1000184000 -> Just StructureTypeCalibratedTimestampInfoKHR
    1000190001 -> Just StructureTypePipelineVertexInputDivisorStateCreateInfo
    1000190002 -> Just StructureTypePhysicalDeviceVertexAttributeDivisorFeatures
    1000192000 -> Just StructureTypePipelineCreationFeedbackCreateInfo
    1000196000 -> Just StructureTypePhysicalDeviceDriverProperties
    1000197000 -> Just StructureTypePhysicalDeviceFloatControlsProperties
    1000199000 -> Just StructureTypePhysicalDeviceDepthStencilResolveProperties
    1000199001 -> Just StructureTypeSubpassDescriptionDepthStencilResolve
    1000201000 -> Just StructureTypePhysicalDeviceComputeShaderDerivativesFeaturesKHR
    1000203000 -> Just StructureTypePhysicalDeviceFragmentShaderBarycentricFeaturesKHR
    1000207000 -> Just StructureTypePhysicalDeviceTimelineSemaphoreFeatures
    1000207001 -> Just StructureTypePhysicalDeviceTimelineSemaphoreProperties
    1000207002 -> Just StructureTypeSemaphoreTypeCreateInfo
    1000207003 -> Just StructureTypeTimelineSemaphoreSubmitInfo
    1000207004 -> Just StructureTypeSemaphoreWaitInfo
    1000207005 -> Just StructureTypeSemaphoreSignalInfo
    1000211000 -> Just StructureTypePhysicalDeviceVulkanMemoryModelFeatures
    1000215000 -> Just StructureTypePhysicalDeviceShaderTerminateInvocationFeatures
    1000217000 -> Just StructureTypeMetalSurfaceCreateInfoEXT
    1000221000 -> Just StructureTypePhysicalDeviceScalarBlockLayoutFeatures
    1000225000 -> Just StructureTypePhysicalDeviceSubgroupSizeControlProperties
    1000225001 -> Just StructureTypePipelineShaderStageRequiredSubgroupSizeCreateInfo
    1000225002 -> Just StructureTypePhysicalDeviceSubgroupSizeControlFeatures
    1000226000 -> Just StructureTypeFragmentShadingRateAttachmentInfoKHR
    1000226001 -> Just StructureTypePipelineFragmentShadingRateStateCreateInfoKHR
    1000226002 -> Just StructureTypePhysicalDeviceFragmentShadingRatePropertiesKHR
    1000226003 -> Just StructureTypePhysicalDeviceFragmentShadingRateFeaturesKHR
    1000226004 -> Just StructureTypePhysicalDeviceFragmentShadingRateKHR
    1000232000 -> Just StructureTypePhysicalDeviceDynamicRenderingLocalReadFeatures
    1000232001 -> Just StructureTypeRenderingAttachmentLocationInfo
    1000232002 -> Just StructureTypeRenderingInputAttachmentIndexInfo
    1000234000 -> Just StructureTypePhysicalDeviceShaderImageAtomicInt64FeaturesEXT
    1000235000 -> Just StructureTypePhysicalDeviceShaderQuadControlFeaturesKHR
    1000237000 -> Just StructureTypePhysicalDeviceMemoryBudgetPropertiesEXT
    1000238000 -> Just StructureTypePhysicalDeviceMemoryPriorityFeaturesEXT
    1000238001 -> Just StructureTypeMemoryPriorityAllocateInfoEXT
    1000241000 -> Just StructureTypePhysicalDeviceSeparateDepthStencilLayoutsFeatures
    1000241001 -> Just StructureTypeAttachmentReferenceStencilLayout
    1000241002 -> Just StructureTypeAttachmentDescriptionStencilLayout
    1000244001 -> Just StructureTypeBufferDeviceAddressInfo
    1000245000 -> Just StructureTypePhysicalDeviceToolProperties
    1000246000 -> Just StructureTypeImageStencilUsageCreateInfo
    1000248000 -> Just StructureTypePhysicalDevicePresentWaitFeaturesKHR
    1000253000 -> Just StructureTypePhysicalDeviceUniformBufferStandardLayoutFeatures
    1000255000 -> Just StructureTypeSurfaceFullScreenExclusiveInfoEXT
    1000255001 -> Just StructureTypeSurfaceFullScreenExclusiveWin32InfoEXT
    1000255002 -> Just StructureTypeSurfaceCapabilitiesFullScreenExclusiveEXT
    1000256000 -> Just StructureTypeHeadlessSurfaceCreateInfoEXT
    1000257000 -> Just StructureTypePhysicalDeviceBufferDeviceAddressFeatures
    1000257002 -> Just StructureTypeBufferOpaqueCaptureAddressCreateInfo
    1000257003 -> Just StructureTypeMemoryOpaqueCaptureAddressAllocateInfo
    1000257004 -> Just StructureTypeDeviceMemoryOpaqueCaptureAddressInfo
    1000259000 -> Just StructureTypePhysicalDeviceLineRasterizationFeatures
    1000259001 -> Just StructureTypePipelineRasterizationLineStateCreateInfo
    1000259002 -> Just StructureTypePhysicalDeviceLineRasterizationProperties
    1000261000 -> Just StructureTypePhysicalDeviceHostQueryResetFeatures
    1000265000 -> Just StructureTypePhysicalDeviceIndexTypeUint8Features
    1000269000 -> Just StructureTypePhysicalDevicePipelineExecutablePropertiesFeaturesKHR
    1000269001 -> Just StructureTypePipelineInfoKHR
    1000269002 -> Just StructureTypePipelineExecutablePropertiesKHR
    1000269003 -> Just StructureTypePipelineExecutableInfoKHR
    1000269004 -> Just StructureTypePipelineExecutableStatisticKHR
    1000269005 -> Just StructureTypePipelineExecutableInternalRepresentationKHR
    1000270000 -> Just StructureTypePhysicalDeviceHostImageCopyFeatures
    1000270001 -> Just StructureTypePhysicalDeviceHostImageCopyProperties
    1000270002 -> Just StructureTypeMemoryToImageCopy
    1000270003 -> Just StructureTypeImageToMemoryCopy
    1000270004 -> Just StructureTypeCopyImageToMemoryInfo
    1000270005 -> Just StructureTypeCopyMemoryToImageInfo
    1000270006 -> Just StructureTypeHostImageLayoutTransitionInfo
    1000270007 -> Just StructureTypeCopyImageToImageInfo
    1000270008 -> Just StructureTypeSubresourceHostMemcpySize
    1000270009 -> Just StructureTypeHostImageCopyDevicePerformanceQuery
    1000271000 -> Just StructureTypeMemoryMapInfo
    1000271001 -> Just StructureTypeMemoryUnmapInfo
    1000276000 -> Just StructureTypePhysicalDeviceShaderDemoteToHelperInvocationFeatures
    1000280000 -> Just StructureTypePhysicalDeviceShaderIntegerDotProductFeatures
    1000280001 -> Just StructureTypePhysicalDeviceShaderIntegerDotProductProperties
    1000281001 -> Just StructureTypePhysicalDeviceTexelBufferAlignmentProperties
    1000290000 -> Just StructureTypePipelineLibraryCreateInfoKHR
    1000294000 -> Just StructureTypePresentIdKHR
    1000294001 -> Just StructureTypePhysicalDevicePresentIdFeaturesKHR
    1000295000 -> Just StructureTypePhysicalDevicePrivateDataFeatures
    1000295001 -> Just StructureTypeDevicePrivateDataCreateInfo
    1000295002 -> Just StructureTypePrivateDataSlotCreateInfo
    1000297000 -> Just StructureTypePhysicalDevicePipelineCreationCacheControlFeatures
    1000314000 -> Just StructureTypeMemoryBarrier2
    1000314001 -> Just StructureTypeBufferMemoryBarrier2
    1000314002 -> Just StructureTypeImageMemoryBarrier2
    1000314003 -> Just StructureTypeDependencyInfo
    1000314004 -> Just StructureTypeSubmitInfo2
    1000314005 -> Just StructureTypeSemaphoreSubmitInfo
    1000314006 -> Just StructureTypeCommandBufferSubmitInfo
    1000314007 -> Just StructureTypePhysicalDeviceSynchronization2Features
    1000316000 -> Just StructureTypePhysicalDeviceDescriptorBufferPropertiesEXT
    1000316001 -> Just StructureTypePhysicalDeviceDescriptorBufferDensityMapPropertiesEXT
    1000316002 -> Just StructureTypePhysicalDeviceDescriptorBufferFeaturesEXT
    1000316003 -> Just StructureTypeDescriptorAddressInfoEXT
    1000316004 -> Just StructureTypeDescriptorGetInfoEXT
    1000316005 -> Just StructureTypeBufferCaptureDescriptorDataInfoEXT
    1000316006 -> Just StructureTypeImageCaptureDescriptorDataInfoEXT
    1000316007 -> Just StructureTypeImageViewCaptureDescriptorDataInfoEXT
    1000316008 -> Just StructureTypeSamplerCaptureDescriptorDataInfoEXT
    1000316009 -> Just StructureTypeAccelerationStructureCaptureDescriptorDataInfoEXT
    1000316010 -> Just StructureTypeOpaqueCaptureDescriptorDataCreateInfoEXT
    1000316011 -> Just StructureTypeDescriptorBufferBindingInfoEXT
    1000316012 -> Just StructureTypeDescriptorBufferBindingPushDescriptorBufferHandleEXT
    1000318004 -> Just StructureTypeMemoryRangeBarriersInfoKHR
    1000318005 -> Just StructureTypeMemoryRangeBarrierKHR
    1000318015 -> Just StructureTypeAccelerationStructureCreateInfo2KHR
    1000320000 -> Just StructureTypePhysicalDeviceGraphicsPipelineLibraryFeaturesEXT
    1000320001 -> Just StructureTypePhysicalDeviceGraphicsPipelineLibraryPropertiesEXT
    1000320002 -> Just StructureTypeGraphicsPipelineLibraryCreateInfoEXT
    1000323000 -> Just StructureTypePhysicalDeviceShaderSubgroupUniformControlFlowFeaturesKHR
    1000325000 -> Just StructureTypePhysicalDeviceZeroInitializeWorkgroupMemoryFeatures
    1000328000 -> Just StructureTypePhysicalDeviceMeshShaderFeaturesEXT
    1000328001 -> Just StructureTypePhysicalDeviceMeshShaderPropertiesEXT
    1000335000 -> Just StructureTypePhysicalDeviceImageRobustnessFeatures
    1000336000 -> Just StructureTypePhysicalDeviceWorkgroupMemoryExplicitLayoutFeaturesKHR
    1000337000 -> Just StructureTypeCopyBufferInfo2
    1000337001 -> Just StructureTypeCopyImageInfo2
    1000337002 -> Just StructureTypeCopyBufferToImageInfo2
    1000337003 -> Just StructureTypeCopyImageToBufferInfo2
    1000337004 -> Just StructureTypeBlitImageInfo2
    1000337005 -> Just StructureTypeResolveImageInfo2
    1000337006 -> Just StructureTypeBufferCopy2
    1000337007 -> Just StructureTypeImageCopy2
    1000337008 -> Just StructureTypeImageBlit2
    1000337009 -> Just StructureTypeBufferImageCopy2
    1000337010 -> Just StructureTypeImageResolve2
    1000338002 -> Just StructureTypeSubresourceLayout2
    1000338003 -> Just StructureTypeImageSubresource2
    1000341000 -> Just StructureTypePhysicalDeviceFaultFeaturesEXT
    1000341001 -> Just StructureTypeDeviceFaultCountsEXT
    1000341002 -> Just StructureTypeDeviceFaultInfoEXT
    1000347000 -> Just StructureTypePhysicalDeviceRayTracingPipelineFeaturesKHR
    1000347001 -> Just StructureTypePhysicalDeviceRayTracingPipelinePropertiesKHR
    1000348013 -> Just StructureTypePhysicalDeviceRayQueryFeaturesKHR
    1000352000 -> Just StructureTypePhysicalDeviceVertexInputDynamicStateFeaturesEXT
    1000352001 -> Just StructureTypeVertexInputBindingDescription2EXT
    1000352002 -> Just StructureTypeVertexInputAttributeDescription2EXT
    1000354000 -> Just StructureTypePhysicalDeviceAddressBindingReportFeaturesEXT
    1000354001 -> Just StructureTypeDeviceAddressBindingCallbackDataEXT
    1000360000 -> Just StructureTypeFormatProperties3
    1000381000 -> Just StructureTypePhysicalDeviceColorWriteEnableFeaturesEXT
    1000381001 -> Just StructureTypePipelineColorWriteCreateInfoEXT
    1000386000 -> Just StructureTypePhysicalDeviceRayTracingMaintenance1FeaturesKHR
    1000388000 -> Just StructureTypePhysicalDeviceGlobalPriorityQueryFeatures
    1000388001 -> Just StructureTypeQueueFamilyGlobalPriorityProperties
    1000392000 -> Just StructureTypePhysicalDeviceMultiDrawFeaturesEXT
    1000392001 -> Just StructureTypePhysicalDeviceMultiDrawPropertiesEXT
    1000396000 -> Just StructureTypeMicromapBuildInfoEXT
    1000396001 -> Just StructureTypeMicromapVersionInfoEXT
    1000396002 -> Just StructureTypeCopyMicromapInfoEXT
    1000396003 -> Just StructureTypeCopyMicromapToMemoryInfoEXT
    1000396004 -> Just StructureTypeCopyMemoryToMicromapInfoEXT
    1000396005 -> Just StructureTypePhysicalDeviceOpacityMicromapFeaturesEXT
    1000396006 -> Just StructureTypePhysicalDeviceOpacityMicromapPropertiesEXT
    1000396007 -> Just StructureTypeMicromapCreateInfoEXT
    1000396008 -> Just StructureTypeMicromapBuildSizesInfoEXT
    1000396009 -> Just StructureTypeAccelerationStructureTrianglesOpacityMicromapEXT
    1000412000 -> Just StructureTypePhysicalDevicePageableDeviceLocalMemoryFeaturesEXT
    1000413000 -> Just StructureTypePhysicalDeviceMaintenance4Features
    1000413001 -> Just StructureTypePhysicalDeviceMaintenance4Properties
    1000413002 -> Just StructureTypeDeviceBufferMemoryRequirements
    1000413003 -> Just StructureTypeDeviceImageMemoryRequirements
    1000416000 -> Just StructureTypePhysicalDeviceShaderSubgroupRotateFeatures
    1000434000 -> Just StructureTypePhysicalDeviceShaderMaximalReconvergenceFeaturesKHR
    1000455000 -> Just StructureTypePhysicalDeviceExtendedDynamicState3FeaturesEXT
    1000455001 -> Just StructureTypePhysicalDeviceExtendedDynamicState3PropertiesEXT
    1000460000 -> Just StructureTypeTensorCreateInfoARM
    1000460001 -> Just StructureTypeTensorViewCreateInfoARM
    1000460006 -> Just StructureTypeTensorDescriptionARM
    1000466000 -> Just StructureTypePhysicalDevicePipelineProtectedAccessFeatures
    1000470000 -> Just StructureTypePhysicalDeviceMaintenance5Features
    1000470001 -> Just StructureTypePhysicalDeviceMaintenance5Properties
    1000470003 -> Just StructureTypeRenderingAreaInfo
    1000470004 -> Just StructureTypeDeviceImageSubresourceInfo
    1000470005 -> Just StructureTypePipelineCreateFlags2CreateInfo
    1000470006 -> Just StructureTypeBufferUsageFlags2CreateInfo
    1000478001 -> Just StructureTypeAccelerationStructureDenseGeometryFormatTrianglesDataAMDX
    1000481000 -> Just StructureTypePhysicalDeviceRayTracingPositionFetchFeaturesKHR
    1000482000 -> Just StructureTypePhysicalDeviceShaderObjectFeaturesEXT
    1000482001 -> Just StructureTypePhysicalDeviceShaderObjectPropertiesEXT
    1000482002 -> Just StructureTypeShaderCreateInfoEXT
    1000483000 -> Just StructureTypePhysicalDevicePipelineBinaryFeaturesKHR
    1000483001 -> Just StructureTypePipelineBinaryCreateInfoKHR
    1000483002 -> Just StructureTypePipelineBinaryInfoKHR
    1000483003 -> Just StructureTypePipelineBinaryKeyKHR
    1000483004 -> Just StructureTypePhysicalDevicePipelineBinaryPropertiesKHR
    1000483005 -> Just StructureTypeReleaseCapturedPipelineDataInfoKHR
    1000483006 -> Just StructureTypePipelineBinaryDataInfoKHR
    1000483007 -> Just StructureTypePipelineCreateInfoKHR
    1000483008 -> Just StructureTypeDevicePipelineBinaryInternalCacheControlKHR
    1000483009 -> Just StructureTypePipelineBinaryHandlesInfoKHR
    1000496000 -> Just StructureTypeLayerSettingsCreateInfoEXT
    1000499000 -> Just StructureTypePhysicalDeviceDynamicRenderingUnusedAttachmentsFeaturesEXT
    1000507000 -> Just StructureTypeDataGraphPipelineCreateInfoARM
    1000507002 -> Just StructureTypeDataGraphPipelineResourceInfoARM
    1000507003 -> Just StructureTypeDataGraphPipelineConstantARM
    1000511000 -> Just StructureTypePhysicalDeviceComputeShaderDerivativesPropertiesKHR
    1000525000 -> Just StructureTypePhysicalDeviceVertexAttributeDivisorProperties
    1000527000 -> Just StructureTypePhysicalDeviceUnifiedImageLayoutsFeaturesKHR
    1000528000 -> Just StructureTypePhysicalDeviceShaderFloatControls2Features
    1000544000 -> Just StructureTypePhysicalDeviceShaderExpectAssumeFeatures
    1000545000 -> Just StructureTypePhysicalDeviceMaintenance6Features
    1000545001 -> Just StructureTypePhysicalDeviceMaintenance6Properties
    1000545002 -> Just StructureTypeBindMemoryStatus
    1000545003 -> Just StructureTypeBindDescriptorSetsInfo
    1000545004 -> Just StructureTypePushConstantsInfo
    1000545005 -> Just StructureTypePushDescriptorSetInfo
    1000545006 -> Just StructureTypePushDescriptorSetWithTemplateInfo
    1000545007 -> Just StructureTypeSetDescriptorBufferOffsetsInfoEXT
    1000545008 -> Just StructureTypeBindDescriptorBufferEmbeddedSamplersInfoEXT
    1000562000 -> Just StructureTypePhysicalDeviceMaintenance7FeaturesKHR
    1000562001 -> Just StructureTypePhysicalDeviceMaintenance7PropertiesKHR
    1000562002 -> Just StructureTypePhysicalDeviceLayeredApiPropertiesListKHR
    1000562003 -> Just StructureTypePhysicalDeviceLayeredApiPropertiesKHR
    1000562004 -> Just StructureTypePhysicalDeviceLayeredApiVulkanPropertiesKHR
    1000572006 -> Just StructureTypeIndirectCommandsLayoutCreateInfoEXT
    1000572007 -> Just StructureTypeIndirectCommandsLayoutTokenEXT
    1000574000 -> Just StructureTypePhysicalDeviceMaintenance8FeaturesKHR
    1000574002 -> Just StructureTypeMemoryBarrierAccessFlags3KHR
    _ -> Nothing
