-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.EXT_external_memory_host (
  ImportMemoryHostPointerInfoEXT (..),
  MemoryHostPointerPropertiesEXT (..),
  PhysicalDeviceExternalMemoryHostPropertiesEXT (..),
  getMemoryHostPointerPropertiesEXT,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Handles
import Lithon.Vk.Core11.Enums.ExternalMemoryHandleTypeFlagBits
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImportMemoryHostPointerInfoEXT.html VkImportMemoryHostPointerInfoEXT>
-- Available: VK_EXT_external_memory_host
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @pHostPointer@ is deliberately un-modelled (raw pointer); see the module notes.
data ImportMemoryHostPointerInfoEXT = ImportMemoryHostPointerInfoEXT
  { handleType :: Flags ExternalMemoryHandleTypeFlagBits
  , pHostPointer :: Ptr ()
  }

instance CStruct ImportMemoryHostPointerInfoEXT where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000178000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.handleType)
    liftIO (pokeByteOff p 24 x.pHostPointer)
    pure ()

instance FromCStruct ImportMemoryHostPointerInfoEXT where
  peekCStruct p = do
    v_handleType <- (peekByteOff p 16)
    v_pHostPointer <- peekByteOff p 24
    pure ImportMemoryHostPointerInfoEXT{handleType = v_handleType, pHostPointer = v_pHostPointer}

instance Nil ImportMemoryHostPointerInfoEXT where
  nil =
    ImportMemoryHostPointerInfoEXT
      { handleType = mempty
      , pHostPointer = nullPtr
      }

instance Chainable ImportMemoryHostPointerInfoEXT where
  sTypeWire = 1000178000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkMemoryHostPointerPropertiesEXT.html VkMemoryHostPointerPropertiesEXT>
-- Available: VK_EXT_external_memory_host
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data MemoryHostPointerPropertiesEXT = MemoryHostPointerPropertiesEXT
  { memoryTypeBits :: Word32
  }

instance CStruct MemoryHostPointerPropertiesEXT where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000178001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.memoryTypeBits)
    pure ()

instance FromCStruct MemoryHostPointerPropertiesEXT where
  peekCStruct p = do
    v_memoryTypeBits <- (peekByteOff p 16)
    pure MemoryHostPointerPropertiesEXT{memoryTypeBits = v_memoryTypeBits}

instance Nil MemoryHostPointerPropertiesEXT where
  nil =
    MemoryHostPointerPropertiesEXT
      { memoryTypeBits = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceExternalMemoryHostPropertiesEXT.html VkPhysicalDeviceExternalMemoryHostPropertiesEXT>
-- Available: VK_EXT_external_memory_host
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceExternalMemoryHostPropertiesEXT = PhysicalDeviceExternalMemoryHostPropertiesEXT
  { minImportedHostPointerAlignment :: Word64
  }

instance CStruct PhysicalDeviceExternalMemoryHostPropertiesEXT where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000178002 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.minImportedHostPointerAlignment)
    pure ()

instance FromCStruct PhysicalDeviceExternalMemoryHostPropertiesEXT where
  peekCStruct p = do
    v_minImportedHostPointerAlignment <- (peekByteOff p 16)
    pure
      PhysicalDeviceExternalMemoryHostPropertiesEXT
        { minImportedHostPointerAlignment = v_minImportedHostPointerAlignment
        }

instance Nil PhysicalDeviceExternalMemoryHostPropertiesEXT where
  nil =
    PhysicalDeviceExternalMemoryHostPropertiesEXT
      { minImportedHostPointerAlignment = 0
      }

instance Chainable PhysicalDeviceExternalMemoryHostPropertiesEXT where
  sTypeWire = 1000178002
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetMemoryHostPointerPropertiesEXT.html vkGetMemoryHostPointerPropertiesEXT>
-- Available: VK_EXT_external_memory_host
getMemoryHostPointerPropertiesEXT
  :: forall m
   . (MonadIO m)
  => Device
  -> Flags ExternalMemoryHandleTypeFlagBits
  -> Ptr ()
  -> m (Outcome MemoryHostPointerPropertiesEXT)
getMemoryHostPointerPropertiesEXT device handleType hostPointer =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_o_memoryHostPointerProperties :: Ptr () <- castPtr <$> new (nil :: MemoryHostPointerPropertiesEXT)
    r_ <-
      liftIO
        ( mkGetMemoryHostPointerPropertiesEXT
            (checkCommandPtr "vkGetMemoryHostPointerPropertiesEXT" device.cmds.pGetMemoryHostPointerPropertiesEXT)
            (castPtr device.handle)
            ((\(Flags w) -> w) handleType)
            hostPointer
            p_o_memoryHostPointerProperties
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      o_memoryHostPointerProperties <- liftIO (peekCStruct (castPtr p_o_memoryHostPointerProperties))
      pure (Ok (openFromWire r_) o_memoryHostPointerProperties)
