-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.EXT_debug_utils (
  DebugUtilsMessageSeverityFlagBitsEXT (..),
  DebugUtilsMessageTypeFlagBitsEXT (..),
  DebugUtilsMessageSeverityFlagsEXT,
  DebugUtilsMessageTypeFlagsEXT,
  DebugUtilsMessengerCallbackDataFlagsEXT,
  DebugUtilsMessengerCallbackDataFlagsEXTBits,
  DebugUtilsMessengerCreateFlagsEXT,
  DebugUtilsMessengerCreateFlagsEXTBits,
  DebugUtilsMessengerEXT (..),
  DebugUtilsLabelEXT (..),
  DebugUtilsMessengerCallbackDataEXT (..),
  DebugUtilsMessengerCreateInfoEXT (..),
  DebugUtilsObjectNameInfoEXT (..),
  DebugUtilsObjectTagInfoEXT (..),
  FN_vkDebugUtilsMessengerCallbackEXT,
  PFN_vkDebugUtilsMessengerCallbackEXT,
  mkPFN_vkDebugUtilsMessengerCallbackEXT,
  cmdBeginDebugUtilsLabelEXT,
  cmdEndDebugUtilsLabelEXT,
  cmdInsertDebugUtilsLabelEXT,
  createDebugUtilsMessengerEXT,
  withDebugUtilsMessengerEXT,
  destroyDebugUtilsMessengerEXT,
  queueBeginDebugUtilsLabelEXT,
  queueEndDebugUtilsLabelEXT,
  queueInsertDebugUtilsLabelEXT,
  setDebugUtilsObjectNameEXT,
  setDebugUtilsObjectTagEXT,
  submitDebugUtilsMessageEXT,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Primitive.Types (Prim)
import Data.Vector qualified as V
import Data.Vector.Generic qualified as VG
import Data.Vector.Generic.Mutable qualified as VGM
import Data.Vector.Primitive qualified as P
import Data.Vector.Storable.Sized qualified as VSS
import Data.Vector.Unboxed qualified as VU
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable, peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)
import Lithon.Core.Unbox (UnboxViaPrim (..))

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.ObjectType
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsMessageSeverityFlagBitsEXT.html VkDebugUtilsMessageSeverityFlagBitsEXT>
-- Available: VK_EXT_debug_utils
data DebugUtilsMessageSeverityFlagBitsEXT
  = DebugUtilsMessageSeverityVerboseBitEXT
  | DebugUtilsMessageSeverityInfoBitEXT
  | DebugUtilsMessageSeverityWarningBitEXT
  | DebugUtilsMessageSeverityErrorBitEXT
  deriving stock (Eq, Ord, Show)

type instance FlagsWire DebugUtilsMessageSeverityFlagBitsEXT = Word32

instance BitPos DebugUtilsMessageSeverityFlagBitsEXT where
  bitOf = \case
    DebugUtilsMessageSeverityVerboseBitEXT -> Flags 0x1
    DebugUtilsMessageSeverityInfoBitEXT -> Flags 0x10
    DebugUtilsMessageSeverityWarningBitEXT -> Flags 0x100
    DebugUtilsMessageSeverityErrorBitEXT -> Flags 0x1000
  allBits =
    [ DebugUtilsMessageSeverityVerboseBitEXT
    , DebugUtilsMessageSeverityInfoBitEXT
    , DebugUtilsMessageSeverityWarningBitEXT
    , DebugUtilsMessageSeverityErrorBitEXT
    ]

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsMessageTypeFlagBitsEXT.html VkDebugUtilsMessageTypeFlagBitsEXT>
-- Available: VK_EXT_debug_utils
data DebugUtilsMessageTypeFlagBitsEXT
  = DebugUtilsMessageTypeGeneralBitEXT
  | DebugUtilsMessageTypeValidationBitEXT
  | DebugUtilsMessageTypePerformanceBitEXT
  | DebugUtilsMessageTypeDeviceAddressBindingBitEXT
  deriving stock (Eq, Ord, Show)

type instance FlagsWire DebugUtilsMessageTypeFlagBitsEXT = Word32

instance BitPos DebugUtilsMessageTypeFlagBitsEXT where
  bitOf = \case
    DebugUtilsMessageTypeGeneralBitEXT -> Flags 0x1
    DebugUtilsMessageTypeValidationBitEXT -> Flags 0x2
    DebugUtilsMessageTypePerformanceBitEXT -> Flags 0x4
    DebugUtilsMessageTypeDeviceAddressBindingBitEXT -> Flags 0x8
  allBits =
    [ DebugUtilsMessageTypeGeneralBitEXT
    , DebugUtilsMessageTypeValidationBitEXT
    , DebugUtilsMessageTypePerformanceBitEXT
    , DebugUtilsMessageTypeDeviceAddressBindingBitEXT
    ]

type DebugUtilsMessageSeverityFlagsEXT = Flags DebugUtilsMessageSeverityFlagBitsEXT

type DebugUtilsMessageTypeFlagsEXT = Flags DebugUtilsMessageTypeFlagBitsEXT

-- | Reserved-empty mask: no bits are defined yet.
data DebugUtilsMessengerCallbackDataFlagsEXTBits
  deriving stock (Eq, Ord, Show)

type instance FlagsWire DebugUtilsMessengerCallbackDataFlagsEXTBits = Word32

instance BitPos DebugUtilsMessengerCallbackDataFlagsEXTBits where
  bitOf = \case {}
  allBits = []

type DebugUtilsMessengerCallbackDataFlagsEXT = Flags DebugUtilsMessengerCallbackDataFlagsEXTBits

-- | Reserved-empty mask: no bits are defined yet.
data DebugUtilsMessengerCreateFlagsEXTBits
  deriving stock (Eq, Ord, Show)

type instance FlagsWire DebugUtilsMessengerCreateFlagsEXTBits = Word32

instance BitPos DebugUtilsMessengerCreateFlagsEXTBits where
  bitOf = \case {}
  allBits = []

type DebugUtilsMessengerCreateFlagsEXT = Flags DebugUtilsMessengerCreateFlagsEXTBits

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsMessengerEXT.html VkDebugUtilsMessengerEXT>
-- Available: VK_EXT_debug_utils
newtype DebugUtilsMessengerEXT = DebugUtilsMessengerEXT Word64
  deriving newtype (Eq, Ord, Prim, Show, Storable)

newtype instance VU.MVector s DebugUtilsMessengerEXT = MV_DebugUtilsMessengerEXT (P.MVector s DebugUtilsMessengerEXT)

newtype instance VU.Vector DebugUtilsMessengerEXT = V_DebugUtilsMessengerEXT (P.Vector DebugUtilsMessengerEXT)

deriving via
  (UnboxViaPrim DebugUtilsMessengerEXT)
  instance
    VGM.MVector VU.MVector DebugUtilsMessengerEXT

deriving via
  (UnboxViaPrim DebugUtilsMessengerEXT)
  instance
    VG.Vector VU.Vector DebugUtilsMessengerEXT

instance VU.Unbox DebugUtilsMessengerEXT

-- | @VK_NULL_HANDLE@.
instance Nil DebugUtilsMessengerEXT where
  nil = DebugUtilsMessengerEXT 0

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsLabelEXT.html VkDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data DebugUtilsLabelEXT = DebugUtilsLabelEXT
  { labelName :: ByteString
  , color :: VSS.Vector 4 Float
  }

instance CStruct DebugUtilsLabelEXT where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000128002 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    p_labelName <- newCString x.labelName
    liftIO (pokeByteOff p 16 p_labelName)
    liftIO (pokeByteOff p 24 x.color)
    pure ()

instance FromCStruct DebugUtilsLabelEXT where
  peekCStruct p = do
    v_labelName <- BS.packCString =<< peekByteOff p 16
    v_color <- (peekByteOff p 24)
    pure DebugUtilsLabelEXT{labelName = v_labelName, color = v_color}

instance Nil DebugUtilsLabelEXT where
  nil =
    DebugUtilsLabelEXT
      { labelName = ""
      , color = VSS.replicate 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsMessengerCallbackDataEXT.html VkDebugUtilsMessengerCallbackDataEXT>
-- Available: VK_EXT_debug_utils
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @queueLabelCount@ is derived from @queueLabels@'s length.
--   * @cmdBufLabelCount@ is derived from @cmdBufLabels@'s length.
--   * @objectCount@ is derived from @objects@'s length.
data DebugUtilsMessengerCallbackDataEXT (es :: [Type]) = DebugUtilsMessengerCallbackDataEXT
  { next :: Chain es
  , flags :: DebugUtilsMessengerCallbackDataFlagsEXT
  , messageIdName :: Maybe ByteString
  , messageIdNumber :: Int32
  , message :: Maybe ByteString
  , queueLabels :: V.Vector DebugUtilsLabelEXT
  , cmdBufLabels :: V.Vector DebugUtilsLabelEXT
  , objects :: V.Vector DebugUtilsObjectNameInfoEXT
  }

instance
  (AllExtends DebugUtilsMessengerCallbackDataEXT es, PokeChain es)
  => CStruct (DebugUtilsMessengerCallbackDataEXT es)
  where
  cSize = 96
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000128003 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    p_messageIdName <- maybe (pure nullPtr) newCString x.messageIdName
    liftIO (pokeByteOff p 24 p_messageIdName)
    liftIO (pokeByteOff p 32 x.messageIdNumber)
    p_message <- maybe (pure nullPtr) newCString x.message
    liftIO (pokeByteOff p 40 p_message)
    p_queueLabels <- if V.null x.queueLabels then pure nullPtr else newVector x.queueLabels
    liftIO (pokeByteOff p 56 p_queueLabels)
    liftIO (pokeByteOff p 48 (fromIntegral (V.length x.queueLabels) :: Word32))
    p_cmdBufLabels <- if V.null x.cmdBufLabels then pure nullPtr else newVector x.cmdBufLabels
    liftIO (pokeByteOff p 72 p_cmdBufLabels)
    liftIO (pokeByteOff p 64 (fromIntegral (V.length x.cmdBufLabels) :: Word32))
    p_objects <- if V.null x.objects then pure nullPtr else newVector x.objects
    liftIO (pokeByteOff p 88 p_objects)
    liftIO (pokeByteOff p 80 (fromIntegral (V.length x.objects) :: Word32))
    pure ()

instance
  (AllExtends DebugUtilsMessengerCallbackDataEXT es, PokeChain es, PeekChain es)
  => FromCStruct (DebugUtilsMessengerCallbackDataEXT es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_messageIdName <- do q <- peekByteOff p 24; if q == nullPtr then pure Nothing else Just <$> BS.packCString q
    v_messageIdNumber <- (peekByteOff p 32)
    v_message <- do q <- peekByteOff p 40; if q == nullPtr then pure Nothing else Just <$> BS.packCString q
    v_queueLabels <- do
      n <- (peekByteOff p 48 :: IO Word32)
      q <- peekByteOff p 56
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    v_cmdBufLabels <- do
      n <- (peekByteOff p 64 :: IO Word32)
      q <- peekByteOff p 72
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    v_objects <- do
      n <- (peekByteOff p 80 :: IO Word32)
      q <- peekByteOff p 88
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    pure
      DebugUtilsMessengerCallbackDataEXT
        { next = v_next
        , flags = v_flags
        , messageIdName = v_messageIdName
        , messageIdNumber = v_messageIdNumber
        , message = v_message
        , queueLabels = v_queueLabels
        , cmdBufLabels = v_cmdBufLabels
        , objects = v_objects
        }

instance (NilChain es) => Nil (DebugUtilsMessengerCallbackDataEXT es) where
  nil =
    DebugUtilsMessengerCallbackDataEXT
      { next = nilChain
      , flags = mempty
      , messageIdName = Nothing
      , messageIdNumber = 0
      , message = Nothing
      , queueLabels = V.empty
      , cmdBufLabels = V.empty
      , objects = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsMessengerCreateInfoEXT.html VkDebugUtilsMessengerCreateInfoEXT>
-- Available: VK_EXT_debug_utils
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @pUserData@ is deliberately un-modelled (raw pointer); see the module notes.
data DebugUtilsMessengerCreateInfoEXT = DebugUtilsMessengerCreateInfoEXT
  { flags :: DebugUtilsMessengerCreateFlagsEXT
  , messageSeverity :: DebugUtilsMessageSeverityFlagsEXT
  , messageType :: DebugUtilsMessageTypeFlagsEXT
  , pfnUserCallback :: PFN_vkDebugUtilsMessengerCallbackEXT
  , pUserData :: Ptr ()
  }

instance CStruct DebugUtilsMessengerCreateInfoEXT where
  cSize = 48
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000128004 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 20 x.messageSeverity)
    liftIO (pokeByteOff p 24 x.messageType)
    liftIO (pokeByteOff p 32 x.pfnUserCallback)
    liftIO (pokeByteOff p 40 x.pUserData)
    pure ()

instance FromCStruct DebugUtilsMessengerCreateInfoEXT where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_messageSeverity <- (peekByteOff p 20)
    v_messageType <- (peekByteOff p 24)
    v_pfnUserCallback <- (peekByteOff p 32)
    v_pUserData <- peekByteOff p 40
    pure
      DebugUtilsMessengerCreateInfoEXT
        { flags = v_flags
        , messageSeverity = v_messageSeverity
        , messageType = v_messageType
        , pfnUserCallback = v_pfnUserCallback
        , pUserData = v_pUserData
        }

instance Nil DebugUtilsMessengerCreateInfoEXT where
  nil =
    DebugUtilsMessengerCreateInfoEXT
      { flags = mempty
      , messageSeverity = mempty
      , messageType = mempty
      , pfnUserCallback = nullFunPtr
      , pUserData = nullPtr
      }

instance Chainable DebugUtilsMessengerCreateInfoEXT where
  sTypeWire = 1000128004
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsObjectNameInfoEXT.html VkDebugUtilsObjectNameInfoEXT>
-- Available: VK_EXT_debug_utils
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data DebugUtilsObjectNameInfoEXT = DebugUtilsObjectNameInfoEXT
  { objectType :: Open ObjectType
  , objectHandle :: Word64
  , objectName :: Maybe ByteString
  }

instance CStruct DebugUtilsObjectNameInfoEXT where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000128000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (openToWire x.objectType))
    liftIO (pokeByteOff p 24 x.objectHandle)
    p_objectName <- maybe (pure nullPtr) newCString x.objectName
    liftIO (pokeByteOff p 32 p_objectName)
    pure ()

instance FromCStruct DebugUtilsObjectNameInfoEXT where
  peekCStruct p = do
    v_objectType <- (openFromWire <$> peekByteOff p 16)
    v_objectHandle <- (peekByteOff p 24)
    v_objectName <- do q <- peekByteOff p 32; if q == nullPtr then pure Nothing else Just <$> BS.packCString q
    pure
      DebugUtilsObjectNameInfoEXT
        { objectType = v_objectType
        , objectHandle = v_objectHandle
        , objectName = v_objectName
        }

instance Nil DebugUtilsObjectNameInfoEXT where
  nil =
    DebugUtilsObjectNameInfoEXT
      { objectType = Known ObjectTypeUnknown
      , objectHandle = 0
      , objectName = Nothing
      }

instance Chainable DebugUtilsObjectNameInfoEXT where
  sTypeWire = 1000128000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDebugUtilsObjectTagInfoEXT.html VkDebugUtilsObjectTagInfoEXT>
-- Available: VK_EXT_debug_utils
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @tagSize@ is derived from @tag@'s length.
data DebugUtilsObjectTagInfoEXT = DebugUtilsObjectTagInfoEXT
  { objectType :: Open ObjectType
  , objectHandle :: Word64
  , tagName :: Word64
  , tag :: ByteString
  }

instance CStruct DebugUtilsObjectTagInfoEXT where
  cSize = 56
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000128001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (openToWire x.objectType))
    liftIO (pokeByteOff p 24 x.objectHandle)
    liftIO (pokeByteOff p 32 x.tagName)
    p_tag <- newBytes x.tag
    liftIO (pokeByteOff p 48 (if BS.null x.tag then nullPtr else (castPtr p_tag :: Ptr ())))
    liftIO (pokeByteOff p 40 (fromIntegral (BS.length x.tag) :: Word64))
    pure ()

instance FromCStruct DebugUtilsObjectTagInfoEXT where
  peekCStruct p = do
    v_objectType <- (openFromWire <$> peekByteOff p 16)
    v_objectHandle <- (peekByteOff p 24)
    v_tagName <- (peekByteOff p 32)
    v_tag <- do
      n <- (peekByteOff p 40 :: IO Word64)
      q <- peekByteOff p 48
      if q == nullPtr then pure BS.empty else BS.packCStringLen (q, fromIntegral n)
    pure
      DebugUtilsObjectTagInfoEXT
        { objectType = v_objectType
        , objectHandle = v_objectHandle
        , tagName = v_tagName
        , tag = v_tag
        }

instance Nil DebugUtilsObjectTagInfoEXT where
  nil =
    DebugUtilsObjectTagInfoEXT
      { objectType = Known ObjectTypeUnknown
      , objectHandle = 0
      , tagName = 0
      , tag = ""
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/PFN_vkDebugUtilsMessengerCallbackEXT.html PFN_vkDebugUtilsMessengerCallbackEXT>
-- Available: VK_EXT_debug_utils
-- | The plain function shape behind 'PFN_vkDebugUtilsMessengerCallbackEXT'.
type FN_vkDebugUtilsMessengerCallbackEXT = Word32 -> Word32 -> Ptr () -> Ptr () -> IO Bool32

type PFN_vkDebugUtilsMessengerCallbackEXT = FunPtr FN_vkDebugUtilsMessengerCallbackEXT

-- | Wrap a Haskell function as a callable 'PFN_vkDebugUtilsMessengerCallbackEXT'.
-- Release with 'Foreign.Ptr.freeHaskellFunPtr' (or bracket via
-- 'Lithon.Core.Funptr.withCallback').
foreign import ccall "wrapper"
  mkPFN_vkDebugUtilsMessengerCallbackEXT
    :: FN_vkDebugUtilsMessengerCallbackEXT -> IO PFN_vkDebugUtilsMessengerCallbackEXT

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdBeginDebugUtilsLabelEXT.html vkCmdBeginDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
cmdBeginDebugUtilsLabelEXT
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> DebugUtilsLabelEXT
  -> m ()
cmdBeginDebugUtilsLabelEXT commandBuffer labelInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_labelInfo :: Ptr () <- castPtr <$> new labelInfo
    liftIO
      ( mkCmdBeginDebugUtilsLabelEXT
          (checkCommandPtr "vkCmdBeginDebugUtilsLabelEXT" commandBuffer.cmds.pCmdBeginDebugUtilsLabelEXT)
          (castPtr commandBuffer.handle)
          p_labelInfo
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdEndDebugUtilsLabelEXT.html vkCmdEndDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
cmdEndDebugUtilsLabelEXT
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> m ()
cmdEndDebugUtilsLabelEXT commandBuffer =
  liftIO do
    liftIO
      ( mkCmdEndDebugUtilsLabelEXT
          (checkCommandPtr "vkCmdEndDebugUtilsLabelEXT" commandBuffer.cmds.pCmdEndDebugUtilsLabelEXT)
          (castPtr commandBuffer.handle)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdInsertDebugUtilsLabelEXT.html vkCmdInsertDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
cmdInsertDebugUtilsLabelEXT
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> DebugUtilsLabelEXT
  -> m ()
cmdInsertDebugUtilsLabelEXT commandBuffer labelInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_labelInfo :: Ptr () <- castPtr <$> new labelInfo
    liftIO
      ( mkCmdInsertDebugUtilsLabelEXT
          (checkCommandPtr "vkCmdInsertDebugUtilsLabelEXT" commandBuffer.cmds.pCmdInsertDebugUtilsLabelEXT)
          (castPtr commandBuffer.handle)
          p_labelInfo
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateDebugUtilsMessengerEXT.html vkCreateDebugUtilsMessengerEXT>
-- Available: VK_EXT_debug_utils
createDebugUtilsMessengerEXT
  :: forall m
   . (MonadIO m)
  => Instance
  -> DebugUtilsMessengerCreateInfoEXT
  -> Maybe AllocationCallbacks
  -> m (Outcome DebugUtilsMessengerEXT)
createDebugUtilsMessengerEXT instance' createInfo allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_createInfo :: Ptr () <- castPtr <$> new createInfo
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_messenger <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateDebugUtilsMessengerEXT
            (checkCommandPtr "vkCreateDebugUtilsMessengerEXT" instance'.cmds.pCreateDebugUtilsMessengerEXT)
            (castPtr instance'.handle)
            p_createInfo
            p_allocator
            (castPtr p_o_messenger)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_messenger <- liftIO (peekByteOff p_o_messenger 0 :: IO Word64)
      let o_messenger = DebugUtilsMessengerEXT w_o_messenger
      pure (Ok (openFromWire r_) o_messenger)

withDebugUtilsMessengerEXT
  :: forall m r
   . (MonadUnliftIO m)
  => Instance
  -> DebugUtilsMessengerCreateInfoEXT
  -> Maybe AllocationCallbacks
  -> (Outcome DebugUtilsMessengerEXT -> m r)
  -> m r
withDebugUtilsMessengerEXT instance' createInfo allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createDebugUtilsMessengerEXT instance' createInfo allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroyDebugUtilsMessengerEXT instance' h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroyDebugUtilsMessengerEXT.html vkDestroyDebugUtilsMessengerEXT>
-- Available: VK_EXT_debug_utils
destroyDebugUtilsMessengerEXT
  :: forall m
   . (MonadIO m)
  => Instance
  -> DebugUtilsMessengerEXT
  -> Maybe AllocationCallbacks
  -> m ()
destroyDebugUtilsMessengerEXT instance' messenger allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroyDebugUtilsMessengerEXT
          (checkCommandPtr "vkDestroyDebugUtilsMessengerEXT" instance'.cmds.pDestroyDebugUtilsMessengerEXT)
          (castPtr instance'.handle)
          (case messenger of DebugUtilsMessengerEXT w_ -> w_)
          p_allocator
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkQueueBeginDebugUtilsLabelEXT.html vkQueueBeginDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
queueBeginDebugUtilsLabelEXT
  :: forall m
   . (MonadIO m)
  => Queue
  -> DebugUtilsLabelEXT
  -> m ()
queueBeginDebugUtilsLabelEXT queue labelInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_labelInfo :: Ptr () <- castPtr <$> new labelInfo
    liftIO
      ( mkQueueBeginDebugUtilsLabelEXT
          (checkCommandPtr "vkQueueBeginDebugUtilsLabelEXT" queue.cmds.pQueueBeginDebugUtilsLabelEXT)
          (castPtr queue.handle)
          p_labelInfo
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkQueueEndDebugUtilsLabelEXT.html vkQueueEndDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
queueEndDebugUtilsLabelEXT
  :: forall m
   . (MonadIO m)
  => Queue
  -> m ()
queueEndDebugUtilsLabelEXT queue =
  liftIO do
    liftIO
      ( mkQueueEndDebugUtilsLabelEXT
          (checkCommandPtr "vkQueueEndDebugUtilsLabelEXT" queue.cmds.pQueueEndDebugUtilsLabelEXT)
          (castPtr queue.handle)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkQueueInsertDebugUtilsLabelEXT.html vkQueueInsertDebugUtilsLabelEXT>
-- Available: VK_EXT_debug_utils
queueInsertDebugUtilsLabelEXT
  :: forall m
   . (MonadIO m)
  => Queue
  -> DebugUtilsLabelEXT
  -> m ()
queueInsertDebugUtilsLabelEXT queue labelInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_labelInfo :: Ptr () <- castPtr <$> new labelInfo
    liftIO
      ( mkQueueInsertDebugUtilsLabelEXT
          (checkCommandPtr "vkQueueInsertDebugUtilsLabelEXT" queue.cmds.pQueueInsertDebugUtilsLabelEXT)
          (castPtr queue.handle)
          p_labelInfo
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkSetDebugUtilsObjectNameEXT.html vkSetDebugUtilsObjectNameEXT>
-- Available: VK_EXT_debug_utils
setDebugUtilsObjectNameEXT
  :: forall m
   . (MonadIO m)
  => Device
  -> DebugUtilsObjectNameInfoEXT
  -> m (Outcome ())
setDebugUtilsObjectNameEXT device nameInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_nameInfo :: Ptr () <- castPtr <$> new nameInfo
    r_ <-
      liftIO
        ( mkSetDebugUtilsObjectNameEXT
            (checkCommandPtr "vkSetDebugUtilsObjectNameEXT" device.cmds.pSetDebugUtilsObjectNameEXT)
            (castPtr device.handle)
            p_nameInfo
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkSetDebugUtilsObjectTagEXT.html vkSetDebugUtilsObjectTagEXT>
-- Available: VK_EXT_debug_utils
setDebugUtilsObjectTagEXT
  :: forall m
   . (MonadIO m)
  => Device
  -> DebugUtilsObjectTagInfoEXT
  -> m (Outcome ())
setDebugUtilsObjectTagEXT device tagInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_tagInfo :: Ptr () <- castPtr <$> new tagInfo
    r_ <-
      liftIO
        ( mkSetDebugUtilsObjectTagEXT
            (checkCommandPtr "vkSetDebugUtilsObjectTagEXT" device.cmds.pSetDebugUtilsObjectTagEXT)
            (castPtr device.handle)
            p_tagInfo
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkSubmitDebugUtilsMessageEXT.html vkSubmitDebugUtilsMessageEXT>
-- Available: VK_EXT_debug_utils
submitDebugUtilsMessageEXT
  :: forall m es3
   . (MonadIO m, AllExtends DebugUtilsMessengerCallbackDataEXT es3, PokeChain es3)
  => Instance
  -> Flags DebugUtilsMessageSeverityFlagBitsEXT
  -> DebugUtilsMessageTypeFlagsEXT
  -> DebugUtilsMessengerCallbackDataEXT es3
  -> m ()
submitDebugUtilsMessageEXT instance' messageSeverity messageTypes callbackData =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_callbackData :: Ptr () <- castPtr <$> new callbackData
    liftIO
      ( mkSubmitDebugUtilsMessageEXT
          (checkCommandPtr "vkSubmitDebugUtilsMessageEXT" instance'.cmds.pSubmitDebugUtilsMessageEXT)
          (castPtr instance'.handle)
          ((\(Flags w) -> w) messageSeverity)
          ((\(Flags w) -> w) messageTypes)
          p_callbackData
      )
    pure ()
