-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.EXT_descriptor_heap (
  TensorARM (..),
  ResourceDescriptorDataEXT (..),
  ImageDescriptorInfoEXT (..),
  ResourceDescriptorInfoEXT (..),
  TensorViewCreateInfoARM (..),
  TexelBufferDescriptorInfoEXT (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Primitive.Types (Prim)
import Data.Vector qualified as V
import Data.Vector.Generic qualified as VG
import Data.Vector.Generic.Mutable qualified as VGM
import Data.Vector.Primitive qualified as P
import Data.Vector.Storable.Sized qualified as VSS
import Data.Vector.Unboxed qualified as VU
import Data.Word (Word32, Word64, Word8)
import Foreign.C.Types (CSize)
import Foreign.Marshal.Utils (fillBytes)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable, peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)
import Lithon.Core.Unbox (UnboxViaPrim (..))

import Lithon.Vk.Core10.Enums.DescriptorType
import Lithon.Vk.Core10.Enums.Format
import Lithon.Vk.Core10.Enums.ImageLayout
import Lithon.Vk.Core10.ImageViewCommands
import Lithon.Vk.Extensions.ARM_tensors
import Lithon.Vk.Extensions.KHR_device_address_commands

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkTensorARM.html VkTensorARM>
-- Available: VK_ARM_tensors,VK_EXT_descriptor_heap
newtype TensorARM = TensorARM Word64
  deriving newtype (Eq, Ord, Prim, Show, Storable)

newtype instance VU.MVector s TensorARM = MV_TensorARM (P.MVector s TensorARM)

newtype instance VU.Vector TensorARM = V_TensorARM (P.Vector TensorARM)

deriving via (UnboxViaPrim TensorARM) instance VGM.MVector VU.MVector TensorARM

deriving via (UnboxViaPrim TensorARM) instance VG.Vector VU.Vector TensorARM

instance VU.Unbox TensorARM

-- | @VK_NULL_HANDLE@.
instance Nil TensorARM where
  nil = TensorARM 0

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkResourceDescriptorDataEXT.html VkResourceDescriptorDataEXT>
-- Available: VK_EXT_descriptor_heap
data ResourceDescriptorDataEXT
  = ResourceDescriptorDataEXTPImage !(Ptr ())
  | ResourceDescriptorDataEXTPTexelBuffer !(Ptr ())
  | ResourceDescriptorDataEXTPAddressRange !(Ptr ())
  | ResourceDescriptorDataEXTPTensorARM !(Ptr ())
  | -- | What peeks return: the union's bytes verbatim (no wire
    -- discriminant); reinterpret via the typed arms when known.
    ResourceDescriptorDataEXTRaw !(VSS.Vector 8 Word8)

instance CStruct ResourceDescriptorDataEXT where
  cSize = 8
  cAlign = 8
  pokeCStruct p x = do
    liftIO (fillBytes (castPtr p) 0 8)
    case x of
      ResourceDescriptorDataEXTPImage v -> liftIO (pokeByteOff p 0 v)
      ResourceDescriptorDataEXTPTexelBuffer v -> liftIO (pokeByteOff p 0 v)
      ResourceDescriptorDataEXTPAddressRange v -> liftIO (pokeByteOff p 0 v)
      ResourceDescriptorDataEXTPTensorARM v -> liftIO (pokeByteOff p 0 v)
      ResourceDescriptorDataEXTRaw v -> liftIO (pokeByteOff p 0 v)

instance FromCStruct ResourceDescriptorDataEXT where
  peekCStruct p = ResourceDescriptorDataEXTRaw <$> peekByteOff p 0

instance Nil ResourceDescriptorDataEXT where
  nil = ResourceDescriptorDataEXTPImage nullPtr

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImageDescriptorInfoEXT.html VkImageDescriptorInfoEXT>
-- Available: VK_EXT_descriptor_heap
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data ImageDescriptorInfoEXT = ImageDescriptorInfoEXT
  { view :: SomeStruct ImageViewCreateInfo
  , layout :: Open ImageLayout
  }

instance CStruct ImageDescriptorInfoEXT where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000135001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    p_view <- withSomeStruct x.view (fmap castPtr . new)
    liftIO (pokeByteOff p 16 p_view)
    liftIO (pokeByteOff p 24 (openToWire x.layout))
    pure ()

instance Nil ImageDescriptorInfoEXT where
  nil =
    ImageDescriptorInfoEXT
      { view = SomeStruct (nil @(ImageViewCreateInfo '[]))
      , layout = Known ImageLayoutUndefined
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkResourceDescriptorInfoEXT.html VkResourceDescriptorInfoEXT>
-- Available: VK_EXT_descriptor_heap
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data ResourceDescriptorInfoEXT (es :: [Type]) = ResourceDescriptorInfoEXT
  { next :: Chain es
  , type' :: DescriptorType
  , data' :: ResourceDescriptorDataEXT
  }

instance (AllExtends ResourceDescriptorInfoEXT es, PokeChain es) => CStruct (ResourceDescriptorInfoEXT es) where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000135002 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 (toWire x.type'))
    pokeCStruct (castPtr (p `plusPtr` 24)) x.data'
    pure ()

instance
  (AllExtends ResourceDescriptorInfoEXT es, PokeChain es, PeekChain es)
  => FromCStruct (ResourceDescriptorInfoEXT es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_type' <- (unsafeFromWire <$> peekByteOff p 16)
    v_data' <- peekCStruct (castPtr (p `plusPtr` 24))
    pure ResourceDescriptorInfoEXT{next = v_next, type' = v_type', data' = v_data'}

instance (NilChain es) => Nil (ResourceDescriptorInfoEXT es) where
  nil =
    ResourceDescriptorInfoEXT
      { next = nilChain
      , type' = DescriptorTypeSampler
      , data' = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkTensorViewCreateInfoARM.html VkTensorViewCreateInfoARM>
-- Available: VK_ARM_tensors,VK_EXT_descriptor_heap
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data TensorViewCreateInfoARM (es :: [Type]) = TensorViewCreateInfoARM
  { next :: Chain es
  , flags :: TensorViewCreateFlagsARM
  , tensor :: TensorARM
  , format :: Open Format
  }

instance (AllExtends TensorViewCreateInfoARM es, PokeChain es) => CStruct (TensorViewCreateInfoARM es) where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000460001 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 24 x.tensor)
    liftIO (pokeByteOff p 32 (openToWire x.format))
    pure ()

instance
  (AllExtends TensorViewCreateInfoARM es, PokeChain es, PeekChain es)
  => FromCStruct (TensorViewCreateInfoARM es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_flags <- (peekByteOff p 16)
    v_tensor <- (peekByteOff p 24)
    v_format <- (openFromWire <$> peekByteOff p 32)
    pure TensorViewCreateInfoARM{next = v_next, flags = v_flags, tensor = v_tensor, format = v_format}

instance (NilChain es) => Nil (TensorViewCreateInfoARM es) where
  nil =
    TensorViewCreateInfoARM
      { next = nilChain
      , flags = mempty
      , tensor = nil
      , format = Known FormatUndefined
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkTexelBufferDescriptorInfoEXT.html VkTexelBufferDescriptorInfoEXT>
-- Available: VK_EXT_descriptor_heap
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data TexelBufferDescriptorInfoEXT = TexelBufferDescriptorInfoEXT
  { format :: Open Format
  , addressRange :: DeviceAddressRangeKHR
  }

instance CStruct TexelBufferDescriptorInfoEXT where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000135000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (openToWire x.format))
    liftIO (pokeByteOff p 24 x.addressRange)
    pure ()

instance FromCStruct TexelBufferDescriptorInfoEXT where
  peekCStruct p = do
    v_format <- (openFromWire <$> peekByteOff p 16)
    v_addressRange <- (peekByteOff p 24)
    pure TexelBufferDescriptorInfoEXT{format = v_format, addressRange = v_addressRange}

instance Nil TexelBufferDescriptorInfoEXT where
  nil =
    TexelBufferDescriptorInfoEXT
      { format = Known FormatUndefined
      , addressRange = nil
      }
