-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.EXT_device_fault (
  DeviceFaultAddressTypeKHR (..),
  DeviceFaultAddressInfoKHR (..),
  DeviceFaultVendorInfoKHR (..),
  DeviceFaultCountsEXT (..),
  DeviceFaultInfoEXT (..),
  PhysicalDeviceFaultFeaturesEXT (..),
  getDeviceFaultInfoEXT,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems, peekFixedString, pokeFixedString)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceFaultAddressTypeKHR.html VkDeviceFaultAddressTypeKHR>
-- Available: VK_KHR_device_fault
-- Alias spellings: VkDeviceFaultAddressTypeEXT
data DeviceFaultAddressTypeKHR
  = DeviceFaultAddressTypeNoneKHR
  | DeviceFaultAddressTypeReadInvalidKHR
  | DeviceFaultAddressTypeWriteInvalidKHR
  | DeviceFaultAddressTypeExecuteInvalidKHR
  | DeviceFaultAddressTypeInstructionPointerUnknownKHR
  | DeviceFaultAddressTypeInstructionPointerInvalidKHR
  | DeviceFaultAddressTypeInstructionPointerFaultKHR
  deriving stock (Eq, Ord, Show)

instance HasWire DeviceFaultAddressTypeKHR where
  toWire = \case
    DeviceFaultAddressTypeNoneKHR -> 0
    DeviceFaultAddressTypeReadInvalidKHR -> 1
    DeviceFaultAddressTypeWriteInvalidKHR -> 2
    DeviceFaultAddressTypeExecuteInvalidKHR -> 3
    DeviceFaultAddressTypeInstructionPointerUnknownKHR -> 4
    DeviceFaultAddressTypeInstructionPointerInvalidKHR -> 5
    DeviceFaultAddressTypeInstructionPointerFaultKHR -> 6
  fromWire = \case
    0 -> Just DeviceFaultAddressTypeNoneKHR
    1 -> Just DeviceFaultAddressTypeReadInvalidKHR
    2 -> Just DeviceFaultAddressTypeWriteInvalidKHR
    3 -> Just DeviceFaultAddressTypeExecuteInvalidKHR
    4 -> Just DeviceFaultAddressTypeInstructionPointerUnknownKHR
    5 -> Just DeviceFaultAddressTypeInstructionPointerInvalidKHR
    6 -> Just DeviceFaultAddressTypeInstructionPointerFaultKHR
    _ -> Nothing

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceFaultAddressInfoKHR.html VkDeviceFaultAddressInfoKHR>
-- Available: VK_KHR_device_fault
-- Alias spellings: VkDeviceFaultAddressInfoEXT
data DeviceFaultAddressInfoKHR = DeviceFaultAddressInfoKHR
  { addressType :: !(Open DeviceFaultAddressTypeKHR)
  , reportedAddress :: !Word64
  , addressPrecision :: !Word64
  }
  deriving stock (Eq, Show)

instance Storable DeviceFaultAddressInfoKHR where
  sizeOf _ = 24
  alignment _ = 8
  peek p =
    DeviceFaultAddressInfoKHR
      <$> (openFromWire <$> peekByteOff p 0)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 16)
  poke p x = do
    pokeByteOff p 0 (openToWire x.addressType)
    pokeByteOff p 8 x.reportedAddress
    pokeByteOff p 16 x.addressPrecision

instance CStruct DeviceFaultAddressInfoKHR where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct DeviceFaultAddressInfoKHR where
  peekCStruct = peek

instance Nil DeviceFaultAddressInfoKHR where
  nil =
    DeviceFaultAddressInfoKHR
      { addressType = Known DeviceFaultAddressTypeNoneKHR
      , reportedAddress = 0
      , addressPrecision = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceFaultVendorInfoKHR.html VkDeviceFaultVendorInfoKHR>
-- Available: VK_KHR_device_fault
-- Alias spellings: VkDeviceFaultVendorInfoEXT
data DeviceFaultVendorInfoKHR = DeviceFaultVendorInfoKHR
  { description :: !ByteString
  , vendorFaultCode :: !Word64
  , vendorFaultData :: !Word64
  }
  deriving stock (Eq, Show)

instance Storable DeviceFaultVendorInfoKHR where
  sizeOf _ = 272
  alignment _ = 8
  peek p =
    DeviceFaultVendorInfoKHR
      <$> (peekFixedString 256 p 0)
      <*> (peekByteOff p 256)
      <*> (peekByteOff p 264)
  poke p x = do
    pokeFixedString 256 p 0 x.description
    pokeByteOff p 256 x.vendorFaultCode
    pokeByteOff p 264 x.vendorFaultData

instance CStruct DeviceFaultVendorInfoKHR where
  cSize = 272
  cAlign = 8
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct DeviceFaultVendorInfoKHR where
  peekCStruct = peek

instance Nil DeviceFaultVendorInfoKHR where
  nil =
    DeviceFaultVendorInfoKHR
      { description = ""
      , vendorFaultCode = 0
      , vendorFaultData = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceFaultCountsEXT.html VkDeviceFaultCountsEXT>
-- Available: VK_EXT_device_fault
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data DeviceFaultCountsEXT = DeviceFaultCountsEXT
  { addressInfoCount :: Word32
  , vendorInfoCount :: Word32
  , vendorBinarySize :: Word64
  }

instance CStruct DeviceFaultCountsEXT where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000341001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.addressInfoCount)
    liftIO (pokeByteOff p 20 x.vendorInfoCount)
    liftIO (pokeByteOff p 24 x.vendorBinarySize)
    pure ()

instance FromCStruct DeviceFaultCountsEXT where
  peekCStruct p = do
    v_addressInfoCount <- (peekByteOff p 16)
    v_vendorInfoCount <- (peekByteOff p 20)
    v_vendorBinarySize <- (peekByteOff p 24)
    pure
      DeviceFaultCountsEXT
        { addressInfoCount = v_addressInfoCount
        , vendorInfoCount = v_vendorInfoCount
        , vendorBinarySize = v_vendorBinarySize
        }

instance Nil DeviceFaultCountsEXT where
  nil =
    DeviceFaultCountsEXT
      { addressInfoCount = 0
      , vendorInfoCount = 0
      , vendorBinarySize = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeviceFaultInfoEXT.html VkDeviceFaultInfoEXT>
-- Available: VK_EXT_device_fault
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @pAddressInfos@ is deliberately un-modelled (raw pointer); see the module notes.
--   * @pVendorInfos@ is deliberately un-modelled (raw pointer); see the module notes.
--   * @pVendorBinaryData@ is deliberately un-modelled (raw pointer); see the module notes.
data DeviceFaultInfoEXT = DeviceFaultInfoEXT
  { description :: ByteString
  , pAddressInfos :: Ptr ()
  , pVendorInfos :: Ptr ()
  , pVendorBinaryData :: Ptr ()
  }

instance CStruct DeviceFaultInfoEXT where
  cSize = 296
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000341002 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeFixedString 256 p 16 x.description)
    liftIO (pokeByteOff p 272 x.pAddressInfos)
    liftIO (pokeByteOff p 280 x.pVendorInfos)
    liftIO (pokeByteOff p 288 x.pVendorBinaryData)
    pure ()

instance FromCStruct DeviceFaultInfoEXT where
  peekCStruct p = do
    v_description <- (peekFixedString 256 p 16)
    v_pAddressInfos <- peekByteOff p 272
    v_pVendorInfos <- peekByteOff p 280
    v_pVendorBinaryData <- peekByteOff p 288
    pure
      DeviceFaultInfoEXT
        { description = v_description
        , pAddressInfos = v_pAddressInfos
        , pVendorInfos = v_pVendorInfos
        , pVendorBinaryData = v_pVendorBinaryData
        }

instance Nil DeviceFaultInfoEXT where
  nil =
    DeviceFaultInfoEXT
      { description = ""
      , pAddressInfos = nullPtr
      , pVendorInfos = nullPtr
      , pVendorBinaryData = nullPtr
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceFaultFeaturesEXT.html VkPhysicalDeviceFaultFeaturesEXT>
-- Available: VK_EXT_device_fault
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceFaultFeaturesEXT = PhysicalDeviceFaultFeaturesEXT
  { deviceFault :: Bool
  , deviceFaultVendorBinary :: Bool
  }

instance CStruct PhysicalDeviceFaultFeaturesEXT where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000341000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.deviceFault then TRUE else FALSE))
    liftIO (pokeByteOff p 20 (if x.deviceFaultVendorBinary then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDeviceFaultFeaturesEXT where
  peekCStruct p = do
    v_deviceFault <- (toBool <$> peekByteOff p 16)
    v_deviceFaultVendorBinary <- (toBool <$> peekByteOff p 20)
    pure
      PhysicalDeviceFaultFeaturesEXT
        { deviceFault = v_deviceFault
        , deviceFaultVendorBinary = v_deviceFaultVendorBinary
        }

instance Nil PhysicalDeviceFaultFeaturesEXT where
  nil =
    PhysicalDeviceFaultFeaturesEXT
      { deviceFault = False
      , deviceFaultVendorBinary = False
      }

instance Chainable PhysicalDeviceFaultFeaturesEXT where
  sTypeWire = 1000341000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetDeviceFaultInfoEXT.html vkGetDeviceFaultInfoEXT>
-- Available: VK_EXT_device_fault
getDeviceFaultInfoEXT
  :: forall m
   . (MonadIO m)
  => Device
  -> m
       ( Outcome
           ( DeviceFaultCountsEXT
           , ByteString
           , V.Vector DeviceFaultAddressInfoKHR
           , V.Vector DeviceFaultVendorInfoKHR
           , ByteString
           )
       )
getDeviceFaultInfoEXT device =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_counts :: Ptr () <- castPtr <$> new (nil :: DeviceFaultCountsEXT)
    r1_ <-
      liftIO
        ( mkGetDeviceFaultInfoEXT
            (checkCommandPtr "vkGetDeviceFaultInfoEXT" device.cmds.pGetDeviceFaultInfoEXT)
            (castPtr device.handle)
            p_counts
            nullPtr
        )
    if r1_ < 0 then
      pure (Err (openFromWire r1_))
    else do
      counts_ <- liftIO (peekCStruct (castPtr p_counts) :: IO DeviceFaultCountsEXT)
      p_info :: Ptr () <- castPtr <$> new (nil :: DeviceFaultInfoEXT)
      p_addr_ <- arenaBytes (24 * max 1 (fromIntegral counts_.addressInfoCount)) 8
      p_vend_ <- arenaBytes (272 * max 1 (fromIntegral counts_.vendorInfoCount)) 8
      p_bin_ <- arenaBytes (max 1 (fromIntegral counts_.vendorBinarySize)) 8
      liftIO (pokeByteOff p_info 272 (castPtr p_addr_ :: Ptr ()))
      liftIO (pokeByteOff p_info 280 (castPtr p_vend_ :: Ptr ()))
      liftIO (pokeByteOff p_info 288 (castPtr p_bin_ :: Ptr ()))
      r2_ <-
        liftIO
          ( mkGetDeviceFaultInfoEXT
              (checkCommandPtr "vkGetDeviceFaultInfoEXT" device.cmds.pGetDeviceFaultInfoEXT)
              (castPtr device.handle)
              p_counts
              p_info
          )
      if r2_ < 0 then
        pure (Err (openFromWire r2_))
      else do
        counts'_ <- liftIO (peekCStruct (castPtr p_counts) :: IO DeviceFaultCountsEXT)
        info_ <- liftIO (peekCStruct (castPtr p_info) :: IO DeviceFaultInfoEXT)
        addrs_ <- liftIO (peekElems (fromIntegral counts'_.addressInfoCount) (castPtr p_addr_))
        vends_ <- liftIO (peekElems (fromIntegral counts'_.vendorInfoCount) (castPtr p_vend_))
        bin_ <- liftIO (BS.packCStringLen (castPtr p_bin_, fromIntegral counts'_.vendorBinarySize))
        pure (Ok (openFromWire r2_) (counts'_, info_.description, addrs_, vends_, bin_))
