-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.EXT_layer_settings (
  LayerSettingTypeEXT (..),
  LayerSettingEXT (..),
  LayerSettingsCreateInfoEXT (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkLayerSettingTypeEXT.html VkLayerSettingTypeEXT>
-- Available: VK_EXT_layer_settings
data LayerSettingTypeEXT
  = LayerSettingTypeBool32EXT
  | LayerSettingTypeInt32EXT
  | LayerSettingTypeInt64EXT
  | LayerSettingTypeUint32EXT
  | LayerSettingTypeUint64EXT
  | LayerSettingTypeFloat32EXT
  | LayerSettingTypeFloat64EXT
  | LayerSettingTypeStringEXT
  deriving stock (Eq, Ord, Show)

instance HasWire LayerSettingTypeEXT where
  toWire = \case
    LayerSettingTypeBool32EXT -> 0
    LayerSettingTypeInt32EXT -> 1
    LayerSettingTypeInt64EXT -> 2
    LayerSettingTypeUint32EXT -> 3
    LayerSettingTypeUint64EXT -> 4
    LayerSettingTypeFloat32EXT -> 5
    LayerSettingTypeFloat64EXT -> 6
    LayerSettingTypeStringEXT -> 7
  fromWire = \case
    0 -> Just LayerSettingTypeBool32EXT
    1 -> Just LayerSettingTypeInt32EXT
    2 -> Just LayerSettingTypeInt64EXT
    3 -> Just LayerSettingTypeUint32EXT
    4 -> Just LayerSettingTypeUint64EXT
    5 -> Just LayerSettingTypeFloat32EXT
    6 -> Just LayerSettingTypeFloat64EXT
    7 -> Just LayerSettingTypeStringEXT
    _ -> Nothing

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkLayerSettingEXT.html VkLayerSettingEXT>
-- Available: VK_EXT_layer_settings
--
-- Marshalling:
--   * @valueCount@ is derived from @values@'s length.
data LayerSettingEXT = LayerSettingEXT
  { layerName :: ByteString
  , settingName :: ByteString
  , type' :: LayerSettingTypeEXT
  , values :: ByteString
  }

instance CStruct LayerSettingEXT where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    p_layerName <- newCString x.layerName
    liftIO (pokeByteOff p 0 p_layerName)
    p_settingName <- newCString x.settingName
    liftIO (pokeByteOff p 8 p_settingName)
    liftIO (pokeByteOff p 16 (toWire x.type'))
    p_values <- newBytes x.values
    liftIO (pokeByteOff p 24 (if BS.null x.values then nullPtr else (castPtr p_values :: Ptr ())))
    liftIO (pokeByteOff p 20 (fromIntegral (BS.length x.values) :: Word32))
    pure ()

instance FromCStruct LayerSettingEXT where
  peekCStruct p = do
    v_layerName <- BS.packCString =<< peekByteOff p 0
    v_settingName <- BS.packCString =<< peekByteOff p 8
    v_type' <- (unsafeFromWire <$> peekByteOff p 16)
    v_values <- do
      n <- (peekByteOff p 20 :: IO Word32)
      q <- peekByteOff p 24
      if q == nullPtr then pure BS.empty else BS.packCStringLen (q, fromIntegral n)
    pure
      LayerSettingEXT
        { layerName = v_layerName
        , settingName = v_settingName
        , type' = v_type'
        , values = v_values
        }

instance Nil LayerSettingEXT where
  nil =
    LayerSettingEXT
      { layerName = ""
      , settingName = ""
      , type' = LayerSettingTypeBool32EXT
      , values = ""
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkLayerSettingsCreateInfoEXT.html VkLayerSettingsCreateInfoEXT>
-- Available: VK_EXT_layer_settings
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @settingCount@ is derived from @settings@'s length.
data LayerSettingsCreateInfoEXT = LayerSettingsCreateInfoEXT
  { settings :: V.Vector LayerSettingEXT
  }

instance CStruct LayerSettingsCreateInfoEXT where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000496000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    p_settings <- if V.null x.settings then pure nullPtr else newVector x.settings
    liftIO (pokeByteOff p 24 p_settings)
    liftIO (pokeByteOff p 16 (fromIntegral (V.length x.settings) :: Word32))
    pure ()

instance FromCStruct LayerSettingsCreateInfoEXT where
  peekCStruct p = do
    v_settings <- do
      n <- (peekByteOff p 16 :: IO Word32)
      q <- peekByteOff p 24
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    pure LayerSettingsCreateInfoEXT{settings = v_settings}

instance Nil LayerSettingsCreateInfoEXT where
  nil =
    LayerSettingsCreateInfoEXT
      { settings = V.empty
      }

instance Chainable LayerSettingsCreateInfoEXT where
  sTypeWire = 1000496000
  chainOffset = 8
