-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.KHR_external_memory_fd (
  ImportMemoryFdInfoKHR (..),
  MemoryFdPropertiesKHR (..),
  MemoryGetFdInfoKHR (..),
  getMemoryFdKHR,
  getMemoryFdPropertiesKHR,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Handles
import Lithon.Vk.Core11.Enums.ExternalMemoryHandleTypeFlagBits
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkImportMemoryFdInfoKHR.html VkImportMemoryFdInfoKHR>
-- Available: VK_KHR_external_memory_fd
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data ImportMemoryFdInfoKHR = ImportMemoryFdInfoKHR
  { handleType :: Flags ExternalMemoryHandleTypeFlagBits
  , fd :: Int32
  }

instance CStruct ImportMemoryFdInfoKHR where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000074000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.handleType)
    liftIO (pokeByteOff p 20 x.fd)
    pure ()

instance FromCStruct ImportMemoryFdInfoKHR where
  peekCStruct p = do
    v_handleType <- (peekByteOff p 16)
    v_fd <- (peekByteOff p 20)
    pure ImportMemoryFdInfoKHR{handleType = v_handleType, fd = v_fd}

instance Nil ImportMemoryFdInfoKHR where
  nil =
    ImportMemoryFdInfoKHR
      { handleType = mempty
      , fd = 0
      }

instance Chainable ImportMemoryFdInfoKHR where
  sTypeWire = 1000074000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkMemoryFdPropertiesKHR.html VkMemoryFdPropertiesKHR>
-- Available: VK_KHR_external_memory_fd
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data MemoryFdPropertiesKHR = MemoryFdPropertiesKHR
  { memoryTypeBits :: Word32
  }

instance CStruct MemoryFdPropertiesKHR where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000074001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.memoryTypeBits)
    pure ()

instance FromCStruct MemoryFdPropertiesKHR where
  peekCStruct p = do
    v_memoryTypeBits <- (peekByteOff p 16)
    pure MemoryFdPropertiesKHR{memoryTypeBits = v_memoryTypeBits}

instance Nil MemoryFdPropertiesKHR where
  nil =
    MemoryFdPropertiesKHR
      { memoryTypeBits = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkMemoryGetFdInfoKHR.html VkMemoryGetFdInfoKHR>
-- Available: VK_KHR_external_memory_fd
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data MemoryGetFdInfoKHR = MemoryGetFdInfoKHR
  { memory :: DeviceMemory
  , handleType :: Flags ExternalMemoryHandleTypeFlagBits
  }

instance CStruct MemoryGetFdInfoKHR where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000074002 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.memory)
    liftIO (pokeByteOff p 24 x.handleType)
    pure ()

instance FromCStruct MemoryGetFdInfoKHR where
  peekCStruct p = do
    v_memory <- (peekByteOff p 16)
    v_handleType <- (peekByteOff p 24)
    pure MemoryGetFdInfoKHR{memory = v_memory, handleType = v_handleType}

instance Nil MemoryGetFdInfoKHR where
  nil =
    MemoryGetFdInfoKHR
      { memory = nil
      , handleType = mempty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetMemoryFdKHR.html vkGetMemoryFdKHR>
-- Available: VK_KHR_external_memory_fd
getMemoryFdKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> MemoryGetFdInfoKHR
  -> m (Outcome Int32)
getMemoryFdKHR device getFdInfo =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_getFdInfo :: Ptr () <- castPtr <$> new getFdInfo
    p_o_fd <- arenaBytes 4 4
    r_ <-
      liftIO
        ( mkGetMemoryFdKHR
            (checkCommandPtr "vkGetMemoryFdKHR" device.cmds.pGetMemoryFdKHR)
            (castPtr device.handle)
            p_getFdInfo
            (castPtr p_o_fd)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_fd <- liftIO (peekByteOff p_o_fd 0 :: IO Int32)
      let o_fd = w_o_fd
      pure (Ok (openFromWire r_) o_fd)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetMemoryFdPropertiesKHR.html vkGetMemoryFdPropertiesKHR>
-- Available: VK_KHR_external_memory_fd
getMemoryFdPropertiesKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> Flags ExternalMemoryHandleTypeFlagBits
  -> Int32
  -> m (Outcome MemoryFdPropertiesKHR)
getMemoryFdPropertiesKHR device handleType fd =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_o_memoryFdProperties :: Ptr () <- castPtr <$> new (nil :: MemoryFdPropertiesKHR)
    r_ <-
      liftIO
        ( mkGetMemoryFdPropertiesKHR
            (checkCommandPtr "vkGetMemoryFdPropertiesKHR" device.cmds.pGetMemoryFdPropertiesKHR)
            (castPtr device.handle)
            ((\(Flags w) -> w) handleType)
            fd
            p_o_memoryFdProperties
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      o_memoryFdProperties <- liftIO (peekCStruct (castPtr p_o_memoryFdProperties))
      pure (Ok (openFromWire r_) o_memoryFdProperties)
