-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.KHR_shader_clock (
  PhysicalDeviceShaderClockFeaturesKHR (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceShaderClockFeaturesKHR.html VkPhysicalDeviceShaderClockFeaturesKHR>
-- Available: VK_KHR_shader_clock
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceShaderClockFeaturesKHR = PhysicalDeviceShaderClockFeaturesKHR
  { shaderSubgroupClock :: Bool
  , shaderDeviceClock :: Bool
  }

instance CStruct PhysicalDeviceShaderClockFeaturesKHR where
  cSize = 24
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000181000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.shaderSubgroupClock then TRUE else FALSE))
    liftIO (pokeByteOff p 20 (if x.shaderDeviceClock then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDeviceShaderClockFeaturesKHR where
  peekCStruct p = do
    v_shaderSubgroupClock <- (toBool <$> peekByteOff p 16)
    v_shaderDeviceClock <- (toBool <$> peekByteOff p 20)
    pure
      PhysicalDeviceShaderClockFeaturesKHR
        { shaderSubgroupClock = v_shaderSubgroupClock
        , shaderDeviceClock = v_shaderDeviceClock
        }

instance Nil PhysicalDeviceShaderClockFeaturesKHR where
  nil =
    PhysicalDeviceShaderClockFeaturesKHR
      { shaderSubgroupClock = False
      , shaderDeviceClock = False
      }

instance Chainable PhysicalDeviceShaderClockFeaturesKHR where
  sTypeWire = 1000181000
  chainOffset = 8
