-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.KHR_win32_surface (
  Win32SurfaceCreateFlagsKHR,
  Win32SurfaceCreateFlagsKHRBits,
  Win32SurfaceCreateInfoKHR (..),
  createWin32SurfaceKHR,
  withWin32SurfaceKHR,
  getPhysicalDeviceWin32PresentationSupportKHR,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)
import Lithon.Core.Platform (HINSTANCE (..), HWND (..))

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Extensions.KHR_surface
import Lithon.Vk.Result (Outcome (..))

-- | Reserved-empty mask: no bits are defined yet.
data Win32SurfaceCreateFlagsKHRBits
  deriving stock (Eq, Ord, Show)

type instance FlagsWire Win32SurfaceCreateFlagsKHRBits = Word32

instance BitPos Win32SurfaceCreateFlagsKHRBits where
  bitOf = \case {}
  allBits = []

type Win32SurfaceCreateFlagsKHR = Flags Win32SurfaceCreateFlagsKHRBits

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkWin32SurfaceCreateInfoKHR.html VkWin32SurfaceCreateInfoKHR>
-- Available: VK_KHR_win32_surface
-- Platform-specific (guarded by @VK_USE_PLATFORM_WIN32_KHR@ in C; emitted unconditionally here).
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data Win32SurfaceCreateInfoKHR = Win32SurfaceCreateInfoKHR
  { flags :: Win32SurfaceCreateFlagsKHR
  , hinstance :: HINSTANCE
  , hwnd :: HWND
  }

instance CStruct Win32SurfaceCreateInfoKHR where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000009000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.flags)
    liftIO (pokeByteOff p 24 x.hinstance)
    liftIO (pokeByteOff p 32 x.hwnd)
    pure ()

instance FromCStruct Win32SurfaceCreateInfoKHR where
  peekCStruct p = do
    v_flags <- (peekByteOff p 16)
    v_hinstance <- (peekByteOff p 24)
    v_hwnd <- (peekByteOff p 32)
    pure Win32SurfaceCreateInfoKHR{flags = v_flags, hinstance = v_hinstance, hwnd = v_hwnd}

instance Nil Win32SurfaceCreateInfoKHR where
  nil =
    Win32SurfaceCreateInfoKHR
      { flags = mempty
      , hinstance = HINSTANCE nullPtr
      , hwnd = HWND nullPtr
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateWin32SurfaceKHR.html vkCreateWin32SurfaceKHR>
-- Available: VK_KHR_win32_surface
-- Platform-specific (guarded by @VK_USE_PLATFORM_WIN32_KHR@ in C; emitted unconditionally here).
createWin32SurfaceKHR
  :: forall m
   . (MonadIO m)
  => Instance
  -> Win32SurfaceCreateInfoKHR
  -> Maybe AllocationCallbacks
  -> m (Outcome SurfaceKHR)
createWin32SurfaceKHR instance' createInfo allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_createInfo :: Ptr () <- castPtr <$> new createInfo
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_surface <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateWin32SurfaceKHR
            (checkCommandPtr "vkCreateWin32SurfaceKHR" instance'.cmds.pCreateWin32SurfaceKHR)
            (castPtr instance'.handle)
            p_createInfo
            p_allocator
            (castPtr p_o_surface)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_surface <- liftIO (peekByteOff p_o_surface 0 :: IO Word64)
      let o_surface = SurfaceKHR w_o_surface
      pure (Ok (openFromWire r_) o_surface)

withWin32SurfaceKHR
  :: forall m r
   . (MonadUnliftIO m)
  => Instance
  -> Win32SurfaceCreateInfoKHR
  -> Maybe AllocationCallbacks
  -> (Outcome SurfaceKHR -> m r)
  -> m r
withWin32SurfaceKHR instance' createInfo allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createWin32SurfaceKHR instance' createInfo allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroySurfaceKHR instance' h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceWin32PresentationSupportKHR.html vkGetPhysicalDeviceWin32PresentationSupportKHR>
-- Available: VK_KHR_win32_surface
-- Platform-specific (guarded by @VK_USE_PLATFORM_WIN32_KHR@ in C; emitted unconditionally here).
getPhysicalDeviceWin32PresentationSupportKHR
  :: forall m
   . (MonadIO m)
  => PhysicalDevice
  -> Word32
  -> m Bool
getPhysicalDeviceWin32PresentationSupportKHR physicalDevice queueFamilyIndex =
  liftIO do
    retw_ <-
      liftIO
        ( mkGetPhysicalDeviceWin32PresentationSupportKHR
            ( checkCommandPtr
                "vkGetPhysicalDeviceWin32PresentationSupportKHR"
                physicalDevice.cmds.pGetPhysicalDeviceWin32PresentationSupportKHR
            )
            (castPtr physicalDevice.handle)
            queueFamilyIndex
        )
    let ret_ = (retw_ /= (0 :: Word32))
    pure ret_
