-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.KHR_surface (
  ColorSpaceKHR (..),
  CompositeAlphaFlagBitsKHR (..),
  PresentModeKHR (..),
  SurfaceTransformFlagBitsKHR (..),
  CompositeAlphaFlagsKHR,
  SurfaceTransformFlagsKHR,
  SurfaceKHR (..),
  SurfaceCapabilitiesKHR (..),
  SurfaceFormatKHR (..),
  destroySurfaceKHR,
  getPhysicalDeviceSurfaceCapabilitiesKHR,
  getPhysicalDeviceSurfaceFormatsKHR,
  getPhysicalDeviceSurfacePresentModesKHR,
  getPhysicalDeviceSurfaceSupportKHR,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Primitive.Types (Prim)
import Data.Vector qualified as V
import Data.Vector.Generic qualified as VG
import Data.Vector.Generic.Mutable qualified as VGM
import Data.Vector.Primitive qualified as P
import Data.Vector.Unboxed qualified as VU
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable (..), peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
 )
import Lithon.Core.Flags (BitPos (..), Flags (..), FlagsWire)
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)
import Lithon.Core.Unbox (UnboxViaPrim (..))

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Enums.Format
import Lithon.Vk.Core10.Enums.ImageUsageFlagBits
import Lithon.Vk.Core10.FundamentalTypesUsedByManyCommandsAndStructures
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkColorSpaceKHR.html VkColorSpaceKHR>
-- Available: VK_KHR_surface
data ColorSpaceKHR
  = ColorSpaceSrgbNonlinearKHR
  | ColorSpaceDisplayP3NonlinearEXT
  | ColorSpaceExtendedSrgbLinearEXT
  | ColorSpaceDisplayP3LinearEXT
  | ColorSpaceDciP3NonlinearEXT
  | ColorSpaceBt709LinearEXT
  | ColorSpaceBt709NonlinearEXT
  | ColorSpaceBt2020LinearEXT
  | ColorSpaceHdr10St2084EXT
  | ColorSpaceDolbyvisionEXT
  | ColorSpaceHdr10HlgEXT
  | ColorSpaceAdobergbLinearEXT
  | ColorSpaceAdobergbNonlinearEXT
  | ColorSpacePassThroughEXT
  | ColorSpaceExtendedSrgbNonlinearEXT
  deriving stock (Eq, Ord, Show)

instance HasWire ColorSpaceKHR where
  toWire = \case
    ColorSpaceSrgbNonlinearKHR -> 0
    ColorSpaceDisplayP3NonlinearEXT -> 1000104001
    ColorSpaceExtendedSrgbLinearEXT -> 1000104002
    ColorSpaceDisplayP3LinearEXT -> 1000104003
    ColorSpaceDciP3NonlinearEXT -> 1000104004
    ColorSpaceBt709LinearEXT -> 1000104005
    ColorSpaceBt709NonlinearEXT -> 1000104006
    ColorSpaceBt2020LinearEXT -> 1000104007
    ColorSpaceHdr10St2084EXT -> 1000104008
    ColorSpaceDolbyvisionEXT -> 1000104009
    ColorSpaceHdr10HlgEXT -> 1000104010
    ColorSpaceAdobergbLinearEXT -> 1000104011
    ColorSpaceAdobergbNonlinearEXT -> 1000104012
    ColorSpacePassThroughEXT -> 1000104013
    ColorSpaceExtendedSrgbNonlinearEXT -> 1000104014
  fromWire = \case
    0 -> Just ColorSpaceSrgbNonlinearKHR
    1000104001 -> Just ColorSpaceDisplayP3NonlinearEXT
    1000104002 -> Just ColorSpaceExtendedSrgbLinearEXT
    1000104003 -> Just ColorSpaceDisplayP3LinearEXT
    1000104004 -> Just ColorSpaceDciP3NonlinearEXT
    1000104005 -> Just ColorSpaceBt709LinearEXT
    1000104006 -> Just ColorSpaceBt709NonlinearEXT
    1000104007 -> Just ColorSpaceBt2020LinearEXT
    1000104008 -> Just ColorSpaceHdr10St2084EXT
    1000104009 -> Just ColorSpaceDolbyvisionEXT
    1000104010 -> Just ColorSpaceHdr10HlgEXT
    1000104011 -> Just ColorSpaceAdobergbLinearEXT
    1000104012 -> Just ColorSpaceAdobergbNonlinearEXT
    1000104013 -> Just ColorSpacePassThroughEXT
    1000104014 -> Just ColorSpaceExtendedSrgbNonlinearEXT
    _ -> Nothing

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkCompositeAlphaFlagBitsKHR.html VkCompositeAlphaFlagBitsKHR>
-- Available: VK_KHR_surface
data CompositeAlphaFlagBitsKHR
  = CompositeAlphaOpaqueBitKHR
  | CompositeAlphaPreMultipliedBitKHR
  | CompositeAlphaPostMultipliedBitKHR
  | CompositeAlphaInheritBitKHR
  deriving stock (Eq, Ord, Show)

type instance FlagsWire CompositeAlphaFlagBitsKHR = Word32

instance BitPos CompositeAlphaFlagBitsKHR where
  bitOf = \case
    CompositeAlphaOpaqueBitKHR -> Flags 0x1
    CompositeAlphaPreMultipliedBitKHR -> Flags 0x2
    CompositeAlphaPostMultipliedBitKHR -> Flags 0x4
    CompositeAlphaInheritBitKHR -> Flags 0x8
  allBits =
    [ CompositeAlphaOpaqueBitKHR
    , CompositeAlphaPreMultipliedBitKHR
    , CompositeAlphaPostMultipliedBitKHR
    , CompositeAlphaInheritBitKHR
    ]

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPresentModeKHR.html VkPresentModeKHR>
-- Available: VK_KHR_surface
data PresentModeKHR
  = PresentModeImmediateKHR
  | PresentModeMailboxKHR
  | PresentModeFifoKHR
  | PresentModeFifoRelaxedKHR
  deriving stock (Eq, Ord, Show)

instance HasWire PresentModeKHR where
  toWire = \case
    PresentModeImmediateKHR -> 0
    PresentModeMailboxKHR -> 1
    PresentModeFifoKHR -> 2
    PresentModeFifoRelaxedKHR -> 3
  fromWire = \case
    0 -> Just PresentModeImmediateKHR
    1 -> Just PresentModeMailboxKHR
    2 -> Just PresentModeFifoKHR
    3 -> Just PresentModeFifoRelaxedKHR
    _ -> Nothing

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSurfaceTransformFlagBitsKHR.html VkSurfaceTransformFlagBitsKHR>
-- Available: VK_KHR_surface
data SurfaceTransformFlagBitsKHR
  = SurfaceTransformIdentityBitKHR
  | SurfaceTransformRotate90BitKHR
  | SurfaceTransformRotate180BitKHR
  | SurfaceTransformRotate270BitKHR
  | SurfaceTransformHorizontalMirrorBitKHR
  | SurfaceTransformHorizontalMirrorRotate90BitKHR
  | SurfaceTransformHorizontalMirrorRotate180BitKHR
  | SurfaceTransformHorizontalMirrorRotate270BitKHR
  | SurfaceTransformInheritBitKHR
  deriving stock (Eq, Ord, Show)

type instance FlagsWire SurfaceTransformFlagBitsKHR = Word32

instance BitPos SurfaceTransformFlagBitsKHR where
  bitOf = \case
    SurfaceTransformIdentityBitKHR -> Flags 0x1
    SurfaceTransformRotate90BitKHR -> Flags 0x2
    SurfaceTransformRotate180BitKHR -> Flags 0x4
    SurfaceTransformRotate270BitKHR -> Flags 0x8
    SurfaceTransformHorizontalMirrorBitKHR -> Flags 0x10
    SurfaceTransformHorizontalMirrorRotate90BitKHR -> Flags 0x20
    SurfaceTransformHorizontalMirrorRotate180BitKHR -> Flags 0x40
    SurfaceTransformHorizontalMirrorRotate270BitKHR -> Flags 0x80
    SurfaceTransformInheritBitKHR -> Flags 0x100
  allBits =
    [ SurfaceTransformIdentityBitKHR
    , SurfaceTransformRotate90BitKHR
    , SurfaceTransformRotate180BitKHR
    , SurfaceTransformRotate270BitKHR
    , SurfaceTransformHorizontalMirrorBitKHR
    , SurfaceTransformHorizontalMirrorRotate90BitKHR
    , SurfaceTransformHorizontalMirrorRotate180BitKHR
    , SurfaceTransformHorizontalMirrorRotate270BitKHR
    , SurfaceTransformInheritBitKHR
    ]

type CompositeAlphaFlagsKHR = Flags CompositeAlphaFlagBitsKHR

type SurfaceTransformFlagsKHR = Flags SurfaceTransformFlagBitsKHR

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSurfaceKHR.html VkSurfaceKHR>
-- Available: VK_KHR_surface
newtype SurfaceKHR = SurfaceKHR Word64
  deriving newtype (Eq, Ord, Prim, Show, Storable)

newtype instance VU.MVector s SurfaceKHR = MV_SurfaceKHR (P.MVector s SurfaceKHR)

newtype instance VU.Vector SurfaceKHR = V_SurfaceKHR (P.Vector SurfaceKHR)

deriving via (UnboxViaPrim SurfaceKHR) instance VGM.MVector VU.MVector SurfaceKHR

deriving via (UnboxViaPrim SurfaceKHR) instance VG.Vector VU.Vector SurfaceKHR

instance VU.Unbox SurfaceKHR

-- | @VK_NULL_HANDLE@.
instance Nil SurfaceKHR where
  nil = SurfaceKHR 0

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSurfaceCapabilitiesKHR.html VkSurfaceCapabilitiesKHR>
-- Available: VK_KHR_surface
-- __Deprecated__.
data SurfaceCapabilitiesKHR = SurfaceCapabilitiesKHR
  { minImageCount :: !Word32
  , maxImageCount :: !Word32
  , currentExtent :: !Extent2D
  , minImageExtent :: !Extent2D
  , maxImageExtent :: !Extent2D
  , maxImageArrayLayers :: !Word32
  , supportedTransforms :: !SurfaceTransformFlagsKHR
  , currentTransform :: !(Flags SurfaceTransformFlagBitsKHR)
  , supportedCompositeAlpha :: !CompositeAlphaFlagsKHR
  , supportedUsageFlags :: !ImageUsageFlags
  }
  deriving stock (Eq, Show)

instance Storable SurfaceCapabilitiesKHR where
  sizeOf _ = 52
  alignment _ = 4
  peek p =
    SurfaceCapabilitiesKHR
      <$> (peekByteOff p 0)
      <*> (peekByteOff p 4)
      <*> (peekByteOff p 8)
      <*> (peekByteOff p 16)
      <*> (peekByteOff p 24)
      <*> (peekByteOff p 32)
      <*> (peekByteOff p 36)
      <*> (peekByteOff p 40)
      <*> (peekByteOff p 44)
      <*> (peekByteOff p 48)
  poke p x = do
    pokeByteOff p 0 x.minImageCount
    pokeByteOff p 4 x.maxImageCount
    pokeByteOff p 8 x.currentExtent
    pokeByteOff p 16 x.minImageExtent
    pokeByteOff p 24 x.maxImageExtent
    pokeByteOff p 32 x.maxImageArrayLayers
    pokeByteOff p 36 x.supportedTransforms
    pokeByteOff p 40 x.currentTransform
    pokeByteOff p 44 x.supportedCompositeAlpha
    pokeByteOff p 48 x.supportedUsageFlags

instance CStruct SurfaceCapabilitiesKHR where
  cSize = 52
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct SurfaceCapabilitiesKHR where
  peekCStruct = peek

instance Nil SurfaceCapabilitiesKHR where
  nil =
    SurfaceCapabilitiesKHR
      { minImageCount = 0
      , maxImageCount = 0
      , currentExtent = nil
      , minImageExtent = nil
      , maxImageExtent = nil
      , maxImageArrayLayers = 0
      , supportedTransforms = mempty
      , currentTransform = mempty
      , supportedCompositeAlpha = mempty
      , supportedUsageFlags = mempty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkSurfaceFormatKHR.html VkSurfaceFormatKHR>
-- Available: VK_KHR_surface
-- __Deprecated__.
data SurfaceFormatKHR = SurfaceFormatKHR
  { format :: !(Open Format)
  , colorSpace :: !(Open ColorSpaceKHR)
  }
  deriving stock (Eq, Show)

instance Storable SurfaceFormatKHR where
  sizeOf _ = 8
  alignment _ = 4
  peek p =
    SurfaceFormatKHR
      <$> (openFromWire <$> peekByteOff p 0)
      <*> (openFromWire <$> peekByteOff p 4)
  poke p x = do
    pokeByteOff p 0 (openToWire x.format)
    pokeByteOff p 4 (openToWire x.colorSpace)

instance CStruct SurfaceFormatKHR where
  cSize = 8
  cAlign = 4
  pokeCStruct p x = liftIO (poke p x)

instance FromCStruct SurfaceFormatKHR where
  peekCStruct = peek

instance Nil SurfaceFormatKHR where
  nil =
    SurfaceFormatKHR
      { format = Known FormatUndefined
      , colorSpace = Known ColorSpaceSrgbNonlinearKHR
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroySurfaceKHR.html vkDestroySurfaceKHR>
-- Available: VK_KHR_surface
destroySurfaceKHR
  :: forall m
   . (MonadIO m)
  => Instance
  -> SurfaceKHR
  -> Maybe AllocationCallbacks
  -> m ()
destroySurfaceKHR instance' surface allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroySurfaceKHR
          (checkCommandPtr "vkDestroySurfaceKHR" instance'.cmds.pDestroySurfaceKHR)
          (castPtr instance'.handle)
          (case surface of SurfaceKHR w_ -> w_)
          p_allocator
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceSurfaceCapabilitiesKHR.html vkGetPhysicalDeviceSurfaceCapabilitiesKHR>
-- Available: VK_KHR_surface
-- __Deprecated__: superseded by vkGetPhysicalDeviceSurfaceCapabilities2KHR.
getPhysicalDeviceSurfaceCapabilitiesKHR
  :: forall m
   . (MonadIO m)
  => PhysicalDevice
  -> SurfaceKHR
  -> m (Outcome SurfaceCapabilitiesKHR)
getPhysicalDeviceSurfaceCapabilitiesKHR physicalDevice surface =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_o_surfaceCapabilities :: Ptr () <- castPtr <$> new (nil :: SurfaceCapabilitiesKHR)
    r_ <-
      liftIO
        ( mkGetPhysicalDeviceSurfaceCapabilitiesKHR
            ( checkCommandPtr
                "vkGetPhysicalDeviceSurfaceCapabilitiesKHR"
                physicalDevice.cmds.pGetPhysicalDeviceSurfaceCapabilitiesKHR
            )
            (castPtr physicalDevice.handle)
            (case surface of SurfaceKHR w_ -> w_)
            p_o_surfaceCapabilities
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      o_surfaceCapabilities <- liftIO (peekCStruct (castPtr p_o_surfaceCapabilities))
      pure (Ok (openFromWire r_) o_surfaceCapabilities)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceSurfaceFormatsKHR.html vkGetPhysicalDeviceSurfaceFormatsKHR>
-- Available: VK_KHR_surface
-- __Deprecated__: superseded by vkGetPhysicalDeviceSurfaceFormats2KHR.
getPhysicalDeviceSurfaceFormatsKHR
  :: forall m
   . (MonadIO m)
  => PhysicalDevice
  -> SurfaceKHR
  -> m (Outcome (V.Vector SurfaceFormatKHR))
getPhysicalDeviceSurfaceFormatsKHR physicalDevice surface =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_n_ <- arenaBytes 4 4
    liftIO (pokeByteOff p_n_ 0 (0 :: Word32))
    let goDual_ = do
          r1_ <-
            liftIO
              ( mkGetPhysicalDeviceSurfaceFormatsKHR
                  ( checkCommandPtr
                      "vkGetPhysicalDeviceSurfaceFormatsKHR"
                      physicalDevice.cmds.pGetPhysicalDeviceSurfaceFormatsKHR
                  )
                  (castPtr physicalDevice.handle)
                  (case surface of SurfaceKHR w_ -> w_)
                  (castPtr p_n_)
                  nullPtr
              )
          if r1_ < 0 then
            pure (Err (openFromWire r1_))
          else do
            n_pSurfaceFormatCount <- liftIO (peekByteOff p_n_ 0 :: IO Word32)
            p_o_surfaceFormats <- arenaBytes (8 * max 1 (fromIntegral n_pSurfaceFormatCount)) 4
            forM_
              ([0 .. fromIntegral n_pSurfaceFormatCount - 1] :: [Int])
              (\i -> pokeCStruct (castPtr (p_o_surfaceFormats `plusPtr` (i * 8))) (nil :: SurfaceFormatKHR))
            r2_ <-
              liftIO
                ( mkGetPhysicalDeviceSurfaceFormatsKHR
                    ( checkCommandPtr
                        "vkGetPhysicalDeviceSurfaceFormatsKHR"
                        physicalDevice.cmds.pGetPhysicalDeviceSurfaceFormatsKHR
                    )
                    (castPtr physicalDevice.handle)
                    (case surface of SurfaceKHR w_ -> w_)
                    (castPtr p_n_)
                    (castPtr p_o_surfaceFormats)
                )
            n_pSurfaceFormatCount' <- liftIO (peekByteOff p_n_ 0 :: IO Word32)
            if r2_ == 5 then
              goDual_
            else
              if r2_ < 0 then
                pure (Err (openFromWire r2_))
              else do
                o_surfaceFormats <-
                  liftIO (peekElems (fromIntegral n_pSurfaceFormatCount') (castPtr p_o_surfaceFormats))
                pure (Ok (openFromWire r2_) o_surfaceFormats)
    goDual_

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceSurfacePresentModesKHR.html vkGetPhysicalDeviceSurfacePresentModesKHR>
-- Available: VK_KHR_surface
getPhysicalDeviceSurfacePresentModesKHR
  :: forall m
   . (MonadIO m)
  => PhysicalDevice
  -> SurfaceKHR
  -> m (Outcome (V.Vector (Open PresentModeKHR)))
getPhysicalDeviceSurfacePresentModesKHR physicalDevice surface =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_n_ <- arenaBytes 4 4
    liftIO (pokeByteOff p_n_ 0 (0 :: Word32))
    let goDual_ = do
          r1_ <-
            liftIO
              ( mkGetPhysicalDeviceSurfacePresentModesKHR
                  ( checkCommandPtr
                      "vkGetPhysicalDeviceSurfacePresentModesKHR"
                      physicalDevice.cmds.pGetPhysicalDeviceSurfacePresentModesKHR
                  )
                  (castPtr physicalDevice.handle)
                  (case surface of SurfaceKHR w_ -> w_)
                  (castPtr p_n_)
                  nullPtr
              )
          if r1_ < 0 then
            pure (Err (openFromWire r1_))
          else do
            n_pPresentModeCount <- liftIO (peekByteOff p_n_ 0 :: IO Word32)
            p_o_presentModes <- arenaBytes (4 * max 1 (fromIntegral n_pPresentModeCount)) 4
            r2_ <-
              liftIO
                ( mkGetPhysicalDeviceSurfacePresentModesKHR
                    ( checkCommandPtr
                        "vkGetPhysicalDeviceSurfacePresentModesKHR"
                        physicalDevice.cmds.pGetPhysicalDeviceSurfacePresentModesKHR
                    )
                    (castPtr physicalDevice.handle)
                    (case surface of SurfaceKHR w_ -> w_)
                    (castPtr p_n_)
                    (castPtr p_o_presentModes)
                )
            n_pPresentModeCount' <- liftIO (peekByteOff p_n_ 0 :: IO Word32)
            if r2_ == 5 then
              goDual_
            else
              if r2_ < 0 then
                pure (Err (openFromWire r2_))
              else do
                o_presentModes <-
                  liftIO
                    ( V.generateM
                        (fromIntegral n_pPresentModeCount')
                        (\i -> (\w_ -> openFromWire w_) <$> (peekByteOff p_o_presentModes (i * 4) :: IO Int32))
                    )
                pure (Ok (openFromWire r2_) o_presentModes)
    goDual_

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceSurfaceSupportKHR.html vkGetPhysicalDeviceSurfaceSupportKHR>
-- Available: VK_KHR_surface
getPhysicalDeviceSurfaceSupportKHR
  :: forall m
   . (MonadIO m)
  => PhysicalDevice
  -> Word32
  -> SurfaceKHR
  -> m (Outcome Bool)
getPhysicalDeviceSurfaceSupportKHR physicalDevice queueFamilyIndex surface =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_o_supported <- arenaBytes 4 4
    r_ <-
      liftIO
        ( mkGetPhysicalDeviceSurfaceSupportKHR
            ( checkCommandPtr
                "vkGetPhysicalDeviceSurfaceSupportKHR"
                physicalDevice.cmds.pGetPhysicalDeviceSurfaceSupportKHR
            )
            (castPtr physicalDevice.handle)
            queueFamilyIndex
            (case surface of SurfaceKHR w_ -> w_)
            (castPtr p_o_supported)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_supported <- liftIO (peekByteOff p_o_supported 0 :: IO Word32)
      let o_supported = (w_o_supported /= (0 :: Word32))
      pure (Ok (openFromWire r_) o_supported)
