-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.KHR_deferred_host_operations (
  DeferredOperationKHR (..),
  createDeferredOperationKHR,
  withDeferredOperationKHR,
  deferredOperationJoinKHR,
  destroyDeferredOperationKHR,
  getDeferredOperationMaxConcurrencyKHR,
  getDeferredOperationResultKHR,
) where

import Control.Exception (bracket)
import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.IO.Unlift (MonadUnliftIO, withRunInIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Primitive.Types (Prim)
import Data.Vector qualified as V
import Data.Vector.Generic qualified as VG
import Data.Vector.Generic.Mutable qualified as VGM
import Data.Vector.Primitive qualified as P
import Data.Vector.Unboxed qualified as VU
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable, peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)
import Lithon.Core.Unbox (UnboxViaPrim (..))

import Lithon.Vk.Core10.DeviceInitialization
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkDeferredOperationKHR.html VkDeferredOperationKHR>
-- Available: VK_KHR_deferred_host_operations
newtype DeferredOperationKHR = DeferredOperationKHR Word64
  deriving newtype (Eq, Ord, Prim, Show, Storable)

newtype instance VU.MVector s DeferredOperationKHR = MV_DeferredOperationKHR (P.MVector s DeferredOperationKHR)

newtype instance VU.Vector DeferredOperationKHR = V_DeferredOperationKHR (P.Vector DeferredOperationKHR)

deriving via
  (UnboxViaPrim DeferredOperationKHR)
  instance
    VGM.MVector VU.MVector DeferredOperationKHR

deriving via (UnboxViaPrim DeferredOperationKHR) instance VG.Vector VU.Vector DeferredOperationKHR

instance VU.Unbox DeferredOperationKHR

-- | @VK_NULL_HANDLE@.
instance Nil DeferredOperationKHR where
  nil = DeferredOperationKHR 0

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCreateDeferredOperationKHR.html vkCreateDeferredOperationKHR>
-- Available: VK_KHR_deferred_host_operations
createDeferredOperationKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> Maybe AllocationCallbacks
  -> m (Outcome DeferredOperationKHR)
createDeferredOperationKHR device allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    p_o_deferredOperation <- arenaBytes 8 8
    r_ <-
      liftIO
        ( mkCreateDeferredOperationKHR
            (checkCommandPtr "vkCreateDeferredOperationKHR" device.cmds.pCreateDeferredOperationKHR)
            (castPtr device.handle)
            p_allocator
            (castPtr p_o_deferredOperation)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      w_o_deferredOperation <- liftIO (peekByteOff p_o_deferredOperation 0 :: IO Word64)
      let o_deferredOperation = DeferredOperationKHR w_o_deferredOperation
      pure (Ok (openFromWire r_) o_deferredOperation)

withDeferredOperationKHR
  :: forall m r
   . (MonadUnliftIO m)
  => Device
  -> Maybe AllocationCallbacks
  -> (Outcome DeferredOperationKHR -> m r)
  -> m r
withDeferredOperationKHR device allocator cont_ =
  withRunInIO \run_ ->
    bracket
      (run_ (createDeferredOperationKHR device allocator))
      ( \o_ -> case o_ of
          Ok _ h_ -> run_ (destroyDeferredOperationKHR device h_ allocator)
          Err _ -> pure ()
      )
      (run_ . cont_)

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDeferredOperationJoinKHR.html vkDeferredOperationJoinKHR>
-- Available: VK_KHR_deferred_host_operations
deferredOperationJoinKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> DeferredOperationKHR
  -> m (Outcome ())
deferredOperationJoinKHR device operation =
  liftIO do
    r_ <-
      liftIO
        ( mkDeferredOperationJoinKHR
            (checkCommandPtr "vkDeferredOperationJoinKHR" device.cmds.pDeferredOperationJoinKHR)
            (castPtr device.handle)
            (case operation of DeferredOperationKHR w_ -> w_)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkDestroyDeferredOperationKHR.html vkDestroyDeferredOperationKHR>
-- Available: VK_KHR_deferred_host_operations
destroyDeferredOperationKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> DeferredOperationKHR
  -> Maybe AllocationCallbacks
  -> m ()
destroyDeferredOperationKHR device operation allocator =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_allocator :: Ptr () <- maybe (pure nullPtr) (fmap castPtr . new) allocator
    liftIO
      ( mkDestroyDeferredOperationKHR
          (checkCommandPtr "vkDestroyDeferredOperationKHR" device.cmds.pDestroyDeferredOperationKHR)
          (castPtr device.handle)
          (case operation of DeferredOperationKHR w_ -> w_)
          p_allocator
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetDeferredOperationMaxConcurrencyKHR.html vkGetDeferredOperationMaxConcurrencyKHR>
-- Available: VK_KHR_deferred_host_operations
getDeferredOperationMaxConcurrencyKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> DeferredOperationKHR
  -> m Word32
getDeferredOperationMaxConcurrencyKHR device operation =
  liftIO do
    retw_ <-
      liftIO
        ( mkGetDeferredOperationMaxConcurrencyKHR
            ( checkCommandPtr
                "vkGetDeferredOperationMaxConcurrencyKHR"
                device.cmds.pGetDeferredOperationMaxConcurrencyKHR
            )
            (castPtr device.handle)
            (case operation of DeferredOperationKHR w_ -> w_)
        )
    let ret_ = retw_
    pure ret_

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetDeferredOperationResultKHR.html vkGetDeferredOperationResultKHR>
-- Available: VK_KHR_deferred_host_operations
getDeferredOperationResultKHR
  :: forall m
   . (MonadIO m)
  => Device
  -> DeferredOperationKHR
  -> m (Outcome ())
getDeferredOperationResultKHR device operation =
  liftIO do
    r_ <-
      liftIO
        ( mkGetDeferredOperationResultKHR
            (checkCommandPtr "vkGetDeferredOperationResultKHR" device.cmds.pGetDeferredOperationResultKHR)
            (castPtr device.handle)
            (case operation of DeferredOperationKHR w_ -> w_)
        )
    if r_ < 0 then
      pure (Err (openFromWire r_))
    else do
      pure (Ok (openFromWire r_) ())
