-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.KHR_fragment_shading_rate (
  FragmentShadingRateCombinerOpKHR (..),
  FragmentShadingRateAttachmentInfoKHR (..),
  PhysicalDeviceFragmentShadingRateFeaturesKHR (..),
  PhysicalDeviceFragmentShadingRateKHR (..),
  PhysicalDeviceFragmentShadingRatePropertiesKHR (..),
  PipelineFragmentShadingRateStateCreateInfoKHR (..),
  RenderingFragmentShadingRateAttachmentInfoKHR (..),
  cmdSetFragmentShadingRateKHR,
  getPhysicalDeviceFragmentShadingRatesKHR,
) where

import Control.Monad (forM_, unless, when)
import Control.Monad.IO.Class (MonadIO, liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Vector qualified as V
import Data.Word (Word16, Word32, Word64, Word8)
import Foreign.C.Types (CSize (..))
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings, runAlloc, withArena)
import Lithon.Core.BaseTypes (Bool32 (..), toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (
  CStruct (..),
  Chainable (..),
  FromCStruct (..),
  Nil (..),
  new,
  newVector,
  peekElems,
 )
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags (..))
import Lithon.Core.Loader (checkCommandPtr)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)

import Lithon.Vk.Core10.Enums.ImageLayout
import Lithon.Vk.Core10.Enums.SampleCountFlagBits
import Lithon.Vk.Core10.FundamentalTypesUsedByManyCommandsAndStructures
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Core12.Other
import Lithon.Vk.Dispatch
import Lithon.Vk.Result (Outcome (..))

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkFragmentShadingRateCombinerOpKHR.html VkFragmentShadingRateCombinerOpKHR>
-- Available: VK_KHR_fragment_shading_rate
data FragmentShadingRateCombinerOpKHR
  = FragmentShadingRateCombinerOpKeepKHR
  | FragmentShadingRateCombinerOpReplaceKHR
  | FragmentShadingRateCombinerOpMinKHR
  | FragmentShadingRateCombinerOpMaxKHR
  | FragmentShadingRateCombinerOpMulKHR
  deriving stock (Eq, Ord, Show)

instance HasWire FragmentShadingRateCombinerOpKHR where
  toWire = \case
    FragmentShadingRateCombinerOpKeepKHR -> 0
    FragmentShadingRateCombinerOpReplaceKHR -> 1
    FragmentShadingRateCombinerOpMinKHR -> 2
    FragmentShadingRateCombinerOpMaxKHR -> 3
    FragmentShadingRateCombinerOpMulKHR -> 4
  fromWire = \case
    0 -> Just FragmentShadingRateCombinerOpKeepKHR
    1 -> Just FragmentShadingRateCombinerOpReplaceKHR
    2 -> Just FragmentShadingRateCombinerOpMinKHR
    3 -> Just FragmentShadingRateCombinerOpMaxKHR
    4 -> Just FragmentShadingRateCombinerOpMulKHR
    _ -> Nothing

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkFragmentShadingRateAttachmentInfoKHR.html VkFragmentShadingRateAttachmentInfoKHR>
-- Available: VK_KHR_fragment_shading_rate
-- __Deprecated__.
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data FragmentShadingRateAttachmentInfoKHR = FragmentShadingRateAttachmentInfoKHR
  { fragmentShadingRateAttachment :: Maybe (SomeStruct AttachmentReference2)
  , shadingRateAttachmentTexelSize :: Extent2D
  }

instance CStruct FragmentShadingRateAttachmentInfoKHR where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000226000 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    p_fragmentShadingRateAttachment <-
      maybe (pure nullPtr) (\s -> withSomeStruct s (fmap castPtr . new)) x.fragmentShadingRateAttachment
    liftIO (pokeByteOff p 16 p_fragmentShadingRateAttachment)
    liftIO (pokeByteOff p 24 x.shadingRateAttachmentTexelSize)
    pure ()

instance Nil FragmentShadingRateAttachmentInfoKHR where
  nil =
    FragmentShadingRateAttachmentInfoKHR
      { fragmentShadingRateAttachment = Nothing
      , shadingRateAttachmentTexelSize = nil
      }

instance Chainable FragmentShadingRateAttachmentInfoKHR where
  sTypeWire = 1000226000
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceFragmentShadingRateFeaturesKHR.html VkPhysicalDeviceFragmentShadingRateFeaturesKHR>
-- Available: VK_KHR_fragment_shading_rate
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceFragmentShadingRateFeaturesKHR = PhysicalDeviceFragmentShadingRateFeaturesKHR
  { pipelineFragmentShadingRate :: Bool
  , primitiveFragmentShadingRate :: Bool
  , attachmentFragmentShadingRate :: Bool
  }

instance CStruct PhysicalDeviceFragmentShadingRateFeaturesKHR where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000226003 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (if x.pipelineFragmentShadingRate then TRUE else FALSE))
    liftIO (pokeByteOff p 20 (if x.primitiveFragmentShadingRate then TRUE else FALSE))
    liftIO (pokeByteOff p 24 (if x.attachmentFragmentShadingRate then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDeviceFragmentShadingRateFeaturesKHR where
  peekCStruct p = do
    v_pipelineFragmentShadingRate <- (toBool <$> peekByteOff p 16)
    v_primitiveFragmentShadingRate <- (toBool <$> peekByteOff p 20)
    v_attachmentFragmentShadingRate <- (toBool <$> peekByteOff p 24)
    pure
      PhysicalDeviceFragmentShadingRateFeaturesKHR
        { pipelineFragmentShadingRate = v_pipelineFragmentShadingRate
        , primitiveFragmentShadingRate = v_primitiveFragmentShadingRate
        , attachmentFragmentShadingRate = v_attachmentFragmentShadingRate
        }

instance Nil PhysicalDeviceFragmentShadingRateFeaturesKHR where
  nil =
    PhysicalDeviceFragmentShadingRateFeaturesKHR
      { pipelineFragmentShadingRate = False
      , primitiveFragmentShadingRate = False
      , attachmentFragmentShadingRate = False
      }

instance Chainable PhysicalDeviceFragmentShadingRateFeaturesKHR where
  sTypeWire = 1000226003
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceFragmentShadingRateKHR.html VkPhysicalDeviceFragmentShadingRateKHR>
-- Available: VK_KHR_fragment_shading_rate
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceFragmentShadingRateKHR = PhysicalDeviceFragmentShadingRateKHR
  { sampleCounts :: SampleCountFlags
  , fragmentSize :: Extent2D
  }

instance CStruct PhysicalDeviceFragmentShadingRateKHR where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000226004 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.sampleCounts)
    liftIO (pokeByteOff p 20 x.fragmentSize)
    pure ()

instance FromCStruct PhysicalDeviceFragmentShadingRateKHR where
  peekCStruct p = do
    v_sampleCounts <- (peekByteOff p 16)
    v_fragmentSize <- (peekByteOff p 20)
    pure
      PhysicalDeviceFragmentShadingRateKHR{sampleCounts = v_sampleCounts, fragmentSize = v_fragmentSize}

instance Nil PhysicalDeviceFragmentShadingRateKHR where
  nil =
    PhysicalDeviceFragmentShadingRateKHR
      { sampleCounts = mempty
      , fragmentSize = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPhysicalDeviceFragmentShadingRatePropertiesKHR.html VkPhysicalDeviceFragmentShadingRatePropertiesKHR>
-- Available: VK_KHR_fragment_shading_rate
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PhysicalDeviceFragmentShadingRatePropertiesKHR = PhysicalDeviceFragmentShadingRatePropertiesKHR
  { minFragmentShadingRateAttachmentTexelSize :: Extent2D
  , maxFragmentShadingRateAttachmentTexelSize :: Extent2D
  , maxFragmentShadingRateAttachmentTexelSizeAspectRatio :: Word32
  , primitiveFragmentShadingRateWithMultipleViewports :: Bool
  , layeredShadingRateAttachments :: Bool
  , fragmentShadingRateNonTrivialCombinerOps :: Bool
  , maxFragmentSize :: Extent2D
  , maxFragmentSizeAspectRatio :: Word32
  , maxFragmentShadingRateCoverageSamples :: Word32
  , maxFragmentShadingRateRasterizationSamples :: Flags SampleCountFlagBits
  , fragmentShadingRateWithShaderDepthStencilWrites :: Bool
  , fragmentShadingRateWithSampleMask :: Bool
  , fragmentShadingRateWithShaderSampleMask :: Bool
  , fragmentShadingRateWithConservativeRasterization :: Bool
  , fragmentShadingRateWithFragmentShaderInterlock :: Bool
  , fragmentShadingRateWithCustomSampleLocations :: Bool
  , fragmentShadingRateStrictMultiplyCombiner :: Bool
  }

instance CStruct PhysicalDeviceFragmentShadingRatePropertiesKHR where
  cSize = 96
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000226002 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.minFragmentShadingRateAttachmentTexelSize)
    liftIO (pokeByteOff p 24 x.maxFragmentShadingRateAttachmentTexelSize)
    liftIO (pokeByteOff p 32 x.maxFragmentShadingRateAttachmentTexelSizeAspectRatio)
    liftIO
      (pokeByteOff p 36 (if x.primitiveFragmentShadingRateWithMultipleViewports then TRUE else FALSE))
    liftIO (pokeByteOff p 40 (if x.layeredShadingRateAttachments then TRUE else FALSE))
    liftIO (pokeByteOff p 44 (if x.fragmentShadingRateNonTrivialCombinerOps then TRUE else FALSE))
    liftIO (pokeByteOff p 48 x.maxFragmentSize)
    liftIO (pokeByteOff p 56 x.maxFragmentSizeAspectRatio)
    liftIO (pokeByteOff p 60 x.maxFragmentShadingRateCoverageSamples)
    liftIO (pokeByteOff p 64 x.maxFragmentShadingRateRasterizationSamples)
    liftIO
      (pokeByteOff p 68 (if x.fragmentShadingRateWithShaderDepthStencilWrites then TRUE else FALSE))
    liftIO (pokeByteOff p 72 (if x.fragmentShadingRateWithSampleMask then TRUE else FALSE))
    liftIO (pokeByteOff p 76 (if x.fragmentShadingRateWithShaderSampleMask then TRUE else FALSE))
    liftIO
      (pokeByteOff p 80 (if x.fragmentShadingRateWithConservativeRasterization then TRUE else FALSE))
    liftIO (pokeByteOff p 84 (if x.fragmentShadingRateWithFragmentShaderInterlock then TRUE else FALSE))
    liftIO (pokeByteOff p 88 (if x.fragmentShadingRateWithCustomSampleLocations then TRUE else FALSE))
    liftIO (pokeByteOff p 92 (if x.fragmentShadingRateStrictMultiplyCombiner then TRUE else FALSE))
    pure ()

instance FromCStruct PhysicalDeviceFragmentShadingRatePropertiesKHR where
  peekCStruct p = do
    v_minFragmentShadingRateAttachmentTexelSize <- (peekByteOff p 16)
    v_maxFragmentShadingRateAttachmentTexelSize <- (peekByteOff p 24)
    v_maxFragmentShadingRateAttachmentTexelSizeAspectRatio <- (peekByteOff p 32)
    v_primitiveFragmentShadingRateWithMultipleViewports <- (toBool <$> peekByteOff p 36)
    v_layeredShadingRateAttachments <- (toBool <$> peekByteOff p 40)
    v_fragmentShadingRateNonTrivialCombinerOps <- (toBool <$> peekByteOff p 44)
    v_maxFragmentSize <- (peekByteOff p 48)
    v_maxFragmentSizeAspectRatio <- (peekByteOff p 56)
    v_maxFragmentShadingRateCoverageSamples <- (peekByteOff p 60)
    v_maxFragmentShadingRateRasterizationSamples <- (peekByteOff p 64)
    v_fragmentShadingRateWithShaderDepthStencilWrites <- (toBool <$> peekByteOff p 68)
    v_fragmentShadingRateWithSampleMask <- (toBool <$> peekByteOff p 72)
    v_fragmentShadingRateWithShaderSampleMask <- (toBool <$> peekByteOff p 76)
    v_fragmentShadingRateWithConservativeRasterization <- (toBool <$> peekByteOff p 80)
    v_fragmentShadingRateWithFragmentShaderInterlock <- (toBool <$> peekByteOff p 84)
    v_fragmentShadingRateWithCustomSampleLocations <- (toBool <$> peekByteOff p 88)
    v_fragmentShadingRateStrictMultiplyCombiner <- (toBool <$> peekByteOff p 92)
    pure
      PhysicalDeviceFragmentShadingRatePropertiesKHR
        { minFragmentShadingRateAttachmentTexelSize = v_minFragmentShadingRateAttachmentTexelSize
        , maxFragmentShadingRateAttachmentTexelSize = v_maxFragmentShadingRateAttachmentTexelSize
        , maxFragmentShadingRateAttachmentTexelSizeAspectRatio =
            v_maxFragmentShadingRateAttachmentTexelSizeAspectRatio
        , primitiveFragmentShadingRateWithMultipleViewports =
            v_primitiveFragmentShadingRateWithMultipleViewports
        , layeredShadingRateAttachments = v_layeredShadingRateAttachments
        , fragmentShadingRateNonTrivialCombinerOps = v_fragmentShadingRateNonTrivialCombinerOps
        , maxFragmentSize = v_maxFragmentSize
        , maxFragmentSizeAspectRatio = v_maxFragmentSizeAspectRatio
        , maxFragmentShadingRateCoverageSamples = v_maxFragmentShadingRateCoverageSamples
        , maxFragmentShadingRateRasterizationSamples = v_maxFragmentShadingRateRasterizationSamples
        , fragmentShadingRateWithShaderDepthStencilWrites = v_fragmentShadingRateWithShaderDepthStencilWrites
        , fragmentShadingRateWithSampleMask = v_fragmentShadingRateWithSampleMask
        , fragmentShadingRateWithShaderSampleMask = v_fragmentShadingRateWithShaderSampleMask
        , fragmentShadingRateWithConservativeRasterization =
            v_fragmentShadingRateWithConservativeRasterization
        , fragmentShadingRateWithFragmentShaderInterlock = v_fragmentShadingRateWithFragmentShaderInterlock
        , fragmentShadingRateWithCustomSampleLocations = v_fragmentShadingRateWithCustomSampleLocations
        , fragmentShadingRateStrictMultiplyCombiner = v_fragmentShadingRateStrictMultiplyCombiner
        }

instance Nil PhysicalDeviceFragmentShadingRatePropertiesKHR where
  nil =
    PhysicalDeviceFragmentShadingRatePropertiesKHR
      { minFragmentShadingRateAttachmentTexelSize = nil
      , maxFragmentShadingRateAttachmentTexelSize = nil
      , maxFragmentShadingRateAttachmentTexelSizeAspectRatio = 0
      , primitiveFragmentShadingRateWithMultipleViewports = False
      , layeredShadingRateAttachments = False
      , fragmentShadingRateNonTrivialCombinerOps = False
      , maxFragmentSize = nil
      , maxFragmentSizeAspectRatio = 0
      , maxFragmentShadingRateCoverageSamples = 0
      , maxFragmentShadingRateRasterizationSamples = mempty
      , fragmentShadingRateWithShaderDepthStencilWrites = False
      , fragmentShadingRateWithSampleMask = False
      , fragmentShadingRateWithShaderSampleMask = False
      , fragmentShadingRateWithConservativeRasterization = False
      , fragmentShadingRateWithFragmentShaderInterlock = False
      , fragmentShadingRateWithCustomSampleLocations = False
      , fragmentShadingRateStrictMultiplyCombiner = False
      }

instance Chainable PhysicalDeviceFragmentShadingRatePropertiesKHR where
  sTypeWire = 1000226002
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkPipelineFragmentShadingRateStateCreateInfoKHR.html VkPipelineFragmentShadingRateStateCreateInfoKHR>
-- Available: VK_KHR_fragment_shading_rate
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data PipelineFragmentShadingRateStateCreateInfoKHR = PipelineFragmentShadingRateStateCreateInfoKHR
  { fragmentSize :: Extent2D
  , combinerOps :: V.Vector FragmentShadingRateCombinerOpKHR
  }

instance CStruct PipelineFragmentShadingRateStateCreateInfoKHR where
  cSize = 32
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000226001 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.fragmentSize)
    unless (V.length x.combinerOps == 2) (error "lithon: combinerOps must have exactly 2 elements")
    liftIO (V.imapM_ (\i v -> pokeByteOff p (24 + i * 4) (toWire v)) x.combinerOps)
    pure ()

instance FromCStruct PipelineFragmentShadingRateStateCreateInfoKHR where
  peekCStruct p = do
    v_fragmentSize <- (peekByteOff p 16)
    v_combinerOps <- V.generateM 2 (\i -> unsafeFromWire <$> peekByteOff p (24 + i * 4))
    pure
      PipelineFragmentShadingRateStateCreateInfoKHR
        { fragmentSize = v_fragmentSize
        , combinerOps = v_combinerOps
        }

instance Nil PipelineFragmentShadingRateStateCreateInfoKHR where
  nil =
    PipelineFragmentShadingRateStateCreateInfoKHR
      { fragmentSize = nil
      , combinerOps = V.replicate 2 FragmentShadingRateCombinerOpKeepKHR
      }

instance Chainable PipelineFragmentShadingRateStateCreateInfoKHR where
  sTypeWire = 1000226001
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkRenderingFragmentShadingRateAttachmentInfoKHR.html VkRenderingFragmentShadingRateAttachmentInfoKHR>
-- Available: VK_KHR_dynamic_rendering,VK_VERSION_1_3+VK_KHR_fragment_shading_rate
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data RenderingFragmentShadingRateAttachmentInfoKHR = RenderingFragmentShadingRateAttachmentInfoKHR
  { imageView :: ImageView
  , imageLayout :: Open ImageLayout
  , shadingRateAttachmentTexelSize :: Extent2D
  }

instance CStruct RenderingFragmentShadingRateAttachmentInfoKHR where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000044006 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.imageView)
    liftIO (pokeByteOff p 24 (openToWire x.imageLayout))
    liftIO (pokeByteOff p 28 x.shadingRateAttachmentTexelSize)
    pure ()

instance FromCStruct RenderingFragmentShadingRateAttachmentInfoKHR where
  peekCStruct p = do
    v_imageView <- (peekByteOff p 16)
    v_imageLayout <- (openFromWire <$> peekByteOff p 24)
    v_shadingRateAttachmentTexelSize <- (peekByteOff p 28)
    pure
      RenderingFragmentShadingRateAttachmentInfoKHR
        { imageView = v_imageView
        , imageLayout = v_imageLayout
        , shadingRateAttachmentTexelSize = v_shadingRateAttachmentTexelSize
        }

instance Nil RenderingFragmentShadingRateAttachmentInfoKHR where
  nil =
    RenderingFragmentShadingRateAttachmentInfoKHR
      { imageView = nil
      , imageLayout = Known ImageLayoutUndefined
      , shadingRateAttachmentTexelSize = nil
      }

instance Chainable RenderingFragmentShadingRateAttachmentInfoKHR where
  sTypeWire = 1000044006
  chainOffset = 8

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkCmdSetFragmentShadingRateKHR.html vkCmdSetFragmentShadingRateKHR>
-- Available: VK_KHR_fragment_shading_rate
cmdSetFragmentShadingRateKHR
  :: forall m
   . (MonadIO m)
  => CommandBuffer
  -> Extent2D
  -> V.Vector FragmentShadingRateCombinerOpKHR
  -> m ()
cmdSetFragmentShadingRateKHR commandBuffer fragmentSize combinerOps =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_fragmentSize :: Ptr () <- castPtr <$> new fragmentSize
    unless
      (V.length combinerOps == 2)
      (error "lithon: vkCmdSetFragmentShadingRateKHR: combinerOps must have exactly 2 elements")
    p_combinerOps <- arenaBytes 8 4
    liftIO (V.imapM_ (\i v_ -> pokeByteOff p_combinerOps (i * 4) (toWire v_)) combinerOps)
    liftIO
      ( mkCmdSetFragmentShadingRateKHR
          (checkCommandPtr "vkCmdSetFragmentShadingRateKHR" commandBuffer.cmds.pCmdSetFragmentShadingRateKHR)
          (castPtr commandBuffer.handle)
          p_fragmentSize
          (castPtr p_combinerOps)
      )
    pure ()

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceFragmentShadingRatesKHR.html vkGetPhysicalDeviceFragmentShadingRatesKHR>
-- Available: VK_KHR_fragment_shading_rate
getPhysicalDeviceFragmentShadingRatesKHR
  :: forall m
   . (MonadIO m)
  => PhysicalDevice
  -> m (Outcome (V.Vector PhysicalDeviceFragmentShadingRateKHR))
getPhysicalDeviceFragmentShadingRatesKHR physicalDevice =
  liftIO $ withArena \arena_ -> runAlloc arena_ do
    p_n_ <- arenaBytes 4 4
    liftIO (pokeByteOff p_n_ 0 (0 :: Word32))
    let goDual_ = do
          r1_ <-
            liftIO
              ( mkGetPhysicalDeviceFragmentShadingRatesKHR
                  ( checkCommandPtr
                      "vkGetPhysicalDeviceFragmentShadingRatesKHR"
                      physicalDevice.cmds.pGetPhysicalDeviceFragmentShadingRatesKHR
                  )
                  (castPtr physicalDevice.handle)
                  (castPtr p_n_)
                  nullPtr
              )
          if r1_ < 0 then
            pure (Err (openFromWire r1_))
          else do
            n_pFragmentShadingRateCount <- liftIO (peekByteOff p_n_ 0 :: IO Word32)
            p_o_fragmentShadingRates <- arenaBytes (32 * max 1 (fromIntegral n_pFragmentShadingRateCount)) 8
            forM_
              ([0 .. fromIntegral n_pFragmentShadingRateCount - 1] :: [Int])
              ( \i ->
                  pokeCStruct
                    (castPtr (p_o_fragmentShadingRates `plusPtr` (i * 32)))
                    (nil :: PhysicalDeviceFragmentShadingRateKHR)
              )
            r2_ <-
              liftIO
                ( mkGetPhysicalDeviceFragmentShadingRatesKHR
                    ( checkCommandPtr
                        "vkGetPhysicalDeviceFragmentShadingRatesKHR"
                        physicalDevice.cmds.pGetPhysicalDeviceFragmentShadingRatesKHR
                    )
                    (castPtr physicalDevice.handle)
                    (castPtr p_n_)
                    (castPtr p_o_fragmentShadingRates)
                )
            n_pFragmentShadingRateCount' <- liftIO (peekByteOff p_n_ 0 :: IO Word32)
            if r2_ == 5 then
              goDual_
            else
              if r2_ < 0 then
                pure (Err (openFromWire r2_))
              else do
                o_fragmentShadingRates <-
                  liftIO (peekElems (fromIntegral n_pFragmentShadingRateCount') (castPtr p_o_fragmentShadingRates))
                pure (Ok (openFromWire r2_) o_fragmentShadingRates)
    goDual_
