-- Generated by lithon-codegen. DO NOT EDIT.
-- Regenerate: cabal run lithon-codegen -- generate --profile profiles/lithon-core.json
{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DerivingVia #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE NoFieldSelectors #-}

module Lithon.Vk.Extensions.NV_ray_tracing (
  AccelerationStructureNV (..),
  AccelerationStructureCreateInfoNV (..),
  AccelerationStructureInfoNV (..),
  GeometryAABBNV (..),
  GeometryDataNV (..),
  GeometryNV (..),
  GeometryTrianglesNV (..),
  RayTracingPipelineCreateInfoNV (..),
  RayTracingShaderGroupCreateInfoNV (..),
) where

import Control.Monad (unless)
import Control.Monad.IO.Class (liftIO)
import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.Int (Int32, Int64)
import Data.Kind (Type)
import Data.Primitive.Types (Prim)
import Data.Vector qualified as V
import Data.Vector.Generic qualified as VG
import Data.Vector.Generic.Mutable qualified as VGM
import Data.Vector.Primitive qualified as P
import Data.Vector.Unboxed qualified as VU
import Data.Word (Word32, Word64)
import Foreign.C.Types (CSize)
import Foreign.Ptr (FunPtr, Ptr, castPtr, nullFunPtr, nullPtr, plusPtr)
import Foreign.Storable (Storable, peekByteOff, peekElemOff, pokeByteOff)
import Lithon.Core.Alloc (arenaBytes, newBytes, newCString, newCStrings)
import Lithon.Core.BaseTypes (Bool32, toBool, pattern FALSE, pattern TRUE)
import Lithon.Core.CStruct (CStruct (..), Chainable (..), FromCStruct (..), Nil (..), new, newVector, peekElems)
import Lithon.Core.Chain (
  AllExtends,
  Chain,
  Extends,
  NilChain (..),
  PeekChain (..),
  PokeChain (..),
  SomeStruct (..),
  withSomeStruct,
  pattern (:&),
 )
import Lithon.Core.Flags (Flags)
import Lithon.Core.Open (HasWire (..), Open (..), openFromWire, openToWire, unsafeFromWire)
import Lithon.Core.Unbox (UnboxViaPrim (..))

import Lithon.Vk.Core10.ComputePipelineCommands
import Lithon.Vk.Core10.Enums.Format
import Lithon.Vk.Core10.Enums.IndexType
import Lithon.Vk.Core10.Enums.PipelineCreateFlagBits
import Lithon.Vk.Core10.Handles
import Lithon.Vk.Extensions.KHR_acceleration_structure
import Lithon.Vk.Extensions.KHR_ray_tracing_pipeline

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkAccelerationStructureNV.html VkAccelerationStructureNV>
-- Available: VK_NV_ray_tracing
newtype AccelerationStructureNV = AccelerationStructureNV Word64
  deriving newtype (Eq, Ord, Prim, Show, Storable)

newtype instance VU.MVector s AccelerationStructureNV
  = MV_AccelerationStructureNV (P.MVector s AccelerationStructureNV)

newtype instance VU.Vector AccelerationStructureNV = V_AccelerationStructureNV (P.Vector AccelerationStructureNV)

deriving via
  (UnboxViaPrim AccelerationStructureNV)
  instance
    VGM.MVector VU.MVector AccelerationStructureNV

deriving via
  (UnboxViaPrim AccelerationStructureNV)
  instance
    VG.Vector VU.Vector AccelerationStructureNV

instance VU.Unbox AccelerationStructureNV

-- | @VK_NULL_HANDLE@.
instance Nil AccelerationStructureNV where
  nil = AccelerationStructureNV 0

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkAccelerationStructureCreateInfoNV.html VkAccelerationStructureCreateInfoNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
data AccelerationStructureCreateInfoNV (es :: [Type]) = AccelerationStructureCreateInfoNV
  { next :: Chain es
  , compactedSize :: Word64
  , info :: AccelerationStructureInfoNV
  }

instance
  (AllExtends AccelerationStructureCreateInfoNV es, PokeChain es)
  => CStruct (AccelerationStructureCreateInfoNV es)
  where
  cSize = 64
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165001 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.compactedSize)
    pokeCStruct (castPtr (p `plusPtr` 24)) x.info
    pure ()

instance
  (AllExtends AccelerationStructureCreateInfoNV es, PokeChain es, PeekChain es)
  => FromCStruct (AccelerationStructureCreateInfoNV es)
  where
  peekCStruct p = do
    v_next <- peekChain =<< peekByteOff p 8
    v_compactedSize <- (peekByteOff p 16)
    v_info <- peekCStruct (castPtr (p `plusPtr` 24))
    pure
      AccelerationStructureCreateInfoNV{next = v_next, compactedSize = v_compactedSize, info = v_info}

instance (NilChain es) => Nil (AccelerationStructureCreateInfoNV es) where
  nil =
    AccelerationStructureCreateInfoNV
      { next = nilChain
      , compactedSize = 0
      , info = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkAccelerationStructureInfoNV.html VkAccelerationStructureInfoNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
--   * @geometryCount@ is derived from @geometries@'s length.
data AccelerationStructureInfoNV = AccelerationStructureInfoNV
  { type' :: AccelerationStructureTypeKHR
  , flags :: BuildAccelerationStructureFlagsKHR
  , instanceCount :: Word32
  , geometries :: V.Vector GeometryNV
  }

instance CStruct AccelerationStructureInfoNV where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165012 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (toWire x.type'))
    liftIO (pokeByteOff p 20 x.flags)
    liftIO (pokeByteOff p 24 x.instanceCount)
    p_geometries <- if V.null x.geometries then pure nullPtr else newVector x.geometries
    liftIO (pokeByteOff p 32 p_geometries)
    liftIO (pokeByteOff p 28 (fromIntegral (V.length x.geometries) :: Word32))
    pure ()

instance FromCStruct AccelerationStructureInfoNV where
  peekCStruct p = do
    v_type' <- (unsafeFromWire <$> peekByteOff p 16)
    v_flags <- (peekByteOff p 20)
    v_instanceCount <- (peekByteOff p 24)
    v_geometries <- do
      n <- (peekByteOff p 28 :: IO Word32)
      q <- peekByteOff p 32
      if q == nullPtr then pure V.empty else peekElems (fromIntegral n) q
    pure
      AccelerationStructureInfoNV
        { type' = v_type'
        , flags = v_flags
        , instanceCount = v_instanceCount
        , geometries = v_geometries
        }

instance Nil AccelerationStructureInfoNV where
  nil =
    AccelerationStructureInfoNV
      { type' = AccelerationStructureTypeTopLevelKHR
      , flags = mempty
      , instanceCount = 0
      , geometries = V.empty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkGeometryAABBNV.html VkGeometryAABBNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data GeometryAABBNV = GeometryAABBNV
  { aabbData :: Buffer
  , numAABBs :: Word32
  , stride :: Word32
  , offset :: Word64
  }

instance CStruct GeometryAABBNV where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165005 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.aabbData)
    liftIO (pokeByteOff p 24 x.numAABBs)
    liftIO (pokeByteOff p 28 x.stride)
    liftIO (pokeByteOff p 32 x.offset)
    pure ()

instance FromCStruct GeometryAABBNV where
  peekCStruct p = do
    v_aabbData <- (peekByteOff p 16)
    v_numAABBs <- (peekByteOff p 24)
    v_stride <- (peekByteOff p 28)
    v_offset <- (peekByteOff p 32)
    pure
      GeometryAABBNV{aabbData = v_aabbData, numAABBs = v_numAABBs, stride = v_stride, offset = v_offset}

instance Nil GeometryAABBNV where
  nil =
    GeometryAABBNV
      { aabbData = nil
      , numAABBs = 0
      , stride = 0
      , offset = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkGeometryDataNV.html VkGeometryDataNV>
-- Available: VK_NV_ray_tracing
data GeometryDataNV = GeometryDataNV
  { triangles :: GeometryTrianglesNV
  , aabbs :: GeometryAABBNV
  }

instance CStruct GeometryDataNV where
  cSize = 136
  cAlign = 8
  pokeCStruct p x = do
    pokeCStruct (castPtr (p `plusPtr` 0)) x.triangles
    pokeCStruct (castPtr (p `plusPtr` 96)) x.aabbs
    pure ()

instance FromCStruct GeometryDataNV where
  peekCStruct p = do
    v_triangles <- peekCStruct (castPtr (p `plusPtr` 0))
    v_aabbs <- peekCStruct (castPtr (p `plusPtr` 96))
    pure GeometryDataNV{triangles = v_triangles, aabbs = v_aabbs}

instance Nil GeometryDataNV where
  nil =
    GeometryDataNV
      { triangles = nil
      , aabbs = nil
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkGeometryNV.html VkGeometryNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data GeometryNV = GeometryNV
  { geometryType :: GeometryTypeKHR
  , geometry :: GeometryDataNV
  , flags :: GeometryFlagsKHR
  }

instance CStruct GeometryNV where
  cSize = 168
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165003 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (toWire x.geometryType))
    pokeCStruct (castPtr (p `plusPtr` 24)) x.geometry
    liftIO (pokeByteOff p 160 x.flags)
    pure ()

instance FromCStruct GeometryNV where
  peekCStruct p = do
    v_geometryType <- (unsafeFromWire <$> peekByteOff p 16)
    v_geometry <- peekCStruct (castPtr (p `plusPtr` 24))
    v_flags <- (peekByteOff p 160)
    pure GeometryNV{geometryType = v_geometryType, geometry = v_geometry, flags = v_flags}

instance Nil GeometryNV where
  nil =
    GeometryNV
      { geometryType = GeometryTypeTrianglesKHR
      , geometry = nil
      , flags = mempty
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkGeometryTrianglesNV.html VkGeometryTrianglesNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data GeometryTrianglesNV = GeometryTrianglesNV
  { vertexData :: Buffer
  , vertexOffset :: Word64
  , vertexCount :: Word32
  , vertexStride :: Word64
  , vertexFormat :: Open Format
  , indexData :: Buffer
  , indexOffset :: Word64
  , indexCount :: Word32
  , indexType :: IndexType
  , transformData :: Buffer
  , transformOffset :: Word64
  }

instance CStruct GeometryTrianglesNV where
  cSize = 96
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165004 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 x.vertexData)
    liftIO (pokeByteOff p 24 x.vertexOffset)
    liftIO (pokeByteOff p 32 x.vertexCount)
    liftIO (pokeByteOff p 40 x.vertexStride)
    liftIO (pokeByteOff p 48 (openToWire x.vertexFormat))
    liftIO (pokeByteOff p 56 x.indexData)
    liftIO (pokeByteOff p 64 x.indexOffset)
    liftIO (pokeByteOff p 72 x.indexCount)
    liftIO (pokeByteOff p 76 (toWire x.indexType))
    liftIO (pokeByteOff p 80 x.transformData)
    liftIO (pokeByteOff p 88 x.transformOffset)
    pure ()

instance FromCStruct GeometryTrianglesNV where
  peekCStruct p = do
    v_vertexData <- (peekByteOff p 16)
    v_vertexOffset <- (peekByteOff p 24)
    v_vertexCount <- (peekByteOff p 32)
    v_vertexStride <- (peekByteOff p 40)
    v_vertexFormat <- (openFromWire <$> peekByteOff p 48)
    v_indexData <- (peekByteOff p 56)
    v_indexOffset <- (peekByteOff p 64)
    v_indexCount <- (peekByteOff p 72)
    v_indexType <- (unsafeFromWire <$> peekByteOff p 76)
    v_transformData <- (peekByteOff p 80)
    v_transformOffset <- (peekByteOff p 88)
    pure
      GeometryTrianglesNV
        { vertexData = v_vertexData
        , vertexOffset = v_vertexOffset
        , vertexCount = v_vertexCount
        , vertexStride = v_vertexStride
        , vertexFormat = v_vertexFormat
        , indexData = v_indexData
        , indexOffset = v_indexOffset
        , indexCount = v_indexCount
        , indexType = v_indexType
        , transformData = v_transformData
        , transformOffset = v_transformOffset
        }

instance Nil GeometryTrianglesNV where
  nil =
    GeometryTrianglesNV
      { vertexData = nil
      , vertexOffset = 0
      , vertexCount = 0
      , vertexStride = 0
      , vertexFormat = Known FormatUndefined
      , indexData = nil
      , indexOffset = 0
      , indexCount = 0
      , indexType = IndexTypeUint16
      , transformData = nil
      , transformOffset = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkRayTracingPipelineCreateInfoNV.html VkRayTracingPipelineCreateInfoNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is the typed @next :: Chain es@ field.
--   * @stageCount@ is derived from @stages@'s length.
--   * @groupCount@ is derived from @groups@'s length.
data RayTracingPipelineCreateInfoNV (es :: [Type]) = RayTracingPipelineCreateInfoNV
  { next :: Chain es
  , flags :: PipelineCreateFlags
  , stages :: V.Vector (SomeStruct PipelineShaderStageCreateInfo)
  , groups :: V.Vector RayTracingShaderGroupCreateInfoNV
  , maxRecursionDepth :: Word32
  , layout :: PipelineLayout
  , basePipelineHandle :: Pipeline
  , basePipelineIndex :: Int32
  }

instance
  (AllExtends RayTracingPipelineCreateInfoNV es, PokeChain es)
  => CStruct (RayTracingPipelineCreateInfoNV es)
  where
  cSize = 80
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165000 :: Int32))
    pokeChain (castPtr (p `plusPtr` 8)) x.next
    liftIO (pokeByteOff p 16 x.flags)
    p_stages <- arenaBytes (48 * max 1 (V.length x.stages)) 8
    V.imapM_ (\i e -> withSomeStruct e (pokeCStruct (castPtr (p_stages `plusPtr` (i * 48))))) x.stages
    liftIO (pokeByteOff p 24 (if V.null x.stages then nullPtr else (castPtr p_stages :: Ptr ())))
    liftIO (pokeByteOff p 20 (fromIntegral (V.length x.stages) :: Word32))
    p_groups <- if V.null x.groups then pure nullPtr else newVector x.groups
    liftIO (pokeByteOff p 40 p_groups)
    liftIO (pokeByteOff p 32 (fromIntegral (V.length x.groups) :: Word32))
    liftIO (pokeByteOff p 48 x.maxRecursionDepth)
    liftIO (pokeByteOff p 56 x.layout)
    liftIO (pokeByteOff p 64 x.basePipelineHandle)
    liftIO (pokeByteOff p 72 x.basePipelineIndex)
    pure ()

instance (NilChain es) => Nil (RayTracingPipelineCreateInfoNV es) where
  nil =
    RayTracingPipelineCreateInfoNV
      { next = nilChain
      , flags = mempty
      , stages = V.empty
      , groups = V.empty
      , maxRecursionDepth = 0
      , layout = nil
      , basePipelineHandle = nil
      , basePipelineIndex = 0
      }

-- | Registry: <https://registry.khronos.org/vulkan/specs/latest/man/html/VkRayTracingShaderGroupCreateInfoNV.html VkRayTracingShaderGroupCreateInfoNV>
-- Available: VK_NV_ray_tracing
--
-- Marshalling:
--   * @sType@ is written automatically.
--   * @pNext@ is reserved and written as null.
data RayTracingShaderGroupCreateInfoNV = RayTracingShaderGroupCreateInfoNV
  { type' :: RayTracingShaderGroupTypeKHR
  , generalShader :: Word32
  , closestHitShader :: Word32
  , anyHitShader :: Word32
  , intersectionShader :: Word32
  }

instance CStruct RayTracingShaderGroupCreateInfoNV where
  cSize = 40
  cAlign = 8
  pokeCStruct p x = do
    liftIO (pokeByteOff p 0 (1000165011 :: Int32))
    liftIO (pokeByteOff p 8 (nullPtr :: Ptr ()))
    liftIO (pokeByteOff p 16 (toWire x.type'))
    liftIO (pokeByteOff p 20 x.generalShader)
    liftIO (pokeByteOff p 24 x.closestHitShader)
    liftIO (pokeByteOff p 28 x.anyHitShader)
    liftIO (pokeByteOff p 32 x.intersectionShader)
    pure ()

instance FromCStruct RayTracingShaderGroupCreateInfoNV where
  peekCStruct p = do
    v_type' <- (unsafeFromWire <$> peekByteOff p 16)
    v_generalShader <- (peekByteOff p 20)
    v_closestHitShader <- (peekByteOff p 24)
    v_anyHitShader <- (peekByteOff p 28)
    v_intersectionShader <- (peekByteOff p 32)
    pure
      RayTracingShaderGroupCreateInfoNV
        { type' = v_type'
        , generalShader = v_generalShader
        , closestHitShader = v_closestHitShader
        , anyHitShader = v_anyHitShader
        , intersectionShader = v_intersectionShader
        }

instance Nil RayTracingShaderGroupCreateInfoNV where
  nil =
    RayTracingShaderGroupCreateInfoNV
      { type' = RayTracingShaderGroupTypeGeneralKHR
      , generalShader = 0
      , closestHitShader = 0
      , anyHitShader = 0
      , intersectionShader = 0
      }
